- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/AssignmentGroupsApi.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/AssignmentsApi.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/AssignmentApiModel.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/AssignmentGroupApiModel.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/Randomizer.kt
Add test case for filtering assignments and sort them by type and time.
Add AssignmentGroup creating API
Extend randomizer
Extend page object
> [MBL-16332][Student] -  Test filter and sort in assignments & implement AssignmentGroupsApi

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/EditDashboardPage.kt
Major extension on DashboardE2E test in Student app.
refs: MBL-16330
> [MBL-16330][Student] - Major extension and refactor on DashboardE2E Test

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AnnouncementsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt
Fix locked announcement handling in AnnouncementE2E test.
Implement locked announcement test steps as well.
refs: MBL-16331
> [MBL-16331][Student] - Fix locked announcement handling

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt
Implement 'Complete a To Do' scenario in ToDoE2E test.
Implement filtering by favorite course on ToDo Page in E2E test.
refs: MBL-16337
> [MBL-16337][Student] -  'Complete a To Do' and 'Filter Favorite Course' scenario in ToDoE2E Test

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/BookmarkInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DashboardInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ProfileSettingsInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/UserFilesInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileUploadPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/PairObserverRenderPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/ScreenshotTestRule.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/matchers/WaitForViewMatcher.kt
Separate LeftSideNavigationDrawerPage from Dashboard
Refactor some methods and replace all usages.
refs: MBL-16410
> [MBL-16410][Student] - Separate left side menu from dashboard

- apps/teacher/src/main/java/com/instructure/teacher/features/dashboard/notifications/TeacherDashboardRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
> [MBL-16488][Teacher] Global announcement cannot be tapped on tablet

- apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/CourseSettingsFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/CreateAnnouncementFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/CreateDiscussionFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/EditPageDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_list/ui/ConferenceListFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/grades/GradesFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/homeroom/HomeroomFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/resources/ResourcesFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/notification/preferences/EmailNotificationPreferencesFragment.kt
refs: MBL-16474
test plan: check with charles that everything is reporting correctly
> [MBL-16474][Student] Add missing Pandata events

- libs/pandautils/src/main/assets/discussion_html_header_item.html
- libs/pandautils/src/main/assets/discussion_html_header_item_rtl.html
- libs/pandautils/src/main/assets/discussion_html_template_item.html
- libs/pandautils/src/main/assets/discussion_html_template_item_rtl.html
- libs/pandautils/src/main/assets/discussion_topic_header_html_template.html
- libs/pandautils/src/main/assets/discussion_topic_header_html_template_rtl.html
- libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebViewWrapper.kt
Test plan: Bug steps and test account info is in the ticket. Also smoke test different discussions in both dark and light theme.
refs: MBL-16461
release note: Fixed discussion replies in dark mode.
> [MBL-16461][Student][Teacher] LTI content in discussion replies make entries invisible in dark mode

- apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_filter_screen/calendar_filter_list_screen.dart
- apps/flutter_parent/lib/screens/calendar/planner_fetcher.dart
- apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_filter_list_screen_test.dart
> [MBL-16513][Parent] Fixed increase calendar context limit

- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewImageFragment.kt
> [MBL-16489][Teacher] Tablet: Crash when opening a graded discussion on Modules after opening a picture

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/TextSubmissionUploadPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderCommentsPage.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderCommentsFragment.kt
- apps/teacher/src/main/res/layout/speed_grader_comment_input_view.xml
Implement media comments E2E test, testing video and audio comment as well
Rename addMediaAttachment to addAttachment (since we developed the 'Add File' feature as well, the name is not correct yet)
refs: MBL-16322
> [MBL-16322][Teacher] - Implement MediaComments E2E test

- apps/flutter_parent/lib/l10n/app_localizations.dart
- apps/flutter_parent/lib/models/authenticated_url.dart
- apps/flutter_parent/lib/models/authenticated_url.g.dart
- apps/flutter_parent/lib/network/api/user_api.dart
- apps/flutter_parent/lib/router/panda_router.dart
- apps/flutter_parent/lib/screens/aup/acceptable_use_policy_interactor.dart
- apps/flutter_parent/lib/screens/aup/acceptable_use_policy_screen.dart
- apps/flutter_parent/lib/screens/splash/splash_screen.dart
- apps/flutter_parent/lib/screens/splash/splash_screen_interactor.dart
- apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
- apps/flutter_parent/lib/utils/common_widgets/web_view/html_description_screen.dart
- apps/flutter_parent/lib/utils/common_widgets/web_view/html_description_tile.dart
- apps/flutter_parent/lib/utils/common_widgets/web_view/web_content_interactor.dart
- apps/flutter_parent/lib/utils/service_locator.dart
- apps/flutter_parent/test/screens/aup/acceptable_use_policy_screen_test.dart
- apps/flutter_parent/test/screens/splash/splash_screen_test.dart
- apps/flutter_parent/test/utils/widgets/webview/html_description_screen_test.dart
- apps/flutter_parent/test/utils/widgets/webview/web_content_interactor_test.dart
refs: MBL-16406
release note: Added the Acceptable Use Policy screen.
test plan: Modify the terms of service, aup screen should be visible after login.
> [MBL-16406][Parent] Parent AUP

- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewFragment.kt
refs: MBL-16528
test plan: Upload files to discussions with the redesign enabled.
> [MBL-16528][Student][Teacher] File upload on discussion redesign

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/InboxApi.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindableRecyclerViewAdapter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxViewModelTest.kt
Test plan:
- Test swipe actions in both apps
Some test notes:
- Archive action is not available in archived folder
- Archive action does not remove messages from starred folder (archived messages can be starred as well)
refs: MBL-16469
release note: Added swipe actions to Inbox.
> [MBL-16469][Student][Teacher] Inbox swipe gestures

- README.md
> [MBL-16544] Update README.md

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxEntryItemCreator.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/itemviewmodels/InboxEntryItemViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxViewModelTest.kt
Test plan: 
- Test undo feature for all swipe actions (mark as read/unread, archive, unarchive, unstar)
- Smoke test swipe actions
refs: MBL-16543
> [MBL-16543][Teacher][Student] Undo feature for swipe gestures.

- translations/import.rb
> [MBL-16315][All] Fixed import translations script

- libs/rceditor/src/main/java/instructure/rceditor/RCEInsertDialog.kt
- libs/rceditor/src/main/java/instructure/rceditor/RCETextEditor.kt
- libs/rceditor/src/main/java/instructure/rceditor/RCETextEditorView.kt
Test plan:
- In the ticket.
- See also my comment on the ticket about the possible workaround.
refs: MBL-16545
> [MBL-16545][Student][Teacher] Attempting to add a link to item removes text in pop up box

- apps/student/src/main/res/values/themes_canvastheme.xml
- apps/teacher/src/main/res/values/styles.xml
- libs/pandautils/src/main/res/values/themes_canvasthemes.xml
- libs/rceditor/src/main/java/instructure/rceditor/RCETextEditor.kt
Test plan: 
- Bug steps are in the ticket
- Smoke text edit text and RCEditor behavior in both appps.
refs: MBL-16495
> [MBL-16495][Student][Teacher] Disable gif keyboard

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/InboxInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ConversationEndpoints.kt
> [MBL-16519][Student][Teacher] Inbox interaction tests

- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt
> [MBL-16592][Teacher] Show grade edit dialog on edigGradeIcon click

- apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
Test plan: smoke test grades screen all possible scenarios
refs: MBL-16597
release note: Fixed what-if score calculation.
> [MBL-16597][Student] What-if grades calculate assignments with “Do not count towards final grade” into the total

- apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
- apps/teacher/src/main/res/layout/view_submission_content.xml
> [MBL-16593][Teacher] Don't show "dropdown icon" when there is one attempt for an assignment

- apps/flutter_parent/lib/l10n/app_localizations.dart
- apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_day.dart
- apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_day_test.dart
- libs/flutter_student_embed/lib/l10n/app_localizations.dart
- libs/flutter_student_embed/lib/screens/calendar/calendar_widget/calendar_day.dart
- libs/flutter_student_embed/test/screens/calendar/calendar_widget/calendar_day_test.dart
> [MBL-16591][Student][Parent] Calendar does not read number of events on day

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FileUploadManager.kt
Test plan: Test profile picture upload, and submission file upload.
refs: MBL-16625
> [MBL-16625][Student][Teacher] Users unable to upload profile picture in app (sfu)

- apps/flutter_parent/lib/screens/login_landing_screen.dart
- apps/flutter_parent/lib/utils/common_widgets/two_finger_double_tap_gesture_detector.dart
Test plan: Verify if the new login design is applied. Smoke test the login flow.
refs: MBL-16471
release note: Improved the design of the login screen.
> [MBL-16471][Parent] Login improvements

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AnnouncementsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DiscussionsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/NotificationsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PagesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SyllabusE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/GradesElementaryE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ImportantDatesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SubmissionsApi.kt
Refactor and extract API calls from the case methods into private method calls.
Minor refactor + add some missing logs.
refs: MBL-16518
> [MBL-16518][Student] - Refactor and extract API calls from Student E2E tests

- apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
- libs/pandautils/src/main/res/layout/viewholder_edit_dashboard_group.xml
> [MBL-16634][Student] Edit Groups

- libs/pandautils/src/main/java/com/instructure/pandautils/views/FloatingRecordingView.kt
- libs/pandautils/src/main/res/layout/view_floating_media_recorder.xml
> [MBL-16696][Teacher] Speedgrader tablet crash

- apps/student/src/main/java/com/instructure/student/features/dashboard/notifications/StudentDashboardRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/dashboard/notifications/TeacherDashboardRouter.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/itemviewmodels/UploadItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/AppDatabase.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/AppDatabaseMigrations.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/entities/DashboardFileUploadEntity.kt
- libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModelTest.kt
Test plan: in the ticket, also test the migration please
refs: MBL-16670
release note: Dashboard upload notification improvements.
> [MBL-16670][Student] Share Extension | Route to the file location after clicking on the Successful Dashboard notification

- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/OfflineContentRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/OfflineContentViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/OfflineContentRepositoryTest.kt
Test plan:
refs: MBL-16707
<table>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>
> [MBL-16707][Student] Optimise offline content screen files fetching

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
Implement add single file as comment test cases to Student and Teacher app as well.
refs: MBL-16526
> [MBL-16526][Student][Teacher] - Implement add files to comments tab test

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
Fix breaking DashboardE2E test on the offline branch in Student application
> Offline test fix

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt
Remove stubbed quiz assignment details interaction test.
refs: MBL-16484
> [MBL-16484][Student] - Remove outdated stubbed quiz assignment details interaction test

- apps/student/src/main/java/com/instructure/student/features/assignmentdetails/gradecellview/GradeCellViewData.kt
Test plan: in the ticket, and also smoke test the grade cell with different states/grades.
refs: MBL-16757
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/660688ce-3b0e-41b0-8d7b-66241f236ea7" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/25d2f08f-3164-4339-a28a-34a7fa1132c0" maxHeight=500></td>
</tr>
</table>
> [MBL-16757][Student] Muted graded submissions to Complete/Incomplete assignments show as Incomplete

- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderCommentsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
Test plan: Description is in the ticket. The change that I removed was a legacy fix for some issues with the bottom sliding panel, smoke test the sliding panel thoroughly and look out for any potential issues. If there is any issue compare it with the current version.
refs: MBL-16753
release note: Fixed a bug where the annotation toolbar would disappear when entering a comment
> [MBL-16753][Teacher] Submission comment disables annotations

- apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt
Test plan: in the ticket. Check discussions also.
refs: MBL-16754
release note: none.
> [MBL-16754][Teacher] Announcements empty view missing

- apps/teacher/src/main/java/com/instructure/teacher/presenters/PeopleListPresenter.kt
> [MBL-16797][Teacher] People is not displayed after deleting a filter and remaining on the search input field

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/DashboardPageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InAppUpdatePageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubAnnotation.kt
- libs/pandautils/src/main/res/layout/item_dashboard_announcement.xml
Create interaction test case for global announcements in Dashboard.
refs: MBL-16492
> [MBL16492][Teacher] - Create interaction test case for global announcements in Dashboard

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
Fix breaking DashboardE2E test in offline branch. (should wait for the view and refactor scrolling process)
> Fix breaking DashboardE2E test in offline branch

- apps/student/src/main/java/com/instructure/student/di/feature/PageListModule.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListFragment.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListRepository.kt
- apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
- apps/student/src/main/java/com/instructure/student/router/RouteResolver.kt
- apps/student/src/main/java/com/instructure/student/util/TabHelper.kt
- apps/student/src/test/java/com/instructure/student/features/pages/list/PageListLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/pages/list/PageListNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/pages/list/PageListRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/PageDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/PageDao.kt
Test plan: Test the Page list online and offline.
refs: MBL-16776
> [MBL-16776][Student] Offline Page list

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AnnouncementsListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsDetailsPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditAnnouncementPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/FileListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PeopleListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/TodoPage.kt
Extend, stabilize, add assertions, simplify, extract and add methods to many E2E tests in the Teacher app.
Successful E2E test run: https://app.bitrise.io/build/6e761cd1-06d9-4fbd-89a1-44976538cf69
refs: MBL-16326
> [MBL-16326][Teacher] - Other test implementations/extensions in Teacher app

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SubmissionsApi.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/SubmissionApiModel.kt
Excuse grade, open submission, expand collapse implementation in gradesE2E test.
refs: MBL-16334
> [MBL-16334][Student] - Excuse grade, open submission, expand collapse implementation in GradesE2E test

- apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionBottomSheetMenuFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt
- apps/teacher/src/main/res/layout/bottom_sheet_discussion_menu.xml
Test plan: Steps are in the ticket.
refs: MBL-16687
> [MBL-16687][Teacher] Reply more menu is out of screen in landscape mode 

- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
Test plan: Steps are in the ticket.
refs: MBL-16678
> [MBL-16678][Teacher] Tablet: Remove split view from Edit Dashboard screen

- apps/student/src/androidTest/java/com/instructure/student/ui/utils/di/TestOfflineDatabaseProviderModule.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/di/LoginModule.kt
- apps/student/src/main/java/com/instructure/student/features/login/StudentAcceptableUsePolicyRouter.kt
- apps/student/src/main/java/com/instructure/student/features/login/StudentLoginNavigation.kt
- apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt
- apps/student/src/main/java/com/instructure/student/util/AppManager.kt
- apps/teacher/src/main/java/com/instructure/teacher/tasks/TeacherLogoutTask.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/DatabaseProvider.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/OfflineDatabaseProvider.kt
Test plan: offline db should be removed on logout, but not when switching user
refs: MBL-16705
> [MBL-16705][Student] Clear Offline user data on logout

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
- automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConversationsApi.kt
Implement E2E test for filtering Inbox by Course.
Add new API method to create message for course.
Rename filtering method.
refs: MBL-16836
> [MBL-16836] [Teacher] - Implement E2E test case for inbox filtering by course

- apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/ConferenceDetailsRenderTest.kt
- apps/student/src/main/java/com/instructure/student/di/ConferenceDetailsModule.kt
- apps/student/src/main/java/com/instructure/student/di/ConferenceListModule.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/ConferenceDetailsEffectHandler.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/ConferenceDetailsRepository.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/datasource/ConferenceDetailsDataSource.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/datasource/ConferenceDetailsLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/datasource/ConferenceDetailsNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/ui/ConferenceDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/ui/ConferenceDetailsRepositoryFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_details/ui/ConferenceDetailsView.kt
- apps/student/src/main/java/com/instructure/student/mobius/conferences/conference_list/ui/ConferenceListView.kt
- apps/student/src/main/java/com/instructure/student/router/RouteResolver.kt
- apps/student/src/test/java/com/instructure/student/test/conferences/conference_details/ConferenceDetailsEffectHandlerTest.kt
- apps/student/src/test/java/com/instructure/student/test/conferences/conference_details/ConferenceDetailsLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/test/conferences/conference_details/ConferenceDetailsNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/test/conferences/conference_details/ConferenceDetailsRepositoryTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/ConferenceRecordingEntity.kt
Test plan: test conference details online and offline
refs: MBL-16793
> [MBL-16793][Student] Offline conference details

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt
refs: MBL-16830
test plan: Test the pandata reporting after logout/switch user.
> [MBL-16830][Student][Teacher] Clear pandata token on switch user

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt
- apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt
- apps/student/src/test/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModelTest.kt
refs: MBL-16846
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/38b3b282-0662-4f58-964f-d4fc829f6c02" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/c84e16d1-a2de-47a4-a08d-64fcc06272ed" maxHeight=500></td>
</tr>
</table>
> [MBL-16846][Student] Navigate to hidden tabs

- apps/student/src/main/java/com/instructure/student/di/feature/PeopleListModule.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListFragment.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListRepository.kt
- apps/student/src/main/java/com/instructure/student/fragment/PeopleDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/holders/PeopleViewHolder.kt
- apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
- apps/student/src/main/java/com/instructure/student/router/RouteResolver.kt
- apps/student/src/main/java/com/instructure/student/util/TabHelper.kt
- apps/student/src/test/java/com/instructure/student/features/people/list/PeopleListRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/list/UserFacadeTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/list/datasource/PeopleListLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/list/datasource/PeopleListNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UserAPI.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/EnrollmentDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/UserDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/EnrollmentDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncSettingsEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/UserEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/PeopleFacade.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/UserFacade.kt
> [MBL-16788][Student] Offline People List

- apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt
Test plan: In the ticket. Smoke test also course and user files.
refs: MBL-16891
> [MBL-16891][Student] Crash in group files

- apps/student/src/main/java/com/instructure/student/di/feature/PeopleDetailsModule.kt
- apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/people/details/PeopleDetailsRepository.kt
- apps/student/src/main/java/com/instructure/student/features/people/list/PeopleListFragment.kt
- apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
- apps/student/src/main/java/com/instructure/student/router/RouteResolver.kt
- apps/student/src/test/java/com/instructure/student/features/people/details/PeopleDetailsRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/details/datasource/PeopleDetailsLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/details/datasource/PeopleDetailsNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/people/list/UserFacadeTest.kt
- apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/GroupAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UserAPI.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/EnrollmentDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/EnrollmentDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/GradesDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/UserFacade.kt
> [MBL-16881][Student] Offline People Details

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FeaturesAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/di/ApiModule.kt
- libs/pandautils/schemas/com.instructure.pandautils.room.appdatabase.AppDatabase/7.json
- libs/pandautils/schemas/com.instructure.pandautils.room.appdatabase.AppDatabase/8.json
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/appdatabase/daos/AttachmentDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/appdatabase/daos/EnvironmentFeatureFlagsDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/appdatabase/daos/SubmissionCommentDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/DatabaseModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/FeatureFlagModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabase.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabaseMigrations.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/daos/EnvironmentFeatureFlagsDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/entities/EnvironmentFeatureFlags.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/common/Converters.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/common/daos/AttachmentDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/common/daos/SubmissionCommentDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/common/entities/AttachmentEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/common/entities/SubmissionCommentEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/utils/FeatureFlagProviderTest.kt
Test plan: Check if the feature flags are saved to the AppDatabase.
refs: MBL-16904
> [MBL-16904][Student][Teacher] Save environment feature flags

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/PageAPI.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
Test plan: only available on beta (you can test it by masquerade as user and qr login on the phone)
refs: MBL-16698
> [MBL-16698][Student] Update Page list call

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DiscussionsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ImportantDatesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AnnouncementListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/GradesPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/NotificationPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt
- apps/student/src/main/res/layout/fragment_file_search.xml
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
Implement many test extensions and stabilizations.
refs: MBL-16333
> [MBL-16333][Student] -  Other Student E2E test extensions and stabilizations

- apps/student/src/main/java/com/instructure/student/adapter/FileListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt
Test plan: test refreshing in case of adding file, adding folder, removing file, removing folder.
refs: MBL-16937
> [MBL-16937][Student] Folder item size does not updated automatically

- apps/student/src/main/java/com/instructure/student/fragment/LtiLaunchFragment.kt
Test plan: Steps are in the ticket
refs: MBL-16938
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/6fb67c34-ffb5-4f15-9f48-7257bf1bcf0a" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/085ccc2f-b6f3-4711-b9bd-490a88e617c3" maxHeight=500></td>
</tr>
</table>
> [MBL-16938][Student] Error occurs when clicking on Launch External Tool

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt
Test plan: Run E2E tests
refs: none
affects: All
> Fix E2E tests

- apps/student/flank_e2e_min.yml
- apps/teacher/flank_e2e_min.yml
Add flank_e2e_min.yml min target workflow files
refs: MBL-16864
> [MBL-16864][Student][Teacher] - Add flank_e2e_min.yml min target workflow files

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PickerSubmissionUploadInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/QuizListInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizListPage.kt
- apps/student/src/main/java/com/instructure/student/adapter/QuizListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/holders/QuizViewHolder.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt
Test plan: quiz points should be hidden if letter grade only.
refs: MBL-16915
> [MBL-16915][Student] Quizzes screen letter grade only

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
- apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
Test plan: test discussions LGO
refs: MBL-16913
> [MBL-16913][Student] Discussions LGO

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt
- apps/student/src/main/java/com/instructure/student/adapter/ModuleListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/holders/ModuleViewHolder.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
Test plan: test modules lgo
refs: MBL-16921
> [MBL-16921][Student] Modules LGO

- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsEffectHandler.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsPresenter.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricModels.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricPresenter.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/ui/SubmissionRubricFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsViewState.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeCellViewState.kt
- apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt
- apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEffectHandlerTest.kt
- apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/rubricTab/SubmissionRubricPresenterTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.kt
Test plan: test rubric with and without restrict quantitative data.
refs: MBL-16956
> [MBL-16956][Student] Rubric LGO

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
Implement not favorited group interaction test on dashboard
refs: MBL-16737
> [MBL-16737][Student] - Implement not favorited group interaction test on dashboard

- apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt
- apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt
- apps/student/src/main/res/layout/fragment_inbox_compose_message.xml
- apps/teacher/src/main/java/com/instructure/teacher/fragments/AddMessageFragment.kt
- apps/teacher/src/main/res/layout/fragment_add_message.xml
Test plan: Check the inbox compose screen, the labels should always be visible.
refs: MBL-16981
> [MBL-16981][All] Inbox input labels always visible

- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusView.kt
> [MBL-17001][Student] Syllabus Summary does not displayed when creating summary event while user has logged in

- apps/flutter_parent/lib/models/course.dart
- apps/flutter_parent/lib/models/course.g.dart
- apps/flutter_parent/lib/models/grade_cell_data.dart
- apps/flutter_parent/lib/models/grading_scheme_item.dart
- apps/flutter_parent/lib/models/grading_scheme_item.g.dart
- apps/flutter_parent/lib/models/serializers.dart
- apps/flutter_parent/lib/models/serializers.g.dart
- apps/flutter_parent/lib/network/api/course_api.dart
- apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
- apps/flutter_parent/lib/screens/assignments/grade_cell.dart
- apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
- apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart
- apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
- apps/flutter_parent/test/models/course_test.dart
- apps/flutter_parent/test/screens/assignments/grade_cell_data_test.dart
- apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
Test plan: test assignment list and assignment details with and without quantitative data restriction
refs: MBL-16996
release note: Added letter grade conversion by grading scheme.
> [MBL-16996][Parent] Score to letter grade conversion

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentListInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/CourseGradesInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NotificationInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt
- apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/assignment/AssignmentListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/assignmentdetails/AssignmentDetailsViewModel.kt
- apps/student/src/main/java/com/instructure/student/features/assignmentdetails/gradecellview/GradeCellViewData.kt
- apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt
- apps/student/src/main/java/com/instructure/student/holders/AssignmentViewHolder.kt
- apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
- apps/student/src/main/java/com/instructure/student/holders/NotificationViewHolder.kt
- apps/student/src/main/java/com/instructure/student/util/BinderUtils.kt
- apps/student/src/main/java/com/instructure/student/widget/GradesViewWidgetService.kt
- apps/student/src/main/java/com/instructure/student/widget/NotificationViewWidgetService.kt
- apps/student/src/main/java/com/instructure/student/widget/TodoViewWidgetService.kt
- apps/student/src/test/java/com/instructure/student/features/assignmentdetail/gradecellview/GradeCellViewDataTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/GradingSchemeRow.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/StreamItem.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ModelExtensions.kt
- libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt
- libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt
- libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/utils/ModelExtensionsTest.kt
Test plan: 
- Verify that the scores are correctly converted to letter grade on all the affected screens.
- Verify that we never show quantitative data when it is restricted.
- Verify that we don't convert the scores when quantitative data is not restricted.
- Compared grades with the web for reference.
refs: MBL-16995
release note: Added letter grade conversion when quantitative data is restricted.
> [MBL-16995][Student] Score to letter grade conversion

- apps/flutter_parent/lib/models/grade_cell_data.dart
> [MBL-17008][Parent] Empty circle shown on assignment details when opening zero points assignment/quiz

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/PageListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/CustomViewAssertions.kt
Implement search logics to Teacher AssignmentE2E test.
Refactor DoesNotExistAssertion to handle timeout in seconds.
refs: MBL-16951
> [MBL-16951][Teacher] - Extend AssignmentsE2E test with search logics

- apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
> [MBL-17011][Student] Documents embedded in RCE content don't load

- apps/student/src/main/java/com/instructure/student/adapter/CourseBrowserAdapter.kt
- apps/student/src/main/java/com/instructure/student/di/feature/CourseBrowserModule.kt
- apps/student/src/main/java/com/instructure/student/features/coursebrowser/datasource/CourseBrowserLocalDataSource.kt
- apps/student/src/test/java/com/instructure/student/features/offline/coursebrowser/CourseBrowserLocalDataSourceTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Tab.kt
Test plan: only synced course tabs should be enabled and clickable in course browser
refs: MBL-16783
> [MBL-16783][Student] Only display synced tabs in Course Browser

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/di/NavigationActivityModule.kt
- apps/student/src/main/java/com/instructure/student/features/modules/progression/CourseModuleProgressionFragment.kt
- apps/student/src/main/java/com/instructure/student/features/navigation/NavigationRepository.kt
- apps/student/src/main/java/com/instructure/student/features/navigation/datasource/NavigationDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/navigation/datasource/NavigationLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/navigation/datasource/NavigationNetworkDataSource.kt
- apps/student/src/test/java/com/instructure/student/features/grades/GradesListRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/features/navigation/NavigationRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/features/navigation/datasource/GradesListLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/navigation/datasource/GradesListNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/pages/details/PageDetailsRepositoryTest.kt
Test plan: Test that links embedded in HTML content (pages, assignment details, etc) route to the correct screens in offline mode as well.
refs: MBL-16875
> [MBL-16875][Student] Navigate links offline

- apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionFilesRenderTest.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/modules/progression/NotAvailableOfflineFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsEffectHandler.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/SubmissionCommentsView.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/views/CommentAttachmentsView.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/views/CommentSubmissionView.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/files/ui/SubmissionFilesAdapter.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
- apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEffectHandlerTest.kt
Test plan: 
- the text entry type should work offline as well
- other types should show the not available offline screen or if it has a button it should show the offline warning dialog when clicked
- on the files tab the files in the list should have icon by type
refs: MBL-16880
> [MBL-16880][Student] Offline submission details

- apps/student/src/main/java/com/instructure/student/holders/CourseViewHolder.kt
Fix minor dev maintenance issue by removing unnecessary course grade white space character from course card.
refs: MBL-17035
> [MBL-17035][Student] - Remove unnecessary whitespace from course grade text in course cards

- apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/SyncProgressDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncHelper.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/CourseProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/FilesTabProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncFrequency.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncSettingsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncSettingsViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncSettingsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/OfflineConverters.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/SyncSettingsEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/SyncSettingsFacade.kt
- libs/pandautils/src/main/res/layout/fragment_sync_settings.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/OfflineSyncHelperTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/CourseProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/FileSyncProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/FilesTabProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/TabProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/syncsettings/SyncSettingsViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/SyncSettingsFacadeTest.kt
Test plan: Quick smoke test of the progress screen.
refs: MBL-17058
> [MBL-17058] Sync progress unit tests

- libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileUploadUtils.kt
Test plan: Steps are in the ticket
refs: MBL-17002
> [MBL-17002][Student][Teacher] Fix iWork MIME types

- apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostGradeView.kt
- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
- apps/teacher/src/main/res/layout/dialog_post_graded_everyone.xml
Test plan: 
- Open an assignment's submissions
- Click 'Post Settings' in top right corner to open Post Policy Settings
refs: MBL-17042
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/e7c68cc7-7186-46bd-8f73-a0687d7b3ccc" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/9ed2a418-471a-4841-b8f0-eb176c9b2ba2" maxHeight=500></td>
</tr>
</table>
> [MBL-17042][Teacher] Tablet: Posted grade page header color mismatch

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/EditDashboardPage.kt
Fix E2E workflow tests on offline branch.
refs: MBL-17071
> [MBL-17071][Student] - Investigate and fix offline branch tests - E2E workflow

- apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
Test plan:
1. Add a new student
2. Select the new student
3. Delete selected student at "Manage students" screen
refs: MBL-17014
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/a544e847-6e84-42d5-b463-7821aee4ea10" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/50fe8196-b432-470d-bd0c-0bcf4188a2bd" maxHeight=500></td>
</tr>
</table>
> [MBL-17014][Parent] Deleted student remains selected

- apps/student/src/main/java/com/instructure/student/features/dashboard/notifications/StudentDashboardRouter.kt
- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
- apps/student/src/main/res/layout/course_grid_recycler_refresh_layout.xml
- apps/teacher/src/main/java/com/instructure/teacher/features/dashboard/notifications/TeacherDashboardRouter.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineSyncModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/itemviewmodels/SyncProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/AggregateProgressObserver.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/SyncProgressDao.kt
- libs/pandautils/src/main/res/layout/fragment_sync_progress.xml
- libs/pandautils/src/main/res/layout/item_sync_progress.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/itemviewmodels/SyncProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/AggregateProgressObserverTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModelTest.kt
Test plan: See ticket and design. Error handling is not finalized, test mostly the happy path.
refs: MBL-16630
> [MBL-16630][Student] Sync Dashboard notification 

- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
> [MBL-17045][Student] Manage offline content screen can be reached while offline

- apps/student/src/main/java/com/instructure/student/activity/LoginLandingPageActivity.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt
Test plan: 
- test auto sync, it should run for the current user
- test removing previous user removes the db and files of it
- test change user offline
- test login landing page actions offline
refs: MBL-17004
> [MBL-17004][Student] Multiple user support

- libs/pandautils/src/main/res/layout/fragment_sync_progress.xml
> [MBL-17073][Student] Sync progress success feedback

- apps/student/src/main/java/com/instructure/student/fragment/ParentFragment.kt
Test plan: Crash happens on tablet when the module list fails to load, but I couldn't reproduce ite.
refs: MBL-17092
> [MBL-17092][Student] Module list crash

- apps/student/src/main/java/com/instructure/student/activity/CandroidPSPDFActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/SettingsActivity.kt
- apps/student/src/main/java/com/instructure/student/di/feature/CourseBrowserModule.kt
- apps/student/src/main/java/com/instructure/student/features/coursebrowser/datasource/CourseBrowserLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/modules/util/ModuleUtility.kt
- apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
- apps/student/src/main/res/layout/activity_settings.xml
- apps/student/src/test/java/com/instructure/student/features/offline/coursebrowser/CourseBrowserLocalDataSourceTest.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewStyler.kt
> [MBL-16794][Student] Disable every functionality that is not available offline

- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusTabAdapter.kt
- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusView.kt
> [MBL-17108][Student] Fix Syllabus WebView routing

- apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
Test plan: In the ticket. See the update in the description.
refs: MBL-17103
> [MBL-17103][Student] Change offline state on Dashboard

- apps/student/src/main/java/com/instructure/student/features/grades/GradesListRecyclerAdapter.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/EnrollmentAPI.kt
- libs/pandautils/schemas/com.instructure.pandautils.room.offline.OfflineDatabase/1.json
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/GradesEntity.kt
> [MBL-17109][Student] Fix offline Course grade

- apps/student/src/main/java/com/instructure/student/features/discussion/list/DiscussionListFragment.kt
Test plan: Smoke test discussion list
> DiscussionListFragment test fix.

- apps/student/src/main/java/com/instructure/student/activity/InterwebsToApplication.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineModule.kt
> [MBL-17107][Student] Fix act as user QR login

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
Fix breaking tablet InboxPageTest interaction test.
> Nightly - Fix breaking Teacher Tablet interaction test

- apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_screen.dart
> [MBL-17015][Parent] Cancel button colour is probably fixed and is not accessible

- apps/student/src/main/java/com/instructure/student/di/feature/ModuleProgressionModule.kt
- apps/student/src/main/java/com/instructure/student/features/modules/progression/ModuleProgressionRepository.kt
- apps/student/src/test/java/com/instructure/student/features/modules/progression/ModuleProgressionRepositoryTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/PageAPI.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/LocalFileDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/PageDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/LocalFileDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/PageDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/PageFacade.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/PageFacadeTest.kt
Test plan: Test course sync with a course that has no tabs. Smoke test offline sync with other courses as well.
refs: MBL-17136
> [MBL-17136][Student] Fixed course sync for hidden tabs

- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/FileSyncWorker.kt
refs: MBL-17106
test plan: Check if the reports are made in Crashlytics.
> [MBL-17106][Student] Sync error Crashlytics reports

- apps/student/src/main/java/com/instructure/student/features/dashboard/edit/datasource/StudentEditDashboardNetworkDataSource.kt
- apps/student/src/test/java/com/instructure/student/features/dashboard/edit/datasource/StudentEditDashboardNetwoekDataSourceTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
> [MBL-16960][Student] Filter unpublished future courses.

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
Test plan: 
- Verify that the file links in HTML content route to the files in offline and online mode correctly. Offline should only work when the file is downloaded. 
- Verify that the Home Page is correctly synced even when the pages tab is not visible.
refs: MBL-17145
> [MBL-17145][Student] Fix file links and home page sync in offline mode.

- apps/student/src/main/java/com/instructure/student/features/files/list/FileListLocalDataSource.kt
- apps/student/src/test/java/com/instructure/student/features/file/list/FileListLocalDataSourceTest.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/FileFolderDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/HtmlParser.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/FileFolderDao.kt
- libs/pandautils/src/main/res/layout/item_additional_files_progress.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/HtmlParserTest.kt
Test plan:
- Create a Page/Assignment/Discussion where we have a file link that is not a public file.
- Check that the file is synced and can be opened offline.
- Check that the linked file does not show up in the course files list.
- Smoke test file sync and files tab in offline.
refs: MBL-17149
> [MBL-17149][Student] Sync linked files

- libs/pandautils/src/main/res/layout/fragment_offline_content.xml
> [MBL-17147][Student] Manage Offline Content Scroll Behaviour

- apps/student/src/main/java/com/instructure/student/di/feature/FileSearchModule.kt
- apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchLocalDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchRepository.kt
- apps/student/src/main/java/com/instructure/student/fragment/ParentFragment.kt
- apps/student/src/test/java/com/instructure/student/features/file/search/FileSearchLocalDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/file/search/FileSearchNetworkDataSourceTest.kt
- apps/student/src/test/java/com/instructure/student/features/file/search/FileSearchRepositoryTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FileFolderAPI.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/FileFolderDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/FileFolderDao.kt
Test plan: File search in course files should work correctly in offline mode. Smoke test file list also and file opening in offline/online mode.
refs: MBL-17150
> [MBL-17150][Student] Offline file search

- libs/pandautils/src/main/assets/discussion_topic_header_html_template.html
- libs/pandautils/src/main/assets/discussion_topic_header_html_template_rtl.html
- libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/HtmlContentFormatter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
Test plan: See ticket. I added a comment to clarify the issue and provided a test case.
refs: MBL-17143
release note: Fixed a bug where the discussion reply actions were not working in some cases.
> [MBL-17143][Student][Teacher] JS events are not responsive when we have an lti or google docs iframe in the discussion reply

- apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/discussion/DiscussionsDetailsFragment.kt
Test plan: In the ticket. See my comment for further explanation.
refs: MBL-17088
release note: Fixed a bug where external tool buttons wouldn't show up in discussion replies.
> [MBL-17088][Student][Teacher] Fixed LTI and Google docs buttons in discussion replies.

- apps/teacher/src/main/java/com/instructure/teacher/fragments/AttendanceListFragment.kt
> [MBL-17161][Teacher] Roll Call fails to load in IAD/PDX region

- apps/flutter_parent/android/app/src/main/AndroidManifest.xml
- apps/flutter_parent/lib/l10n/app_localizations.dart
- apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
- apps/flutter_parent/lib/utils/notification_util.dart
- apps/flutter_parent/pubspec.lock
- apps/flutter_parent/pubspec.yaml
- apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
- apps/flutter_parent/test/utils/notification_util_test.dart
- apps/flutter_parent/test/utils/test_helpers/mock_helpers.dart
- apps/flutter_parent/test/utils/test_helpers/mock_helpers.mocks.dart
refs: MBL-17158
release note: Fixed a bug where alerts were not working on Android 14
> [MBL-17158][Parent] Assignment alerts not working on Android 14

- libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt
Test plan: Test discussion redesign in release build.
refs: MBL-17171
release note: Added support for redesigned discussions and announcements.
> [MBL-17171][Student][Teacher] Remove discussion redesign local feature flag

- apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/SimpleWebViewFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderLtiSubmissionFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderQuizWebViewFragment.kt
> [MBL-17096][Teacher] Page error when accessing NQ on Teacher app

- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/DiscussionTopicEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/DiscussionTopicFacade.kt
> [MBL-17172][Student] Annoucement replies not loading in offline mode

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/BookmarksFragment.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/discussion/DiscussionsDetailsFragment.kt
> [MBL-17162][Student][Teacher] Change deprecated android yes/no string values to ok/cancel

- apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt
- libs/pandautils/schemas/com.instructure.pandautils.room.offline.OfflineDatabase/1.json
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/CourseSyncProgressDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/FileSyncProgressDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineSyncModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/AggregateProgressObserver.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSync.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/FileSync.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncHelper.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/AdditionalFilesProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/CourseProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/FilesTabProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/TabProgressItemViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/CourseSyncProgressDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/CourseSyncProgressEntity.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/OfflineSyncHelperTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/AggregateProgressObserverTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/SyncProgressViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/AdditionalFilesProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/CourseProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/FilesTabProgressItemViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/progress/itemviewmodels/TabProgressItemViewModelTest.kt
Test plan: Test the sync. Check the background progresses after cancel, restart, etc.
refs: MBL-17180
> [MBL-17180][Student] Sync fixes

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/SettingsActivity.kt
- apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/dashboard/DashboardRepository.kt
- apps/student/src/main/java/com/instructure/student/features/modules/util/ModuleUtility.kt
- apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
- apps/student/src/test/java/com/instructure/student/features/dashboard/DashboardRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/test/util/ModuleUtilityTest.kt
- libs/pandautils/schemas/com.instructure.pandautils.room.offline.OfflineDatabase/1.json
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/LockInfoDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/LockedModuleDaoTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/PageDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSync.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/FileSync.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/HtmlParser.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/LockInfoDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/PageDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/LockInfoEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/LockedModuleEntity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/LockInfoFacade.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/sync/HtmlParserTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/LockInfoFacadeTest.kt
- libs/recyclerview/src/main/java/com/instructure/pandarecycler/PaginatedRecyclerAdapter.kt
Test plan: 
- Each bug is listed in the ticket.
- The best way to review is commit by commit, each commit represents one bugfix.
refs: MBL-17182
> [MBL-17182][Student] Offline content fixes

- libs/pandautils/src/main/java/com/instructure/pandautils/di/FeatureFlagModule.kt
refs: MBL-17201
test plan: Check the offline features.
> [MBL-17201][Student] Fetch feature flags for the correct user

- apps/student/src/main/java/com/instructure/student/navigation/StudentWebViewRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/navigation/TeacherWebViewRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/navigation/WebViewRouter.kt
refs: MBL-17212
test plan: Navigate to an external route from the discussion redesign page.
> [MBL-17212][Student][Teacher] Open external routes from discussions

- apps/student/src/main/java/com/instructure/student/mobius/common/ui/MobiusFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/SpeedGraderCommentHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/mobius/common/ui/MobiusFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ActivityExtensions.kt
Test plan:
- submission details -> comments -> student avatar click -> crash
- also modified the mobiusFragment slightly in teacher and student, smoke test a few screens like SubmissionList ans Details in student and Syllabus in Teacher
refs: MBL-17237
> [MBL-17237][Teacher] SpeedGraderCommentHolder crash

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAllCoursesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineCourseBrowserE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncProgressE2ETest.kt
Fix breaking offline E2E test.
Stabilize all remaining offline E2E tests.
> Nightly - Offline E2E tests stabilization

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ToDo.kt
> [MBL-17241][Student] One Ungraded quiz is included in the To Do list when there are multiple

- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsViewModel.kt
- apps/student/src/test/java/com/instructure/student/features/assignmentdetails/AssignmentDetailsViewModelTest.kt
> [MBL-17211][Student] Hide submit button when submission is not possible

- libs/pandautils/src/main/java/com/instructure/pandautils/di/ApplicationModule.kt
Test plan: open student app from teacher by student view
refs: MBL-17253
release note: Fixed StudentView crash.
> [MBL-17253][Student] App crashes when opened from Teacher Student View

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
Fix breaking OfflineDashboardE2ETest.
> Nightly - Fix breaking OfflineDashboardE2ETest

- apps/teacher/src/main/java/com/instructure/teacher/fragments/LtiLaunchFragment.kt
Test plan: in the ticked, and also test this https://instructure.atlassian.net/browse/MBL-17189, we introduced the issue with this change.
refs: MBL-17255
release note: LTI launch fix.
> [MBL-17255][Teacher] LTI launch inconsistent between teacher and student apps

- apps/student/src/main/java/com/instructure/student/adapter/BaseListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/BookmarkRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/ExpandableRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/InboxRecipientAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/adapter/TodoListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/discussion/list/adapter/DiscussionListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/grades/GradesListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/pages/list/PageListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/features/quiz/list/QuizListRecyclerAdapter.kt
- libs/recyclerview/src/main/java/com/instructure/pandarecycler/BaseRecyclerAdapter.kt
Attempt to fix ModuleListRecyclerView lateinit not initialized flakyness.
> Attempt to fix ModuleListRecyclerView lateinit not initialized flakyness

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/PersonDetailsPage.kt
Implement Offline test for People page.
Stabilize existing ManageOfflineContentE2ETest.
Add some page object methods and test class.
refs: MBL-17312
> [MBL-17312][Student] - Create Offline E2E test for People page

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/ModuleListRenderTest.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListEffectHandler.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListModels.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListPresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListUpdate.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListMobiusFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListRecyclerAdapter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListViewState.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListSubHeaderBinder.kt
- apps/teacher/src/main/res/layout/adapter_module.xml
- apps/teacher/src/main/res/layout/adapter_module_item.xml
- apps/teacher/src/main/res/layout/adapter_module_sub_header.xml
- apps/teacher/src/main/res/menu/menu_module.xml
- apps/teacher/src/main/res/menu/menu_module_list.xml
- apps/teacher/src/qa/java/com/instructure/teacher/SingleFragmentTestActivity.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListEffectHandlerTest.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListPresenterTest.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListUpdateTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ModuleAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/postmodels/BulkUpdateResponse.kt
- libs/pandares/src/main/res/drawable/ic_publish.xml
- libs/pandares/src/main/res/drawable/ic_unpublish.xml
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/Extensions.kt
Test plan: See ticket for design. Test all the publish/unpublish actions. Compare with the web if needed.
refs: MBL-17276
> [MBL-17276][Teacher] Bulk module update actions

- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouteHelperNetworkDataSource.kt
> [MBL-17345][Student][Teacher] Course discussion feature flag independent from account

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsFragment.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/page/PageExtensions.kt
> [MBL-17274][Student] Remind me UI tests

- apps/flutter_parent/android/app/src/main/AndroidManifest.xml
- apps/student/src/main/AndroidManifest.xml
- apps/teacher/src/main/AndroidManifest.xml
Test plan: There is no need to test this, we still need to upload the asset links, so until nothing changes. 
refs: MBL-17238
affects: All
> [MBL-17238][All] Auto verify wildcard deeplinks

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
Test plan: In the ticket + smoke test dashboard reorder and bottom navigation.
refs: MBL-17368
release note: Fixed a crash while reordering the dashboard cards.
> [MBL-17368][Student] Dashboard reorder issues

- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListEffectHandler.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListModels.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListUpdate.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListEffectHandlerTest.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListUpdateTest.kt
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ProgressAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Progress.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/build.gradle
- libs/pandautils/schemas/com.instructure.pandautils.room.appdatabase.AppDatabase/10.json
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/CanvasTheme.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/ProgressModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/ProgressDialogFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/ProgressPreferences.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/ProgressUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/ProgressViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/progress/composables/ProgressScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/mvvm/Event.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabase.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabaseMigrations.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/daos/ModuleBulkProgressDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/entities/ModuleBulkProgressEntity.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/filter/ContextFilterViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/progress/ProgressViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/progress/ProgressViewModelTests.kt
Test plan: Test the bulk update progress screen. See ticket for design. All bulk module operations should show the progress screen **except** when only a single module is updated.
refs: MBL-17277
> [MBL-17277][Teacher] Progress screen

- apps/student/build.gradle
- apps/teacher/build.gradle
Test plan: Check the Bitrise builds.
refs: MBL-17382
affects: Student/Teacher
> [MBL-17382][Student/Teacher] Create build flavor for Compose Bitrise builds

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAnnouncementsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineCourseBrowserE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineFilesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLeftSideMenuE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLoginE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncProgressE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncSettingsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
Implement Offline Announcements E2E test.
Add SecondaryFeatureCategory to other Offline tests.
refs: MBL-17370
> [MBL-17370][Student] - Create Offline Announcements E2E test

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt
> Fix breaking testPagesE2E

- apps/teacher/src/main/res/layout/fragment_dialog_update_file.xml
- libs/pandautils/src/main/res/drawable/bg_rounded_rectangle.xml
>  [Teacher] Bulk module update CRs

- apps/student/flank_coverage.yml
- apps/student/flank_e2e_coverage.yml
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ShareExtensionInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/UserFilesInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileUploadPage.kt
- apps/teacher/flank_coverage.yml
- apps/teacher/flank_e2e_coverage.yml
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubCoverageAnnotation.kt
Resurrect code coverage, update device, manage annotations.
refs: MBL-17392
> [MBL-17392][Student][Teacher] -  Resurrect code coverage

- buildSrc/src/main/java/GlobalDependencies.kt
Test plan: Test compose screens in both apps.
refs: MBL-17416
> [MBL-17416][Student][Teacher] Fix conflicting dependencies.

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CommentLibraryE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CourseSettingsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SyllabusE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt
Simplify API calls in Teacher E2E tests.
Eliminate private API call functions within test classes.
refs: MBL-16672
> [MBL-16672][Teacher] - Simplify API calls in Teacher E2E tests

- libs/pandares/src/main/res/drawable/ic_refresh.xml
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewFragment.kt
- libs/pandautils/src/main/res/layout/fragment_discussion_details_web_view.xml
- libs/pandautils/src/main/res/menu/menu_discussion_details.xml
refs: MBL-17428
affects: Student. Teacher
release note: Fixed a bug where swipe down refreshes redesigned discussions.
> [MBL-17428][Student][Teacher] Swipe down refreshes new discussion details page

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDiscussionsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTestExtensions.kt
Implement Offline Discussions E2E test.
Add overflow extension function.
Add webview action.
refs: MBL-17385
> [MBL-17385][Student] - Create Offline Discussions E2E Test

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListSubHeaderBinder.kt
- apps/teacher/src/main/res/layout/adapter_module.xml
- apps/teacher/src/main/res/layout/adapter_module_item.xml
- apps/teacher/src/main/res/layout/adapter_module_sub_header.xml
> [MBL-17457][Teacher] Bulk publish updates

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
Extend Modules E2E Test with Unpublishable module item.
refs: MBL-17451
> [MBL-17451][Student] - Extend Modules E2E Test with unpublishable module item

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ProgressPage.kt
Fix compilation error on master (statusWrapper id changed to publishActions)
> Fix master compilation error

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarStateMapper.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
Test plan: Test with TalkBack. Compare with prod version.
refs: MBL-17323
> [MBL-17323][Student][Teacher] Calendar accessibility

- apps/student/src/main/java/com/instructure/student/features/calendar/StudentCalendarRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/inbox/list/TeacherInboxRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/DashboardFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarRouter.kt
Test plan: In the ticket. I also added some clarification there about how to reproduce the issue.
refs: MBL-17492
> [MBL-17492][Teacher] Opening left-side menu when on calendar page in landscape mode dismisses user account information

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/composables/CalendarFilterScreen.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterViewModelTest.kt
> [MBL-17429][Student][Teacher] Put Select all/Deselect All button on Calendar filter

- apps/flutter_parent/lib/models/assignment.dart
- apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsViewModel.kt
- apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
refs: MBL-17469
release note: Fixed a bug where Missing status was not visible for certain assignments.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/c9920101-849f-4324-9c60-aa55261cf3e7" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/63cd6670-1efd-451b-999a-6e2428017122" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/9bcdaf28-5369-4b2d-b545-4328b9e924f8" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/ff152add-7042-444f-8c0d-d9af411dfc11" maxHeight=500></td>
</tr>
</table>
<table> …
> [MBL-17469][Student][Parent] Add missing tag to On Paper and No Submssion assignments

- apps/teacher/src/main/java/com/instructure/teacher/fragments/ProfileEditFragment.kt
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/pandautils/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEControls.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/details/composables/ToDoScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/MediaUploadUtils.kt
Test plan: Test the RCE in the create ToDo screen. Smoke test other RCEs, the image insertion has changed a bit.
refs: MBL-17455
> [MBL-17455][Student] Compose RCE

- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/OfflineSyncHelper.kt
> [MBL-17228][Student] Enable manual sync when the battery is low

- apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt
Test plan: I couldn't reproduce it, but it's basically just a missing null check.
refs: MBL-17526
> [MBL-17526][Teacher] EditAssignmentDetails crash

- apps/flutter_parent/lib/utils/alert_helper.dart
> [MBL-17540][Parent] Alerts list filtered incorrectly

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarEventsTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarScreenTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasThemedAppBar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarEvents.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
Test plan: Run tests
refs: MBL-17266
> [MBL-17266][Student][Teacher] Calendar render tests

- apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/adapters/StudentContextFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/factory/SpeedGraderPresenterFactory.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderPresenter.kt
refs: MBL-17552
release note: Fixed a bug where not only the selected submissions would load into SpeedGrader.
> [MBL-17552][Teacher] Pass submission ids to SpeedGrader

- apps/student/src/main/java/com/instructure/student/features/calendar/StudentCalendarRepository.kt
- apps/student/src/main/java/com/instructure/student/features/calendarevent/StudentCreateUpdateEventRepository.kt
- apps/student/src/test/java/com/instructure/student/features/calendar/StudentCalendarRepositoryTest.kt
- apps/student/src/test/java/com/instructure/student/features/calendarevent/StudentCreateUpdateEventRepositoryTest.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRepository.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/calendarevent/TeacherCreateUpdateEventRepository.kt
- apps/teacher/src/test/java/com/instructure/teacher/features/calendar/TeacherCalendarRepositoryTest.kt
- apps/teacher/src/test/java/com/instructure/teacher/features/calendarevent/TeacherCreateUpdateEventRepositoryTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoRepository.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoRepositoryTest.kt
> [MBL-17581][Student][Teacher] Fix calendar course request.

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ListHeaderItem.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SelectCalendarScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/composables/CalendarFilterScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
Test plan: See design in the ticket. The functionality should remain the same. Smoke test also calendar filters.
refs: MBL-17551
> [MBL-17551][Student][Teacher] Calendar selector redesign

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt
Extend SpeedGraderE2ETest with clicking on user avatar on assignment details 'results' page.
(Covering a previous crash).
refs: MBL-17569
> [MBL-17569][Teacher] - Extend SpeedGraderE2ETest with clicking on user avatar on assignment details 'results' page.

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarEvents.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
Test plan: Verify that the full calendar is refreshed (current, next and previous month) on pull to refresh.
refs: MBL-17600
> [MBL-17600][Student][Teacher] Refresh full calendar on pull to refresh

- libs/rceditor/src/main/java/instructure/rceditor/RCEInsertDialog.kt
> [MBL-17580][Student][Teacher] RCE insert link fix

- libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.kt
> [MBL-17539][Student] Added error message when file not found

- apps/parent/build.gradle
- apps/parent/src/main/java/com/instructure/parentapp/util/AppManager.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/BaseAppManager.kt
Test plan: Run Bitrise workflows.
refs: MBL-17484
> [MBL-17484][Parent] CI/CD setup

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/StudentCreateUpdateToDoInteractionTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/TeacherCreateUpdateToDoInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateEventInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateToDoInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarEventCreateEditPage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoCreateUpdatePage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoDetailsPage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendartodo/createupdate/CreateUpdateToDoScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasAppBar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/OverflowMenu.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SingleChoiceAlertDialog.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/details/composables/ToDoScreen.kt
Test plan: I made some changes to overflow menu and single choice dialog, smoke test those please.
refs: MBL-17567
> [MBL-17567][Student][Teacher] Create edit todo tests

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateEventInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateToDoInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarScreenPage.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
Cherrypick Calendar E2E test fix from release branch
> Cherrypick Calendar E2E test fix from release branch

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
Change invalid credentials error message on login screen
> Change invalid credentials error message on login screen

- apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/MediaSubmissionViewRenderTest.kt
- apps/student/src/main/java/com/instructure/student/activity/VideoViewActivity.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/MediaSubmissionViewFragment.kt
- apps/student/src/main/res/layout/activity_video_view.xml
- apps/student/src/main/res/layout/exo_player_control_view.xml
- apps/student/src/main/res/layout/fragment_media_submission_view.xml
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewMediaFragment.kt
- apps/teacher/src/main/res/layout/activity_view_media.xml
- apps/teacher/src/main/res/layout/exo_player_control_view.xml
- apps/teacher/src/main/res/layout/fragment_speed_grader_media.xml
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/pandautils/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/activities/BaseViewMediaActivity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ExoPlayerHelper.kt
- libs/pandautils/src/main/res/layout/activity_view_media.xml
- libs/pandautils/src/main/res/layout/exo_player_control_view.xml
Test plan: Test every player view in the apps. Submissions, files, etc.
refs: MBL-17243
> [MBL-17243][Student][Teacher] Migrate ExoPlayer to Media3

- apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
- apps/student/src/main/java/com/instructure/student/fragment/AccountPreferencesFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/LocaleUtils.kt
Test plan: Easiest way to test is logging in with site admin and under Settings > Account Preferences changing the language.
refs: MBL-17655
release note: Fixed a bug, where the app would not restart after changing the language.
> [MBL-17655][All] Fix app restart

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/Utils.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/Dropdown.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CustomFrequencyScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/details/composables/EventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/details/composables/ToDoScreen.kt
Test plan: See ticket. Test it with Teacher, student has no config change on orientation.
refs: MBL-17649
> [MBL-17649][Student][Teacher] Remember delete event dialog state on configuration change

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/compose/CalendarE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentComposeTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/compose/CalendarE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherComposeTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarScreenPage.kt
Implement Calendar Screen E2E test in both the Student and Teacher apps
Add page object methods.
refs: MBL-17267
> [MBL-17267][Student][Teacher] - Implement Calendar Screen E2E tests

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateEventInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateToDoInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoCreateUpdatePage.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SelectCalendarScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
> [MBL-17638][Student][Teacher] Calendar selection A11y

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarScreenPage.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ExpandableFloatingActionButton.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
Test plan: See ticket. The switch access issue is not fixed, only the issues regarding TalkBack.
refs: MBL-17635
release note: Fixed accessibility issues in the calendar.
> [MBL-17635][Student][Teacher] "Add New" Button in Calendar Redsign a11y issues

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
> [MBL-17630][Student][Teacher] Calendar Redesign Focus Management Issues when selecting Calendar

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
- apps/teacher/src/main/res/values-en/strings.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/annotations/src/main/res/values-en/strings.xml
- libs/canvas-api-2/src/main/res/values-en/strings.xml
- libs/login-api-2/src/main/res/values-en/strings.xml
- libs/pandares/src/main/res/values-en/strings.xml
- libs/pandautils/src/main/res/values-en/strings.xml
Test plan: Smoke test the app
refs: MBL-17642
affects: All
> [MBL-17642][All] Upgrade AGP to 7.4.2

- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsFragment.kt
> [MBL-17709][Student] Fixed alarm permission error

- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpDialogFragmentBehavior.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/help/ParentHelpLinkFilter.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
- apps/parent/src/main/res/layout/fragment_dashboard.xml
- apps/parent/src/test/java/com/instructure/parentapp/features/help/ParentHelpLinkFilterTest.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/mobius/settings/help/StudentHelpDialogFragmentBehavior.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/help/TeacherHelpDialogFragmentBehavior.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginFindSchoolActivity.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/dialog/ErrorReportDialog.kt
Test plan:
- Select Help option from the Navigation Drawer.
- Try out all available options at the dialog.
- Compare the available options with the previous Parent app
- All three application should be tested because the Report a Problem dialog has been refactored
refs: MBL-17610
> [MBL-17610][Parent] Implement help dialog

- apps/student/src/main/java/com/instructure/student/di/DatabaseModule.kt
> [MBL-17765][Student] Fallback destructive migration for student db

- apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
Show 'No Internet Connection' dialog when click on 'Open in browser' link in offline mode, on anonymous discussion details screen.
Test plan: Check that click on 'Open in browser' link in an anonymous discussion details page in offline mode will show the 'No Internet Connection' dialog.
refs: MBL-17778
> [MBL-17778][Student] - Show 'No Internet Connection' dialog when click on Anonymous discussion details 'Open in browser' link

- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxViewModelTest.kt
> [MBL-17732][All] Making a conversation 'unread' by clicking on the toolbar 'unread' icon will not make the item disappear from 'archived' list

- apps/student/src/main/java/com/instructure/student/features/assignments/list/AssignmentListFragment.kt
- apps/student/src/main/java/com/instructure/student/features/assignments/list/adapter/AssignmentListRecyclerAdapter.kt
- libs/pandares/src/main/res/values/strings.xml
Add 'Grading Period' string resource and display it on the Assignment List Page top-left corner.
refs: MBL-17780
release note: Displaying 'Grading Period' string on the Assignment List Page.
<table>
<tr>
<td>
</td>
<td><img width="500" alt="image" src="https://github.com/user-attachments/assets/a3cc72fa-6260-4814-8da1-3e90144e98d2" /></td>
</tr>
</table>
> [MBL-17780][Student] - Add 'Grading Period' string resource and display it on the Assignment List Page

- apps/student/src/main/java/com/instructure/student/features/discussion/list/adapter/DiscussionListRecyclerAdapter.kt
> [MBL-17781][Student] Handle cancellation on Discussion List

- apps/flutter_parent/lib/l10n/app_localizations.dart
- apps/flutter_parent/lib/network/utils/analytics.dart
- apps/flutter_parent/lib/router/panda_router.dart
- apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
- apps/flutter_parent/lib/utils/common_widgets/web_view/simple_web_view_screen.dart
- apps/flutter_parent/test/router/panda_router_test.dart
- apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
- apps/flutter_parent/test/utils/widgets/webview/simple_web_view_screen_test.dart
Test plan: 
- Go to assignment details screen.
- Tap on submission & rubric button.
- Check if the assignment's submission website loads and the selected user is correct.
refs: MBL-17748
release note: Added submission feedback button to assignment details screen.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/6bc0e9ec-4b85-4dd8-8dba-83e179735504" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/c20e6a46-2721-4364-bf4a-8f863eb9dd0d" maxHeight=500></td>
</tr>
<tr>
<td></td>
<td><img src="https://github.com/user-attachments/assets/ab7ceaf7-b890-4bdd-8880-4ecd94e14e78" maxHeight=500></td>
</tr>
</table>
> [MBL-17748][Parent] Feedback button

- apps/teacher/src/main/java/com/instructure/teacher/view/AssignmentOverrideView.kt
refs: MBL-17788
release note: Available from time defaults to 12:00 AM.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/d74edc80-5397-47d3-b398-62fef330d891" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/d07ef868-e3fd-4c2b-828d-e3f68035f36d" maxHeight=500></td>
</tr>
</table>
> [MBL-17788][Teacher] Set default available from time in assignment override

- apps/student/build.gradle
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/PersonDetailsPage.kt
- apps/teacher/build.gradle
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/LoginLandingPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PeopleListPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PersonContextPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ProfileSettingsPage.kt
Implement Pronouns checking E2E test in Student and Teacher apps.
refs: MBL-17708
> [MBL-17708][Student][Teacher] - Implement E2E tests for Pronouns 

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineConferencesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyllabusE2ETest.kt
Implement Offline Conferences E2E test.
Rename Offline Syllabus class + extract syllabus body to variable.
refs: MBL-17389
> [MBL-17389][Student] - Implement Offline Conferences E2E test.

- apps/student/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
This reverts commit 3d219a59dd0cec1a9ab88d4fc26994eaa5e10259.
> Revert "Merge release/student to master (#2533)"

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/di/feature/CalendarModule.kt
- apps/student/src/main/java/com/instructure/student/features/calendar/StudentCalendarRouter.kt
- apps/student/src/main/java/com/instructure/student/features/inbox/list/StudentInboxRouter.kt
- libs/interactions/src/main/java/com/instructure/interactions/Navigation.kt
Test plan: In the ticket. Inbox screen is not mentioned there but it also had this issue.
refs: MBL-17790
> [MBL-17790][Student] Open from bookmark does not handle the user profile image

- apps/parent/build.gradle
- apps/student/build.gradle
- apps/teacher/build.gradle
- automation/espresso/build.gradle
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/DocumentScanner/build.gradle
- libs/annotations/build.gradle
- libs/blueprint/build.gradle
- libs/canvas-api-2/build.gradle
- libs/interactions/build.gradle
- libs/login-api-2/build.gradle
- libs/pandares/build.gradle
- libs/pandautils/build.gradle
- libs/rceditor/build.gradle
- libs/recyclerview/build.gradle
Test plan: -
refs: MBL-17242
affects: All
> [MBL-17242][All] Update Mockk dependency

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionListPresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderPresenter.kt
refs: MBL-17831
release note: Excused submissions are now available from the Graded submissions list
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/5ec1ee13-c5e5-4b9e-8c16-b2d78685ab52" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/7deb1703-28c2-4e5a-9d09-233bc4b9c974" maxHeight=500></td>
</tr>
</table>
> [MBL-17831][Teacher] Show excused submissions

- apps/student/src/main/java/com/instructure/student/fragment/LtiLaunchFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/LtiLaunchFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/HtmlContentFormatter.kt
refs: MBL-17852
release note: Kaltura videos now can be opened with the Launch External Tool button
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/cb11b697-e61c-4b11-b3b2-0cdfbd541d7c" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/d684362e-32c1-4143-81d4-755771360f70" maxHeight=500></td>
</tr>
</table>
> [MBL-17852][Student][Teacher] Launch Kaltura external tool

- automation/espresso/build.gradle
- automation/espresso/src/main/kotlin/com/instructure/espresso/ActivityHelper.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/EspressoLog.kt
- automation/espresso/src/main/kotlin/com/instructure/espresso/matchers/WaitForCheckMatcher.kt
> [MBL-16669][All] Update Espresso lib dependency

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAssignmentsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentListInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/SubmissionDetailsPage.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionCommentsRenderPage.kt
Create Offline E2E Test for Assignments.
Minor refactors.
refs: MBL-17386
> [MBL-17386][Student] - Create Offline Assignments E2E Test

- apps/parent/flank.yml
- apps/parent/flank_coverage.yml
- apps/parent/flank_landscape.yml
- apps/parent/flank_multi_api_level.yml
- apps/parent/flank_tablet.yml
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/NotAParentInteractionsTest.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/managestudents/ManageStudentsViewModelTest.kt
> Fix breaking tests

- apps/parent/src/main/java/com/instructure/parentapp/features/managestudents/ManageStudentsScreen.kt
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/pandautils/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/CanvasTheme.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/ComposeRCE.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarEvents.kt
Test plan: Smoke test the Jetpack Compose screens (Calendar in all apps, most of the Parent app). There is also a linked accessibility ticket that this update fixes.
refs: MBL-17720
affects: All
release note: Accessibility improvements in the calendar
> [MBL-17720][All] Updated Jetpack Compose

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModelTest.kt
Test plan: test event creation with custom frequency ending on date
refs: MBL-17966
affects: All
> [MBL-17966][All] Fixed rrule datetime format

- apps/flutter_parent/lib/models/help_link.dart
- apps/flutter_parent/lib/models/help_link.g.dart
- apps/flutter_parent/lib/screens/help/help_screen.dart
- apps/flutter_parent/lib/screens/help/help_screen_interactor.dart
- apps/flutter_parent/test/screens/help/help_screen_interactor_test.dart
refs: MBL-17888
release note: Fixed an issue where help links wouldn't load in some cases
> [MBL-17888][Parent] Fixed help menu serialization

- apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
Test plan: Check global announcement toolbar title in light/dark mode
> Fixed text color in Global announcements

- apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/OAuthManager.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewViewModel.kt
> [MBL-17911][Student] Reply/edit options viewable in closed discussions when acting as student

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/PlannerItem.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
Test plan: can be tested on beta, details in the ticket
refs: MBL-18036
release note: Added support for Discussion Checkpoints in Calendar.
> [MBL-18036][Student] Calendar display crash for Discussions with checkpoints

- apps/parent/src/main/java/com/instructure/parentapp/util/navigation/ParentWebViewRouter.kt
- apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/pages/details/PageDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusRepositoryFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusView.kt
- apps/student/src/main/java/com/instructure/student/navigation/StudentWebViewRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/navigation/TeacherWebViewRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/navigation/WebViewRouter.kt
Test plan: test all kind of links in webview of
- Assignment Details
- Syllabus
- Page Details
refs: MBL-18032
release note: Fixed an issue where embedded video urls would not open.
> [MBL-18032][Student] Can't open embedded video file

- apps/student/src/main/java/com/instructure/student/holders/InboxMessageHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/binders/MessageBinder.kt
refs: MBL-18037
release note: Fixed a crash in inbox.
> [MBL-18037][Teacher][Student] Inbox forward/delete crash

- apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
refs: MBL-18012
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/944c53e5-04ef-455d-9da0-d6307feeca01" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/f4f02103-6032-49fa-8686-c60387dbbfbb" maxHeight=500></td>
</tr>
</table>
> [MBL-18012][Student] Fix Quiz details toolbar color

- libs/pandautils/src/main/res/layout-sw720dp/dialog_color_picker.xml
> [MBL-18000][Student][Teacher] Fixed color picker alignment on tablet

- libs/DocumentScanner/src/main/AndroidManifest.xml
- libs/DocumentScanner/src/main/java/com/zynksoftware/documentscanner/ui/camerascreen/CameraScreenFragment.kt
Test plan: Test the photo picker in the document scanner.
refs: MBL-17940
> [MBL-17940][Student] Handle Google Play's photo and permission policy

- apps/student/src/main/java/com/instructure/student/activity/VideoViewActivity.kt
Test plan: test videos from files eg. user files - uploaded media
refs: MBL-18042
> [MBL-18042][Student] Video view issues

- apps/student/src/main/java/com/instructure/student/util/BaseAppManager.kt
- apps/teacher/src/main/java/com/instructure/teacher/utils/BaseAppManager.kt
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
Test plan: Smoke test the places where PSPDFKit is used. Compare it with the current version.
- Student Annotation submission (Student)
- View PDF submissions (Student)
- View and edit PDF files from the files list (Student)
- Annotate PDF submissions (Teacher)
- View PDF files from the files list (Teacher)
refs: MBL-18003
> [MBL-18003][Student][Teacher] Update PSPDFKit

- apps/flutter_parent/lib/l10n/app_localizations.dart
- apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_extensions.dart
- apps/flutter_parent/lib/screens/alerts/alerts_screen.dart
- apps/flutter_parent/lib/screens/announcements/announcement_details_screen.dart
- apps/flutter_parent/test/screens/alert_thresholds/alert_thresholds_screen_test.dart
- apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart
- apps/flutter_parent/test/screens/announcements/announcement_details_screen_test.dart
> [MBL-18039][Parent] Rename Institution Announcement to Global Announcement

- apps/parent/src/main/java/com/instructure/parentapp/di/ApplicationModule.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
- apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/commentTab/SubmissionCommentsEffectHandlerTest.kt
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
- libs/pandautils/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/analytics/OfflineAnalyticsManager.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/ApplicationModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncSettingsViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/analytics/OfflineAnalyticsManagerTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/syncsettings/SyncSettingsViewModelTest.kt
Test plan: This ticket cannot be tested properly as developers has no access to analytics dashboards. You can check the sent events from Logcat.
The event names are identical to the iOS app: https://github.com/instructure/canvas-ios/pull/2912
refs: MBL-17885
> [MBL-17885][Student] Track Offline usage

- apps/student/src/main/java/com/instructure/student/features/modules/list/adapter/ModuleViewHolder.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/LtiSubmissionViewFragment.kt
- apps/student/src/main/res/layout/fragment_lti_submission_view.xml
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListPresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/AssignmentViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/ToDoViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/utils/AssignmentExtensions.kt
- apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListPresenterTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ModuleItem.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentExtensions.kt
> [MBL-17962][Student][Teacher] New Quiz LTI Labeling

- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/settings/SyncSettingsFragment.kt
Test plan: See in ticket
refs: MBL-18065
> [MBL-18065][Student] Wi-Fi only toggle confirmation dialog fix

- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
refs: MBL-18048
release note: External links are now supported to People List screen.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/890416a1-e1a7-4b1a-8316-1bb8c5b91009" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/5c94a3ff-3822-4021-97a7-73339cc0cd0e" maxHeight=500></td>
</tr>
</table>
> [MBL-18048][Teacher] Deeplink support for people list

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/courses/details/frontpage/FrontPageScreenTest.kt
- apps/parent/src/main/java/com/instructure/parentapp/di/feature/FrontPageModule.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsWebViewScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageRepository.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageUiState.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/grades/ParentGradesScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryScreen.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageRepositoryTest.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageViewModelTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ComposeCanvasWebViewWrapper.kt
Test plan: compare with the flutter version
refs: MBL-17679
> [MBL-17679][Parent] Course details - Front page

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PdfInteractionTest.kt
- apps/student/src/main/java/com/instructure/student/activity/BaseRouterActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/CandroidPSPDFActivity.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/java/com/instructure/student/features/assignments/details/StudentAssignmentDetailsRouter.kt
- apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt
- apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchFragment.kt
- apps/student/src/main/java/com/instructure/student/features/modules/progression/ModuleQuizDecider.kt
- apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/ParentFragment.kt
- apps/student/src/main/java/com/instructure/student/fragment/StudioWebViewFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/SubmissionCommentsView.kt
- apps/student/src/main/java/com/instructure/student/navigation/StudentWebViewRouter.kt
- apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.kt
refs: MBL-18067
release note: Local PDF annotations are now remain available after logout.
> [MBL-18067][Student] PDF annotation saving

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/courses/details/CourseDetailsScreenTest.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsUiState.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsWebViewScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageUiState.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/grades/ParentGradesScreen.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/courses/details/CourseDetailsViewModelTest.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/courses/details/frontpage/FrontPageViewModelTest.kt
- libs/pandares/src/main/res/values/strings.xml
> [MBL-18080][Parent] Course details - Refactor refresh logic

- apps/parent/src/androidTest/java/com/instructure/parentapp/utils/ParentTestExtensions.kt
Extend seedData with parents by adding some methods to ParentTestExtensions.kt
refs: MBL-17994
> [MBL-17994][Parent] - Imporove DataSeeding to handle parents

- README.md
- apps/student/build.gradle
- apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
- apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt
- apps/student/src/main/java/com/instructure/student/util/BaseAppManager.kt
- apps/teacher/build.gradle
- apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/tasks/TeacherLogoutTask.kt
- apps/teacher/src/main/java/com/instructure/teacher/utils/BaseAppManager.kt
- buildSrc/src/main/java/GlobalDependencies.kt
- libs/canvas-api-2/build.gradle
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
- libs/pandautils/build.gradle
Test plan: Verify that Heap tracking works correctly.
refs: MBL-18104
> [MBL-18104][Student][Teacher] Updated Heap

- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/splash/SplashRepository.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/splash/SplashViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/BaseAppManager.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
- apps/parent/src/main/res/layout/activity_route_validator.xml
- apps/parent/src/main/res/layout/fragment_dashboard.xml
- apps/parent/src/main/res/menu/nav_drawer.xml
- apps/parent/src/test/java/com/instructure/parentapp/features/splash/SplashRepositoryTest.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/splash/SplashViewModelTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UserAPI.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/dialog/MasqueradingDialog.kt
Test plan: Test all types of masquerading in the Parent app (qr code, site admin login, admin login)
refs: MBL-17613
> [MBL-17613][Parent] Implement Masquerading

- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/pairingcode/PairingCodeScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/qr/QrPairingScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/CanvasTheme.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelValueSwitch.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelValueVerticalItem.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SingleChoiceAlertDialog.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/utils/InboxMessageView.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
Test plan: Smoke test the apps, we should use Lato everywhere.
refs: MBL-18086
> [MBL-18086][All] Fix compose fonts

- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/annnotation/AnnotationSubmissionUploadFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/AnnotationSubmissionViewFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/PdfStudentSubmissionView.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/PdfSubmissionViewFragment.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/datasource/SubmissionDetailsNetworkDataSource.kt
- apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
- apps/student/src/main/java/com/instructure/student/router/EnabledTabs.kt
- apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
- libs/annotations/src/main/java/com/instructure/annotations/CanvaDocsExtensions.kt
- libs/annotations/src/main/java/com/instructure/annotations/CanvaDocsRedirectAsyncTask.kt
- libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/RequestInterceptor.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/SubmissionManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Tab.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt
Test plan: See ticket. Also heavily smoke test the submission flows, mostly pdfs, student annotations and files.
refs: MBL-17872
release note: Fixed a bug where submissions failed sometimes for consortia users.
> [MBL-17872][Student] Consortia domain handling

- apps/teacher/src/main/java/com/instructure/teacher/features/speedgrader/commentlibrary/CommentLibraryViewModel.kt
- apps/teacher/src/test/java/com/instructure/teacher/features/speedgrader/commentlibrary/CommentLibraryViewModelTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/fakes/FakeCommentLibraryManager.kt
- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/CommentLibraryQuery.graphql
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/QLClientConfig.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CommentLibraryManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CommentLibraryManagerImpl.kt
Test plan: Check if comment library works correctly with 20+ items in the library.
refs: MBL-18027
> [MBL-18027][Teacher] Use pagination in graphql in comment library 

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/CoursesInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/DashboardInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentCalendarInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/CourseDetailsPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/CreateAccountPage.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/calendar/ParentCalendarRouter.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/SelectedStudentHolder.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/login/routevalidator/RouteValidatorAction.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/login/routevalidator/RouteValidatorActivity.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/login/routevalidator/RouteValidatorViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/AppManager.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/dashboard/TestSelectStudentHolder.kt
- apps/parent/src/test/java/com/instructure/parentapp/login/routevalidator/RouteValidatorViewModelTest.kt
- apps/student/src/main/java/com/instructure/student/features/calendar/StudentCalendarRouter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRouter.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ObserveeAssignment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/BaseCalendarFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/FlowExtensions.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
Implemented opening Discussion and Quiz assignments is calendar
Implemented different domain case when opening the app from a link
Fixed student selector blinking
Fixed invalid error state on courses screen when changing user
Fixed a flaky test in DashboardInteractionTest
Fixed the icon of quiz type assignments on the grades tab
> Native parent todos & bug fixes

- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewHtmlFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewImageFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewPdfFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewUnsupportedFileFragment.kt
> [MBL-18162][Teacher] Tablet: File names (and whole toolbar) are barely visible in Dark Mode

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/help/HelpDialogViewModelTest.kt
> [MBL-18153][All] Removed custom submit feature idea action

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/pageview/PageViewUploadService.kt
Test plan: I couldn't reproduce a failing page view, it just fails randomly for some users, because of an issue in the PaperDB library. We will monitor the non-fatal events to test this.
refs: MBL-18139
> [MBL-18139][Student][Teacher] Some page views are failing to upload

- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/smartsearch/SmartSearchScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/smartsearch/SmartSearchScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/smartsearch/SmartSearchUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/smartsearch/SmartSearchViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/smartsearch/SmartSearchViewModelTest.kt
Test plan: See design in epic.
refs: MBL-17901
> [MBL-17901][Student] Smart Search visited indication

- apps/student/src/main/java/com/instructure/student/dialog/AskInstructorDialogStyled.kt
Add 'Cancel' button on 'Ask Your Instructor a Question' dialog.
refs: MBL-18143
release note: Add 'Cancel' button on 'Ask Your Instructor a Question' dialog.
> [MBL-18143][Student] - Add 'Cancel' button on 'Ask Your Instructor a Question' dialog.

- apps/student/src/androidTest/java/com/instructure/student/ui/pages/HelpPage.kt
- apps/student/src/main/AndroidManifest.xml
- apps/student/src/qa/AndroidManifest.xml
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/HelpPage.kt
- automation/dataseedingapi/build.gradle
Refactor testHelpMenuE2E test (update strings to current state and add assertions).
Fix E2E test running problem since AGP update.
Fix E2E permission issues in student app.
Successful Student E2E test run: https://app.bitrise.io/build/b02a09c6-a8c6-434e-b39f-7175a81aa640?tab=log
Successful Teacher E2E test run: https://app.bitrise.io/build/278bdadb-830c-4536-be11-2cb0cc82f5f6?tab=log
refs: MBL-18541
release note:
> [MBL-18541][Student][Teacher] -  Refactor Help Menu E2E tests + Fix E2E test running problem and Student permission problem

- apps/teacher/src/main/res/layout-sw760dp/view_submission_content.xml
- apps/teacher/src/main/res/layout/fragment_speedgrader_grade.xml
- apps/teacher/src/main/res/layout/view_submission_content.xml
> [MBL-18191][Teacher][A11y] Speedgrader accessibility headings added

- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderCommentsFragment.kt
- apps/teacher/src/main/res/layout/adapter_submission_comment.xml
- libs/pandares/src/main/res/values/strings.xml
> [MBL-18194][Teacher][A11y] SpeedGrader Comment status announcements

- apps/teacher/src/main/res/layout/fragment_speedgrader_grade.xml
> [MBL-18187][Teacher][A11y] SpeedGrader grade announcement

- libs/pandautils/src/main/res/layout/fragment_inbox.xml
> [MBL-18199][Student][Teacher] Specify Inbox heading

- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/summary/SummaryRepository.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/courses/list/CoursesViewModel.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/AlertCountUpdater.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardFragment.kt
- apps/parent/src/main/res/layout/fragment_dashboard.xml
- apps/parent/src/test/java/com/instructure/parentapp/features/courses/details/summary/SummaryRepositoryTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/lti/LtiLaunchFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/reminder/ReminderViewState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/reminder/composables/ReminderView.kt
- libs/pandautils/src/main/res/layout/fragment_assignment_details.xml
Test plan: I added a list of the issues I found in the ticket.
refs: MBL-17614
> [MBL-17614][Parent] Remaining styling/behavior issues

- apps/student/src/main/java/com/instructure/student/features/discussion/list/DiscussionListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/details/DiscussionDetailsWebViewFragment.kt
> [MBL-18035][Student][Teacher] Refresh discussions list

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
- libs/pandautils/src/main/res/layout/fragment_inbox.xml
- libs/pandautils/src/main/res/layout/item_inbox_entry.xml
Note: I also added a clarification content description for the inbox scope filter. I got the wording from the mobile web behavior.
Test plan: 
- Verify that "button" is announced for both filter buttons on the Inbox list and the list items as well.
refs: MBL-18200
affects: All
> [MBL-18200][All] Add button role to inbox items.

- apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
Test plan: Verify that "button" is announced for grades list items.
refs: MBL-18216
> [MBL-18216][Student] Added button class to grades list items.

- apps/student/src/main/java/com/instructure/student/holders/AssignmentViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/AssignmentViewHolder.kt
Test plan: 
- Verify that "button" is announced for assignment list items.
- Test both apps.
refs: MBL-18210
> [MBL-18210][Student][Teacher] Added button class to assignment list items.

- apps/student/src/main/res/layout/fragment_submission_details.xml
- apps/teacher/src/main/res/layout-sw760dp/view_submission_content.xml
- apps/teacher/src/main/res/layout/view_submission_content.xml
Test plan: Check the attached screenshot in the ticket. The text should be fully visible. This also affects the Student app.
refs: MBL-18205
> [MBL-18205][Student][Teacher] Handle big fonts in Speedgrader tab layout.

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/res/layout/fragment_inbox.xml
> [MBL-18198][All] Added list announcement for Inbox RecyclerView

- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListSubHeaderBinder.kt
> [MBL-18229][Teacher] Fixed module item publish button content description.

- apps/student/src/main/res/layout/assignment_list_layout.xml
> [MBL-18213][Student] Assignment list heading

- apps/student/src/main/res/layout/fragment_course_pages.xml
- apps/student/src/main/res/layout/fragment_file_list.xml
- apps/teacher/src/main/res/layout/fragment_file_list.xml
- apps/teacher/src/main/res/layout/fragment_page_list.xml
- apps/teacher/src/main/res/layout/fragment_people_list_layout.xml
Test plan: 
1. Page List toolbar
2. File List toolbar
3. People List toolbar
refs: MBL-18556
> [MBL-18556][Teacher][A11y] Fix a11y toolbar height on list screens

- apps/teacher/src/main/res/layout/fragment_discussion_list.xml
> [MBL-18267][Teacher][A11y] Fix Discussions toolbar height

- apps/teacher/src/main/res/layout/fragment_assignment_submission_list.xml
> [MBL-18245][Teacher][A11y] Fix Submissions toolbar height

- apps/teacher/src/main/res/layout/fragment_module_list.xml
> [MBL-18228][Teacher][A11y] Fix modules toolbar height

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
> [MBL-18249][Student][Teacher][A11y] Set minimum height instead of fixed height

- apps/teacher/src/main/res/layout/view_submission_content.xml
- libs/pandares/src/main/res/values/strings.xml
> [MBL-18204][Teacher] SpeedGrader drawer content description

- libs/pandautils/src/main/res/layout/view_student_enhanced_grade_cell.xml
Test plan: 
1. Open an Assignment
2. Submit a new Submission
3. Check all state of the submission cell view both with normal and increased font size.
refs: MBL-18214
> [MBL-18214][Student][A11y] Assignment details submission cell header

- apps/student/src/main/res/layout/fragment_picker_submission_upload.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/reminder/composables/ReminderView.kt
- libs/pandautils/src/main/res/layout/fragment_assignment_details.xml
> [MBL-18223][Student] Assignment details headings

- apps/student/src/main/res/layout/fragment_annotation_submission_upload.xml
> [MBL-18224][Student] Student annotation heading

- apps/teacher/src/main/java/com/instructure/teacher/dialog/RadioButtonDialog.kt
- apps/teacher/src/main/res/layout/fragment_assignment_submission_list.xml
- libs/pandautils/src/main/res/values/styles.xml
- Note that I created a new AlertDialog style that can be used at any dialogs to mark it's title as heading
refs: MBL-18277
> [MBL-18277][Teacher][A11y] Fix Submissions headings

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasThemedAppBar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
- libs/pandautils/src/main/res/layout/fragment_notification_preferences.xml
- libs/pandautils/src/main/res/layout/item_notification_header.xml
> [MBL-18263][Student][Teacher][A11y] Fix Settings screen headings

- apps/student/src/main/java/com/instructure/student/dialog/BookmarkCreationDialog.kt
- apps/student/src/main/res/layout/fragment_course_grades.xml
- apps/student/src/main/res/layout/viewholder_header_expandable.xml
> [MBL-18211][Student] Grades a11y

- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- libs/pandares/src/main/res/values/strings.xml
> [MBL-18232][Teacher] Modules a11y

- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListSubHeaderBinder.kt
> [MBL-18230][Teacher] Modules a11y class names

- apps/student/src/main/java/com/instructure/student/features/quiz/list/QuizListRecyclerAdapter.kt
- apps/student/src/main/java/com/instructure/student/holders/ExpandableViewHolder.kt
- apps/student/src/main/java/com/instructure/student/holders/QuizViewHolder.kt
- apps/student/src/main/res/layout/viewholder_quiz.xml
> [MBL-18235][Student] Quizzes class names

- apps/student/src/main/res/layout/quiz_list_layout.xml
- libs/login-api-2/src/main/res/values/styles.xml
> [MBL-18242][Student] Quizzes heading

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/res/layout/item_offline_course.xml
> [MBL-18523][Student][A11y] Ensure elements provide an accessible name

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarScreenPage.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
> [MBL-18278][Teacher][Student][A11y] Ensure elements provide an accessible name

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SingleChoiceAlertDialog.kt
> [MBL-18262][Student][Teacher][A11y] Fix dialog title heading

- libs/pandautils/src/main/java/com/instructure/pandautils/features/notification/preferences/EmailNotificationPreferencesFragment.kt
- libs/pandautils/src/main/res/values/themes_canvasthemes.xml
> [MBL-18268][Student][Teacher][A11y] Fix dialog title heading

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasAppBar.kt
> [MBL-18292][Student][Teacher][A11y] Calendar toolbar heading

- libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogFragment.kt
> [MBL-18489][Student][Teacher][A11y] File upload dialog heading

- apps/teacher/src/main/res/layout/fragment_quiz_details.xml
> [MBL-18248][Teacher][A11y] Quiz details accessibility fix

- libs/pandautils/src/main/res/layout/fragment_offline_content.xml
> [MBL-18522][Student] Provide for user control of font size (Manage offline content screen)

- apps/student/src/main/res/layout/view_comment.xml
> [MBL-18533][Student] Provide for user control of font size (Submission comment)

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt
- libs/pandautils/src/main/res/layout/fragment_offline_content.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
> [MBL-18525][Student] Ensure elements provide an accessible name (Manage offline content)

- libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/A11yUtils.kt
> [MBL-18272][All]Add accessibility class to legal dialog buttons.

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelValueRow.kt
> [MBL-18275][Student][Teacher] Ensure element role and state are correct (LabelValueRow)

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
> [MBL-18289][Student][Teacher] Ensure element role and state are correct

- apps/teacher/src/main/java/com/instructure/teacher/holders/DiscussionExpandableViewHolder.kt
- apps/teacher/src/main/res/layout/viewholder_header_expandable.xml
> [MBL-18269][Teacher] a11y discussion list headings

- apps/teacher/src/main/java/com/instructure/teacher/holders/DiscussionListHolder.kt
> [MBL-18271][Teacher] a11y discussion list element role

- libs/pandautils/src/main/res/layout/fragment_offline_content.xml
> [MBL-18524][Student] Ensure headings are denoted through structure and not implicitly (Manage offline content)

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelSwitchRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/ContextValueRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/RecipientChip.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/RecipientPickerScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/utils/InboxMessageView.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt
Test plan: Check entire Inbox if all previous functionalities are working.
> Release inbox fixes

- apps/student/src/main/java/com/instructure/student/holders/AssignmentViewHolder.kt
- apps/student/src/main/java/com/instructure/student/holders/ExpandableViewHolder.kt
- apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListSubHeaderBinder.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/AssignmentViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/DiscussionListHolder.kt
> [MBL-18274][Teacher] a11y submission button role

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/rce/RCEControls.kt
> [MBL-18284][Student][Teacher] Ensure element role and state are correct (Compose rce)

- apps/student/src/main/java/com/instructure/student/fragment/ToDoListFragment.kt
> [MBL-18526][Student] Add class to to do dialog items.

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/A11yUtils.kt
> [MBL-18285][All] Fixed calendar heading accessibility.

- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
- libs/pandautils/src/main/res/layout/item_email_notification_preference.xml
> [MBL-18283][All] a11y settings button role

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarEventCreateEditPage.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendarevent/createupdate/CreateUpdateEventScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SingleChoiceAlertDialog.kt
> [MBL-18255][Student][Teacher][A11y] Calendar frequency picker accessibility fix

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/Utils.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
> [MBL-18259][All] Provide valid labels for all form elements (Create ToDo & event screens)

- apps/student/src/main/res/layout/fragment_submission_details.xml
> [MBL-18531][Student] Ensure headings are denoted through structure and not implicitly

- apps/teacher/src/main/res/layout/fragment_module_list.xml
- libs/pandautils/src/main/res/values/styles.xml
> [MBL-18233][Teacher] Modules heading

- apps/student/src/main/java/com/instructure/student/fragment/ToDoListFragment.kt
- apps/student/src/main/res/layout/fragment_list_todo.xml
Test plan: In the ticket. I only modified the ToDoFragment, the other occurrences already had the heading announced.
refs: MBL-18537
> [MBL-18537][Student] Added headings to todo fragment.

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendartodo/createupdate/CreateUpdateToDoViewModelTest.kt
> [MBL-18290][All] Announce creation and update of todos and events in the calendar.

- apps/student/src/main/res/layout/fragment_submission_comments.xml
> [MBL-18535][Student] Provide valid labels for all form elements (Submission comment)

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt
- libs/pandautils/src/main/res/layout/item_sync_progress.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
> [MBL-18521][Student] Ensure assistive technologies are aware of content changes in real time

- apps/teacher/src/main/res/layout/fragment_assignment_submission_list.xml
> [MBL-18276][Teacher] a11y submissions focus order

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewData.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/A11yUtils.kt
- libs/pandautils/src/main/res/layout/item_offline_course.xml
- libs/pandautils/src/main/res/layout/item_offline_file.xml
- libs/pandautils/src/main/res/layout/item_offline_tab.xml
> [MBL-18528][Student] Improved offline content items accessibility.

- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/student/src/main/res/layout/navigation_drawer.xml
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- apps/teacher/src/main/res/layout/navigation_drawer.xml
"Ensure that functionality can be operated through a single pointer except when a multi-point or path based gesture is essential."
refs: MBL-18256
> [MBL-18256][Student][Teacher] Navigation drawer close button

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionListFragment.kt
- libs/pandares/src/main/res/values-en/strings.xml
- libs/pandares/src/main/res/values/strings.xml
> [MBL-18287][Teacher][A11y] Submission filter a11y announcement

- apps/parent/build.gradle
- apps/parent/flank_e2e.yml
Test plan: Check the pipelines.
refs: MBL-17675
> [MBL-17675][Parent] CI/CD

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/AssignmentDetailsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/AssignmentDetailsPage.kt
Fix breaking Assignment E2E test.
> Fix breaking Assignment E2E Test

- apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt
> [MBL-18226][Teacher][A11y] Fix Module list dialog heading

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/alerts/list/AlertsScreenTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/login/createaccount/CreateAccountScreenTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/managestudents/ManageStudentsScreenTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/notaparent/NotAParentScreenTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/CreateAccountInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/AlertSettingsPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/CoursesPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/CreateAccountPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/compose/NotAParentPage.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/login/createaccount/CreateAccountScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/managestudents/ManageStudentsScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/notaparent/NotAParentScreen.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/GradesInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/InboxDetailsInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/InboxComposePage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ConversationEndpoints.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/EmptyContent.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
Test plan: Check if all the landscape tests pass.
refs: MBL-17476
> [MBL-17476][Parent] Fix landscape tests

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/InboxE2ETest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentInboxComposeInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/LeftSideNavigationDrawerPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/ParentInboxCoursePickerPage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/utils/ParentComposeTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/utils/ParentTest.kt
The same test cases are implemented as in the Student and Teacher application.
refs: MBL-18111
> [MBL-18111][Parent] Implement Parent Inbox E2E Tests

- apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/FlutterAppMigration.kt
- apps/parent/src/test/java/com/instructure/parentapp/util/FlutterAppMigrationTest.kt
- apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/ApplicationModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewAuthenticator.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/utils/WebViewAuthenticatorTest.kt
Test plan: Repro steps and test user in the ticket.
refs: MBL-18548
affects: Student, Parent, Teacher
> [MBL-18548][All] Images embedded in pages fail to load after 24h from first logging into the app

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoDetailsPage.kt
> Fix breaking Calendar To Do E2E test

- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt
> [MBL-18602][Parent] Delete student dialog and more menu are disappearing after orientation change

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/AlertSettingsPage.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/legal/ParentLegalRouter.kt
> [MBL-18600][Parent] Terms of Use' link in 'Legal' menu shows an outdated webpage

- apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
> [MBL-18606][Parent] We don't have any message if the user tries to upload but exceeded it's storage quota

- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.kt
Test plan: See ticket. Also smoke test the login with different kinds of auth providers.
refs: MBL-18546
> [MBL-18546][All] Fix login redirect loop

- apps/parent/src/main/res/layout/fragment_dashboard.xml
- apps/parent/src/main/res/layout/item_add_student.xml
- apps/parent/src/main/res/layout/item_student.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
- libs/pandautils/src/main/res/layout/view_student_enhanced_grade_cell.xml
> [MBL-18596][Parent] Buttons need to read as Buttons to TalkBack users in the Parent App Redesign

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
> [MBL-18597][Parent] Focus does not move to the "today" button when using "jump to today" in Calendar

- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderLtiSubmissionFragment.kt
refs: MBL-18573
release note: Fixed a bug where SpeedGrader would require login to view quiz submissions.
> [MBL-18573][Teacher] Authenticate new quiz url in SpeedGrader

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt
refs: MBL-18612
release note: Fixed a bug where designer roles couldn't open LTI tools.
> [MBL-18612][Teacher] Designer enrollments cannot view external tool assignments using Teacher app

- apps/teacher/src/main/java/com/instructure/teacher/dialog/ConfirmDeleteFileFolderDialog.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFileFolderFragment.kt
> [MBL-18589][Teacher] Delete file will not do anything if change orientation when the dialog displayed

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/InboxE2ETest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/SettingsE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/base/BaseCanvasActivity.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/base/PageViewFragmentDelegate.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/AnalyticsModule.kt
> Investigate interaction tests on master

- apps/teacher/src/main/res/layout/fragment_discussion_list.xml
> [MBL-18264][Teacher] Ensure headings are denoted through structure and not implicitly

- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsFragment.kt
Test plan: I could not reproduce the issue, but it happens when a Bitmap is too large (probably large screen devices) on the settings app theme selector animation. You can reproduce it from code by editing the try part and throwing an exception to see the fallback option. Basically we won't show the animation if the bitmap is too big. I also reduced the size of the bitmap.
refs: MBL-18629
release note: Fixed a crash when changing app theme
> [MBL-18629][All] Settings crash

- libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsBehaviour.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewExtensions.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/settings/SettingsViewModelTest.kt
Test plan: Check that the settings items with online content won't open offline.
refs: MBL-18568
> [MBL-18568][All] Added offline check for settings menu items.

- apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsScreen.kt
> [MBL-18513][Parent] Ensure text and images of text provide sufficient contrast

- apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
> [MBL-18594][Teacher] Make settings screens fullscreen on tablet.

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/RequestInterceptor.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginFindSchoolActivity.kt
- libs/pandautils/src/main/res/xml/network_security_config.xml
Test plan: You need a local canvas instance to test these changes. Setup a proxy for either your localhost (10.0.2.2) on emulator or your local ip address on a physical device.
refs: -
affects: All 
> Local development support

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderPage.kt
- apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/adapters/SubmissionContentAdapter.kt
- apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
- apps/teacher/src/main/res/layout-sw760dp/view_submission_content.xml
- apps/teacher/src/main/res/layout/activity_speedgrader.xml
- apps/teacher/src/main/res/layout/view_submission_content.xml
- apps/teacher/src/main/res/menu/menu_post_policies.xml
- libs/pandares/src/main/res/values/strings.xml
Test plan: See design in ticket.
refs: MBL-18176
release note: Course and Assignment name is now visible in Speed Grader.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/fe64527f-a882-4057-aacb-a6f77f96e9ce"
maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/c7ab6373-395b-4fd2-88e1-e22466c7b4c9" maxHeight=500></td>
</tr>
</table>
> [MBL-18176][Teacher] SpeedGrader visible assignment name

- apps/teacher/src/main/java/com/instructure/teacher/adapters/FileListAdapter.kt
- apps/teacher/src/main/java/com/instructure/teacher/dialog/ConfirmDeleteFileFolderDialog.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/files/search/FileSearchAdapter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/files/search/FileSearchFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/files/search/FileSearchPresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/files/search/FileSearchView.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFileFolderFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/FileFolderViewHolder.kt
- apps/teacher/src/main/java/com/instructure/teacher/interfaces/ConfirmDeleteFileCallback.kt
- apps/teacher/src/main/java/com/instructure/teacher/presenters/FileListPresenter.kt
- apps/teacher/src/main/res/layout/adapter_file_folder.xml
- apps/teacher/src/main/res/menu/menu_file_list_item.xml
Test plan: Check that the file edit and delete options work correctly in the file list. Both in user files and course files. Also smoke test the file delete functionality on the edit file screen.
refs: MBL-18158
release note: Added file edit and delete menu options to the files list.
> [MBL-18158][Teacher] File edit and delete options in files list.

- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/AssignmentDetailsPage.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/details/InboxDetailsFragment.kt
- libs/pandautils/src/main/res/layout/fragment_assignment_details.xml
- On locked assignment details locked image and reminder part overlaps.
- Routing to course links not working from inbox messages.
> Smoke test findings common issues

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/FontPageE2ETest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/FrontPagePage.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/utils/ParentTest.kt
> [MBL-18128][Parent] Create E2E Test for Course Details - Front Page Tab

- apps/buildSrc/src/main/java/GlobalDependencies.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt
- apps/student/src/main/res/layout/fragment_create_announcement.xml
- apps/student/src/main/res/layout/fragment_create_discussion.xml
- apps/student/src/main/res/layout/navigation_drawer.xml
- apps/teacher/src/main/res/layout/adapter_feature_flag.xml
- apps/teacher/src/main/res/layout/adapter_post_policy_section.xml
- apps/teacher/src/main/res/layout/fragment_create_discussion.xml
- apps/teacher/src/main/res/layout/fragment_create_or_edit_announcement.xml
- apps/teacher/src/main/res/layout/fragment_create_or_edit_page.xml
- apps/teacher/src/main/res/layout/fragment_edit_assignment_details.xml
- apps/teacher/src/main/res/layout/fragment_edit_quiz_details.xml
- apps/teacher/src/main/res/layout/fragment_edit_syllabus.xml
- apps/teacher/src/main/res/layout/navigation_drawer.xml
- libs/login-api-2/src/main/res/layout/activity_acceptable_use_policy.xml
- libs/pandares/src/main/res/drawable/ic_switch_icon.xml
- libs/pandares/src/main/res/values-night/colors.xml
- libs/pandares/src/main/res/values/colors.xml
- libs/pandautils/build.gradle
- libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasSwitch.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelSwitchRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelValueSwitch.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewStyler.kt
- libs/pandautils/src/main/res/layout/fragment_sync_settings.xml
- libs/pandautils/src/main/res/layout/item_push_notification_preference.xml
Test plan: Check if all the switches in the app were changed to the new design and verify that they look correct in both dark and light mode.
refs: MBL-18258
> [MBL-18258][All] Material3 switches

- apps/parent/src/main/java/com/instructure/parentapp/features/inbox/list/ParentInboxRouter.kt
- apps/parent/src/main/java/com/instructure/parentapp/util/navigation/Navigation.kt
- apps/student/src/main/java/com/instructure/student/features/inbox/list/StudentInboxRouter.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/LoginLandingPageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/inbox/list/TeacherInboxRouter.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/details/InboxDetailsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/details/InboxDetailsViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/details/InboxDetailsViewModelTest.kt
Test plan: In the ticket. FYI this also happens in the other apps as well.
refs: MBL-18671
> [All][MBL-18671] Inbox unread counter does not refreshing automatically after reading a conversation and navigate back

- apps/parent/src/main/java/com/instructure/parentapp/di/feature/LtiLaunchModule.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/lti/ParentLtiLaunchFragmentBehavior.kt
- apps/student/src/main/java/com/instructure/student/di/feature/LtiLaunchModule.kt
- apps/student/src/main/java/com/instructure/student/features/lti/StudentLtiLaunchFragmentBehavior.kt
- apps/student/src/main/res/layout/fragment_submission_comments.xml
- apps/teacher/src/main/java/com/instructure/teacher/di/LtiLaunchModule.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/lti/TeacherLtiLaunchFragmentBehavior.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/lti/LtiLaunchFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/lti/LtiLaunchFragmentBehavior.kt
Test plan: In the ticket. Some notes:
- The studio issue affects the Teacher as well.
- I couldn't reproduce the outcomes issue.
refs: MBL-18683
> [MBL-18683][Student][Teacher] Dark mode color issues

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/edit/EditDashboardViewModelTest.kt
> [MBL-18670][Student][Teacher] All Courses page empty result screen has wrong text

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/InboxE2ETest.kt
Fix testComposeMessageShortcutsE2E test (it was broken by exit confirmation PR).
Some refactor + add logs.
> Fix testComposeMessageShortcutsE2E test

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt
> [MBL-18261][All] Changed hint colors in calendar edit screens.

- apps/parent/proguard-rules.txt
- apps/teacher/build.gradle
- apps/teacher/proguard-rules.txt
Test plan:
- Open Teacher app, go to Submissions screen on any assignment
- App should not crash
refs: MBL-18731
release note:
> [MBL-18731][Teacher] Crash on submission list

- apps/parent/src/main/java/com/instructure/parentapp/features/inbox/coursepicker/ParentInboxCoursePickerViewModel.kt
> [MBL-18728][Parent] Parent inbox picker distinct items

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/CanvasNetworkSignInPage.kt
Fix breaking Canvas Network Sign In page E2E test. (DOM change)
> Fix breaking Canvas Network Sign In page E2E test. (DOM change)

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/SubmissionListScreen.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/SubmissionListUiState.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/SubmissionListViewModel.kt
- apps/teacher/src/test/java/com/instructure/teacher/features/assignment/submission/SubmissionListViewModelTest.kt
> [MBL-18733][Teacher] 'Test Student' missing 'Created by Student View' label

- libs/DocumentScanner/build.gradle
- libs/DocumentScanner/src/main/java/com/zynksoftware/documentscanner/ui/camerascreen/CameraScreenFragment.kt
Test plan: Check the document scanner.
> Remove rxpermissions

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/ComposeExtensions.kt
Test plan:
We could not reproduce this crash, so there is no way to test it  by us.
refs: MBL-18746
> [MBL-18746][All] Calendar crashes fixed

- libs/pandautils/src/main/res/layout/item_dashboard_conference.xml
- libs/pandautils/src/main/res/layout/item_dashboard_invitation.xml
> [MBL-18787][Student] Dashboard notification network handling

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/LabelSwitchRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/inboxsignature/InboxSignatureScreen.kt
refs: MBL-18784
release note: Fixed a bug where ui components would overlap.
> [MBL-18784][All] Fix text overlapping with switch

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/LoginInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/LoginFindSchoolPage.kt
Implement interaction test for Find my School search logic.
ShareExtension test fix attempt.
refs: MBL-18810
release note:
> [MBL-18810][Student] - Find school search logic interaction test

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/alerts/list/AlertsListItemTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PickerSubmissionUploadInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SubmissionDetailsInteractionTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/AssignmentListPage.kt
Attempt to fix testSubmit, testComments_addCommentToMultipleAttemptSubmission, testComments_addCommentToSingleAttemptSubmission tests.
> Attempt to fix interaction tests

- apps/parent/src/main/java/com/instructure/parentapp/features/managestudents/ManageStudentsScreen.kt
> [MBL-18501][Parent] Ensure element role and state are correct

- apps/buildSrc/src/main/java/GlobalDependencies.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ModuleItem.kt
- libs/pandautils/schemas/com.instructure.pandautils.room.appdatabase.AppDatabase/12.json
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/appdatabase/daos/FileDownloadProgressDaoTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/filedetails/ImageFileContent.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/filedetails/MediaFileContent.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/di/DatabaseModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/file/download/FileDownloadWorker.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabase.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/AppDatabaseMigrations.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/daos/FileDownloadProgressDao.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/room/appdatabase/entities/FileDownloadProgressEntity.kt
Test plan: Test db migration. Install the app from master then update it from this branch. Smoke test the app, especially the file download
refs: -
affects: - 
> Common changes from CLX-1189

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CommentLibraryE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CourseSettingsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PushNotificationsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SyllabusE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/compose/CalendarE2ETest.kt
Updated some E2E test logs.
refs: MBL-18816
release note:
> [MBL-18816] [Teacher] Update E2E test logs

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/InboxComposePage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/RecipientPickerPage.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/inbox/compose/InboxComposeScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/MultipleValuesRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/RecipientChip.kt
refs: MBL-18481
release note: a11y improvements
> [MBL-18481][All] A11y Inbox Recipients fix

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
> [Teacher] - Attempt to stabilize Inbox Swipe Actions E2E Test

- apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/adapters/SubmissionContentAdapter.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewMediaFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
refs: MBL-18860
release note: Videos in SpeedGrader pause now when switching students.
> [MBL-18860][Teacher] Videos are not paused when switching in Speedgrader

- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
refs: MBL-18254
affects: Parent, Teacher, Student
> [MBL-18254][All] Ensure headings are denoted through structure and not implicitly

- apps/teacher/src/main/res/layout/adapter_quiz.xml
> [MBL-18241][Teacher] Ensure element role and state are correct

- libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
refs: MBL-18197
affects: Parent, Teacher, Student
> [MBL-18197][All] Ensure hidden, decorative and duplicate content and artifact elements are not exposed to assistive technologies

- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/SubmissionContentQuery.graphql
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderSharedViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/SpeedGraderDetailsScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/SpeedGraderGradeScreen.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/SpeedGraderSharedViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModelTest.kt
> [MBL-18845][Teacher] Speed grader attempt selector

- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderLtiSubmissionFragment.kt
Test plan: in the ticket - the file links in speedgrader new quizzes should be clickable and open the file
refs: MBL-18801
release note: Fixed file links in Quiz content in SpeedGrader.
> [MBL-18801][Teacher] App fails to preview student submission files in New Quizzes

- apps/student/src/main/java/com/instructure/student/util/StudentPrefs.kt
refs: MBL-18908
release note: App defaults "Show Grades" option to Off from now.
> [MBL-18908][Student] App defaults "Show Grades" option to On

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
- libs/pandares/src/main/res/drawable/ic_refresh_lined.xml
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/GroupHeader.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/GroupedListView.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderBottomSheet.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderSubmissionScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/SpeedGraderDetailsScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotes.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/SpeedGraderViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotesViewModelTest.kt
Test plan: see ticket + figma
refs: MBL-18883
> [MBL-18883][Teacher] SpeedGrader Student notes

- libs/pandautils/src/main/res/layout/fragment_sync_settings.xml
refs: MBL-18915
release note: Added scroll to the synchronization settings screen.
> [MBL-18915][Student] The Synchronization page doesn’t scroll in landscape mode

- apps/teacher/src/main/res/layout/fragment_edit_filefolder.xml
refs: MBL-18940
release note: Added scroll to edit folder screen.
> [MBL-18940][Teacher] Restricted Access schedule screen not scrollable in landscape mode

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
Test plan: see the ticket - actually it needed to open student view twice to be able to reporoduce the issue
refs: MBL-18934
release note: Fixed an issue where embedded images did not load in Student View in some cases.
> [MBL-18934][Student] Embedded pictures cannot be displayed in Student View

- apps/student/src/main/java/com/instructure/student/router/EnabledTabs.kt
- apps/student/src/test/java/com/instructure/student/router/EnabledTabsTest.kt
refs: MBL-18922
release note: Fixed an issue where Collaborations did not open from a link.
> [MBL-18922][Student] Embedded 'Collaborations' link cannot be opened

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt
Fix breaking todo e2e test.
refs: MBL-18985
affects: Teacher, Student, Parent
release note:
> [MBL-18985][Student][Teacher] - Fix breaking E2E tests

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/TodoPage.kt
Extend To Do E2E test with quiz submission item.
refs: MBL-16837
release note:
> [MBL-16837][Teacher] - Add Quiz To Do item type to ToDoE2E test

- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/SubmissionContentQuery.graphql
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModelTest.kt
> [MBL-18987][Teacher] Media Recording Submissions Fail to Load Properly

- apps/parent/src/main/java/com/instructure/parentapp/features/login/ParentLoginNavigation.kt
- apps/student/build.gradle
- apps/student/src/main/java/com/instructure/student/features/login/StudentAcceptableUsePolicyRouter.kt
- apps/student/src/main/java/com/instructure/student/features/login/StudentLoginNavigation.kt
- apps/student/src/main/java/com/instructure/student/features/settings/StudentSettingsBehaviour.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/login/TeacherLoginNavigation.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ExperienceAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/di/ApiModule.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ExperienceSummary.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountRepository.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountUiState.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountViewModel.kt
- libs/horizon/src/main/res/values/strings.xml
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/LoginNavigation.kt
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/viewmodel/LoginViewModel.kt
- libs/login-api-2/src/test/java/com/instructure/loginapi/login/viewmodel/LoginViewModelTest.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/di/SettingsModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsBehaviour.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsFragment.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/settings/SettingsViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/settings/SettingsRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/settings/SettingsViewModelTest.kt
Note: After this PR is merged the Horizon experience would be built in the Student app.
Test plan: 
- Test the login flow in both apps.
- Test all the scenarios in the Student app (Canvas user, K5 user, Career user)
- Optionally test the acceptable use policy
refs: CLX-1592
> [CLX-1592][All] Login Flow

- libs/login-api-2/build.gradle
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/viewmodel/LoginViewModel.kt
- libs/login-api-2/src/test/java/com/instructure/loginapi/login/viewmodel/LoginViewModelTest.kt
Test plan: Don't need to test it, but if you want you can force a crash on a local build and check logs.
refs: CLX-2105
> [CLX-2105] Add Crashlytics key for reporting app experience

- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/submission/HorizonSubmissionWorker.kt
> [CLX-2113][Horizon] Remove draft when file submission is complete

- apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/StudentAssignmentDetailsPage.kt
Implement E2E test case for the bug which was about creating bookmark from the course home page didn't work. (MBL-18910)
refs: MBL-18959
release note:
> [MBL-18959][Student] - Implement E2E test case for create bookmark from course home page

- libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListRepository.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListViewModel.kt
> [CLX-2051][Horizon] Inbox crash when no courses are present

- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ModuleItem.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleItemCardStateMapper.kt
- libs/horizon/src/main/res/values/strings.xml
> [CLX-1448][Horizon]Display requirement for module items.

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/notaparent/NotAParentScreenTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/DashboardInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ManageStudentsInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/NotAParentInteractionsTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/pages/compose/NotAParentPage.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/qr/QrPairingFragment.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/qr/QrPairingScreen.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/login/LoginLandingPageActivity.kt
- apps/parent/src/main/java/com/instructure/parentapp/features/notaparent/NotAParentScreen.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/pages/offline/ManageOfflineContentPage.kt
- apps/student/src/main/java/com/instructure/student/activity/LoginLandingPageActivity.kt
- apps/student/src/main/res/values/strings_no_translate.xml
- apps/teacher/src/main/java/com/instructure/teacher/activities/LoginLandingPageActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/holders/CourseBrowserViewHolder.kt
- apps/teacher/src/main/res/layout/fragment_not_a_teacher.xml
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt
- libs/pandautils/src/main/res/layout/fragment_offline_content.xml
- libs/pandautils/src/test/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModelTest.kt
Test plan: See occurrences in the ticket.
refs: MBL-18895
> [MBL-18895][All] Changed Canvas Student references to Canvas

- libs/horizon/src/main/java/com/instructure/horizon/features/learn/score/LearnScoreScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/ModuleItemSequenceViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/AssignmentDetailsViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddSubmissionViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/comments/CommentsViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/LearningObjectCard.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleHeaderStateMapper.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleItemCard.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/DateExtensions.kt
> [CLX-2062][Horizon] Use common date format.

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderGradePage.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/HintTextField.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TriStateBottomSheet.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingScreen.kt
> [MBL-19057] [Teacher] Refactor SpeedGrader E2E tests to handle new SpeedGrader.

- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/SubmissionContentQuery.graphql
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/graphql/SubmissionContentManagerImpl.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModel.kt
> [MBL-19061][Teacher] SpeedGrader - Attempts paging

- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/profile/AccountProfileViewModel.kt
> [CLX-2162][Horizon] Change full name to display name on the profile screen

- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TriStateBottomSheet.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentScreen.kt
> [MBL-19062][Teacher] SpeedGrader bottomsheet fixes

- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/AssignmentDetailsScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddSubmissionContent.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddTextSubmissionContent.kt
> [CLX-2040][Horizon] RCE is focused only on second tap

- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddFileSubmissionContent.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddSubmissionContent.kt
> [CLX-2043][Horizon] Scroll to bottom on file added.

- libs/horizon/src/main/java/com/instructure/horizon/features/learn/LearnScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/overview/LearnOverviewScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/progress/LearnProgressScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/notebook/NotebookScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/notebook/NotebookViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleContainer.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/inputs/singleselect/SingleSelect.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/tabrow/TabRow.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ComposeCanvasWebViewWrapper.kt
> [CLX-2059][Horizon] Learn screen UI issues

- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentInboxComposeInteractionTest.kt
- apps/parent/src/androidTest/java/com/instructure/parentapp/ui/interaction/ParentInboxSignatureInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/StudentInboxComposeInteractionTest.kt
- apps/student/src/androidTest/java/com/instructure/student/ui/interaction/StudentInboxSignatureInteractionTest.kt
- libs/pandares/src/main/res/values/colors.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/composables/SpeedGraderDetailsSectionLoading.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/studentnotes/StudentNotes.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/submissiondetails/SubmissionDetails.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsSection.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryModule.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/composables/SpeedGraderCommentInput.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/comments/commentlibrary/SpeedGraderCommentLibraryViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/rubric/SpeedGraderRubricRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/rubric/SpeedGraderRubricViewModelTest.kt
Test plan: known issue that the keyboard pushes up the whole screen, also the appbar
refs: MBL-19059
> [MBL-19059][Teacher] SpeedGrader - Comment library

- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddSubmissionContent.kt
> [CLX-2078][Horizon] Scroll is glitchy on the Assignment learning object

- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/details/SpeedGraderDetailsScreen.kt
Test plan: Open an Assignment in SpeedGrader, which has no submission details and student notes. Empty image and text should be present.
refs: MBL-19102
release note:
> [MBL-19102][Teacher] SpeedGrader details empty state

- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingScreen.kt
Test plan: Open an excused letter grade assignment, Letter Grade should be 'Excused' and not 'Not Graded'
refs: MBL-19106
release note:
> [MBL-19106][Teacher] Excused label fix

- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/ModuleItemSequenceScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/page/PageDetailsContentScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/notebook/common/webview/ComposeNotesHighlightingCanvasWebView.kt
> [CLX-2572][Horizon] Fix web view state handling

- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderGradePageTest.kt
- apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/compose/SpeedGraderGradePage.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/fakes/FakeSubmissionContentManager.kt
- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/fakes/FakeSubmissionGradeManager.kt
- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/SubmissionContentQuery.graphql
- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/SubmissionGradeQuery.graphql
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TextDropdown.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/TriStateBottomSheet.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderErrorHolder.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/SpeedGraderSharedViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/content/SpeedGraderContentViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/rubric/SpeedGraderRubricScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/rubric/SpeedGraderRubricViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/SpeedGraderSharedViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/rubric/SpeedGraderRubricViewModelTest.kt
Test plan: See ticket for list of issues
refs: MBL-19101
> [MBL-19101][Teacher] SpeedGrader findings

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsPresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/list/TeacherAssignmentListRepository.kt
> [MBL-19116][Teacher] Submission counter cards local calculation is wrong

- apps/student/src/main/java/com/instructure/student/dialog/AskInstructorDialogStyled.kt
> [MBL-19139][Student] Fixed ask your instructor dialog error handling

- apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
- apps/teacher/src/main/java/com/instructure/teacher/adapters/StudentContextFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/events/BusEvents.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/SubmissionListFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostGradeView.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt
- apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderGradePresenter.kt
- apps/teacher/src/main/java/com/instructure/teacher/view/edit_rubric/RubricEditView.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/PandaRationedBusEvent.kt
Test plan: see ticket
refs: MBL-19114
release note: Fixed submission list refreshing issue.
> [MBL-19114][Teacher] Statuses won't be refreshed automatically in some cases

- apps/parent/src/main/java/com/instructure/parentapp/features/calendar/ParentCalendarRepository.kt
- apps/parent/src/test/java/com/instructure/parentapp/features/calendar/ParentCalendarRepositoryTest.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRepository.kt
- apps/teacher/src/test/java/com/instructure/teacher/features/calendar/TeacherCalendarRepositoryTest.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CalendarEventAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DiscussionTopicHeader.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Plannable.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/PlannerItem.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ScheduleItem.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarEventsTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarEvents.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/PlannerItemExtensions.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt
Test plan: 
Create a graded discussion with checkpoints
Open calendar in all 3 apps, item should be visible
refs: MBL-19122
release note:
> [MBL-19122][All] Calendar Discussion Checkpoints

- libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListViewModel.kt
> [CLX-2704][Horizon] Show the correct date for inbox messages

- libs/horizon/src/main/java/com/instructure/horizon/features/inbox/details/HorizonInboxDetailsScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/score/LearnScoreScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/ModuleItemSequenceViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/AssignmentDetailsViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/addsubmission/AddSubmissionViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/moduleitemsequence/content/assignment/comments/CommentsViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/notebook/NotebookScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/notification/NotificationViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/LearningObjectCard.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleHeaderStateMapper.kt
- libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleItemCard.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/DateExtensions.kt
> [CLX-2769][Horizon] Localize date formats

- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsSection.kt
> [MBL-19217][Teacher] Replace attachment type dialog with bottom sheet

- automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/fakes/FakeSubmissionGradeManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/SubmissionAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Submission.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/DateHelper.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/HintTextField.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingRepository.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModel.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingRepositoryTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/grading/SpeedGraderGradingViewModelTest.kt
> [MBL-19221][Teacher] Late policy override

- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountUiState.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/AccountViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/navigation/AccountNavigation.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/navigation/AccountRoute.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/account/reportabug/ReportABugWebView.kt
- libs/horizon/src/main/res/values/strings.xml
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ComposeCanvasWebViewWrapper.kt
> [CLX-2771][Horizon] Report a problem

- libs/canvas-api-2/build.gradle
- libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/HorizonGetProgramCourseById.graphql
- libs/canvas-api-2/src/main/graphql/com/instructure/journey/GetProgramById.graphql
- libs/canvas-api-2/src/main/graphql/com/instructure/journey/GetPrograms.graphql
- libs/canvas-api-2/src/main/graphql/com/instructure/journey/ProgramFields.graphql
- libs/canvas-api-2/src/main/graphql/com/instructure/journey/schema.graphqls
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/DomainServicesAdapter.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/DomainServicesGraphQLClientConfig.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/DomainServicesRequestInterceptor.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/di/ApiModule.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/DomainServicesAuthenticationManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/HorizonGetCoursesManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/graphql/JourneyApiManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DomainService.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/DomainServicesApiPrefs.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/DomainServicesAuthenticator.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/ProgramDetailsRepository.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/ProgramDetailsScreen.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/ProgramDetailsUiState.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/ProgramDetailsViewModel.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/components/ProgramCourseCard.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/components/ProgramProgress.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/components/ProgramProgressItem.kt
- libs/horizon/src/main/java/com/instructure/horizon/features/learn/programs/components/ProgramsProgressBar.kt
- libs/horizon/src/main/res/values/strings.xml
- libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
> [CLX-2538][Horizon]Program details screen

- apps/student/src/main/java/com/instructure/student/features/assignments/list/StudentAssignmentListBehavior.kt
- apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
- apps/student/src/main/java/com/instructure/student/util/BinderUtils.kt
- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/list/TeacherAssignmentListBehavior.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
- libs/pandares/src/main/res/values/strings.xml
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/assignments/list/AssignmentListScreenTest.kt
- libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/grades/GradesScreenTest.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/ChekcpointItem.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SubmissionState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/list/AssignmentListBehavior.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/list/AssignmentListUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/list/AssignmentListViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/list/composables/AssignmentListScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesUiState.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesViewModel.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentExtensions.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/assignments/list/AssignmentListViewModelTest.kt
- libs/pandautils/src/test/java/com/instructure/pandautils/features/grades/GradesViewModelTest.kt
Test plan: see epic and figma, filtering is not working as expected because of API limitations
refs: MBL-19125
release note: Showing discussion checkpoints on Assignment list.
> [MBL-19125][Student][Teacher] Assignment list discussion checkpoints

- apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/OAuthManager.kt
- libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/QuizManager.kt
test plan: See ticket
refs: MBL-19109
release note: Fixed a bug where quizzes would not open in some cases.
> [MBL-19109][Student] Consortia quizzes open with root account

- apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/SubmissionListFiltersScreen.kt
- libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CheckboxText.kt
refs: MBL-19309
release note: Fixed a bug occurred while filtering by section on Submission list.
> [MBL-19309][Teacher] Section filtering does not work by clicking on the text

- libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt
refs: MBL-19199
release note: Fixed downloading files in Submission details.
> [MBL-19199][Parent] File Upload submissions (image/PDF) fail to download
