instructure/canvas-android

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/TextSubmissionEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/TextSubmissionUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/ui/TextSubmissionView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/ui/TextSubmissionViewState.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUpdateTest.kt

We don't have a submission service layer yet, but I was imagining that the view would have to start any kind of service as it holds a context. We will have to research the service layer further to get something that meets our needs. I was basing this work off of a JobIntentService, though we may need to use a foreground service so that the actions happen immediately.
Here's the example class I was thinking of:
```
class SubmissionService: JobIntentService() {
override fun onHandleWork(intent: Intent) {
when (intent.action) {
SubmissionAction.SUBMIT_TEXT_ENTRY.name -> {
val submission = apiAsync<Submission> {
SubmissionManager.postTextSubmission(
intent.getParcelableExtra(Const.CANVAS_CONTEXT),
intent.getLongExtra(Const.ASSIGNMENT_ID, -1),
intent.getStringExtra(Const.MESSAGE),
it)
}
// …
```

[Student][MBL-10249] Text submission mobius loop

---

apps/teacher/build.gradle
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/ConsumerQueueWrapper.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/CoroutineConnection.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/GlobalEvents.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/LateInit.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/MobiusFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/MobiusKotlinUtils.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/modules/ModulesListModels.kt
apps/teacher/src/main/java/com/instructure/teacher/mobius/common/ui/MobiusFragment.kt

For now, I've just duplicated things over to the teacher app, removing student specific elements. I'll also create a tech debt ticket to help us remember to take another look at our common mobius code and see what should be pulled out into a new or existing module.

[Teacher][MBL-12224] Add mobius and modules moflow to teacher

---

apps/student/src/main/AndroidManifest.xml
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/TextSubmissionEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/TextSubmissionModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/TextSubmissionUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/ui/TextSubmissionView.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUpdateTest.kt
libs/pandautils/src/main/res/values/strings.xml

This allows us to have long living network calls in the background when doing a submission, and handles all of the data persistence for failures (once persistence is added).

[Student][MBL-12223] Submission service (ready for review)

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
apps/teacher/src/main/res/layout/fragment_edit_quiz_details.xml
apps/teacher/src/main/res/layout/view_assignment_override.xml
apps/teacher/src/main/res/layout/view_comment.xml
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt

There are a few things going on here:
- Now excluding/ignoring accessibility issues with pspdfkit and date/time picker.  This required a fairly horrendous hack.
- Mopped up a few random accessibility failures.
- Accessibility testing now enabled by default for Teacher tests.  (UPDATE: Backed off of this.)
I also created tickets https://instructure.atlassian.net/browse/MBL-12258 and https://instructure.atlassian.net/browse/MBL-12259 for us to revisit / actually address the accessibility problems with pspdfkit and date/time picker at a later date if we so choose.  But ignoring them for now allows us to enable accessibility testing by default for the teacher app.

[Teacher][Accessibility][MBL-11805, MBL-12179, MBL-11802, MBL-11808]: Accessibility fixes

---

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt

There was an issue where assignment group weights were not being refreshed (except by unchecking the ‘what if’ grade box) and caused the grades screen to use stale weights for a long time.
There is a 'weighted course' in my sandbox that can be used to your hearts content while testing.

[Student][MBL-12211] Force refresh on initial load of grades screen

---

apps/teacher/src/main/java/com/instructure/teacher/presenters/AddMessagePresenter.kt

This fixes an issue where line breaks were being stripped out of messages sent from Inbox in the Teacher app. The issue appears to have been introduced in [this commit](https://github.com/instructure/android-uno/pull/1908) (related to GSON and semicolon encoding). Specifically, the Inbox API was updated to specify that the message subject and body are pre-encoded - and those Strings are indeed pre-encoded in the Student app - but the Teacher app was never updated to match that behavior.
To test: Send a new message from Inbox in Teacher that includes line breaks and semicolons. The sent message should exactly match the input text.

[Teacher][MBL-12252] Fix encoding issue when sending messages

---

libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.java

See ticket for test plan.
Could only reproduce by logging in to the canvas instance mentioned, then either waiting a while or by logging into another canvas instance and then switching back to the one mentioned. The first time I opened the app to the mentioned instance I was able to play the videos fine, but for whatever reason it would then have issues trying to access it later on.

[Student][Teacher][MBL-12241] Fix webview embedded videos not playing

---

libs/canvas-api-2/build.gradle
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/student/GetNoteAnnotationPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/student/GetSessionPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/teacher/GetNoteAnnotationPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/teacher/GetSessionPact.kt

Changed encoding in Content-Type header from "UTF-8" to "utf-8".  Got rid of "deleted" field in annotation object.
As near as I can tell, this will fix the problems called out in https://instructure.atlassian.net/browse/MBL-12312.
But I'll still need some help with publishing the tweaked contracts.

[Canvas][Pact][MBL-12312]: Canvas Pact fixes

---

apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt
libs/recyclerview/src/main/java/com/instructure/pandarecycler/BaseExpandableRecyclerAdapter.java
libs/recyclerview/src/main/java/com/instructure/pandarecycler/util/GroupSortedList.java

See ticket for test instance.
Old behavior, always opened to the top of modules when doing a deep link to the module list for a specific module.
New behavior, open the desired module to the top of the list and expand it as the default.

[Student][MBL-12343] Support deep linking to module group in list

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/QuizSubmissionViewRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/QuizSubmissionViewRenderTest.kt
apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/QuizSubmissionViewFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsUpdateTest.kt

We are loading a unique url here to mimic iOS and get the best user experience. It will load right to the quiz submission to let the user see their answers, rather than to the generic quiz submission page that always loads the most recent submission (even when trying to load the preview url for a previous submission).

[Student][MBL-11329] Support viewing quizzes in submission details

---

apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt

This fixes clicking links to deleted files in both the old and new assignment details flow. It likely also displays the error when clicking a file link from almost anywhere in the app now.

[Student][MBL-12135] Fix for clicking a link to a deleted file

---

apps/teacher/src/main/java/com/instructure/teacher/dialog/CanvasContextListDialog.kt
apps/teacher/src/main/java/com/instructure/teacher/dialog/PeopleListFilterDialog.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/MessageThreadFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/MessageThreadPresenter.java
apps/teacher/src/main/java/com/instructure/teacher/presenters/StudentContextPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/viewinterface/MessageThreadView.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/RequestInterceptor.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/StatusCallback.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/ApiAsync.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/AwaitApi.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/AwaitApis.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/AwaitParallel.kt

Repro:
- Install apps (student, teacher, and parent)
- Log into an account
- Kill the app and clear its cache
- Enable airplane mode on the device
- Open the app
Old behavior:
- Student: Only shows navigation tabs and blank pages
- Teacher: Pages load indefinitely
- Parent: Shows splash screen indefinitely
New behavior:
- Student: All pages display. Some still load indefinitely, others display empty state
- Teacher: Dashboard shows empty state, other pages still load indefinitely
- Parent: Still shows splash screen indefinitely

[All][MBL-12449] Remove special 504 handling from StatusCallback

---

apps/student/src/main/java/com/instructure/student/adapter/AssignmentDateListRecyclerAdapter.kt
apps/student/src/main/java/com/instructure/student/binders/ExpandableHeaderBinder.java

Click listeners in the notification list headers cause TalkBack to announce that the items can be 'activated', but doesn't let the user know if they've collapsed or expanded the corresponding list. 
Since expand/collapse is disabled when TalkBack is enabled this doesn't make sense to have, so here we're just not adding the click listener if TalkBack is enabled.

[Student][MBL-11098] A11y fix for expand/collapse notifications

---

apps/teacher/src/main/java/com/instructure/teacher/holders/DiscussionListHolder.kt

Test Plan:
Create a new announcement (from a different account but with no replies)
Open teacher app
Navigate to announcements in the course
Verify the new announcement has an unread icon

[Teacher][MBL-12467] Fix unread icon for announcements

---

libs/annotations/src/main/java/com/instructure/annotations/AnnotationConverter.kt

The fixes from web made the two smallest sizes work properly now, but the last size was still being cropped. This is the largest size that works without being cropped.

[MBL-9020] Updated the annotation converter text size for largest font

---

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt

Super weird minor bug. To repro, you need to have a teacher with only a single unpublished course. The dashboard api returns the value but the courses api doesn't (because we are only including available courses). I stumbled onto this issue while testing against a canvas portal.

[Student][MBL-12536] Fix issue with unpublished courses in student

---

apps/student/src/main/db/com/instructure/student/FileSubmission.sq
apps/student/src/main/db/com/instructure/student/Submission.sq
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/CanvasRestAdapter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FileUploadAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/builders/RestBuilder.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FileUploadManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ProgressResponseBody.kt
libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt
libs/pandautils/src/main/res/values/strings.xml

Save file uploads to our database to persist for the new submission flow.
Also adds a progress body for file uploads, updates sent through eventbus ProgressEvent so that anything can receive events.
To test:
This is a pain to actually test. It's not hooked up to any screens yet, so you have to go manually change some files to be able to test it directly.
First - change UploadFilesDialog.kt at line 457 (bottom of `uploadFiles` function) to look like this:
```
if(bundle != null) {
dialogCallback?.invoke(EVENT_ON_UPLOAD_BEGIN)
dialogAttachmentCallback?.invoke(EVENT_ON_UPLOAD_BEGIN, fileList.first())
//                intent.putExtras(bundle)
//                activity?.startService(intent)
dismiss()
}
```
Second - change AddSubmissionFragment.kt at line 281 (top of `setupListeners` function) …

[Student][MBL-12229] File upload persistence

---

apps/parent/src/main/java/com/instructure/parentapp/binders/CalendarWeekBinder.java
apps/teacher/src/main/java/com/instructure/teacher/presenters/AssignmentSubmissionListPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/utils/AssignmentExtensions.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentUtils2.kt
libs/pandautils/src/test/java/com/instructure/pandautils/unit/AssignmentUtils2Test.kt

There was a bug where a graded student that didn’t submit an assignment that was muted, would not show up when clicking the “graded” donut in teacher speed grader. They instead showed up with the filter “submitted” without a grade.

[Teacher][MBL-12537] Fix viewing submissions for teacher

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentDetailsPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/QuizDetailsPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizDetailsPage.kt

Speculative fix for intermittent failures in Teacher UI tests due to not waiting for activity launched via routeTo() to complete rendering before asserting against it.

[Teacher][Automation][MBL-12549]: Fix flaky Teacher UI tests

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.java

Successful and failed notifications from the submission service now navigate to a meaningful location in the app when clicked.

[Student][MBL-12231] Make submission notifications navigate

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/CoursesListPageTest.kt

Simple fix for CoursesListPageTest.displaysNoCoursesView.
I think that the problem was that we were trying to do a live operation using a token from taped data, and the token expired.  This shouldn't happen if we change the test to run in "Live" mode.

[Teacher][Automation][MBL-12698]: Fix broken Teacher UI test

---

apps/student/src/main/db/com/instructure/student/Submission.sq
apps/student/src/main/java/com/instructure/student/fragment/AddSubmissionFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadEffectHandlerTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.java
libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt
libs/pandautils/src/main/java/com/instructure/pandautils/services/NotoriousUploadService.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.java
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Utils.java

To test, make sure you’re not using the new file submission flow.
Go to an assignment that accepts media recording submissions.
Make sure line 205 and 206 look like this in `NotoriousMediaUploadPicker`:
```kotlin
callback?.invoke(mediaUri.path, NotoriousUploadService.ACTION.ASSIGNMENT_SUBMISSION)
// startService(serviceIntent)
```
and add this as part of the companion object of the same class:
```kotlin
var callback: ((String, NotoriousUploadService.ACTION) -> Unit)? = null
```
Add this in `NotoriousUploadService`, line 262:
```kotlin
val uploadCompleteIntent = Intent(FileUploadService.ALL_UPLOADS_COMPLETED)
uploadCompleteIntent.putExtra(Const.SUBMISSION_ID, notificationId.toLong())
assignment?.name?.let { uploadCompleteIntent.putExtra(Const.ASSIGNMENT_NAME, it)} …
```

[Student][MBL-12230] Wire up Notorious service to SubmissionService

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFavoritesFragment.kt

The empty message was showing for both the title and the message on the empty screen:
"It looks like there aren't any courses associated with this account. Visit the web to create a course today."

[Teacher][MBL-12707] Fix duplicate empty message on favorrites screen.

---

libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
libs/pandautils/src/main/java/com/instructure/pandautils/receivers/PushExternalReceiver.kt

To test, in the PushExternalReceiver onMessageReceived method, I looped and added the push notification 1000 times each receive to get a lot of messages stored locally. Once I had the crash, removing that loop and just getting one notification resulted in the same crash.
Replace this:
```
val push = PushNotification(htmlUrl, from, alert, collapseKey, userId)
if (PushNotification.store(push)) {
postNotification(this, msg, getAppName(this), getStartingActivityClass(), getAppColor())
}
```
with
```
val push = PushNotification(htmlUrl, from, alert, collapseKey, userId)
for (i in 0..1000) {
PushNotification.store(push)
}
if (PushNotification.store(push)) {
postNotification(this, msg, getAppName(this), getStartingActivityClass(), getAppColor())
}
```
This does take a little time to store all …

[MBL-11604][Student][Teacher] Fix notification crash

---

apps/student/src/main/java/com/instructure/student/util/AppManager.kt
buildSrc/src/main/java/GlobalDependencies.kt
libs/canvas-api-2/build.gradle
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/PrefRepoInterface.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/PrefUtils.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigPrefs.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/RemoteConfigUtilsTest.kt

Initially, we're only doing this in the Student app.
We may want to do a few more things before charging into Remote Config usage:
- Decide on a naming scheme for remote config parameters.  Should we name specifically for app (e.g., "student_rubric_v2"), with the possibility of naming for all apps (e.g., "all_rubric_v2")?
- Add a "remote config settings" menu/activity in debug builds to allow us to locally override remote config parameter values.

[Student][MBL-12672]: Initial attempt at incorporating Firebase Remote Config

---

apps/student/src/main/db/com/instructure/student/Submission.sq
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/test/java/com/instructure/student/db/sqlColAdapters/SubmissionDbQueriesTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt

Also added time when creating database submissions. This will let us diff in the assignment details screen to know if we have a (failed) persisted submission that's newer than what's given from the API.

[Student][MBL-12846] Add user ID to submissions in database

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/QuizSubmissionViewRenderTest.kt

This was the only test failing in our "multi-device" student UI test runs.

[Student][MBL-12547]: Disabling problematic UI test on < API 24

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/AssignmentDetailsRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/main/db/com/instructure/student/FileSubmission.sq
apps/student/src/main/db/com/instructure/student/Submission.sq
apps/student/src/main/java/com/instructure/student/db/Extensions.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/main/res/layout/fragment_assignment_details.xml
apps/student/src/test/java/com/instructure/student/db/sqlColAdapters/SubmissionDbQueriesTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt

To test:
Make a file submission, notice that when you come back to assignment details the page should update for "uploading in progress". When it succeeds, you'll see a succeeded message. When it fails (file quota limit for a group upload assignment), you'll see a failure message.
Should also update status for url/text submissions.

[Student][MBL-12847] Hooked in database submissions to status on assignment details

---

libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.java

To test: 
Search for 'scoe' in the school finder. Two results will pop up, one will work normally, the other won't... _until now._

[Student][MBL-12828] Fix passing 'Null' auth provider back to Canvas

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/ui/PickerSubmissionUploadView.kt

Before, it was always adding/removing the first item in the list, which looked weird. Now it will animate less, but new items are added to the bottom, while removed items just render again.

[Student] Made adding/removing files from file picker better

---

libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt

Now, they'll only peek the first time.
This was especially annoying when uploading a large file or multiple large files. Every time you swiped the notification up to let it keep going in the background, the next progress update would make it peek again.

[Student] Fix progress notifications always peeking

---

apps/student/src/main/res/layout/fragment_assignment_details.xml

So, the problem only occurs when there is a description for the assignment, which means that the description webview needs to be rendered.  It seems that, when the webview is rendered, it demands focus and therefore causes a scroll event to occur.
This is a pretty simple fix, but let me know if you see any potential problems with it.

[Student][MBL-12921]: Fixed problem with assignment details scrolling at startup

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt

This was mainly an issue on first submission, where a user submitting for the first time would see the status (in progress/failed) for their pending submission, but once it succeeds and the submission is deleted from the database, we would then not show any status or success for the submission on the assignment deets until pull to refresh.

[Student][MBL-12923] Refresh assignment deets on successful submission

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/pandares/src/main/res/values/strings.xml

This shows “graded” if the assignment was graded, “submitted” if it was submitted”, “missing” if there is no student submission and it was marked as missing or is past due, and “not submitted” otherwise.

[Student][MBL-12935][MBL-12937] Handle submission state in assignment

---

libs/pandautils/src/main/res/values/strings.xml

This tab shows the different file attachments for only one submission at a time, not just files for the assignment.

[Student] Fix string for empty files in submission

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadUpdate.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadUpdateTest.kt

If a file failed or if a file was the wrong type, the loading spinner wouldn't go away.

[Student] Fix spinner staying up for failed files in file picker

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUploadUpdateTest.kt

Instead, only encode when we're actually submitting the text to the API.

[Student][MBL-12985] Fix url encoded text submissions in database

---

apps/student/src/main/java/com/instructure/student/fragment/QuizQuestionsFragment.kt

See https://fabric.io/instructure/android/apps/com.instructure.candroid/issues/5c991dc8f8b88c29639899d1
To repro: Open the quiz details page for a timed quiz and double-tap "start" or "resume quiz" fast enough to open two instances of the quiz questions fragment. After the second fragment has opened and the timer is counting down, back out to the quiz details page and wait for the app to crash.

[Student] Fix quiz question timer crash

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadEventBusSource.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/ui/TextSubmissionUploadFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/ui/TextSubmissionUploadView.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUploadEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUploadEventBusSourceTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUploadPresenterTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/TextSubmissionUploadUpdateTest.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ProfileEditFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/UploadFilesDialog.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/MediaUploadUtils.kt

Altered the MediaUploadUtils to support a nullable fragment, falling back to the activity for requesting permission and dealing with activity results for images.

[Student][MBL-13013] Add rce images to text submission

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/CanvasRestAdapter.kt

In order to avoid excessive network calls, the assignment details page does not force load from the network unless the user has pulled to refresh. This can lead to an issue where routing to the page from a notification (e.g. a notification pushed because the student's submission has been graded or the assignment has otherwise been updated) before the cache has expired could result in the user seeing stale, misleading data. This commit works around the issue by clearing the network cache for the associated assignment when routing from a URL, causing the assignment details page to pull fresh data from the network.

[Student][MBL-12991] Pull assignment details from network when routing from a URL

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt

Before, if an assignment was graded and there was a failed local submission (in the database), then we weren’t showing the grade.

[Student][MBL-13033] Show grade even with a failed submission attempt

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt

We are already supporting navigating in module progression for items in the same module. We will not support intermodule navigation at this time.
See ticket for test details.
There is also a page in mobiledev -> Android dev -> pages -> "A link to a module item" :: that has a link to "Page 3" and can be used to verify navigation buttons inside the course module progression.

[Student][MBL-12952] Fix module name when linking to module item

---

apps/student/src/main/java/com/instructure/student/binders/AssignmentBinder.kt
apps/student/src/main/java/com/instructure/student/binders/GradeBinder.kt

We shouldn't be using assignment.muted to determine if we are showing grades to the user. Instead, if needed, the API should restrict our access to grades if we aren't allowed to see them.

[Student][MBL-13027] Remove assignment.muted from grades and assignment list

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/ModuleListRenderTest.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListViewState.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListItemBinder.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListModuleBinder.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ModuleItem.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ModuleObject.kt

If a user is enrolled in a course with a custom teacher role that does not have permission to edit course content, the publish status for modules will be null for that user. This commit updates the teacher app to not show any publish status icon for modules when null. See ticket for repro steps.

[Teacher][MBL-12971] Honor module publish status nullability

---

apps/student/src/main/java/com/instructure/student/mobius/common/MobiusExceptionLogger.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/MobiusFragment.kt

In release builds, any exceptions caught in the update or init operations, or in EffectHandler.accept, will be logged to Crashlytics.
In debug builds, logging for all loop operations is enabled; exceptions are not logged to crashlytics, instead they are logged locally and then thrown.

[Student] Log mobius exceptions to Crashlytics

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionsReplyFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/ProfileSettingsFragment.kt

See ticket for fabric links.
The first one in the profile is pretty easy to repro, simply edit the user profile, and hit back before the loading finishes.
I was unable to repro the discussion crash, but noticed that a similar fix had already been applied to a similar location calling the problematic function.

[Student][MBL-13060] 2 crash fixes

---

apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FileUploadAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FileUploadManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/NotoriousManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/DataResult.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ProgressRequestBody.kt
libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt
libs/pandautils/src/main/java/com/instructure/pandautils/services/NotoriousUploadService.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileUploadUtils.java
libs/pandautils/src/main/java/com/instructure/pandautils/utils/NotoriousUploader.kt

Do all of the file uploading inline in the submission service rather than splitting out the tasks between services requiring gross extra communication. 
Media uploads still need to be addressed, and comments still could be cleaned up.

[Student][MBL-12704] Combine file uploads into submission service

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/UploadStatusSubmissionViewRenderPage.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEventBusSource.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/UploadStatusSubmissionEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/UploadStatusSubmissionModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/UploadStatusSubmissionUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/ui/UploadStatusSubmissionView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/ui/UploadStatusSubmissionViewState.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/text/TextSubmissionUploadEventBusSource.kt
apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt
apps/student/src/main/res/layout/fragment_upload_status_submission.xml
apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionUpdateTest.kt
libs/pandares/src/main/res/values/strings.xml

Two extra things in this PR:
1. Fix a bug with onActivityResult event bus messages. Not removing the event was causing the event to leak to other things listening to that event.
2. Moved inserting into the database into the start service call. This will allow multiple submissions to be in progress WITH meaningful messages to users. Before, no ‘in progress’ messages would be visible to users and the submission service wouldn’t update to in progress until it was handling that submission. Now it will update everything to in progress right away, updating the actual progress of uploads as it happens. (This wasn’t an issue before as we were quickly moving through file uploads to the file upload service, meaning our submission service could quickly handle all the incoming intents. This doesn’t …

[Student][MBL-13042] Add retry/cancel to submissions

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/AssignmentDetailsRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt

See the ticket for more details. The gist is simple tho, we now hide the submission status indicator (Not Submitted, Mising, etc) for on paper/none submission types. We still show the Graded submission status regardless of submission type.

[Student][MBL-13079] Fix submission status for submission NONE

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/PickerSubmissionUploadRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/PickerSubmissionUploadRenderTest.kt
apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/ui/PickerSubmissionUploadView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/ui/PickerSubmissionUploadViewState.kt
apps/student/src/main/res/layout/activity_navigation.xml
apps/student/src/main/res/layout/fragment_picker_submission_upload.xml
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadPresenterTest.kt
libs/pandares/src/main/res/drawable/vd_add_from_camera.xml
libs/pandares/src/main/res/drawable/vd_add_from_device.xml
libs/pandares/src/main/res/drawable/vd_add_from_gallery.xml
libs/pandautils/src/main/res/layout/dialog_files_upload.xml
libs/pandautils/src/main/res/values/strings.xml

Also updates the empty state subtext in the non-submisison file upload dialog, and updates NavigationActivity to only show the bottom nav bar for 'root' fragments or if there is only one fragment on the backstack.

[Student][MBL-12861] Replace submission file picker FAB with bottom bar

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CalendarPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SubmissionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SyllabusPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionCommentsRenderPage.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt

There were a few corner cases, with additional constraints, that were not converted.  But most RecyclerView-scrolling logic now uses the centralized utility methods.

[Student][Automation][MBL-13158]: Abstracted most uses of RecyclerView scrolling logic to utility methods

---

apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeEffectHandler.kt
apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeModel.kt
apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeUpdate.kt
apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostGradeView.kt
apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostPolicyFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentSubmissionListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteResolver.kt
apps/teacher/src/test/java/com/instructure/teacher/unit/postpolicies/PostGradeEffectHandlerTest.kt
apps/teacher/src/test/java/com/instructure/teacher/unit/postpolicies/PostGradeUpdateTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ProgressAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/ProgressManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Progress.kt
libs/pandares/src/main/res/values/strings.xml

To test:
Post or Hide grades on the new post policy screen in Teacher.
Wait for a few seconds while the delayed job on Canvas finishes.
Verify that the screen will go back and refresh the submission list automagically.

[Teacher][MBL-13157] Add refresh to submissions list when post/hide grades

---

apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewHtmlFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
apps/teacher/src/main/java/com/instructure/teacher/utils/ModelExtensions.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/FileFolder.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.java

Repro steps on my sandbox (ask me for creds if needed, or see ticket for additional creds):
Student App
- Login as a student -> Change user (this clears cached cookies) -> Select previous login -> The Blue Course -> Files -> htmlpage.html
- There should be three lines of text. The first two lines should be large, italicized, and magenta. 
- The second line is styled by an external CSS file and prior to this commit was not being styled.
- The third line is a link to an assignment and should work as expected.
- Go to user files -> html -> htmlpage2.html. This should look and behave identical to the other HTML file.
Teacher
- Same as student, but log in as a teacher

[Student][Teacher][MBL-13064] Use authenticated session to view HTML files to allow linking to other file resources

---

apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt

When accessing a peer review from the notifications list, clicking on "Open in Browser" would crash the app.
Repro: My sandbox -> Notification list -> "Peer Review for Peer Review Assignment" -> Open in Browser

[Student][MBL-13151] Fix crash when opening peer review in browser

---

libs/login-api-2/src/main/res/values/strings.xml
libs/pandares/src/main/res/values/strings.xml

Apparently the translation folks were a bit confused by these strings and wanted clarity. I figured we'd remove them since they are not in use, they have been informed of this. Removing from the base file and letting the next import take care of the translations seems like the best way to handle this.

Removed a few unused strings

---

apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentUtils2.kt
libs/pandautils/src/test/java/com/instructure/pandautils/unit/AssignmentUtils2Test.kt

On paper assignments will still show "In Class", but all other non-online submissions will not show anything. They will also show 'Submitted' if there is a grade for the assignment.
Before, they would show a big red 'Missing' label if they were past due.

[Parent][MBL-13081] Fix 'No Submission' on non-submittable assignments

---

apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt

Repro: Compose/reply to a message, tap the send button, and then quickly tap the back button to show the exit confirmation dialog. Previously this dialog would remain open after the message had successfully sent and the compose fragment had been removed, and tapping 'Exit' would then cause a crash. This change causes the confirmation dialog to be dismissed along with the compose fragment.

[Student] Fix crash in compose message fragment

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt

If an assignment had been graded but was never submitted, the assignment detail page would show that status as "Submitted". This commit fixes the status for those cases and now shows either "Not Submitted" or "Missing".

[Student][MBL-13200] Assignment details page: Fix submission status for graded-but-not-submitted assignments

---

apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
apps/student/src/main/res/layout/fragment_application_settings.xml
libs/pandautils/src/main/java/com/instructure/pandautils/fragments/RemoteConfigParamsFragment.kt
libs/pandautils/src/main/res/layout/adapter_remote_config_param.xml
libs/pandautils/src/main/res/layout/fragment_remote_config_params.xml
libs/pandautils/src/main/res/values/strings_no_translate.xml

I added a UI for applying local overrides to Remote Config parameters, found in the settings menu next to Feature Flag functionality.  This allows developers to mess with the local settings of Remote Config parameters w/o messing with our global settings.
Some notes:
--The UI is drop-dead simple (and possibly ugly and inefficient).  But it only shows up in debug builds, and it gets the job done.
--I believe that parameter override(s) will persist until the next time that the app re-reads the Remote Config params from firebase.  That's about once per hour according to our current settings.
--I put as much of the logic as I could in the pandautils lib, so it shouldn't be too hard to duplicate this functionality in teacher and parent.

[Student][RemoteConfig][MBL-12852]: Added simple Remote Config override capability

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/DataResult.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/DataResultTest.kt

Wasn't able to reproduce the crash, but onFail was apparently not actually safe checking types. Hopefully this makes it work as intended.

[Student][Teacher][Parent] Fix onFail to not crash with the wrong type

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/CoursesListPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTestExtensions.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/CoursesApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt

To test:
Create an unpublished course with a new teacher that is only for unpublished courses. Login to the app. The current version will take you the the "Not a teacher" page, this patch allows those teachers to login to the app again.

[Teacher][MBL-13285] Allow teachers with only unpublished courses

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt

To test:
See ticket details, but basically any non native quiz was routing to the QuizStartFragment, which should only be navigated to if we have a native quiz. Otherwise, our BasicQuizViewFragment handles displaying quiz content that has web content.

[Student][MBL-13260] Fix non native quizzes from assignments

---

apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt

Since 2017, Google has blocked WebViews from accessing their auth stuff. What they didn't count on was devs changing their user agent string...
(See ticket for repro creds)

[Student][MBL-13261] Fix Google Apps LTI Auth

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricPresenter.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/rubricTab/SubmissionRubricPresenterTest.kt

If a rubric uses ranges it is possible for the assessed points to be different than the points of the matching rating. Previously we would only show the rating points, and the actual assessment value was not displayed. This PR updates our logic to show the assessed points of ranged rubrics as custom score, but only if it does not match the rating points.

[Student][MBL-13288] Show custom ratings in ranged rubrics

---

apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/CalendarListViewFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/CourseBrowserFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InboxFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/PeopleListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/QuizListFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/ToDoListFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusFragment.kt

Absent these tags, New Relic will consider each fragment/activity/interaction to be called "Display ComponentActivity".  We add these tags to differentiate between fragments/activities for the purpose of interaction tracking in New Relic.
Please let me know if you can think of other fragments that should be tagged like this.

MBL-13216: Tagged some fragments for New Relic interaction tracing

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionDetailsRenderTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/TextSubmissionViewRenderTest.kt

MBL-13328: Disabled ProgressBar test for API-23
MBL-13290: Speculative fix for a test involving orientation change.

[Student][Tests][MBL-13290,MBL-13328]: Fixed some overnight test issues

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt
apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/models/PushNotification.kt

This will also cause the app to go to the submission details page if the app is opened fresh from a push notification, then the user backs out completely and opens the app again. I don't think it's too big of an issue, but to make it stay on the assignment details page if the user opens the app again requires a bit more work (somehow modifying the fragment arguments between when it gets released from the Fragment Manager and when it gets loaded up again). I think the behavior of the app when it opens and we don't have a backstack setup is already wonky, so I didn't think this issue would be much of a problem.

[Student][MBL-13267] Graded non-gradeable assignment push notification work around

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsUpdateTest.kt

LTIs are viewable from the submission details page even if the assignment is locked. This just adds in a page that will show if the assignment is locked.

[Student][MBL-13364] Fix LTI viewable when assignment is locked

---

apps/teacher/src/main/res/layout/fragment_attendance_list.xml

Because Attendance is an LTI, in order to create a native experience the Teacher app uses a hidden WebView for managing parts of the attendance-taking process that can't be accomplished via exposed APIs. However, this WebView was being picked up by the accessibility service and Talkback/switch controls had to traverse through the entire web page first before it could get to the native elements. This commit fixes that behavior by marking the WebView as not being important for accessibility, allowing it to be skipped by screen readers.

[Teacher][MBL-13373] A11y - Fix hidden elements being traversed in the Attendance page

---

apps/student/src/main/java/com/instructure/student/binders/BaseBinder.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt
apps/teacher/src/main/java/com/instructure/teacher/adapters/StudentContextFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/holders/GradeableStudentSubmissionViewHolder.kt
apps/teacher/src/main/java/com/instructure/teacher/holders/StudentContextSubmissionView.kt
apps/teacher/src/main/java/com/instructure/teacher/utils/AssignmentExtensions.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/A11yUtils.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/DisplayGrade.kt

Originally this PR was attempting to consolidate grade formatting across all apps, but due to the scope of that task it has been moved to a [separate ticket](https://instructure.atlassian.net/browse/MBL-13435). This PR simply adds stronger typing to some existing logic (`Pair<String, String>` -> `DisplayGrade`) and ensures that grades in the Teacher app now use appropriate content descriptions.

[Teacher][MBL-13429] A11y - Fix content descriptions for grades

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionDetailsRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionDetailsRenderTest.kt

This was caused by the SlidingUpPanelLayout not using the correct type of animators, meaning that espresso couldn’t tell when it was “idle”. We were changing orientation while the layout was still “dragging”, and then fell back to it’s default state when showing in the new orientation (which is “collapsed”).

[Student][MBL-13405] Fix flakey drawer test

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/CourseInteractionTest.kt
automation/canvas_espresso/build.gradle
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/RootEndpoint.kt

MockWebServer allows us to spin up a mock server that actually binds to an address/port (e.g.,  http://localhost:41634).  We can then intercept every request to that server and mock a response.
So how do we get Webviews to direct their calls to our mock server?  It seems that every time we show content in an internal webview, we issue a /login/session_token call to make sure that the session is properly set up.  That call has a "return_to" query parameter that contains the url that the webview would like to load.  Normally, we echo back that "return_to" parameter in the /login/session_token response.  But for this hack we return a url in which we substitute the MockWebServer host for the original host of the "return_to" parameter, and then catch and process the request in our …

[Student][InteractionTests][MBL-13451]: Hack for supporting mocked Webview calls

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/CourseInteractionTest.kt

Disabled CourseInteractionTest.testCourse_openFile() for now on API-28.  API-28 disapproves of the HTTP call that we make from a webview.  We'll have to keep this test disabled on API-28 until we add HTTPS support to our MockWebServer.  
I'll keep MBL-13499 open; I just wanted to eliminate the nightly test failure that we were seeing.

[Student][InteractionTests][MBL-13499]: Disabled failing test on API-28.

---

apps/flutter_parent/README.md
apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/l10n/generated/messages_all.dart
apps/flutter_parent/lib/l10n/generated/messages_ar.dart
apps/flutter_parent/lib/l10n/generated/messages_en.dart
apps/flutter_parent/lib/l10n/generated/messages_en_unimelb_AU.dart
apps/flutter_parent/lib/l10n/generated/messages_messages.dart
apps/flutter_parent/lib/l10n/res/intl_ar.arb
apps/flutter_parent/lib/l10n/res/intl_en.arb
apps/flutter_parent/lib/l10n/res/intl_en_unimelb_AU.arb
apps/flutter_parent/lib/l10n/res/intl_messages.arb
apps/flutter_parent/lib/main.dart
apps/flutter_parent/lib/parent_app.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/l10n/app_localizations_delegate_test.dart
apps/flutter_parent/test/utils/accessibility_utils.dart
apps/flutter_parent/test/widget_test.dart

This uses intl to handle localization. Currently there is nothing to test, as there are no pages created to navigate to yet.
All the files in the `generated` folder can be ignored during PR's. They are generated code from the `intl_translation` tool and cannot be edited. They are necessary pieces for hooking up the strings resources (in the `res` folder) to the AppLocalization class.
Also, created a new app that's hooked up to all the localization stuff, but there's no screens to load yet so it's not being used by anything. We should be good to use this new ParentApp widget going forward.

[Parent][MBL-13481] Support flutter localizations

---

apps/flutter_parent/.gitignore
apps/flutter_parent/ios/Flutter/Debug.xcconfig
apps/flutter_parent/ios/Flutter/Release.xcconfig
apps/flutter_parent/ios/Podfile

I don’t think we care about iOS, but every time I delete these files they just generate again. Seems like we just need to add them when they change. Also, adding `coverage/` as an ignored directory for git, so we don’t accidentally push coverage reports.

Add generated changes for iOS

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt

I'll leave MBL-13604 open,  to remind us that we have no automated video submission comment test.

[Student][E2E][MBL-13604]: Stubbing out video comment logic that breaks E2E test

---

apps/flutter_parent/lib/api/assignment_api.dart
apps/flutter_parent/lib/api/course_api.dart
apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/assignment_group.dart
apps/flutter_parent/lib/models/assignment_group.g.dart
apps/flutter_parent/lib/models/course.dart
apps/flutter_parent/lib/models/course.g.dart
apps/flutter_parent/lib/models/enrollment.dart
apps/flutter_parent/lib/models/enrollment.g.dart
apps/flutter_parent/lib/models/serializers.dart
apps/flutter_parent/lib/models/serializers.g.dart
apps/flutter_parent/lib/screens/courses/courses_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_details_interactor.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_summary_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_syllabus_screen.dart
apps/flutter_parent/lib/utils/base_model.dart
apps/flutter_parent/lib/utils/service_locator.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/screens/courses/course_details_interactor_test.dart
apps/flutter_parent/test/screens/courses/course_details_model_test.dart
apps/flutter_parent/test/screens/courses/course_details_screen_test.dart
apps/flutter_parent/test/screens/courses/courses_screen_test.dart
apps/flutter_parent/test/utils/base_model_test.dart

This is just the holder for the three tabs on the course details screen. Since those 3 screens all share the course and assignment data, this parent widget is loading that information for all of its children. For children to refresh the data, they need a consumer of the model, and just call model on the load. I’ve created 3 stub classes for these finer detail screens and shown how to do a refresh of data.
Also adds a new ‘BaseModel’ class, this is used for complex screens where we want to make use of provider for sharing data with children widgets. It keeps track of the loading state (via the ViewState property) and allows children and parents to use/load/refresh data when needed.

[Flutter-Parent][MBL-13573] Add course details holder

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt

Evidently, it can take a little time from when you reply to a discussion (or a reply) and when that reply shows up in the webview (and therefore our asserts for its existence pass).  Espresso does not naturally wait for this action, so I had to add a sleep().  And I found that 1 second was not long enough, so I made it 2 seconds.  The methods where these sleeps were added are called a total of 8 times by our interaction test suite, and once by our E2E test suite.
The sleep() calls are unfortunate, but I think they are necessary, and it's annoying when your PR is blocked on these tests failing.
If desired, I can create a ticket to find a way to create an idling resource to wait for the webview to be updated.

[Student][Interaction][MBL-13558]: Fix intermittent problems with discussion replies

---

apps/teacher/src/main/java/com/instructure/teacher/adapters/StudentContextFragment.kt
apps/teacher/src/main/res/layout/fragment_student_context.xml

On Android 10, adding a view during runtime was having it take the entire view height. Placing it in the xml file and toggling the visibility allows the children to actually wrap_content like we want.

[Teacher][RC-1.9.1] Fix student context page having full height views

---

apps/flutter_parent/.gitignore
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/api/api_prefs_test.dart
apps/flutter_parent/test/api/dio_config_test.dart
apps/flutter_parent/test/screens/courses/courses_screen_test.dart
apps/flutter_parent/test/screens/not_a_parent_screen_test.dart
apps/flutter_parent/test/utils/test_app.dart

Upgrading Flutter to the newest stable requires a newer version of the intl dependency. I also ran a package upgrade to our dependencies.
I added `.flutter-plugins-dependencies` to the gitignore as well.

[Flutter-Parent] Upgrade dependencies and update gitignore

---

apps/flutter_parent/lib/api/accounts_api.dart
apps/flutter_parent/lib/api/alert_api.dart
apps/flutter_parent/lib/api/assignment_api.dart
apps/flutter_parent/lib/api/auth_api.dart
apps/flutter_parent/lib/api/course_api.dart
apps/flutter_parent/lib/api/enrollments_api.dart
apps/flutter_parent/lib/api/inbox_api.dart
apps/flutter_parent/lib/api/user_api.dart
apps/flutter_parent/lib/api/utils/dio_config.dart
apps/flutter_parent/lib/api/utils/fetch.dart
apps/flutter_parent/test/api/dio_config_test.dart

Also finishes fleshing out DioConfig which helps to set up and configure Dio instances for different use cases while retaining core functinality like logging, cache options, per_page query param, etc. For example, a configuration for typical Canvas API usage can be obtained with `DioConfig.canvas()`, and a Dio instance can be obtained by calling `.dio` on that config.
For convenience, the `canvasDio()` function has been kept and now just calls through to `DioConfig.canvas().dio`

[Flutter-Parent][MBL-13675] Use fetch/fetchList for api calls

---

apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart
apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart
apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
apps/flutter_parent/lib/utils/design/parent_theme.dart

An optional flag has been added to allow screens to have a white app bar that are using the default parent theme (that has no student context, so colors won’t change). Defaults to true, as every screen using this default theme right now wants a white app bar. And by white, I really mean the background color (white normally, black in dark mode).

[Flutter-Parent][MBL-13681] Support white app bar in default theme

---

apps/parent/build.gradle
apps/parent/src/main/AndroidManifest.xml
apps/parent/src/main/java/com/instructure/parentapp/util/ApplicationManager.kt
apps/teacher/build.gradle
apps/teacher/src/main/AndroidManifest.xml

Essentially a revert of https://github.com/instructure/canvas-android/commit/f44b66defe5a4664cc8c0a6afc168aaedf1b5422
In an attempt to fix the ‘crash statistics’ in firebase that reports crash free users, I removed the old fabric API key as the new setup docs didn’t state anything about it. Turns out, that just broke crashlytics entirely for us. Since we are an old firebase project, we still need to provide the api key.
Also, bump to next version to do a new hotfix

[Teacher][RC-1.9.1] Fix crashlytics | version bump

---

apps/flutter_parent/android/app/build.gradle
apps/flutter_parent/android/app/src/main/AndroidManifest.xml
apps/flutter_parent/android/build.gradle
apps/flutter_parent/lib/main.dart
apps/flutter_parent/lib/utils/crash_utils.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml

To test: verify crashes show up in Crashlytics. They show up as non-fatals (unless we change the forceCrash flag).
An easy way to test, pull the branch `parent/MBL-13600-crashlytics-CRASH` and run it in release mode (on a real device). This branch allows the app crash in three different ways to test crashlytics:
1. Tapping on a course (no UI change)
2. Trying to pair a student (no UI change)
3. Clicking on ‘alerts’ or ‘calendar’ (shows crash panda)

[Flutter-Parent][MBL-13600] Add crashlytics support

---

apps/student/src/main/java/com/instructure/student/adapter/ModuleListRecyclerAdapter.kt
apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt

To repro: Deep link to the module list via a module url, e.g. `https://jmarshall.instructure.com/courses/1/modules/1`, and then quickly back out of the page before it has finished loading

[Student][MBL-13739] Fix crash when closing module list immediately after routing to it with a module_id route param

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt

This wasn’t stripping out module items that we couldn’t show in the course module progression (subheader, unlockRequirements), thus was causing content to not be visible and would cause a crash on back press.
To test: see Jira ticket for details

[Student][MBL-13738] Fix routing to module items

---

apps/student/flank_sweep.yml

Replace API-25 with API-29 in our multi-device test runs.  API-29 is gaining popularity, and we already test API-25 in our PR runs.
Note that I did try one run on API-29, and there were some failures, but they were PdfInteractionTest failures, which are more or less expected at this point.

[Student][Automation][MBL-13756] : Test on API-29

---

apps/parent/src/main/java/com/instructure/parentapp/tasks/ParentLogoutTask.kt
apps/polling/src/main/java/com/instructure/androidpolling/app/asynctasks/PollsLogoutTask.kt
apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt
apps/teacher/src/main/java/com/instructure/teacher/tasks/TeacherLogoutTask.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CommunicationChannelsAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CommunicationChannelsManager.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
libs/pandautils/src/main/java/com/instructure/pandautils/models/PushNotification.kt
libs/pandautils/src/main/java/com/instructure/pandautils/receivers/PushExternalReceiver.kt

Filtering notifications is problematic, as the domain users log in with may be different that the account’s root domain. This makes it hard to store notifications based on user info. Instead, we will just always show notifications.
Instead of keeping old communication channels alive, we now delete them when logging out or switching users. This prevents the currently logged in account from seeing notifications meant for an account which they don’t have access to.
To test: (student and teacher)
Log into an account, verify you can get notifications.
Switch users, verify notifications disappear from the status bar.
Log out, verify you no don't get any notifications.
*vanity domain* would be nice to test, don't think we have an instance of this (should be able to log in via the non vanity …

[Student][Teacher][MBL-13725] Don’t filter notifications

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt

This was a little frustrating to chase, because all 4 failures/retries showed slightly different causes and crash locations.  And also because the test intermittently passes in Bitrise and runs flawlessly locally.  
I don't know for sure what is going wrong, but what I added has a chance to address all flavors of the failures that we were seeing.

[Student][Test][MBL-13793]: Speculative fixes to stabilize Grades E2E test

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PickerSubmissionUploadInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/PickerSubmissionUploadPage.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt

These changes seemed to make a difference locally (where I was always failing the first attempt but passing the retry.  ???)  And I suspect that they will address the other failure modes I was seeing on FTL as well.
(And, to follow up on a Slack thread, I don't think that notifications are interfering with the test.)

[Student][Tests][MBL-13802] : Stabilized PickerSubmissionUploadInteractionTest.testSubmit

---

apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart
apps/flutter_parent/lib/screens/crash_screen.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart
apps/flutter_parent/lib/screens/inbox/conversation_details/conversation_details_screen.dart
apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart
apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
apps/flutter_parent/lib/screens/manage_students/manage_students_screen.dart
apps/flutter_parent/lib/screens/settings/settings_screen.dart
apps/flutter_parent/lib/screens/theme_viewer_screen.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
apps/flutter_parent/lib/utils/design/parent_colors.dart
apps/flutter_parent/lib/utils/design/parent_theme.dart

Cleans up light mode divider for default parent theme as well, and changed the bottom navigation bar to be white/black matching designs rather than the default gray that Flutter uses.
To test:
Navigate around the app in light/dark modes. 
* Verify shadows show up when the app bar is using the student color. 
* Verify dividers show up on screens with a white app bar or for any screen in dark mode
* Verify the bottom nav is white/black in light/dark mode
Note: High Contrast mode doesn't change the divider color at all in the designs.

[Flutter-Parent][MBL-13747] Add divider in dark mode

---

apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
apps/flutter_parent/lib/screens/inbox/reply/conversation_reply_screen.dart
apps/flutter_parent/test/screens/inbox/create_conversation/create_conversation_screen_test.dart
apps/flutter_parent/test/screens/inbox/reply/conversation_reply_screen_test.dart

- Disabled maxLines on the message input to avoid nested scrolling
- Disabled attachment interactions while message is sending
- Fixed a condition where ErrorWidget could briefly flicker on screen when deleting an attachment

[Flutter Parent] Small tweaks and fixes for conversation create/reply

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/network/api/enrollments_api.dart
apps/flutter_parent/lib/network/api/error_report_api.dart
apps/flutter_parent/lib/screens/crash_screen.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/utils/common_widgets/error_report/error_report_dialog.dart
apps/flutter_parent/lib/utils/common_widgets/error_report/error_report_interactor.dart
apps/flutter_parent/lib/utils/service_locator.dart
apps/flutter_parent/test/utils/widgets/error_report/error_report_dialog_test.dart
apps/flutter_parent/test/utils/widgets/error_report/error_report_interactor_test.dart

This lets app users contact support via the error report endpoint. Added to the ‘contact support’ button on crash screens. Also defaulted our ‘help’ button in the drawer to use this dialog to make it easier for testing. Should not be the default for the ‘help’ dialog in the end game.
To test:
Verify the dialog shows up. If you hit send, it will send an actual error report to canvas support, so probably don't hit send without commenting out the api call. I have done this and will not move the ticket to done until I get a response.

[Flutter-Parent][MBL-13683] Report a problem dialog

---

apps/flutter_parent/assets/html_wrapper.html
apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/account_notification.dart
apps/flutter_parent/lib/models/account_notification.g.dart
apps/flutter_parent/lib/models/alert.dart
apps/flutter_parent/lib/models/announcement.dart
apps/flutter_parent/lib/models/announcement.g.dart
apps/flutter_parent/lib/models/remote_file.dart
apps/flutter_parent/lib/models/remote_file.g.dart
apps/flutter_parent/lib/models/serializers.dart
apps/flutter_parent/lib/models/serializers.g.dart
apps/flutter_parent/lib/network/api/announcement_api.dart
apps/flutter_parent/lib/screens/alerts/alerts_screen.dart
apps/flutter_parent/lib/screens/announcements/announcement_details_interactor.dart
apps/flutter_parent/lib/screens/announcements/announcement_details_screen.dart
apps/flutter_parent/lib/screens/announcements/announcement_view_state.dart
apps/flutter_parent/lib/utils/service_locator.dart
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/models/alert_test.dart
apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart
apps/flutter_parent/test/screens/announcements/announcement_details_interactor_test.dart
apps/flutter_parent/test/screens/announcements/announcement_details_screen_test.dart

Couple of things to note:
-Institution level announcements that don't target the observer role will result in an error screen. This behavior is consistent with the current playstore version, I'm not sure if this is an api issue or not. It seems odd that the alert would show up, but not be viewable (api returns a 401).
-The webview in use needs a bit of work. I'm going to start on another commit that adds an extension function to format/load Html, so we can use the html_wrapper consistently. We also need to handle a few of the things that CanvasWebView is doing for us, so things like the new RCE images work.

[Parent][MBL-13618] Announcement Details

---

apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt

Super simple change to help us further investigate this issue. The next step will most likely be a looping refresh attempt on the grades page, to combat possible delayed grades calculation.

[MBL-13828][Student] Add some logs to E2E grades test

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PeopleInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/PersonDetailsPage.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt

I had to make a slight modification to how we set up users in MockCanvas.init(). Unfortunately, in order to create enrollments, we have to FIRST have users. But the user field needs its enrollments list populated, and with our models being immutable, it required some annoying copying. It should be a pretty safe change, 🤞 That it doesn't effect any existing tests.

[Student][MBL-13243] People interaction test

---

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt

Okay, so going to add some context around this small change.
It was noticed that we were hiding final grades for all periods when outside of the grading period start/end date range. This was happening specifically as a result of our function call that checks for "hasActiveGradingPeriods()". When we combine the boolean result of hasActiveGradingPeriods() w/ isTotalsForAllGradingPeriodsEnabled to determine if the course grade is locked, we run into problems. The problem here is that we (really I) were using hasActiveGradingPeriods() to determine if we should be viewing the "All Grading Periods" period, and forgot about the case of a user attempting to view individual grading periods after their term was over. In order to correct this within the current function for getting a course grade, …

[Student] A small change to displaying total grades for MGP

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/CoursesApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/EnrollmentsApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/UserApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/CanvasRestAdapter.kt

This was a bit of a pain because we had to do some tweaking of data-seeding logic to allow for non-default retrofit clients and service instances.
I've verified that the test's API requests are hitting the vanity domain.

[Student][E2E][MBL-13891]: E2E test for signing into vanity domain

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/assignment_group.g.dart
apps/flutter_parent/lib/models/course.dart
apps/flutter_parent/lib/models/course_grade.dart
apps/flutter_parent/lib/models/enrollment.dart
apps/flutter_parent/lib/models/enrollment.g.dart
apps/flutter_parent/lib/models/grading_period.dart
apps/flutter_parent/lib/models/grading_period.g.dart
apps/flutter_parent/lib/models/grading_period_response.dart
apps/flutter_parent/lib/models/grading_period_response.g.dart
apps/flutter_parent/lib/models/serializers.dart
apps/flutter_parent/lib/models/serializers.g.dart
apps/flutter_parent/lib/network/api/assignment_api.dart
apps/flutter_parent/lib/network/api/course_api.dart
apps/flutter_parent/lib/network/api/enrollments_api.dart
apps/flutter_parent/lib/screens/courses/details/course_details_interactor.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/lib/screens/courses/details/grading_period_modal.dart
apps/flutter_parent/test/models/course_grade_test.dart
apps/flutter_parent/test/models/enrollment_test.dart
apps/flutter_parent/test/screens/assignments/assignment_details_interactor_test.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
apps/flutter_parent/test/screens/courses/course_details_interactor_test.dart
apps/flutter_parent/test/screens/courses/course_details_model_test.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
apps/flutter_parent/test/screens/courses/courses_screen_test.dart
apps/flutter_parent/test/utils/widgets/error_report/error_report_interactor_test.dart

MGP filter on course grades.
Also, fixes tests that aren't actually clearing mocks via `clearInteractions` and replaced with `reset`.
Note: While it looks like a massive PR, here's some stats:
model line count - 99
generated line count - 406
test line count - 753
other code lines - 262

[Flutter-Parent][MBL-13226]: Multiple grading periods

---

apps/postProcessTestRun.bash
apps/student/flank.yml
automation/canvas_espresso/build.gradle
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt

Changes:
--Test failure reporting is now routed through the same callback as test retry reporting.  This will allow us to see failure message + stack trace for failures, just like we do for retries.
--I capped the failure message at 4096 bytes.
--We are now reporting info on passing tests.  This will allow us to analyze which tests are taking the most time to run.
--I converted a reporting script that only existed in a Bitrise step to a script file that lives in our repo.

[Student][Splunk][MBL-13809] | More splunk

---

apps/postProcessTestRun.bash

Combining all successful-test info across all devices/test suites produced a message / shell command that was too long.  (Only a problem when running against more than one device.)  So I altered the logic to send a success-message out after each device's results has been processed.

[All][Splunk][MBL-13927]: Limited length of test "success report" to Splunk

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/locked_module.dart
apps/flutter_parent/lib/models/locked_module.g.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart

No need to manually build the ‘unlock_at’ message, it is included in the lock explanation of the assignment (which the fullyLocked check makes sure the unlock_at is after the current date).

[Flutter-Parent] Fix incorrect lockAt usage in assignment details

---

apps/flutter_parent/lib/screens/assignments/assignment_details_interactor.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_summary_screen.dart
apps/flutter_parent/test/screens/assignments/assignment_details_interactor_test.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart

Using the course fetch that it already had instead, so that screens routing to assignment details don’t have to have a course code.

[Flutter-Parent] Remove course code dependency for assignment details

---

apps/flutter_parent/assets/html/html_wrapper.html
apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/schedule_item.dart
apps/flutter_parent/lib/network/api/calendar_events_api.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_summary_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_syllabus_screen.dart
apps/flutter_parent/lib/screens/events/event_details_interactor.dart
apps/flutter_parent/lib/screens/events/event_details_screen.dart
apps/flutter_parent/lib/utils/common_widgets/constrained_web_view.dart
apps/flutter_parent/lib/utils/service_locator.dart
apps/flutter_parent/lib/utils/web_view_utils.dart
apps/flutter_parent/test/screens/courses/course_summary_screen_test.dart
apps/flutter_parent/test/screens/events/event_details_interactor_test.dart
apps/flutter_parent/test/screens/events/event_details_screen_test.dart
apps/flutter_parent/test/utils/widgets/constrained_web_view_test.dart

Made a 'ConstrainedWebView' that is reusable between assignment details and this. Really, any scrollable screen that needs a webview as one of it's children can use it.
Also added optional padding to our loadHtml function to let webviews add padding if they want it. Made this optional as there are a few places where webviews are getting padded via the parent container padding. In the old app this was always getting set to 10px. (touched the syllabus to add padding as well)
To test:
My sandbox' Course 1 has some calendar events on Feb 17 that can be used for testing the different cases.

[Flutter-Parent][MBL-13619] Event details screen

---

libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.java
libs/pandautils/src/main/res/values/strings.xml

We were only supporting uploading video files through the Studio LTI. Now we will allow uploads for any of the allowed file types that the web view is asking for. This enables LTIs like turnitin to be used from the mobile apps.
To test:
See ticket for test credentials to use the Turnitin LTI
Also should test with other LTIs (Studio is the only one I could think of)

[Student][MBL-13932] Support LTI file uploads

---

apps/flutter_parent/lib/screens/dashboard/dashboard_interactor.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/utils/service_locator.dart

No need to obtain the selected student notifier via locator, since it’s always available through provider. This was causing a crash as provider was disposing of the notifier, and the locator was trying to reuse the same one.
Also reset the selected student to 0 so that the color theme resets on logouts. We'll probably want to persist this later in the login object.
To test:
Currently on master, switching users will show a crash screen once the new user is loaded (after the splash screen). This should no longer happen.

[Flutter-Parent] Fix crash when switching users

---

apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/test/screens/login/login_landing_screen_test.dart

Previously the nav backstack was not being cleared after switching logins, so the user could press the back button and it would return to the login landing page instead of closing the app.

[Flutter Parent] Clear nav backstack when switching users

---

apps/flutter_parent/lib/models/course_grade.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/lib/utils/common_widgets/empty_panda_widget.dart
apps/flutter_parent/lib/utils/common_widgets/error_panda_widget.dart
apps/flutter_parent/lib/utils/common_widgets/full_screen_scroll_container.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
apps/flutter_parent/test/utils/widgets/empty_panda_widget_test.dart
apps/flutter_parent/test/utils/widgets/error_panda_widget_test.dart
apps/flutter_parent/test/utils/widgets/full_screen_scroll_container_test.dart

Fix ‘legacy’ parents failing to load enrollments for a given user.
Show period header in empty/error states (so they can still switch around to different grading periods)

[Flutter-Parent] Fix course grade screen bugs

---

apps/flutter_parent/.gitignore
apps/flutter_parent/lib/models/course.dart
apps/flutter_parent/lib/models/course_grade.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/test/models/course_grade_test.dart
apps/flutter_parent/test/models/course_test.dart
apps/flutter_parent/test/screens/courses/course_details_model_test.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart

Now shows current grading period by default when going into course details.
Will default to showing the course enrollments current_grade for All Grading Periods if we can’t get the enrollment from the individual enrollment endpoint. i.e., for legacy parents (didn’t pair via pairing code) we can’t get grades by the enrollment endpoint, we can only see the course enrollment which has current_grade (all grading periods) and the current_period_computed_current_grade (current period).

[Flutter-Parent] Moar grade fixes

---

apps/flutter_parent/lib/screens/courses/courses_screen.dart

We are hiding grades if locked, as that is the behavior we are seeing on web. This also matches the behavior we chose on the course grade screen that hides the 'total grade' if it's locked.

[Flutter-Parent] Hide grades on dashboard if locked

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt

One speculative fix for "late delayed job" problem: If we expect a list of stuff returned from an API and that list is empty, try a couple of swipe-refreshes before giving up.

[Student][E2E][MBL-13979]: E2E test stabilization

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/screens/help/help_dialog.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart
apps/flutter_parent/test/screens/help/help_dialog_test.dart
apps/flutter_parent/test/utils/test_app.dart
apps/flutter_parent/test/utils/widgets/error_report/error_report_dialog_test.dart

Also adds a static convenience method to TestApp to enable testing widgets that need a build context (like dialogs).
Main pain point here, I had to include a second intent library to support emails. The url_launcher can start an email activity, but only the default one and it can’t handle a multiline body. There’s also the android_intent library we are using for showing files from inbox, this unfortunately has a bug where we emails aren’t getting set up properly on the actual intent, therefore the email app can’t read the ‘to’ email we’re trying to send to.
Unfortunately, the intent library I found handles emails correctly, but does not support setting both data and a type, so it does not work for the original intent inclusion of viewing a file from a url (just passing the url will …

[Flutter-Parent][MBL-13509] Help Dialog

---

libs/canvas-api-2/build.gradle
libs/canvas-api-2/pact_encoding_fixup.bash
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/ApiPactTestBase.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/EnrollmentsApiPactTests.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/UsersApiPactTests.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactCommonLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactCourseLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactEnrollmentLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactSectionLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactTermLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactUserLogic.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/parent/CanvasPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/parent/GetCourse.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/student/CanvasPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/student/GetCourse.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/teacher/CanvasPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/teacher/GetCourse.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/student/DocViewerPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/student/GetNoteAnnotationPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/student/GetSessionPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/teacher/DocViewerPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/teacher/GetNoteAnnotationPact.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/docviewer/teacher/GetSessionPact.kt

In the process of writing provider states and running our contracts against those provider states, we had to make several tweaks to our contracts.  
One of those tweaks was to upgrade our pact-jvm-consumer to a more modern version.  Unfortunately, it was not backward-compatible, and so we had to make a bunch of mechanical changes to all of our pact contract code, including the legacy stuff written years ago.  These changes bloated this PR.  Feel free to give only cursory attention to any files in pact/canvas/student. pact/canvas/teacher, pact/canvas/parent and pact/docviewer.

[Student][Pact][MBL-13808] | pact round2

---

apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart

Just delaying the intensive GPU content until after our grade animation is done, that way the animation is more smooth. Loading images and web views (especially with images) takes up too much of the GPU’s power and causes some stuttering by Flutter.

r[Flutter-Parent] Chunky assignment loading hack fix

---

apps/flutter_parent/lib/utils/crash_utils.dart
apps/flutter_parent/lib/utils/quick_nav.dart

You can test by throwing an exception somewhere in the code, running in release mode, and making the crash happen.
Or you can view what it looks like when this is done: https://console.firebase.google.com/project/automatic-rite-88319/crashlytics/app/android:com.instructure.parentapp/issues/c3c4934e105770e3ee0ee85bcfd20db0

[Flutter-Parent] Add more logs and info for crashes to help debugging

---

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_home_page_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_syllabus_screen.dart

This allows the screens to retain state (like scroll position) when moving between tabs

[Flutter Parent] Add keep-alive mixin to course details screens

---

apps/flutter_parent/lib/utils/crash_utils.dart

This is to help us differentiate between widget crashes and dart crashes.

[Flutter-Parent] Add log if we catch a ‘widget crash’

---

apps/flutter_parent/tools/l10n_extract_push.rb

hub_config was missing (can be used for local usage, not needed for bitrise).
Also was missing a `pub get` (local testing was fine because I had already done this).

[Flutter-Parent] Translation export script fix

---

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt

Not sure why I never thought of this before, super simple fix for the annotation resize issue, see [https://instructure.atlassian.net/browse/MBL-13464](ticket) for explanation.
This is probs our best option, at least from the various fixes I've tried before. I simply collapse the sliding panel layout before loading in new pdfs. That way, we never render a pdf into the half sized content pane. This way we don't have to compromise with either additional re-draws on the pdf view, removing the content scaling, or messing with any other content type. It might be slightly annoying to see the sliding panel collapse on a new pdf load though.

[Teacher][MBL-13464] Simple fix for pdf annotation resize issue

---

apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/PageDetailsFragment.kt

For some reason, we were at one time excluding studio from the authentication of iframe src urls. Calvin and I noticed this while testing earlier today. Perhaps studio has changed, but this is now necessary to get these videos to not require the user to login. Also, videos weren't pausing upon hitting the back arrow from student page details, hence the lifecycle pass throughs to canvas webview in student.

[Student][Teacher] Quick fix for studio vids embedded in pages

---

apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
apps/flutter_parent/test/screens/splash/splash_screen_test.dart
apps/flutter_parent/test/utils/test_app.dart
apps/flutter_parent/test/utils/widgets/webview/canvas_web_view_test.dart
apps/flutter_parent/test/utils/widgets/webview/simple_web_view_screen_test.dart

Makes use of the TestApp’s platforConfig field, rather than manually calling setupPlatformChannels, for widget tests that use test app.

[Flutter-Parent] Cleaned up tests a little for platform configuration

---

apps/flutter_parent/android/app/src/main/AndroidManifest.xml
apps/flutter_parent/android/app/src/main/kotlin/com/instructure/parentapp/MainActivity.kt
apps/flutter_parent/android/app/src/main/kotlin/com/instructure/parentapp/plugins/DataSeedingPlugin.kt
apps/flutter_parent/lib/parent_app.dart
apps/flutter_parent/lib/router/parent_router.dart
apps/flutter_parent/lib/screens/splash/splash_screen.dart

Also moved data seeding logic to it's own plugin to keep MainActivity a little more clean.
Also fixes a new bug from SplashScreen, where _navigate was getting called multiple times for already logged in users (can't control how many times build is called in a widget). This was causing multiple animation listeners to be added. Instead, just add the animation listener once at when creating the animation.

[Flutter-Parent][MBL-14043] External routing

---

apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt

See ticket for more deets. We had a route in place in student that was perhaps intended for a similar case, but wasn't functioning. The new RCE content creates a route with no canvas context id, even for course files.

[Student][Teacher] Add route support for new rce files

---

apps/student/src/main/java/com/instructure/student/activity/CandroidPSPDFActivity.kt
apps/student/src/main/res/values/styles.xml

There are issues with theming the toolbar to the institution color when it is white. Rather than hack our way into a way to customize all the toolbar colors, just default to gray with white icons.

[Student][MBL-14023] Always use gray for pdf toolbar

---

apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_month.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart
apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_widget_test.dart

On most screens in landscape, and even on very small screens in portrait, the expanded month view in the calendar will overflow vertically. Shinking the height of the calendar elements is not an option, as that would reduce the tap target size below the acceptable a11y threshold. We also can't wrap the month view in a scrollable widget as that would interfere with swipe-to-expand. As such, the month view needs to be disabled entirely in these cases.
With this change, the height available to the calendar widget is now monitored. If the height ever becomes insufficient to display the full-height month view then the month view will be disabled entirely, and re-enabled when the height becomes sufficient again. If the month view is disabled while expanded, it will trigger a collapse animation.

[Flutter Parent][MBL-14088] Fix calendar month height overflow

---

apps/flutter_parent/lib/network/utils/analytics.dart
apps/flutter_parent/lib/network/utils/authentication_interceptor.dart
apps/flutter_parent/lib/network/utils/dio_config.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
apps/flutter_parent/test/network/authentication_interceptor_test.dart

Unfortunately, testing this is a little complicated, and requires pulling the branch down to make a small change before running.
* Check mobile dev developer key for the one created by Nate (login as site admin, click on Developer Keys in the menu)
* Set the client id/secret using the number above the 'Show Key' button, and the string shown after pressing the 'Show Key' button respectively
* This requires a small change in `WebLoginScreen#_webView`
* This line `final verifyResult = snapshot.data;`
* Becomes `final verifyResult = snapshot.data.rebuild((b) => b..clientId = 'id'..clientSecret = 'secret');` with the hid/secret obtained from the dev key page
* Then, build the app and sign in to mobiledev.test (to bypass mobile verify).
* Log into web as that user, check for a token that has an …

[Flutter-Parent][MBL-13938] Refresh token interceptor

---

apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart

Fixes an issue where the selected week can be off by one if the current date is a week or more past a DST change. This is related to [another fix](https://github.com/instructure/canvas-android/pull/612) where the selected day could be off by one after a DST change. Note that the month view _should_ be immune to this category of issue.

[Flutter Parent] Calendar week DST fix

---

apps/flutter_parent/lib/screens/alerts/alerts_screen.dart

Since the dismiss button needs to be 48x48 min, the padding at the end is unnecessary.

[Parent-Flutter] Take off extra padding on alert dismiss button

---

apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_day_of_week_headers.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_week.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart
apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_day_of_week_headers_test.dart
apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_week_test.dart
apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_widget_test.dart

It turns out that PageView automatically reverses for RTL locales, so we don't need to handle that ourselves.
Also, this commit moves most calendar tests into groups, so make sure to enable 'Hide whitespace changes'

[Flutter Parent][MBL-13925] Calendar RTL fixes

---

apps/flutter_parent/lib/network/utils/api_prefs.dart
apps/flutter_parent/lib/network/utils/dio_config.dart
apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/lib/screens/settings/settings_interactor.dart
apps/flutter_parent/lib/utils/crash_utils.dart
apps/flutter_parent/lib/utils/debug_flags.dart
apps/flutter_parent/lib/utils/logger.dart

All release/debug checks now key off of `ApiPrefs.isDebug`. This is to simplify logic for debug related features to one place, and making it easy to enable debug features in a release build.
Feel free to request any other changes/features with this. Kept is very simple so we could modify as needed, but would be nice to have a way to change this at runtime (without leaking into actual release builds)

[Flutter-Parent][MBL-14102] Simplify debug flag

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.java

To test:
Use my sandbox and go to course 1.
* Google Meet -> Opens our LTIWebView momentarily, then goes straight to the play store page (or opens the app if already downloaded)
* Google Meet (new tab) -> Opens our LTIWebView, once you click "open in new tab" it behaves like "Google Meet"
* Goog intent -> Opens our LTIWebView, once you click "open in new tab" it loads googles search page as a fallback for a non-supported intent.

[Student][Teacher][MBL-14122] Support opening LTI links that are intents

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/FileUtils.java
libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileUploadUtils.java

To test:
I don't remember the exact case I got to this, but I have a downloaded video in Photos on my emulator. It has a valid filename and extension, but mime type of "*/*".
Trying to submit this file as a media upload for an assignment crashes.
Normal media files should also still upload without issue.

[Student][MBL-14108] Fix crash for media uploads without file extension

---

apps/flutter_parent/android/app/src/main/kotlin/com/instructure/parentapp/MainActivity.kt
apps/flutter_parent/lib/network/api/user_api.dart
apps/flutter_parent/lib/router/panda_router.dart
apps/flutter_parent/lib/screens/calendar/calendar_screen.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_interactor.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/screens/dashboard/student_expansion_widget.dart
apps/flutter_parent/lib/utils/service_locator.dart
apps/flutter_parent/test/router/panda_router_test.dart
apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_widget_test.dart
apps/flutter_parent/test/screens/dashboard/dashboard_interactor_test.dart
apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart

There's some behavior we might want to tweak, mainly that when deep linking to one of the bottom nav screens a new Dashboard is loaded. The user can navigate in that new Dashboard like normal, but when they hit back enough times, that Dashboard screen is popped and the previous Dashboard screen is shown. Might not be a big deal, but it might seem kind of weird if the user navigates a lot in the new Dashboard screen.

[Flutter Parent][MBL-13916] Dashboard Tab Routing

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/models/serializers.g.dart
apps/flutter_parent/lib/models/user.dart
apps/flutter_parent/lib/models/user.g.dart
apps/flutter_parent/lib/network/api/user_api.dart
apps/flutter_parent/lib/router/panda_router.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_interactor.dart
apps/flutter_parent/lib/utils/common_widgets/web_view/simple_web_view_screen.dart
apps/flutter_parent/test/router/panda_router_test.dart
apps/flutter_parent/test/screens/dashboard/dashboard_interactor_test.dart

To test:
Change the account settings at the institution level to limit web access to parents using the mobile app.
Open the app and go to an assignment with some links to places we don't handle in the app (my sandbox, course1 -> link assignment). Things like modules, files, groups, pages.
When the checkbox is not enabled, the links should open out to the browser (or show the action sheet to choose between apps, always pick browser).
When the checkbox is enabled (to limit web access), then links should open to our simple web view that doesn't allow any further page loads, also displaying an alert that only disappears when clicked.

[Flutter-Parent][MBL-13924] Limit web access

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/RemoteConfigSettingsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
libs/pandautils/src/main/res/layout/adapter_remote_config_param.xml
libs/pandautils/src/main/res/layout/fragment_remote_config_params.xml

Ensures that former bizarre behavior associated with interacting with soft keyboard from remote config settings page no longer occurs.
Why an E2E test?  It was easier to code than an interaction test, and also the dataseeding that takes place at the start of the test ensures that the remote config settings will be read successfully before the main test logic starts.

[Student][RemoteConfig][MBL-14172]: An E2E test for remote-config-settings

---

apps/flutter_parent/lib/screens/dashboard/dashboard_interactor.dart
apps/flutter_parent/test/screens/dashboard/dashboard_interactor_test.dart

To test:
The app should now show data in the nav drawer again for users that don't have any permissions defined.

[Flutter-Parent] Fix getting self when no permissions are present

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionDetailsEmptyContentRenderTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEmptyContentPresenterTest.kt

So that it works on April 1-3.

MBL-14187: Fix for SubmissionDetailsEmptyContentRenderTest.displaysDueDate

---

apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart

Previously, the dashboard would fetch the user (self) exclusively from the API. This change initializes the dashboard with the user value cached in ApiPrefs, acting as a fallback in the event of an API error. This eliminates the need for the error state which (1) was not fully implemented as it had no designs, and (2) would prevent the user from accessing features in the nav drawer.

[Flutter Parent] Init dashboard with cached user

---

apps/flutter_parent/lib/screens/alerts/alerts_interactor.dart
apps/flutter_parent/lib/screens/dashboard/selected_student_notifier.dart
apps/flutter_parent/lib/screens/dashboard/student_horizontal_list_view.dart
apps/flutter_parent/test/screens/alerts/alerts_interactor_test.dart
apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart
apps/flutter_parent/test/screens/calendar/calendar_screen_test.dart
apps/flutter_parent/test/screens/courses/courses_screen_test.dart
apps/flutter_parent/test/screens/dashboard/student_horizontal_list_view_test.dart

To test:
Have two students under an observer, with different amounts of alerts (create an alert in the course for student 1, but no alerts for courses for student2).
Switch between the two students, make sue the alert count notifier updates properly.
Also, PTR on the alerts screen should now update the alert count as well.

[Flutter-Parent] Update alert count when switching students

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/RemoteConfigSettingsPage.kt

The problem was that "qr_login_enabled" is a prefix for "qr_login_enabled_teacher", so when I looked for the former (as a partial string) Espresso got confused.  I fixed the matcher to look for rc_name+':'.
I also consolidated some common logic into a single method to get rid of some code duplication.

[Student][E2E][MBL-14172]: Fix RemoteConfigSettings E2E test issue

---

apps/flutter_parent/lib/main.dart
apps/flutter_parent/lib/utils/remote_config_utils.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/utils/remote_config_utils_test.dart

For now, this does not include an rc-settings page where you can enforce local overrides.  That will need to be a separate ticket.
Works very similar to native Android RemoteConfigUtils: remote config values are stored in shared preferences.  When we fetch updates from Firebase, we store them in shared preferences.  All reads are fetched from shared preferences.  Internal defaults are in effect until the initial Firebase read completes.

[Parent][Architecture][MBL-14173] | added remote config support to flutter-parent

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
apps/flutter_parent/test/screens/login/domain_search_screen_test.dart
apps/flutter_parent/test/screens/login/web_login_screen_test.dart

To test:
* Try entering in the domain search www.<sandbox> and make sure it still works (strips out www.)
* Try skipping mobile verify and using the expiring refresh token key in mobile dev (manually input client id/secret from the key)
* Special test: Pull down the code, change the user-agent header in AuthApi to ‘candroid’ -> Try loading canvas.sfu.ca and verify you get redirected (doesn’t allow ‘canvasParent’ normally)

[Flutter-Parent][MBL-13598] Login improvements

---

apps/flutter_parent/lib/screens/settings/settings_screen.dart

This fixes an issues where light/dark mode buttons were missing semantic labels and did not indicate the selected state when using a screen reader

[Flutter Parent][MBL-14193] A11y fix for light/dark mode buttons

---

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart

To test:
The course Android Dev on our mobiledev sandbox fits the criteria for only showing the grade, without showing the grading period header. Before, the grade was right against the top of the screen. Now there is padding whether there is just the grade, just the grading period header, or both.

[Flutter-Parent] Fix course grade having no padding

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/screens/help/terms_of_use_screen.dart
apps/flutter_parent/lib/screens/settings/settings_screen.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart
apps/flutter_parent/lib/utils/common_widgets/web_view/simple_web_view_screen.dart
apps/flutter_parent/lib/utils/design/parent_theme.dart
apps/flutter_parent/lib/utils/design/theme_prefs.dart
apps/flutter_parent/plugins/webview_flutter/android/build.gradle
apps/flutter_parent/plugins/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
apps/flutter_parent/plugins/webview_flutter/lib/platform_interface.dart
apps/flutter_parent/plugins/webview_flutter/lib/src/webview_method_channel.dart
apps/flutter_parent/plugins/webview_flutter/lib/webview_flutter.dart
apps/flutter_parent/test/screens/settings/settings_screen_test.dart
apps/flutter_parent/test/utils/test_app.dart

This change updates the androidx webkit dependency to add support for dark mode in WebViews. This requires a recent version of the native WebView to test, so it may not work on emulators without Google Play. Tested working on an Android 7 emulator w/ Google Play and an up-to-date physical device running Lollipop. 
Note that the background of WebViews in dark mode is a very dark gray, which doesn't fully match the app's completely black background. Cursory research on this issue did not reveal an easy fix, so we may just have to live with it.

[Flutter Parent] Support dark mode in WebViews where possible

---

apps/flutter_parent/run_all_ui_tests.bash

The "flutter drive" mechanism is klunky, only allowing one test to be run at once.  I had already created run_all_ui_tests.bash to run multiple ui tests.  This commit/PR adds some aggregation logic to that script to facilitate running on bitrise and failing for *any* failure.

[Parent][E2E][MBL-14223]: Added logic to aggregate Parent E2E test results

---

apps/flutter_parent/lib/screens/dashboard/student_horizontal_list_view.dart

To test:
Student names should be centered, even when in an RTL language

[Flutter-Parent] Fix student switcher in RTL

---

apps/flutter_parent/lib/network/utils/analytics.dart
apps/flutter_parent/lib/screens/settings/settings_interactor.dart
apps/flutter_parent/lib/screens/settings/settings_screen.dart
apps/flutter_parent/lib/utils/design/theme_transition/theme_transition_target.dart
apps/flutter_parent/lib/utils/notification_util.dart
apps/flutter_parent/test/screens/settings/settings_interactor_test.dart
apps/flutter_parent/test/screens/settings/settings_screen_test.dart
apps/flutter_parent/test/utils/accessibility_utils.dart
apps/flutter_parent/test/utils/notification_util_test.dart

Added events for toggling dark/hc modes, as well as for creating reminders. Creating different events for each as we only get 25 parameters across all events, so saving those for more important things.
Also created a new `testNonWidgetsWithContext` test wrapper for testing NON widgets that need a BuildContext (there’s interactors that have contexts as parameters, using this test method and the widget tester you can achieve testing those functions).

[Flutter-Parent] More analytics

---

apps/postProcessTestRun.bash

We were emitting one big message for all successful tests in a run.  As we approached 300 tests, we began observing that that message was getting too large for curl to send.  So now we emit the message every 100 tests.

[Student][Automation][MBL-14238] | fix splunk reporting for individual test results

---

apps/flutter_parent/lib/network/api/auth_api.dart
apps/flutter_parent/run_all_ui_tests.bash
apps/flutter_parent/test_driver/apis/user_seed_api.dart

Also MBL-14242: Suppressed a RemoteConfigUtils call that was messing up the tests.
(I also tried to convert all tabs to 8-spaces in the script file, leading to some insignificant diffs.)

[Parent][E2E][MBL-14233]: Added retry capability to e2e test script

---

apps/flutter_parent/lib/models/reminder.dart
apps/flutter_parent/lib/models/reminder.g.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_interactor.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/lib/screens/events/event_details_interactor.dart
apps/flutter_parent/lib/screens/events/event_details_screen.dart
apps/flutter_parent/lib/utils/db/db_util.dart
apps/flutter_parent/lib/utils/db/reminder_db.dart
apps/flutter_parent/lib/utils/notification_util.dart
apps/flutter_parent/test/screens/assignments/assignment_details_interactor_test.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
apps/flutter_parent/test/screens/events/event_details_interactor_test.dart
apps/flutter_parent/test/screens/events/event_details_screen_test.dart

To test:
- Set up a reminder for an assignment or calendar event (~1 minute in the future to avoid waiting too long)
- Wait for the notification to appear
- Tap the notification and the app should route to the correct assignment/event.
- Routing should succeed regardless of whether the the app is in the foreground, background, or not started.

[Flutter Parent][MBL-14236] Wire up notifications to router

---

apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/test/screens/login/login_landing_screen_test.dart

- Increases login button width to 260
- Uses outline style instead of solid style for help button icon
- Removes extra horizontal padding around help icon
- Adjusts space between login button and QR code button
Before/after:

[Flutter Parent] Login landing page UI tweaks

---

apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
apps/flutter_parent/lib/utils/common_widgets/avatar.dart
apps/flutter_parent/lib/utils/design/parent_theme.dart

- Updates the Avatar widget style to match existing apps (white background, gray text, thin gray border)
- Fixes recipient list avatars not showing user initials
- Changes dark mode divider color to a slightly lighter value
- Increases nav drawer avatar size to match designs
Before/after

[Flutter Parent] Avatar tweaks

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/CourseBrowserPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt

The remote config flag is set to false for now. Student View api work is still beta, and we'll want to flip that flag once we're 100% rolled out for the student and teacher release that has the student view feature.

[Teacher] Add remote config flag for Student View and also check for old student app

---

apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
apps/flutter_parent/test/utils/widgets/webview/canvas_web_view_test.dart

Shows loading before web views finish page load, also consolidates loading indicators for assignment details, since web view was showing two different loaders which felt icky.
To test:
Navigate to all the different screens that have webviews: Assignment Details (most important), Home Page, Syllabus, Event Details, and Announcement Details.
Verify that all content still loads.
Verify loading indicators are more consolidated and look better.

[Flutter-Parent][MBL-14269] Make RCE having a loading indicator while loading

---

apps/flutter_parent/lib/screens/web_login/web_login_screen.dart

It's still not the greatest experience, but at least it's now possible.
BTW, portrait login on small-screen devices is not a great experience either -- you have to scroll the screen to see the fields into which you are typing.  But this fix didn't make it any worse.

[Parent][Login][MBL-14271]: Fixed landscape login.

---

apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart

Wasn’t opening an authenticated link before, so the user would have to login again.
To test:
Open some rich content with an lti in an iframe and click on the ‘Launch External Tool’ button at the bottom of the page. Verify it opens a web view directly to the content (no login required)

[Flutter-Parent] Fix opening iframe LTIs externally

---

apps/flutter_parent/android/app/proguard-rules.pro

To test, pull this branch locally and build in release mode from Android Studio. The app should no longer crash on launch.

[Flutter Parent] Fix building in release mode from IDE

---

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart

If a course has no assignments with a current grading period, filtering to ‘All Grading Periods’ removes the period header and requires users to back out and in to filter by period again.
To test:
Use Wilsons sandbox and view the course `Better Chat`, ensure you can change the grading period to "All Grading Periods" and then change again without having to reload the screen.

[Flutter-Parent] Fix edge case for grading period header

---

apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart
apps/flutter_parent/test/screens/login/domain_search_screen_test.dart

This will only debounce the network request now, letting the user navigate to the next screen immediately if they want to instead of waiting for a debounce to hit the ‘next’ button or the ‘go’ button on the keyboard.

[Flutter-Parent] Made domain search only debounce network

---

apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_interactor.dart
apps/flutter_parent/test/screens/inbox/conversation_list/conversation_list_interactor_test.dart

When no matching course can be found for an enrollment provided to the convo list when creating a message, we get an error screen. This happens for me when I have a pending invite to a course, but could happen for many cases (concluded perhaps?)

[Flutter-Parent][RC 3.2.0] Fix error screen in convo course list

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsEffectHandler.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEffectHandlerTest.kt
apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/EnrollmentManager.kt

Submission details page would error out because we were using the observer's ID instead of the observee's ID when retrieving submissions.
If the user is an observer, we use the ID of the first observee we retrieve that is in that course.

[Student][MBL-14248] Show submission when observer

---

apps/flutter_parent/android/app/src/main/AndroidManifest.xml
apps/flutter_parent/lib/network/utils/api_prefs.dart
apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/lib/screens/splash/splash_screen.dart
apps/flutter_parent/lib/screens/splash/splash_screen_interactor.dart
apps/flutter_parent/lib/utils/veneers/barcode_scan_veneer.dart
apps/flutter_parent/test/network/api_prefs_test.dart
apps/flutter_parent/test/screens/login/login_landing_screen_test.dart
apps/flutter_parent/test/screens/login/qr_login_tutorial_screen_interactor_test.dart
apps/flutter_parent/test/screens/splash/splash_screen_interactor_test.dart
apps/flutter_parent/test/screens/splash/splash_screen_test.dart
apps/flutter_parent/test/utils/test_helpers/mock_helpers.dart

To Test:
I don't have a real device without a camera, but using an emulator with 0 cameras did the trick. The splash screen does the check/awaiting, and the login landing page should show/hide the qr code button. We can just re-use the ApiPrefs value for QR scanning pairing codes in the future.

[Parent] Cameras optional

---

apps/flutter_parent/lib/screens/qr_login/qr_login_tutorial_screen.dart
apps/flutter_parent/lib/screens/qr_login/qr_login_tutorial_screen_interactor.dart
apps/flutter_parent/lib/screens/splash/splash_screen.dart
apps/flutter_parent/lib/screens/splash/splash_screen_interactor.dart
apps/flutter_parent/test/screens/login/qr_login_tutorial_screen_interactor_test.dart
apps/flutter_parent/test/screens/login/qr_login_tutorial_screen_test.dart
apps/flutter_parent/test/screens/splash/splash_screen_interactor_test.dart
apps/flutter_parent/test/utils/test_helpers/mock_helpers.dart

This is in response to this [crash](https://console.firebase.google.com/project/automatic-rite-88319/crashlytics/app/android:com.instructure.parentapp/issues/cb52c6344beab447e5e6b1c5c354592a?time=1587513600000:1587772799000&sessionId=5EA24134006600014EC6F3E1B437B260_DNE_0_v2):
How to repro:
Login with qr code, log out immediately, attempt to login again with the same qr code.
Basically, anytime something went wrong inside of the sign on portion of QR login, the error handling wasn't working. This PR fixes those issues and fixes properly handling an error message and pop without resulting in an app crash.

[Parent] Beef up QR error handling

---

apps/flutter_parent/lib/network/utils/api_prefs.dart
apps/flutter_parent/lib/router/panda_router.dart
apps/flutter_parent/pubspec.lock
apps/flutter_parent/pubspec.yaml
apps/flutter_parent/test/router/panda_router_test.dart

To Test:
Sooo its kinda gross to test this. You need to install a 2.0 version of parent app and sign in. Then, install this branch over it (pref over adb, you can't open the app). Without ever opening the app (and thus setting the current student) click an external link to the assignment details screen.
Let me know if you have any issues.

[Parent] Fix for migrated deep linking

---

apps/flutter_parent/android/app/src/main/res/values/colors.xml
apps/flutter_parent/lib/router/panda_router.dart
apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart
apps/flutter_parent/lib/utils/common_widgets/attachment_indicator_widget.dart
apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart
apps/flutter_parent/lib/utils/design/parent_colors.dart
apps/flutter_parent/test/router/panda_router_test.dart

When an empty url is passed to an image loader (FadeInImage/NetworkImage/etc) it can throw a non-fatal exception. It won’t crash the app but does create a non-fatal on Firebase.
Encoding domain provided by users so navigation can happen. If the url is invalid, the web login page may show an empty screen, but that’s what our native apps do in the same scenario (and it is better than not navigating to the screen with a non url safe character)
Updated native splash screen to use same accessible color as flutter

[Flutter-Parent] Fix small, miscellaneous problems

---

apps/flutter_parent/lib/screens/dashboard/student_horizontal_list_view.dart

TO Test:
Add a student with a really long name. Notice that when its overflowed it is no longer centered with the users avatar.
Before / After

[Parent] Student dropdown name text alignment

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/network/utils/analytics.dart
apps/flutter_parent/lib/network/utils/api_prefs.dart
apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
apps/flutter_parent/lib/screens/help/help_screen.dart
apps/flutter_parent/lib/utils/common_widgets/rating_dialog.dart
apps/flutter_parent/lib/utils/url_launcher.dart
apps/flutter_parent/lib/utils/veneers/AndroidIntentVeneer.dart
apps/flutter_parent/test/screens/help/help_screen_test.dart
apps/flutter_parent/test/utils/test_app.dart
apps/flutter_parent/test/utils/test_helpers/mock_helpers.dart
apps/flutter_parent/test/utils/veneer/android_intent_veneer_test.dart
apps/flutter_parent/test/utils/widgets/rating_dialog_test.dart

Added a rating dialog, only shows after 4 weeks, good luck testing that 😉
Also consolidated some intent logic behind a veneer to be reusable by different screens.
Unable to add a widget test for the dashboard showing this new dialog, as we purposefully don't show the rating dialog during tests to keep e2e tests stable (this may not be an issue in flutter, it was in native so I'm also hiding it in tests here).
To test locally:
* Comment out the first block of the `showDialogIfPossible ` in the RatingDialog class so that the method just runs `showDialog`. This will show the dialog every time you open the app. 
* 4 & 5 stars go to the app store (native only did 5 stars, we're adding 4 here as we need the positive ratings)
* 3 and under are asked to leave a comment. If no comment is provided …

[Flutter-Parent][MBL-14286] Rating dialog

---

libs/pandautils/src/main/java/com/instructure/pandautils/fragments/RemoteConfigParamsFragment.kt
libs/pandautils/src/main/res/layout/adapter_remote_config_param.xml

On physical devices, local override of remote config settings was not working.
Fix: Apparently onKeyListener doesn't work so well when the soft keyboard is in use, so I switched over to TextChangedListener, which works much better.

[Student][Teacher][MBL-14361]: Fix remote config overrides on physical devices

---

apps/flutter_parent/.gitignore
apps/flutter_parent/android/gradle/wrapper/gradle-wrapper.properties
apps/flutter_parent/plugins/encrypted_shared_preferences/android/gradle/wrapper/gradle-wrapper.properties
apps/flutter_parent/plugins/webview_flutter/android/gradle/wrapper/gradle-wrapper.properties

Ignored so it's built fresh every time, that way it's always up to date.

[Flutter-Parent] Update gradle wrapper

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
apps/student/src/main/AndroidManifest.xml
apps/student/src/main/java/com/instructure/student/activity/BaseRouterActivity.kt
apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/activity/StudentViewStarterActivity.kt
apps/student/src/main/res/layout/activity_student_view_starter.xml
libs/canvas-api-2/build.gradle
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/AppManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/util/MasqueradeUI.kt

Sometimes going into Student view would work, but would have some weird behavior that caused the Student app to return to the Landing screen. This could also wipe out the Teacher's token. 
This PR also solves another issue that allowed the user to go into Student view, then press the back button, returning to the landing screen while still being in masquerade mode.

[Student][Hotfix-6.7.1] Fix issue with Student view

---

apps/flutter_parent/lib/screens/dashboard/student_horizontal_list_view.dart

Someone (not naming any names...) accidentally wiped out this change. So here it is again :D.

[Parent] Add back the text alignment

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/fragment/PeopleDetailsFragment.kt

Found an edge case where:
1. The user is in Student view
2. Tap switch user
3. Close the app (swipe away or force close, hitting the back button doesn't work). 
4. Relaunch the app
5. The app relaunches with the intent used to start Student view, launching the app back into Student view.
Users in Student view were also able to message other users from the People details screen. We don't want them to be able to message anyone, so a condition was put in to block that.

[Student][Hotfix-6.7.1] Another Student view fix and block messaging from People details

---

apps/student/src/main/java/com/instructure/student/events/RationedBusEvent.kt
apps/student/src/main/java/com/instructure/student/flutterChannels/FlutterComm.kt
apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt
libs/flutter_student_embed/lib/screens/calendar/calendar_day_planner.dart
libs/flutter_student_embed/lib/screens/calendar/calendar_screen.dart
libs/flutter_student_embed/lib/screens/calendar/planner_fetcher.dart
libs/flutter_student_embed/lib/utils/native_comm.dart
libs/flutter_student_embed/test/screens/calendar/calendar_screen_test.dart

This PR fixes an issue where calendar screens on the back stack would not update properly when there was a change to the calendar. To test, open the calendar tab multiple times and perform calendar-related changes such as adding/editing/deleting planner notes, pulling to refresh after making changes via the web interface, and deleting calendar events. Backing out to previous calendar screens should result in those screens showing the update calendar information.
This PR also fixes an issue where the CalendarEventFragment would not show the overflow menu for deletable events.

[Student][MBL-14376] Propagate planner changes to all planner screens

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
libs/pandautils/src/main/java/com/instructure/pandautils/models/PushNotification.kt
libs/pandautils/src/main/java/com/instructure/pandautils/receivers/PushDeleteReceiver.kt
libs/pandautils/src/main/java/com/instructure/pandautils/receivers/PushExternalReceiver.kt
libs/pandautils/src/main/res/values/strings.xml

This also removed support for old notifications that were stored using the user id and domain prior to MBL-13725. Removing here as we have now released two versions of teacher/student that should have put everyone on the new format for storing notifications.
This commit will now show each push notification received as its own notification on the device. On devices higher than API 23 (Android 6.0) we will always show each push as its own notification, as groups aren’t supported very well on this API version. Higher than 23 will collapse 2 or more notifications into a notification group. This group can be expanded letting users deal with each notification themselves. Clearing the group will clear all notifications.
The JIRA ticket allows for extra customizations if any were desired beyond …

[Student][Teacher][MBL-12556] Push notification updates

---

apps/flutter_parent/run_all_ui_tests.bash

I had mistakenly added some logic in between running a test and checking for that test's result code, so I was always seeing passing tests.

[Parent][E2E][MBL-14433]: Fix Parent E2E test reporting

---

apps/flutter_parent/run_all_ui_tests.bash

Should fix the message-formatting problems that prevented retries from being reported before.

[Parent][E2E][MBL-14433]: Fix reporting of retries in E2E tests

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/AssignmentDetailsRenderPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt
apps/student/src/main/res/layout/fragment_assignment_details.xml
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
libs/pandares/src/main/res/values/strings.xml

This feature is currently behind a flag at the course level in canvas.
To test:
* Verify "Attempts" don't show on old assignments
* Verify "Attempts" show correct allowed number and used number when an assignment has a limit
* Verify when all allowed attempts have been used that the resubmit button is disabled

[Student][MBL-14303] Support submission limits for Assignments 2

---

apps/flutter_parent/android/app/src/main/kotlin/com/instructure/parentapp/MainActivity.kt

Leaving in some extra comments with it in case the next Flutter version changes this again.
For more info, if anyone is curious, there is not a documented way that works for doing deep links from Android using Flutter.
The closest thing is this link: https://api.flutter.dev/flutter/dart-ui/Window/defaultRouteName.html
Which says to use the deprecated (non-embedded native side lib) FlutterView to do setInitialRoute. This method was removed in the newer FlutterView (that was changed in Flutter 1.12) and was completely left out of the migration notes: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
Hence why we're hacking around and using the intent extra that is package private.
To test:
* Run the parent app
* Kill the app
* Click a link to open the app from the …

[Parent][MBL-14430] Fix broken cold deep links from Flutter 1.17

---

apps/flutter_parent/test_driver/pages/course_summary_page.dart

I'm confused as to why this test is failing with "Expected due date to contain 12:00 AM" so I'm including the element text in my printout.

[Parent][E2E][MBL-14439]: Add log info for failing test

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt

The basic problem was that we could press the "reply" link to reply to a reply, and the RCE editor would fail to pop up.  Or we could press the attachment icon in a reply and not be taken to the attachment.  So I did all that I could to address those situations, and I *think* that they have improved.

[Student][DIscussions][MBL-14436]: Another round of stabilization for discussion tests

---

apps/flutter_parent/lib/models/conversation.dart
apps/flutter_parent/lib/screens/inbox/reply/conversation_reply_interactor.dart
apps/flutter_parent/test/screens/inbox/reply/conversation_reply_interactor_test.dart

Okay, so this got a lot grosser than I had hoped. In order to filter out improper recipients from all usages of reply all, we have to make a couple of api calls. I'm open to feedback and suggestions on this. For now, it's working and tested.
To Test (I found creating the repro case for this was easier from web):
-Create a message as a teacher in a course with an observer, teachers/tas, and some students
-Reply All to this message from the current parent app, notice that it replies to all, including observed and non-observed students
-This change will filter out all non-observed students, and ALL students / self if the "send messages" permission is off

[Parent][MBL-14388] Reply all fix

---

libs/flutter_student_embed/lib/screens/calendar/calendar_screen.dart
libs/flutter_student_embed/lib/screens/calendar/calendar_widget/calendar_filter_screen/calendar_filter_list_screen.dart
libs/flutter_student_embed/lib/screens/to_do/create_update_to_do_screen.dart
libs/flutter_student_embed/lib/screens/to_do/to_do_details_screen.dart
libs/flutter_student_embed/lib/utils/common_widgets/appbar_dynamic_style.dart
libs/flutter_student_embed/test/utils/common_widgets/appbar_dynamic_style_test.dart

Flutter's AppBar widget always uses the same fixed height, causing a height (and style) mismatch when compared to the native Toolbar in landscape mode and on tablets. This commit wraps the AppBars and enforces size and style changes to match the native app. Specifically, on tablets the height is extended to 64 and extra padding is applied, while in landscape the height is shortened to 48 and the title font size is reduced to 14.

[Student][MBL-14378] Fix flutter appbar style for landscape and tablets

---

apps/student/build.gradle

This prevents a 'missing libflutter.so' crash on x86 devices by excluding the x86 libs, allowing said devices to be served the ARM version of the app.

[Student][R-6.8.0] Set up NDK filters to only support armabi-v7a, arm64-v8a, and x86_64

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/AssignmentManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ObserveeAssignment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ObserverAssignment.kt

To Test:
-Log into the student app with an observer account with a submission with some status (graded, etc).
-Note that the assignment details screen now displays all the correct submission details for your first observer (no other way to "pick" observers right now in student, we just default to #1).

[Student][MBL-14398] Update for student app observer assignment deets

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionDetailsEmptyContentRenderTest.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/SubmissionDetailsEmptyContentPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/SubmissionDetailsEmptyModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/ui/SubmissionDetailsEmptyContentFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/ui/SubmissionDetailsEmptyContentView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/ui/SubmissionDetailsEmptyContentViewState.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEmptyContentPresenterTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.java

To Test:
-Sign into the student app with an observer
-Go to any submittable assignment, note that the submission button should now be gone
-Make sure its still visible for students

[Student] Disable submit button for observers

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/l10n/fallback_material_localizations_delegate.dart
apps/flutter_parent/lib/models/grade_cell_data.dart
apps/flutter_parent/lib/parent_app.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_day.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_day_of_week_headers.dart
apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart
apps/flutter_parent/lib/screens/events/event_details_screen.dart
apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart
apps/flutter_parent/lib/utils/core_extensions/date_time_extensions.dart
apps/flutter_parent/test_driver/pages/assignment_details_page.dart
apps/flutter_parent/test_driver/pages/course_summary_page.dart

The process for adding new Material translations does not appear to be very maintainable or automatable, so instead this change adds a locale fallback for Material translations, which have only a minimal presence in the app. 
In the process of testing, I also discovered that formatting dates would cause widget crashes when using unsupported locales. Unfortunately there does not appear to be a way to manually add new date symbols for specific locales, so a centralized solution was not attainable there. Instead, every DateFormat call site in the app has been updated to pass in a supported locale.
To test: Use web to set an observer's language to one not supported by `flutter_localizations` (Welsh, Haitian Creole, or Maori), then log into the app as that user. You should be able to browse …

[Parent][MBL-14417] Add locale fallback for Material strings and Date formatting

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SyllabusRenderPage.kt
apps/student/src/main/java/com/instructure/student/mobius/syllabus/SyllabusPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusView.kt
apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusViewState.kt
apps/student/src/main/res/layout/fragment_syllabus.xml
apps/student/src/test/java/com/instructure/student/test/syllabus/SyllabusPresenterTest.kt

This addresses a recent regression which affects the ability to Pull-To-Refresh the syllabus in its empty state. It also cleans up and consolidates some of the syllabus View and Presenter logic.

[Student] Fix PTR for empty syllabus state

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt

Most of the problems seemed to be in SpeedGraderFilesPageTest.displaysEmptyFilesView and SpeedGraderCommentsPageTest.showsNoCommentsMessage.  And both had the same point of failure, which is addressed with this fix.

[Teacher][Tests][MBL-14522]: Small change that will hopefully stabilize SpeedGrader tests

---

apps/flutter_parent/lib/utils/qr_utils.dart
apps/flutter_parent/test/router/panda_router_test.dart
apps/flutter_parent/test/screens/pairing/qr_pairing_screen_test.dart
apps/flutter_parent/test/utils/qr_utils_test.dart
apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/PairObserverRenderTest.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/PairObserverEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/PairObserverModels.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/PairObserverPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/PairObserverUpdate.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/ui/PairObserverView.kt
apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/ui/PairObserverViewState.kt
apps/student/src/test/java/com/instructure/student/test/settings/pairobserver/PairObserverEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/settings/pairobserver/PairObserverPresenterTest.kt
apps/student/src/test/java/com/instructure/student/test/settings/pairobserver/PairObserverUpdateTest.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/AccountEndpoints.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/UserManager.kt

This update just modifies the qr code url to be aligned with the code iOS is going to use, the pattern is:
`canvas-parent://host/pair?code=$code&account_id=$accountId`

[MBL-14531] Update qr pairing

---

apps/student/build.gradle
buildSrc/src/main/java/com/instructure/android/buildtools/transform/FlutterA11yOffsetTransformer.kt
buildSrc/src/main/java/com/instructure/android/buildtools/transform/FlutterTextureDisconnectFix.kt
buildSrc/src/main/java/com/instructure/android/buildtools/transform/FlutterTextureRenderModeFix.kt
buildSrc/src/main/java/com/instructure/android/buildtools/transform/ProjectTransformer.kt

This commit addresses the current top crash in Student by introducing a new project transformer that adds a catch to `FlutterTextureView.disconnectSurfaceFromRenderer()`, where an edge case appears to be causing an NPE. When this NPE is caught, the incident is added to the Crashlytics logs so it can be used for troubleshooting unintended side effects of this change (if any) in the future. 
This commit also adds some informative build logs and clarifying comments, and updates ProjectTransform to always fail on a jar transform failure.
To repro: In developer settings, enable "Don't keep activities." Log into the app, click around on the bottom nav enough to get 3-4 instances of the Calendar on the back stack, then background the app. You may need to repeat this a few times before it will …

[Student][MBL-14529] Fix FlutterTextureView crash

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/MessageThreadFragment.kt

Every time the conversation was refreshed, an additional divider decoration item was being added to the recycler view. This change causes existing decorations to be removed before adding new ones, preventing more than one divider.
repro: Reply to a conversation, or pull to refresh a conversation

[Teacher][MBL-13062] Fix extra spacing between messages

---

apps/student/build.gradle

The rest of the heavy lifting is done in the "ui-test-coverage" workflow in the "Android Student UI Tests" Bitrise app.  That workflow now generates and reports coverage data for UI tests ("normal" + E2E) as well as combined UI/unit tests.

[Student][CodeCov][MBL-14551]: Added gradle task to report combined coverage

---

apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt

It turns out that the crash was happening in a different part of the app (discussions) and was inadvertently fixed in a separate pull request

[Teacher][MBL-13563] Remove DNS crash logging that is no longer needed

---

apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt

When deep linking to a module, the app opens to the module list which then scrolls to and expands that module. However, because the scroll is happening prior to expansion, modules located near the bottom of the list will not be scrolled as close to the top as they could have been. This can partially or entirely negate the highlighting effect of the scroll/expand behavior.
This change introduces a delay to the scrolling behavior so that the expansion animation can finish first, providing extra vertical space which allows the module to be scrolled more closely to the top of the list.

[Student][MBL-10542] Improve scroll behavior when routing to a specific module

---

apps/student/src/main/java/com/instructure/student/fragment/CalendarFragment.kt

We were previously using the plannable ID when routing from the planner to the assignemnt details page, but in the case of quiz assignments the plannable ID is the quiz ID and not the assignment ID, which would cause an unhelpful error message to be displayed. This change updates the route to use the plannable's assignment ID instead for quizzes.

[Student][MBL-14556] Use assignment ID when routing from planner to quiz assignments

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt

Sooo it looks like we were simply overriding the name of the current module fragment by incorrectly calling setPrevModuleName when calling markAsRead. I've tested this a bunch and it seems to be completely unnecessary.

[Student][MBL-14584] Module title fix

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt
apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
libs/pandautils/src/main/assets/discussion_html_template_item.html
libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionEntryHtmlConverter.kt
libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionUtils.kt

refs: MBL-11767
affects: student
release note: Adding rating to discussions when only graders can like
Test plan:
- View a discussion that does not allow rating
- Student & Teacher: No rating content should be displayed
- View a discussion that allows ratings
- Student & Teacher: You should be able to like and see the like count
- View a discussion that allows ratings and only allows graders to like
- Student:
- You should see like counts when the count is greater than 0
- You should not see the like button
- You should not be able to edit likes
- Teacher:
- You should be able to like the replies and the count should be displayed

[MBL-11767][Student] Display rating when only graders can like

---

README.md
apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/AddMessagePresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/InboxApi.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/InboxManager.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/InboxApiPactTests.kt

refs: MBL-14444
affects: student, teacher
Test plan:
- Log in as the student in the ticket
- Inbox > Tap the only conversation
- Reply directly to the first message (begins with _I am a teacher_)
- View the conversation as the teacher (in app or on web)
- You should not see the reply that the student made
I don't know how we test this since it doesn't impact the UI for the
current user. Only difference is that the receiver does not actually
receive the message.

[MBL-14444][Student/Teacher] Send context code when adding a new message

---

apps/flutter_parent/lib/models/assignment.dart
apps/flutter_parent/lib/models/assignment.g.dart
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/AssignmentUnitTest.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/ConversationUnitTest.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/TodoUnitTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentUtils2.kt

`muted` wasn't being used anywhere for the UI but I figured we'd better
remove it completely since it has been removed from the API.
Test plan: tests should pass.

[MBL-14636][All] Remove muted

---

apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/test/screens/login/login_landing_screen_test.dart
libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt

This is temporary while we figure out a better solution to mobile login
issues.
Support is overwhelmed with these requests right now and are
having to mass-reply to them all so this button is doing more harm than
good right now.
Test plan: Landing pages in all the apps should not have a help button.

[MBL-14642][All] Hide help buttons on landing pages

---

open_source_data/dataseeding-flutter/files.list
open_source_data/dataseeding-flutter/private_consts.dart

Populated open_source_data/dataseeding-flutter private_consts with blank strings as values.
Note that these secrets/values are only used in flutter driver tests, of which we have about a half-dozen.  So their absence should not cause any breakage except for those tests.

[Parent][OpenSource][MBL-14649]:  Fixed flutter-parent open source build 

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt

Messed around for most of the day on a conditional fix that detected if the LTI tool was using quizzes 2 and then fell back to the old implementation for fetching launch url only to be informed that I was simply missing the launch_type query param. See ticket for repro.

[Student][MBL-14645] Fix for quizzes 2 lti

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/SubmissionDetailsEmptyContentPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt

See ticket to test. The goal for this is to match canvas behavior for showing the submit button. Essentially, if the course is set to "read only" from any source we hide the submit button. This can be for course, section, or term dates, as well as the course workflow state.

[Student][MBL-14622] Hide submit button for soft conclude

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/StudentContextPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/StudentContextPage.kt

Unfortunately, converting to MockCanvas turned really ugly, as it wasn't readily apparent how to create the required response object.  So this test was converted to a "live" test instead.  It's not ideal, but it gets rid of our final use of Ditto in our test suite.
If we create an E2E suite for the Teacher app, we can make this test E2E.

[Teacher][Test][MBL-14657]: Converted StudentContextPageTest from Ditto

---

apps/flutter_parent/lib/network/api/enrollments_api.dart

This fixes an issue where users will incorrectly be shown the "Not A Parent?" screen if none of the observee courses have started. See ticket for repro steps.

[Parent][MBL-14633] Include current_and_future state when fetching enrollments

---

apps/student/src/main/java/com/instructure/student/activity/ShareFileUploadActivity.kt
apps/student/src/main/java/com/instructure/student/dialog/ShareFileDestinationDialog.kt

The activity was being finished in between the two dialogs, I looked 3 years back into the codes history and I have no idea why it was doing this.
Also, we were only checking the contents scheme for file to determine if we need to request permission, so I added "content", which seems common, at least on Samsung.

[Student][MBL-14648] File sharing bug

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderQuizWebViewFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
apps/teacher/src/main/res/layout/fragment_unsupported_file_type.xml
libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.kt

SpeedGraderQuizWebViewFragment currently disallows internal routing. In the case of canvas file download links, this causes files to be loaded via the redirect URL which drops important information such as the file name and mime type. The result is that the file may download successfully, but the app does not know how to handle it.
This PR adds a route for context-less file download links (as seen in quiz file submissions), and updates the fragment to allow internal routing for files.
Additional changes:
- Fixes a resource leak and typo in the media loader
- Adds authentication to the quiz webview so users don't have to sign in again after switching logins
- Centers the filename text in ViewUnsupportedFileFragment
refs: MBL-14662
release note: Fixed an issue where quiz …

[Teacher][MBL-14662] Fix viewing quiz files

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AnnouncementInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ProfileSettingsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/ProfileSettingsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
apps/student/src/main/res/layout/dialog_edit_text.xml
apps/student/src/main/res/layout/fragment_create_announcement.xml
apps/student/src/main/res/layout/fragment_profile_settings.xml
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/UserEndpoints.kt
libs/pandares/src/main/res/values/strings.xml

Worked on tests for announcement creation, discussions linked to assignments and profile settings.
ProfileSettingsFragment: 0% coverage -> 22% coverage
CreateAnnouncementFragment: 0% -> 79%
DIscussionDetailsFragment: 60% -> 70%
Overall coverage: 50.1% to 51.5%. (I'll try to get more bang for the buck in future related PRs.)
refs: MBL-14682
release note: Fixed some minor Student a11y issues

[Student][Coverage][MBL-14682] | Increase UI test code coverage, rd1

---

apps/teacher/src/main/java/com/instructure/teacher/presenters/MessageThreadPresenter.kt

This fixes a crash that can occur when a conversation fails to load from the API after routing to MessageThreadFragment from a push notification. After some investigation is appears that this was an existing crash, but shows up as a new crash due to line changes.

[Teacher][RC-1.11.1] Fix message thread crash

---

apps/polling/src/main/res/xml/global_tracker.xml
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/InboxInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SyllabusInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CalendarEventPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SyllabusPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
apps/student/src/main/res/layout/fragment_calendar_event.xml
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ConversationEndpoints.kt
automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt

Attempted to beef up UI test coverage for Student app.  Added CalendarEventFragment coverage via the Todo page (since we can't test via the Flutter calendar), and added InboxConversationFragment coverage via tests for archiving a conversation, marking a conversation unread, starring a conversation, deleting a conversation and deleting a message.
Results:
--CalendarEventFragment: 0% to 57% 
--InboxConversationFragment: 53% to 82%
--com.instructure.student.fragment: 44% to 47%
--overall: 51.3% to 52.2%
refs: MBL-14704
release note: Added UI tests

[Student][Coverage][MBL-14704] | Beef up UI test code coverage, round 2

---

libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt

Keyboards weren't showing  up in places like essay quizzes, looks like it was the same issue as the RCE webview problem.

[All][MBL-14746] Fix for webview keyboards

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Pronouns.kt
libs/pandautils/build.gradle
libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionEntryHtmlConverter.kt

This change removes the recently-added HTML sanitizer dependency which was triggering a [D8/AGP bug](https://issuetracker.google.com/issues/157681341) that caused a NoClassDefFoundError on API 23 when viewing discussions. Sanitization has been moved to `Pronouns.html()` and uses HTML encoding rather than element removal. While this approach continues to prevent the XSS issues resolved by #1011, it does mean that unwanted elements (like script tags) will be shown as non-executable text instead of being removed entirely.

[Student][Teacher][MBL-14763] Fix discussions on API 23

---

apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt

I was matching against a content description to pull up a menu, and that content description could get extra junk characters embedded in it on API 27/28/29.
The normal PR logic won't test the fix, since the issue only manifests on API 27/28/29.  But I did manually run an FTL job with this code against the InboxInteractionTest on API 27/28/29 and it passed.  So I *think* that I've fixed the issue(s).
refs: MBL-14772
release note: Fixed new inbox tests for later android versions

[Student][Inbox][MBL-14772]: Fixed problems with new inbox tests on API-27/28/29

---

apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/PeopleDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/adapters/StudentContextFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/factory/AddMessagePresenterFactory.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/AddMessageFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentSubmissionListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/MessageThreadFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/AddMessagePresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/AssignmentSubmissionListPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/BasicUser.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Recipient.kt
libs/pandautils/src/main/res/layout/view_recipient_chips_input.xml

Also:
- Fixes recipient search and selection not working for 'message students who'
- Fixes crash when trying to use 'message students who' with groups
- Constrains recipient search input to a single line

[Student][Teacher][MBL-14725] Pass Recipient instead of BasicUser when composing messages

---

apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt

This fixes a crash that occurs in CalendarEventFragment when the fragment is removed before its initial API call completes. To repro, open a calendar event (from the calendar, to do list, or syllabus) and then quickly press the back button.

[Student] Fix crash in CalendarEventFragment

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/NumberHelper.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/NumberHelperTest.kt

I was unable to repro the crash, so this is a speculative fix. As far as I can tell the crash occurs when `NumberHelper.readableFileSize()` is passed what appears to be a very incorrect file size (e.g. 1 exabyte or more), causing an ArrayIndexOutOfBoundsException when attempting to look up the unit name from an array that only handles units up to the terabyte. I'm not sure where the bad files size is coming from, but it appears to disproportionately affect OPPO devices.
This change fixes the crash by capping the max unit to terabyte, and hardens the function with additional range checks. It also changes how file sizes are rounded, fixing an issue where file sizes slightly below the threshold of the next-highest unit were displayed in a potentially confusing way. For example, 1023.96 KB …

[Student] Fix crash during submission file upload

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
apps/student/src/main/java/com/instructure/student/activity/InterwebsToApplication.kt
apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/RouteValidatorActivity.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt

This PR removes the existing remote configs currently set to true in student/teacher. To test, simply check that the features are on and working. This includes qr_login and pairing (from student).

[Student][Teacher] Retire remote configs set to true

---

libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/UploadFilesDialog.kt

Repro: In the file/folder list, choose the file upload option and select two or more files to be uploaded. Then attempt to remove the files by tapping the items' 'X' buttons in rapid sequence, which will result in a crash.
refs: none
release note: Fixed a crash when rapidly removing files from the file upload dialog

[Student][Teacher] Fix crash in UploadFilesDialog

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/CreateOrEditAnnouncementFragment.kt

Due to a difference in how announcements are created and how they are updated in the Teacher app, it is currently not possible to add attachments to an existing announcement - at least not without rewriting a significant portion of the create/edit screen. Originally the attachment icon in the toolbar was hidden while editing, but at some point a change must have erroneously begun to show the icon when it wasn't supposed to. This PR restores the original behavior by ensuring that the toolbar is set up prior to running the rest of the view setup logic that determines the icon's visibility.
refs: MBL-11776
release note: Hide non-functional attachment button when editing announcements

[Teacher][MBL-11776] Hide the attachment button when editing announcements

---

apps/student/src/main/java/com/instructure/student/dialog/ShareFileDestinationDialog.kt

Repro: In the files list select and view a PDF, and then in the menu overflow choose "Upload To Canvas". This will show a red screen and will begin animating a dialog into position (if it requests permissions, grant them and then back out and start over). If you press the back button after the dialog begins animating but before it finishes, the app will crash.
refs: none
release note: Fixed a crash when closing the share dialog shortly after opening it

[Student] Fix crash in ShareFileDestinationDialog

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt
apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt

The reproduction steps and the expected behavior can be seen in the ticket.
refs: MBL-14775
release note: Fixed an issue where a group remains on the dashboard when unfavorited.

[Student][MBL-14806] Group remains on dashboard when un-favorited

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewPdfFragment.kt

The reproduction steps and the expected behavior can be seen in the ticket. To test this you need a user, who has a PDF in their files.
refs: MBL-11775
release note: Fixed an issue where a the edited file's name doesn't update.

[Teacher][MBL-11775] Changing a PDF file name doesn't show the name change in the preview fragment after saving

---

apps/teacher/src/main/java/com/instructure/teacher/holders/SpeedGraderCommentHolder.kt

When anonymous grading is enabled for an assignment, the Teacher app will show "Student" as the author for any submission comment whose author ID does not match the current user. The problem here is that for anonymous grading, Canvas generally returns submission comments with the author ID redacted - including comments authored by the current user or by other teachers/TAs. This results in most, if not all, comments being shown as authored by "Student" regardless of the actual author, which can be misleading.
Fortunately, Canvas provides an anonymous author name such as "Anonymous User" in these cases. This PR updates the comment item binder to use the canvas-provided author name when the author ID has been redacted.
refs: none
release note: Fixed an issue where the author …

[Teacher] Use canvas-provided author name for submission comments when grading anonymously

---

apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt

During logout, the app attempts to retrieve the FCM registration ID so that the canvas push communication channel can be cleaned up. However, on some devices (particularly devices without GMS, e.g. some Huawei, Xioami, and Amazon devices) this process can fail and crash the app. This PR catches that failure and allows the logout process to skip that step and proceed normally.
refs: none
release note: Fixed an uncommon crash when logging out

[Student] Fix crash on logout

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt

The repro steps are in the ticket.
refs: MBL-14786
release note: Fixed an issue where an infinite loading indicator is shown when returning from a To Do item.

[Teacher][MBL-14786] Infinite spinner in To Do list after selecting and item and returning

---

apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt

The repro steps are in the ticket.
refs: MBL-14788
release note: Fixed an issue where new assignment submission comments are not visible when reopening the submission.

[Teacher][MBL-14788] New submission comments are not cached

---

apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart
apps/flutter_parent/lib/screens/courses/routing_shell/course_routing_shell_screen.dart
apps/flutter_parent/test/screens/courses/course_details_screen_test.dart

I also changed the icon on the `CourseRoutingShellScreen` to maintain consistency, however I couldn't find where this screen can be seen. From the router it seems to me that it is unused currently, but maybe I am missing something.
refs: MBL-14783
release note: Changed refresh button size

[Parent][MBL-14783] Resize the refresh button in the course details AppBar

---

apps/flutter_parent/lib/screens/alerts/alerts_screen.dart

Repro steps included in the ticket.
refs: MBL-14782
release note: Alert count badge is now properly updated after deleting an unread alert.

[Parent][MBL-14782] Deleting an unread alert from the alert list does not update the alert count badge

---

apps/student/src/main/AndroidManifest.xml
apps/teacher/src/main/AndroidManifest.xml

Temporary fix to get api 29 working for downloading/saving files locally. To Test: On either master or prod, using an api 29 device, attempt to save a panda avatar or download a file. You should get an error. With this fix, no error :D.

[Teacher][Student] Api 29 File Scope Fix

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ProfileSettingsInteractionTest.kt

Need access to external storage in order to save panda avatars, in certain circumstances.

[Student][ProfileSettings][MBL-14887]: EZ: Fix permissions problem in ProfileSettingsInteractionTest

---

apps/student/build.gradle

This is the magic bullet to disabling animations in the student app when running tests locally.  I don't know exactly what is currently happening in Flank/FTL (i.e., whether animations are being properly disabled there), but this should also take care of any problems there.

[Student][Tests][MBL-14828]: EZ: Disable animations during tests

---

apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadPresenterTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/NumberHelper.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/NumberHelperTest.kt

After noticing that the file sizes displayed for the same files were different between the apps and web, I realized that the app is using binary calculations while web is using metric (e.g. 1KB = 1024B vs 1KB = 1000B). This PR updates the app logic to match [web](https://github.com/instructure/canvas-lms/blob/7b1d44f99899937e5269fcdecdcd1ce4bc4166b2/app/coffeescripts/util/friendlyBytes.js).
refs: none
release note: File size calculation now matches web
test plan: Compare displayed file sizes against web. They should be identical in every case except for bytes, where the app will show 'B' and the web will show 'bytes'

[Student][Teacher] Update file size calculation to match web

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PdfInteractionTest.kt

They popped up a ProgressBar spinner, which spins forever in API-23.

[Student][PDF][MBL-14900]: Disabled a couple of PDF interaction tests on API-23

---

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt

I noticed that our sliding panel in teacher is still resizing pdf content which does not play nicely with pspdfkit. It also fully opens the sliding panel anytime you try to comment on something (with the dialog).
refs: MBL-14920
release note: Fixed a bug with the sliding panel in Speed Grader.
test plan: Make sure the sliding panel isn't resizing pdfs or fully expanding when commenting for the first time on annotations.

[Teacher][MBL-14920] Speedgrader bug fix for sliding panel

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/SubmissionCommentsEffectHandler.kt

refs: MBL-14791
release note: Fixed the bug, where video comment recording would not start the first time after giving permission.
test plan:
- Revoke Camera and Audio permissions if needed.
- Submission > Comments > Add > Add video comment > The recording should be visible after giving the permissions

[Student][MBL-14791] Added Record Audio permission for video comment recording.

---

apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt

Just a quick safe call for an NPE happening in the inbox.

[Student] Crash fix for inbox

---

apps/flutter_parent/lib/screens/help/help_screen_interactor.dart
apps/flutter_parent/test/screens/help/help_screen_interactor_test.dart

refs: MBL-14929
release note: Help links are only visible for the correct user group.

[MBL-14929][Parent] Only show help links if they are available for everyone or observers.

---

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

This PR fixes a bug with off page annotations causing the annotation toolbar to disappear _forever_... It also adds a simple clean up to the annotation/edit lists.
refs: MBL-14944
release note: Fixed a bug with the annotation tools disappearing for off page clicks.
test plan: On a landscape pdf, attempt to annotate on the blank space arround the page of the document, not on the document/page itself. The annotation toolbar will flicker, but won't disappear! This is the best I could get, and that was with help from PSPDFKits support staff haha.

[PDF][MBL-14944] Fix bug with offpage annotations

---

apps/student/src/main/java/com/instructure/student/adapter/FileUploadAssignmentsAdapter.kt

refs: MBL-13153
release note: Fixed a bug where locked assignments were visible in the share extension.
test plan: Create a locked assignment > Use the share function > The locked assignment should not be visible in the list.

[MBL-13153][Student] Locked assignments are no longer visible in the share extension.

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/SimpleWebViewFragment.kt

Testing: Details in the ticket. I also added a comment to the ticket for easier testing.
refs: MBL-14891
release note: Fixed an issue where login is needed to view a discussion in speed grader.

[MBL-14891][Teacher] Unable to view discussion replies in SpeedGrader when masquerading

---

apps/student/src/main/AndroidManifest.xml
apps/teacher/src/main/AndroidManifest.xml
libs/pandautils/src/main/res/xml/network_security_config.xml

Testing: Doesn't really require testing, it isn't affecting the app functionality. To verify the changes work check if the traffic can be inspected with Charles/Fiddler on debug builds and not on production builds.
refs: MBL-14964

[MBL-14964][Student][Teacher] Add possiblity to inspect network traffic in debug mode

---

libs/annotations/src/main/java/com/instructure/annotations/AnnotationConverter.kt
libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

This PR fixes two bugs with the stamp/point annotations (looks like a pin). They would often not retain their color when updating or when created. In addition, duplicate annotations were occurring very regularly, this adds a race condition check to prevent them from being created twice.
refs: MBL-14954
release note: Fixed a bug with the point annotation not retaining its color on updates
test plan: Create a stamp annotatation, any color other than blue. Exit the pdf and re-open it, confirm its still the same color. Now update the annotation, move it, resize it, etc. Exit/re-enter and confirm the color remains the same. For the duplicate fix, just check that there isn't a second one hiding underneath :).

[PDF][MBL-14954] Fixed bug with stamp color and duplicate annotations

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/view/grade_slider/SpeedGraderSlider.kt
apps/teacher/src/main/java/com/instructure/teacher/view/grade_slider/SpeedGraderSliderTooltipView.kt

refs: MBL-11020
release note: Added grade slider support for "display grade as: percentage" assignments.
test plan:
Open a "display grade as: percentage" assignment without rubrics.
The grade slider should be visible.
Assign the grade percentage using the slider > The grade should update.
If you update the grade with the custom grade dialog, the slider should update as well.
If you hold the slider at the minimum value for one second, you can clear the grade.
If you hold the slider at the maximum value one second, you can excuse the student.

[MBL-11020][Teacher] Added grade slider support for "display grade as: percentage" assignments

---

apps/teacher/src/main/res/layout/adapter_page.xml

Testing: Run the mentioned UI tests on a low res (360x640 for example) phone API 25 emulator in landscape. 
refs: MBL-14941
release note: Fixed accessibility issues.

[MBL-14941][Teacher] Accessibility issue on fragment_page_list in Landscape

---

apps/teacher/src/main/java/com/instructure/teacher/view/edit_rubric/CriterionRatingLayout.kt
apps/teacher/src/main/java/com/instructure/teacher/view/edit_rubric/RubricEditView.kt

Testing: Steps in the ticket.
refs: MBL-14935
release note: Fixed an issue when a rubric comment cannot be saved without adding points.

[MBL-14935][Teacher] Rubrics with points removed require users to add points in order to save rubric comments

---

apps/flutter_parent/lib/network/utils/dio_config.dart

In Flutter it's not so straightforward to use a proxy for network monitoring. To achieve this we need to inline the IP and the port of our machine which we use as a proxy. This would make the code coupled for a specific IP/port and everybody would need to change that part of the code. To prevent this we can use launch arguments. Using launch arguments, we can specify our own IP and port. To specify this go to `Edit configurations...` in Android Studio and create a new run configuration with the following additional arguments:
`--dart-define=PROXY_IP=192.168.0.1,PROXY_PORT=8888` - replace the IP and the port with your own proxy settings.
Testing: This change does not change the production code, but it can be tested if the proxying works correctly.
refs: MBL-14973
release …

[MBL-14973][Parent] Add possiblity to inspect network traffic in debug mode

---

apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/student/src/main/java/com/instructure/student/holders/AnnouncementViewHolder.kt

Disabled unsupported routing for the WebView in global announcements, so it won't try to route to the file, instead shows it in the webview.
This ticket is marked as Student/Teacher, however it only affects Student, sincs teacher does not have this feature.
Testing: Repro steps in the ticket, account info in comments.
refs: MBL-14932
release note: Fixed an issue, where linked documents couldn't be viewed in global announcements.

[MBL-14932][Student] Can't view documents linked to Global Announcements

---

apps/student/src/main/java/com/instructure/student/adapter/ModuleListRecyclerAdapter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ModuleAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/ModuleManager.kt

So the way our expandable recycler view code is set up doesn't play well with paginated modules _or_ the empty view stuff that was added back in when trying to "scroll to" a group position. This is a possible solution to get linking to modules linking fixed quickly, but it disables empty views and exhausts the pagination. A more involved solution is likely viable, but would require much more serious changes to the modules code. I think this one should go to product.
refs: MBL-14960
release note: Fixed a bug with links to modules

[Student][MBL-14960] Potential modules fix - needs product approval

---

apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt

refs: MBL-14792
release note: Fixed a bug where you had to press back twice to go back from HTML files.
test plan:
Upload a html file to your course files.
Open the file from the files list.
You should only have to click once to go back to the files list.

[MBL-14792][Student] Don't have to press twice for HTML files to go back

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt

refs: MBL-14996
release note: Fixed a bug with the loading indication on the Course details screen.
test plan: Steps to reproduce is in the ticket. If you navigate back to the CourseBrowser screen the loading indicator should not be visible.

[MBL-14996][Teacher] Loading indicator fix

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt

Fixed npe on tablet view due to tabbed layout when trying to invoke refresh method
refs: MBL-15059
test plan: Bitrise tablet workflow

[MBL-15059][Teacher] Fixed tablet tests

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt

refs: MBL-15057
release note: Fixed a bug where documents linked in discussion replies cannot be opened.

[Student][MBL-15057] Cant view documents embedded by students in a discussion

---

apps/flutter_parent/lib/router/panda_router.dart
apps/flutter_parent/test/router/panda_router_test.dart

refs: MBL-14785
release note: Links for grades now open inside the app.
test plan: Navigate to the course grades > Send a message from that page > Open inbox > Click link in the message > The link should route inside the app

[MBL-14785][Parent] Routing set up for grades page

---

libs/pandautils/src/main/res/xml/network_security_config.xml

Test plan: In the ticket. To test this flow you need to enter the whole Canvas instance url and click next instead of selecting the name of the University, because currently that flow redirects to saml authentication.
refs: MBL-14876

[MBL-13876][Student][Teacher] University is getting Cleartext errors.

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/CreateOrEditPageDetailsFragment.kt

refs: MBL-15145
release note: Exit confirmation no longer appears after saving a page.
test plan: Go to Pages > Create or Edit a page > After clicking save the exit confirmation should not be visible.

[MBL-15145][Teacher] Remove exit confirmation on saved page

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt

refs: MBL-15097
release note: Accessibility bugfix
test plan: Using TalkBack navigate through the submission details page. If the SlidingPanel is full screen the content behind the panel should not be focusable.

[MBL-15097][Student] Remove focus for views under SlidingPanel

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/SubmissionDetailsEmptyContentPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt

refs: MBL-15129
release note: Fixed a bug where assignments show as locked before the end date of the course.

[MBL-15129][Student] Assignments added to a module locked in the app, when the term has ended but overwritten by course end date

---

apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt
libs/pandares/src/main/res/values/strings.xml

refs: MBL-15122
release note: Accessibility fix
test plan: See more in the ticket. 
Open files > Navigate using TalkBack
- The FAB description should change
- After opening the FABs the focus should change to the Folder FAB
- After closing the FABs TalkBack should announce the buttons are no longer visible

[MBL-15122][Teacher] Files FAB accessibility fix

---

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt

refs: MBL-15265
test plan: See ticket. The content should not be focusable by the screen reader when the panel is open.

[MBL-15265][Teacher] Content disabled when sliding panel open

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/StreamAPI.kt

refs: MBL-15266
release note: Fixed a bug where notifications would appear from inactive courses.
test plan: The environment specified in the ticket is no longer active.
1. Create and publish a new course with an assignment and a student.
2. Submit to the assignment, but do not grade it.
3. Unpublish the course.
4. Grade the assignment.
5. The student should not get a notifications about the assignment being graded.

[MBL-15266][Student] ActivityStream API change

---

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

refs: MBL-15279
release note: Added the possibility to retain selected annotation color when annotating submissions.

[MBL-15279][Teacher] Draw annotation tool it doesn't retain previously selected color when switching

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt

refs: MBL-15097
test plan: Go to submissions & rubric > Using talkback navigate through the screen >
1. If the sliding panel is collapsed the details should be focusable
2. If the sliding panel is anchored or expanded the details should NOT be focusable

[MBL-15097][Student] Remove a11y focus behind sliding panel if anchored

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ModelExtensions.kt

refs: MBL-15415
release note: Fixed a bug where the mark done checkbox was available for locked assignments.
test plan: See ticket. Keep in mind you will need to disable the K5 feature flag to use the user in the ticket.

[MBL-15415][Student] Mark done no longer available for locked assignment

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/A11yUtils.kt

refs: MBL-15265
test plan: Go to SubmissionContentView if the SlidingPanel is anchored or expanded the content behind should not be focusable by TalkBack

[MBL-15265][Teacher] Sliding panel a11y fix

---

libs/pandautils/src/main/assets/html_wrapper_k5.html
libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt

Test plan:
- Test if the content in the WebViews with the K5 user has the Balsamiq font. 
- Check if the content in the WebViews are correct for standard users and uses the default font.
refs: MBL-15459

[MBL-15459][Student] K5 WebView font change

---

apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/adapters/SubmissionContentAdapter.kt
libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CanvaDocsManager.kt

refs: MBL-15434
release note: Fixed a bug, where annotations weren't visible when going back to the previous document in Speed Grader.

[MBL-15434][Teacher] Free draw annotations disappear after submission swipes

---

libs/rceditor/src/main/java/instructure/rceditor/RCEUtils.kt

refs: MBL-15441
release note: Fixed a bug where saving page content removes styling.

[Teacher][MBL-15441] Saving content removes semicolons

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ElementaryDashboardInteractionTest.kt
apps/student/src/main/java/com/instructure/student/mobius/elementary/ElementaryDashboardFragment.kt
apps/student/src/main/java/com/instructure/student/util/FeatureFlagPrefs.kt

Test plan: Login with a K5 user and verify that only the Homeroom tab is visible. Verify that the feature flag can be changed in developer settings.
refs: MBL-15522

[MBL-15522][Student] Hide K5 tabs

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/TermsOfService.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt

refs: MBL-15533
release note: Fixed a bug where students could generate pairing code, when it's disabled.

[MBL-15533][Student] Students are able to generate pairing codes when self-registration is disabled

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/fragment/FlutterCalendarFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/elementary/ElementaryDashboardFragment.kt
libs/interactions/src/main/java/com/instructure/interactions/Navigation.kt

Test plan: Test the in app navigation thoroughly. Bottom navigation screens should only be added to the backstack once, and keep their state even when going back to a previous tab.
refs: MBL-15598
release note: Improved bottom menu navigation.

[Student][MBL-15598] Bottom bar navigation

---

apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt

Test plan: Test user and course linked in the ticket.
refs: MBL-15684
release note: Fixed self enrolment link opening.

[MBL-15684][Student] Self-enroll links in the RCE are unresponsive

---

apps/student/src/main/java/com/instructure/student/activity/StudentViewStarterActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.kt

refs: MBL-15657
release note: Student view now opens Canvas for Elementary courses with the correct design.
test plan: You have to install both apps
1. Login with a C4E teacher -> When using student view the elementary dashboard and subject pages should be visible.
2. Login with a non-C4E teacher -> When using student view the original dashboard and subject pages should be visible.

[MBL-15657][Teacher] C4E for Student View

---

apps/flutter_parent/lib/network/api/enrollments_api.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/test/screens/courses/course_details_model_test.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart

refs: MBL-15719
release note: Fixed a bug where total grades were not visible for past and future enrolments.

[MBL-15719][Parent] Omit userId from enrolments call

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt

refactor and reorder existing k5 grades interaction tests and implement a new test case.
refs: MBL-15760

[MBL-15760] - Refactor, reorder k5 grades interaction tests and implement a new test case

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt

Test plan: Bug description in the ticket. Also smoke test module item opening from the standard modules page and module item opening from links.
refs: MBL-15790
release note: Fixed a bug where links from the elementary subject modules don't open.

[Student][MBL-15790] K5 modules routing

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt

fix stubbed grades test (it asserts to elementaryCoursePage , aka subjectpage now)
refs: MBL-15805

[MBL-15805] - Fix stubbed grades interaction test

---

apps/flutter_parent/lib/l10n/app_localizations.dart
apps/flutter_parent/lib/network/utils/dio_config.dart
apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart

refs: MBL-15747
release note: Fixed a bug where inbox wouldn't update after sending a message.

[Parent][MBL-15747] Sent mail from course page only displays in inbox after refresh

---

apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt

refs: MBL-15769
release note: Fixed a bug where inbox didn't refresh after deleting a reply.

[MBL-15769][Student] Messages won't update after reply deleted.

---

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

Test plan: Bug description in the ticket. OK button should work just like the Cancel button on empty input, when creating text annotations. On editing it should remove the annotation when the user enters an empty text. Test on Teacher and Student app as well.
refs: MBL-15770

[MBL-15770][Student][Teacher] Unexpected error after put an empty input text in student annotation

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditPageDetailsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderGradePage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/StudentContextPage.kt

Fix breaking Teacher UI E2E tests - cut off navigateBack() function because of UI change. We are using Espresso.pressBack() instead of it yet.
refs: MBL-15809

[MBL-15809] - Fix breaking teacher UI e2e tests

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt

refs: MBL-15815
release note: Fixed a bug where assignments with student annotation submission type couldn't be edited

[MBL-15815][Teacher] Student Annotation prevent teachers updating assignments

---

apps/student/flank_e2e.yml

Change student e2e tests locale to en instead of en_US. (Hoping that the timezone will also change by this)
refs: MBL-15835

[MBL-15835][Student] - Change student e2e tests locale to en instead of en_US

---

apps/student/src/main/AndroidManifest.xml
apps/teacher/src/main/AndroidManifest.xml

refs: MBL-15826
release note: Fixed zoom links not opening on Android 11

[MBL-15826][Student/Teacher] Zoom links not opening on Android 11

---

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
apps/student/src/main/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModel.kt
apps/student/src/test/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModelTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Section.kt

refs: MBL-15837
release note: Fixed a bug where courses with closed sections would show up as current enrolments.
test plan: Smoke test the Dashboard and Edit Dashboard screens with different terms and sections. See ticket for more info.

[MBL-15837][Student] Filtering Dashboard based on sections and terms

---

apps/student/src/main/java/com/instructure/student/widget/GradesViewWidgetService.kt

refs: MBL-15884
release note: Fixed a bug where concluded courses would still be visible in the Grades widget.
test plan:
1. Create a Course with an assignment
2. Submit to the course
3. Grade the submission
4. Enable the Grades widget, verify the grade is visible.
5. Conclude the course
6. Verify the grade is no longer visible in the widget.

[MBL-15884][Student] Concluded courses no longer appear in grades widget

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/grades/GradesViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/elementary/grades/GradesViewModelTest.kt

Test plan: Compare K5 grades page with the web. Test user included in the ticket.
refs: MBL-15895
release note: Fixed a bug where grades where shown for the wrong grading period on the homeroom grades screen.

[Student][MBL-15895] K5 Grades not showing correct values

---

apps/teacher/src/main/java/com/instructure/teacher/holders/DiscussionListHolder.kt

refs: MBL-15850
release note: Fixed a bug where the unread indicator would not disappear.
test plan: See if the indicator is working as intended.

[MBL-15850][Teacher] Changed the status indicator logic to match Student

---

apps/student/src/main/AndroidManifest.xml
apps/teacher/src/main/AndroidManifest.xml

Test plan: See ticket. Should be also tested in the Teacher app, because it had the same issue. With this fix the teacher works as well, but doesn't have the loading screen when opening a file (never had).
refs: MBL-15881
release note: Fixed a bug where some linked files wouldn't open the associated apps.

[Student][Teacher][MBL-15881] Some Android devices don't recognize available apps that can open external files

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/QuizListFragment.kt
apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
apps/student/src/main/res/layout/course_module_progression.xml
apps/student/src/main/res/layout/fragment_assignment_details.xml
apps/student/src/test/java/com/instructure/student/test/util/RouterUtilsTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt
libs/interactions/src/main/java/com/instructure/interactions/router/BaseRouteMatcher.kt
libs/interactions/src/main/java/com/instructure/interactions/router/Route.kt

Test plan: I added a test user in the JIRA ticket. Each type of module item there has 3 links, 1 that has module_item_id and 1 that doesn't. These two should work the same, navigation buttons should be visible. The 3rd link is a content that is not included in the course modules. This link should open the same page, but redirect to the standalone screen after that.
Opening module items from the modules list should also be smoke tested.
refs: MBL-9773
release note: Module items opened from links now show module navigation buttons.

[MBL-9773][Student] Module navigation buttons are not included when accessing module items from links

---

apps/student/flank.yml
apps/student/flank_e2e.yml
apps/student/flank_e2e_flaky.yml
apps/student/flank_e2e_knownbug.yml
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt
apps/teacher/flank.yml
apps/teacher/flank_e2e.yml
apps/teacher/flank_e2e_flaky.yml
apps/teacher/flank_e2e_knownbug.yml
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/FlakyE2EAnnotation.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/KnownBug.kt

Introduce FlakyE2E and KnownBug annotations in both apps (Teacher, Student) to separate these breaking tests from nightly. (They'll also run but separately).
refs: MBL-15859

[MBL-15859] [Student] [Teacher] -  Introduce new test related annotations

---

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt

Test plan: It's not easy to reproduce this issue, but the crash is pretty self-explanatory, so instead of trying to reproduce it I would suggest to smoke test the Speed Grader and the Comment Library if everything works as intended.
refs: MBL-15930
release note: Fixed a crash in Speed Grader

[MBL-15930][Teacher] Crash in SlidingPanel in Speed Grader.

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt
apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseFragment.kt
apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewData.kt
apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt
apps/student/src/main/res/layout-sw720dp/fragment_elementary_course.xml
apps/student/src/main/res/layout/fragment_elementary_course.xml
apps/student/src/test/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModelTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/MiscEndpoints.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DashboardCard.kt

Test plan: Description in the ticket. There are also more cases where this bug could happen. It can also happen when opening a non K5 course grades from the K5 grades page. In that case we should redirect to the standard grades page.
refs: MBL-15936
release note: Fixed a bug where elementary subject page would open instead of course page.

[MBL-15936][Student] Canvas for Elementary theme is applied to courses which don't have it enabled.

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt

It works locally so the Stub annotation has been removed. I have tested it on bitrise as well, it has passed. (We will see it running again under this PR check)
refs: MBL-15729

[MBL-15729][Student] - Remove stub from show privacyPolicy test 

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/student/src/main/res/layout/fragment_discussions_details.xml
apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/DiscussionsDetailsPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/viewinterface/DiscussionsDetailsView.kt
apps/teacher/src/main/res/layout/fragment_discussions_details.xml
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DiscussionTopicHeader.kt
libs/pandares/src/main/res/values/strings.xml

Test plan: 
- Create an anonymous discussion with the discussions redesign (one is included in the ticket)
- Open the anonymous discussion
- You should see a text that the discussion is not supported on mobile and a link to open the discussion in a WebView.
- Verify that the discussion opens
- Also smoke test regular discussions
refs: MBL-15913
release note: Added a button to open anonymous discussions in browser.

[MBL-15913][Student][Teacher] Discussion Redesign, anonymous replies don't load

---

apps/student/src/main/java/com/instructure/student/fragment/LtiLaunchFragment.kt

Test plan: I wasn't able to reproduce this, but added a check that could prevent these edge cases.
refs: MBL-15997
release note: Fixed a crash when launching LTI tools

[MBL-15997][Student] Crash on LTI launch

---

apps/student/src/main/res/layout/panda_recycler_refresh_layout.xml

refs: MBL-15960
release note: Fixed a bug where modules links would always navigate to the first module.

[MBL-15960][Student] Direct links to modules navigate to the top of modules page

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/StudentContextPage.kt

Fix assertion for seeding user with e-mail.
refs: MBL-15466

[MBL-14665] [Teacher] - Fix seeding user with email

---

apps/teacher/src/main/java/com/instructure/teacher/activities/ViewMediaActivity.kt

refs: MBL-16006
release note: Fixed a crash when trying to edit media files.

[MBL-16006][Teacher] Crash fix when editing media files

---

apps/student/src/main/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModel.kt
apps/student/src/test/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModelTest.kt

refs: MBL-16002
release note: Fixed a bug where course on the edit dashboard screen would show up multiple times.

[MBL-16002][Student] Fixed section filtering on Edit Dashboard

---

apps/teacher/src/main/java/com/instructure/teacher/events/BusEvents.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListEventBusSource.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFileFolderFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewHtmlFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewImageFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewPdfFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewUnsupportedFileFragment.kt

refs: MBL-16033
release note: Fixed a bug where a video file's new name was not shown after editing.

[Teacher][MBL-16033] Editing video file name does not get applied until navigating back to Files page

---

apps/student/src/main/java/com/instructure/student/adapter/TodoListRecyclerAdapter.kt
apps/student/src/main/java/com/instructure/student/widget/TodoViewWidgetService.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/ToDoManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ScheduleItem.kt

Test plan: See ticket. There are 2 scenarios in the ticket. The 1st is not valid, it only occurred because no curse was favorited. The second one should be verified, but you cannot reproduce it anymore with the attached user, so you need to create the data yourself.
refs: MBL-16015
release note: Fixed a bug where To Do widget displayed completed assignments.

[MBL-16015][Student] To do list widget does not update changes

---

apps/student/src/test/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModelTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt

refs: MBL-16036
release note: Fixed a bug where courses would show up under the incorrect section on the Edit Dashboard screen.
test plan: Masquerade based on the ticket. See [this docs](https://community.canvaslms.com/t5/Canvas-Basics-Guide/How-do-term-dates-course-dates-and-section-dates-work-in-Canvas/ta-p/37) for the hierarchy.

[MBL-16036][Student] Edit Dashboard fix filtering

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/url/ui/UrlSubmissionUploadView.kt
apps/student/src/main/res/layout/fragment_submission_rubric_description.xml
apps/student/src/main/res/layout/fragment_url_submission_upload.xml
apps/student/src/main/res/values/styles.xml
apps/teacher/src/main/java/com/instructure/teacher/activities/FeedbackActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/AttendanceListFragment.kt
apps/teacher/src/main/res/values/styles.xml
buildSrc/src/main/java/GlobalDependencies.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.kt
libs/pandautils/build.gradle
libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionUtils.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt
libs/pandautils/src/main/res/values/themes_canvasthemes.xml

Test notes:
- In this PR I set up forced dark mode for all the WebViews and all the web content we have in the app (only exception is url preview in the url submission view). Later we might revert some of them, but this will be discussed with the team.
These are the screens that should be checked:
- Login
- Discussion details
- Announcement details
- K5 homeroom/important links/subject pages
- Calendar event
- Assignment details
- Quiz details
- Quiz submission
- Rubric description
- Syllabus
- Text submission details
- Page details
refs: MBL-15985

[MBL-15985][Student][Teacher] Dark mode for WebViews

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt

refs: MBL-16098
release note: Fixed an issue when the attendance tool was displayed as an LTI tool in course navigation.

[MBL-16098][Teacher] Attendance tool is shown as LTI tool in course navigation in some cases

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizListFragment.kt

Test plan: Verify that the new quizzes route to the assignment details screen instead of the quiz details screen.
refs: MBL-16091
release note: Fixed a bug where teachers couldn't preview quizzes created with the new quizzes tool.

[Teacher][MBL-16091] Page Error when previewing NQ assessments via Quizzes

---

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

refs: MBL-16097
release note: Fixed a crash when opening rotated image submissions.

[MBL-16097][Student][Teacher] Viewing rotated images for a submission crashes the app

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFileFolderFragment.kt

refs: MBL-16108
release note: Fixed a bug where deleted folders would still be accessible until manual refresh.
test plan: Delete a folder on the Files screen > The folder should no longer be visible.

[MBL-16108][Teacher] FileList folder delete refresh

---

apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt

[MBL-16110][Student] Modifying course nickname triggers an unnecessary reorder on Dashboard

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ProfileSettingsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SettingsPage.kt
automation/espresso/src/main/kotlin/com/instructure/espresso/CustomViewAssertions.kt

Implement Teacher Dark Mode settings test case.
Extend some pages in Teacher app with color asserting methods.
Extend Teacher SettingsPage with AppTheme related elements and methods.
Rename 'launch'-leading method name conventions to 'open'.
+Some refactor
Implement Student Dark Mode settings test case.
Extend some pages with color asserting methods.
Extend SettingsPage with AppTheme related elements and methods.
Rename 'launch'-leading method name conventions to 'open'.
+Some little refactor.
refs: MBL-15990

[MBL-15990] [Student][Teacher] - Implement Dark mode tests in both apps

---

libs/pandautils/src/main/java/com/instructure/pandautils/utils/ThemePrefs.kt

Test plan: 
- Clear the app data. 
- Intercept the brand variables endpoint in Charles and make it fail.
- Now you should see the default colors instead of the colors from the server.
refs: MBL-16116

[MBL-16116][Student][Teacher] Change default theme colors

---

apps/student/src/main/java/com/instructure/student/AnnotationComments/AnnotationCommentListFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/annnotation/AnnotationSubmissionUploadFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/AnnotationSubmissionViewFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/PdfStudentSubmissionView.kt
libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt

Test plan: 
- Specification and expected behavior is in the ticket.
- Smoke test also the following scenarios:
- Students can comment on teacher's annotations on PDF submissions
- Teachers commenting annotations on both student annotation and PDF submission types.
refs: MBL-16115

[MBL-16115][Student] Students cannot comment student annotations

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt

Fix unnecessary % sign in customize grade dialog when the grade type is percentage.
refs: MBL-16117

[MBL-16117] [Teacher] - Remove unnecessary % sign from customize grade dialog

---

apps/flutter_parent/lib/utils/crash_utils.dart
apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt

Test plan:
- Not necessary but you can test with some fake crashes and verify that the logs don't contain the user id.
refs: MBL-16138

[MBL-16186][All] Remove Id and domain from firebase reporting

---

apps/student/src/main/res/layout-sw720dp/fragment_elementary_course.xml
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt
libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt

refs: MBL-16130
release note: Added banner image to the Elementary Course Details screen.
test plan: 
Only the tablet layout is affected.
If the banner image has been set in the course settings it should show on the elementary course details screen.
If the banner image is not set, the course image is used instead.
If the course image and the banner image are not set the course color is used.

[MBL-16130][Student] Banner image on K5 Course details

---

apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderGradePresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/ToDoPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/view/edit_rubric/RubricEditView.kt
libs/recyclerview/src/main/java/com/instructure/pandarecycler/util/UpdatableSortedList.kt

Test plan:
- Repro steps in the ticket, but one thing is not mentioned there. To reproduce the issue first you need to open that assignment details screen from the assignments list to have it cached. Than follow the steps in the ticket.
- I also fixed the issue that the todo item is not disappearing when all the assignments were graded for that item.
refs: MBL-16173

[MBL-16173][Teacher] Grading and grading state gets confused after grading via To Do section

---

apps/flutter_parent/lib/network/api/enrollments_api.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/flutter_parent/test/screens/courses/course_details_model_test.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart

[MBL-15753][Parent] Add back the userId param when the api is fixed

---

apps/flutter_parent/android/app/build.gradle

add variant section
define an apk build name which contains the word 'parent' instead of using a default build name (app-debug.apk or app-release.apk)
add timestamp to debug builds to be more accurate
refs: MBL-16227
release note:
test plan:

[MBL-16227][Parent] - Rename build apk names to contains the appname

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt

Implement testModules_launchesIntoExternalTool interaction test.
Extend MockCanvas class addItemToModule method to handle LTITool type as well.
Add URL assertion to testModules_launchesIntoExternalURL method.
refs: MBL-13517

[MBL-13517][Student] - Investigate and put in order lti related tests

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsListPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditDiscussionsDetailsPage.kt

implement discussion creation flow on UI.
add searching to the discussionE2E test
add expand/collapse to the test as well.
refs: MBL-16210

[MBL-16210][Teacher] - Insert discussion creation on UI

---

apps/student/src/main/AndroidManifest.xml
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/ShareExtensionActivity.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/ShareExtensionViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/file/upload/FileUploadViewModelTest.kt

refs: MBL-16236
release note: Added support for sharing multiple files to the app.
test plan: Select multiple files in the device file explorer. Canvas should be visible in the share sheet. All the files should be visible in the file upload dialog.

[MBL-16236][Student] Multiple file sharing support

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/file/upload/FileUploadViewModelTest.kt

refs: MBL-16249
release note: Added the option to select multiple files from the file browser for uploading.
test plan: Test all the screens where the file upload dialog is available.
- User files in both apps
- Discussion reply in both apps
- Create discussion in both apps
- Messages in both apps
- Create/Edit announcement in the Teacher app

[MBL-16249][Student][Teacher] Multiple file selection on FileUpload

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt

refs: MBL-15766
test plan: in the ticket
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/190413255-00de0f0c-be91-462f-bc85-07ae89ad436b.jpg" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/190413284-205c64da-16b3-41bf-b53c-7ef107ff4ba6.jpg" maxHeight=500></td>
</tr>
</table>

[MBL-15766][Student][Teacher] The keyboard is not hiding when changing the tab

---

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt

Test plan:
- In the ticket
- Also verify that the assignments will show up as missing if the teacher explicitly marks it in the gradebook (you need to create new assignments for this in your sandbox).
refs: MBL-16228
release note: Fixed a bug where on paper and no submission assignments would show as missing in grades.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72397075/190406746-4c122220-b29a-4a04-9893-2e8304f6583d.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72397075/190405849-850a5464-4240-4fb1-b9ce-66015d8b2415.png" maxHeight=500></td>
</tr>
</table>

[MBL-16228][Student] On Paper and No Submission assignments with a past due date display missing label

---

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart

refs: MBL-16237
release note: Fixed a bug where Excused label was missing.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/191279275-291fd83e-b817-4762-b671-fafbc9d523cb.png" height=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/191279077-6a746d07-5ead-44c5-9a32-860f52a801f6.png" height=500></td>
</tr>
</table>

[MBL-16237][Parent] Excused does not appear in the app

---

apps/student/src/main/java/com/instructure/student/mobius/syllabus/SyllabusPresenter.kt
apps/student/src/test/java/com/instructure/student/test/syllabus/SyllabusPresenterTest.kt
apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusPresenter.kt
apps/teacher/src/test/java/com/instructure/teacher/features/syllabus/SyllabusPresenterTest.kt

refs: MBL-16257
release note: Fixed a bug where events for specific sections show for everyone.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/191468834-2f12714a-0bc1-4021-9e8d-d1da9e7e803b.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/191468730-1406c1a5-aaec-4588-bd86-3e4d44ded7d2.png" maxHeight=500></td>
</tr>
</table>

[MBL-16257][Student][Teacher] Calendar events for specific sections show for everyone in the app on the Syllabus

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt

refs: MBL-16274
test plan: in the ticket

[MBL-16274][Student] Inconsistent reordering of announcement list after view

---

libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogFragment.kt

refs: MBL-16357
test plan: In the ticket. See my comment on the ticket for repro steps.

[MBL-16357][Student] Camera Permissions Prompt doesn't show when attempting to share a file to Student App

---

libs/flutter_student_embed/lib/l10n/app_localizations.dart
libs/flutter_student_embed/lib/network/utils/dio_config.dart
libs/flutter_student_embed/lib/screens/calendar/calendar_widget/calendar_filter_screen/calendar_filter_list_screen.dart
libs/flutter_student_embed/test/screens/calendar/calendar_screen_test.dart
libs/flutter_student_embed/test/screens/calendar/calendar_widget/calendar_filter_list_screen_test.dart

refs: MBL-15938
release note: Added filtering option for user calendar.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72397075/198229039-776af3e8-2f54-44e6-b6ab-a23ad48c75ab.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72397075/198229410-49bae582-2901-43c8-803e-d5515019091a.png" maxHeight=500></td>
</tr>
</table>

[MBL-15938][Student] Display calendar events without course even tough some courses are deselected

---

libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt

[MBL-16375][Student][Teacher] Video colors are inverted when embedded in discussion replies with dark mode enabled

---

apps/teacher/src/main/java/com/instructure/teacher/presenters/PeopleListPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Recipient.kt

Fix searching on people list page only showed shortname (in automation context).
refs: MBL-16369
test plan: in the ticket.
<table>
<tr>
<td>
<td>
</td>
</tr>
</table>

[MBL-16369][Teacher] - Searching people only shows shortname

---

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt

refs: MBL-16387
release note: Fixed a bug regarding Course filtering on the Dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72087159/202505992-53d52b3b-58c2-4e8c-b1ea-cfce19c4aa08.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72087159/202505869-e40ecd82-305d-4c71-81c1-bf5684911cac.png"
maxHeight=500></td>
</tr>
</table>

[MBL-16387][Student] Fix Dashboard filtering

---

apps/student/src/main/java/com/instructure/student/features/dashboard/edit/StudentEditDashboardRepository.kt

refs: MBL-16388
release note: Fixed a bug regarding Course filtering on Edit Dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72087159/202509624-def38cfb-57ad-4bdd-a1e3-059b8172189e.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72087159/202509692-4d81e6c6-793e-4ae5-9c70-97b02b656e48.png"
maxHeight=500></td>
</tr>
</table>

[MBL-16388][Student] Fix Edit Dashboard filtering

---

apps/student/src/main/java/com/instructure/student/di/DashboardNotificationModule.kt
apps/student/src/main/java/com/instructure/student/features/dashboard/notifications/StudentDashboardNotificationRepository.kt
apps/student/src/test/java/com/instructure/student/features/dashboard/edit/StudentEditDashboardRepositoryTest.kt
apps/teacher/src/main/java/com/instructure/teacher/di/DashboardNotificationModule.kt
apps/teacher/src/main/java/com/instructure/teacher/features/dashboard/notifications/TeacherDashboardNotificationRepository.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationRepository.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModelTest.kt

refs: MBL-16391
release note: Fixed a bug regarding the invitations on the Dashboard.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72087159/202721791-8e372ba2-e66d-41c7-97ee-9f7b7b07a326.png"
maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72087159/202721850-f13b23ed-d39d-4101-a3df-f1cb16917d85.png" maxHeight=500></td>
</tr>
</table>

[MBL-16391][Student][Teacher] Fix Dashboard invites for multi role

---

apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
apps/student/src/main/java/com/instructure/student/tasks/StudentLogoutTask.kt
apps/student/src/main/java/com/instructure/student/util/BaseAppManager.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/tasks/TeacherLogoutTask.kt
apps/teacher/src/main/java/com/instructure/teacher/utils/BaseAppManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FeaturesAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FeaturesManager.kt

Test plan:
- If the feature flag is set to true, the events should be displayed in Heap, otherwise they shouldn't be displayed.
- Currently the feature flag cannot be set in the sandbox settings so you need use a Charles breakpoint and set the flag to true.
refs: MBL-16396

[MBL-16396][Student][Teacher] Heap feature flag

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt

[MBL-16398][Teacher] Delete description on different screens does not refresh automatically

---

apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusEffectHandler.kt
apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/CanvasContextPermission.kt

Test plan:
- Test the Edit Syllabus in your prod and beta sandbox, edit button should be displayed in both cases. (Currently it only displays in prod)
refs: MBL-16425

[MBL-16425][Teacher] Edit syllabus not working after change to detailed permission

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt

Fix null canvasContext object in Modules (which made color diff anomaly on split view on tablet when there was no module selected).
refs: MBL-16428
<table>
<tr>
<td><img src="" maxHeight=500>
</td>
<td><img src="" maxHeight=500>
</td>
</tr>
</table>

[MBL-16428][Teacher] - Fix Modules Empty list color anomaly

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt

[MBL-16429][Student][Teacher] Dark mode content (which switched to light) set back to dark after reply

---

apps/student/src/main/res/layout/fragment_discussions_details.xml
apps/teacher/src/main/res/layout/fragment_discussions_details.xml

[Student][Teacher][MBL-16439] Dark Mode | Paperclip icon for viewing attachments is dark on black

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt
libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebViewWrapper.kt
libs/pandautils/src/main/res/layout/view_canvas_web_view_wrapper.xml

Test plan: Verify that both tickets are fixed. Smoke test screens with CanvasWebViewWrapper.
refs: MBL-16441, MBL-16442
release note: Fixed an issue where classic quizzes wouldn't load. Fixed an issue where the keyboard is not opening for web forms.

[Student][Teacher][MBL-16441][MBL-16442] CanvasWebViewWrapper issues

---

apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt

Test plan: Press back immediately after opening assignments screen.
refs: MBL-16444

[Student][MBL-16444] Crash on AssignmentListFragment

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouterFragment.kt

Test plan: You can reproduce the crash by setting the error value as the initial value in the `DiscussionRouterViewModel` events. Smoke test discussion routing in both apps.
refs: MBL-16445

[Student][MBL-16445] Crash on NavigationActivity

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt
libs/pandautils/src/main/assets/discussion_html_header_item.html
libs/pandautils/src/main/assets/discussion_html_header_item_rtl.html
libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebViewWrapper.kt

Test plan:
- Verify that nested discussion replies (when you need to open a new screen to see more replies) work correctly in both themes, and new nested replies update correctly.
- Verify that replies are added to the correct discussion item.
- Smoke test discussions in both apps.
refs: MBL-16438
release note: Fixed discussion replies in dark mode
[MBL-16438]: https://instructure.atlassian.net/browse/MBL-16438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-16438][Student][Teacher] Discussion replies in dark mode

---

apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt
apps/student/src/main/res/layout/fragment_webview.xml
apps/teacher/src/main/res/layout/fragment_page_details.xml

- Smoke test also different pages in both apps in dark/light mode.
- The theme switcher should stick to the top of the screen.
refs: MBL-16456
release note: Fixed a bug where pages with global CSS don't load

[MBL-16456][Student][Teacher] Pages that import styles through global CSS does not load

---

buildSrc/src/main/java/GlobalDependencies.kt

Test plan: 
- Repro steps for the bug are in the ticket.
- I have updated PSPDFKit so smoke test all the usages:
- PDF opening in the Student/Teacher app
- Annotating PDF submissions as a teacher
- Submitting Student Annotation submission types
- Opening PDFs in the student app from Files, making annotations and submitting to an assignment
refs: MBL-16452
release note: Fixed a bug where restricted PDFs didn't open

[MBL-16452][Student][Teacher] Restricted PDFs fail to open in Android

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt

Previous run: https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.51e9e887f5fb835f/matrices/8193952435797445814/details
Successful run: https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.51e9e887f5fb835f/matrices/4877244168722846798/details
Fix HomeroomE2E test and put back ScheduleE2E test into nightly.
refs: MBL-16338

[MBL-16338][Student] - Investigate and fix HomeroomE2E Test

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ExhaustiveCallback.kt

Test plan: In the ticket. Ticket only mentions the student app, but this change affects the teacher as well and probably it has the same problem. There was no test user for teacher.
refs: MBL-16512

[MBL-16512][Student][Teacher] Only the first 100 course discussions from the api results show in the mobile app

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt

[MBL-16464][Student] Some of the page titles displayed with too small size

---

libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewExtensions.kt

refs: MBL-16498
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/217817469-3d4efdca-cf01-4c87-aaa3-8c16b2a51c30.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/217814798-365e4e05-9bfe-456f-9c41-39ca928f2388.png" maxHeight=500></td>
</tr>
</table>

[MBL-16498][Student] Tablet: Assignment Search Input Field size is too short

---

apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt
libs/pandautils/src/main/assets/discussion_html_template_item.html
libs/pandautils/src/main/assets/discussion_html_template_item_rtl.html
libs/pandautils/src/main/assets/discussion_topic_header_html_template.html
libs/pandautils/src/main/assets/discussion_topic_header_html_template_rtl.html

I accidentally changed the colors of the LTI button in the last PR, so this is fixed here as well.
refs: MBL-16493

[MBL-16493][Student] Back button handling on Pages

---

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt

Test plan: In the ticket, smoke test the page on phone as well - they did not resize the field on orientation change intentionally, but I don't understand why
refs: MBL-16490
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/217876215-9ad3f35f-6989-447d-9286-0c15ddfd5161.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/217875386-f4b97dc7-57f2-4a30-9292-86b82e42575a.png" maxHeight=500></td>
</tr>
</table>

[MBL-16490][Teacher] Weird behaviour of the comment input field while changing orientation

---

PULL_REQUEST_TEMPLATE

Update PR template by adding a "Run E2E test suite or not needed" checkbox to remind us to run the E2E test suite in case if we think a development could affect existing features. (Mainly it's needed on stories, especially in case of we are "rewriting", or redesigning some existing (regression) feature)

Update PULL_REQUEST_TEMPLATE - add 'Run E2E test suite or not needed' reminder

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CommentLibraryE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CourseSettingsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SyllabusE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt

Extract API calls from Teacher E2E tests into private methods. (Further improvements will be done with this in the future, see MBL-16533)
Put back filesE2E test from known bug to nightly
refs: MBL-16517
Teacher E2E test run (successful): https://app.bitrise.io/build/ce38ab57-4a9e-4fa6-a924-f3159871e923

[MBL-16517] [Teacher] - Refactor API calls in E2E test cases

---

apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/AddMessageFragment.kt

refs: MBL-16532
release note: Users can add themself to a message from the recipient selector screen.

[MBL-16532][Student][Teacher] Can add self from recipients list

---

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt
apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt

Test plan: In the ticket. Instead of adding a loading indicator as the ticket suggests I added a cache loading to load the grades immediately when exiting "what if" mode.
refs: MBL-16496

[MBL-16496][Student] Grades loading indicator

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/InboxInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ConversationsApi.kt
libs/pandautils/src/main/res/menu/menu_inbox_edit.xml

Extend InboxE2E test in both apps, Student and Teacher with new Inbox features (archive, unread/read, star/unstar)
remove deprecated function (filterInbox)
add methods to page objects.
**_IMPORTANT: This pull request also contains the fix of the Inbox interaction test fails on landscape mode._**
Teacher successful E2E test run: https://app.bitrise.io/build/6640e317-4743-4130-9860-fc39b3fadb74
Student successful E2E test run:  https://app.bitrise.io/build/5d034279-5b5f-42a0-971e-494589b876bb
refs: MBL-16531

[MBL-16531][Student][Teacher] - Extend and major refactor on inbox E2E tests

---

libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/adapter/PreviousUsersAdapter.kt

Test plan: the crash occurred when there was at least 2 previous user, and we removed them from top to bottom
refs: MBL-16553

[MBL-16553][Student][Teacher] Previous user crash

---

libs/login-api-2/src/main/java/com/instructure/loginapi/login/features/acceptableusepolicy/AcceptableUsePolicyViewModel.kt
libs/login-api-2/src/test/java/com/instructure/loginapi/login/features/acceptableusepolicy/AcceptableUsePolicyViewModelTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/di/ApplicationModule.kt

Test plan: Need to check if all webview where we load url (quiz, discussions etc.) works fine after accepting the use policy (in that particular login, when accepting it) in student and teacher also.
refs: MBL-16587

[MBL-16587][Student] Acceptable Use Policy displayed on K5 webviews after accepting it after mobile login

---

apps/teacher/src/main/AndroidManifest.xml
apps/teacher/src/main/java/com/instructure/teacher/features/shareextension/TeacherShareExtensionActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/features/shareextension/TeacherShareExtensionRouter.kt
libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadUtilsHelper.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressDialogFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressDialogViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/room/daos/DashboardFileUploadDao.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileUploadUtils.kt
libs/pandautils/src/main/res/layout/fragment_share_extension_progress_dialog.xml
libs/pandautils/src/main/res/layout/fragment_share_extension_status_dialog.xml
libs/pandautils/src/main/res/layout/item_dashboard_upload.xml
libs/pandautils/src/main/res/layout/item_file_progress.xml
libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModelTest.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/file/upload/FileUploadViewModelTest.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/shareextension/progress/ShareExtensionProgressViewModelTest.kt

Test plan: smoke test share extension uploads, and other file uploads using the file upload dialog (teacher speedgrader comments too)
refs: MBL-16264
release note: Added proper failed screen and retry logic for share extension.

[MBL-16264][Student] Share Extension | Retry upload from progress screen

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
apps/student/src/main/res/layout/course_module_progression.xml

refs: MBL-16537
release note: Fixed a bug where items were marked as viewed incorrectly.

[MBL-16537][Student] Remove ViewPager from module progression

---

apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt

Test plan: In the ticket. Keep in mind that this only applies to the old discussions/announcements. Redesign never supported bookmarks.
refs: MBL-16680

[MBL-16680][Student] Announcement/Discussion Details screen bookmark does nothing

---

apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/StudioWebViewFragment.kt

Test plan: Steps in the ticket. I also found and fixed a view binding issue. When you edit a page and close it then reopen it again the app crashes.
refs: MBL-16646

[MBL-16646][Student] Student cannot modify locked page module items but pencil is displayed

---

apps/student/src/main/java/com/instructure/student/activity/VideoViewActivity.kt

Test plan: Open an mp4 file from Files
refs: MBL-16668
release note: Fixed video playback from files

[MBL-16668][Student] Video media comments cannot be played from Files

---

apps/student/src/main/java/com/instructure/student/binding/BindingAdapters.kt
apps/student/src/main/java/com/instructure/student/features/assignmentdetails/gradecellview/GradeCellViewData.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeStatisticsView.kt
apps/student/src/main/res/layout/view_student_enhanced_grade_cell.xml
apps/student/src/main/res/layout/view_student_grade_cell.xml

Test plan: in the ticket, also check if the score chart still looks good on the rubric screen
refs: MBL-16713
release note: Added score graph to the grade cell on assignment details screen.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/109959688/236840929-25eb0f56-998a-4bc7-a31c-133dc19719bd.jpg" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/109959688/236841037-5ddec4f2-83e5-42cf-8ad8-fde9fe4c4f78.jpg" maxHeight=500></td>
</tr>
</table>

[MBL-16713][Student] Distribution score graph does not appear on app

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/EditDashboardPage.kt
libs/pandautils/src/main/res/layout/fragment_edit_dashboard.xml

Extend DashboardE2E test to test the new group favorizing/unfavorizing logics (that the groups should be displayed independently from courses)
Add new id for swipeRefreshLayout in edit dashboard fragment
Implement some necessary page object methods
refs: MBL-16733

[MBL-16733][Student] - Groups can independently selected on Edit Dashboard Page test implementation

---

apps/student/src/main/java/com/instructure/student/activity/StudentViewStarterActivity.kt
apps/student/src/main/java/com/instructure/student/activity/WidgetSetupActivity.kt
apps/student/src/main/java/com/instructure/student/features/documentscanning/DocumentScanningActivity.kt

Test plan: In the ticket. I also fixed the other similar activity binding errors. (Document scanner toolbar was not showing the correct title.)
refs: MBL-16725
release note: Fixed a bug where users could not add widgets to the home screen.

[MBL-16725][Student] Unable to place widgets due to light/dark theme selection

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/SubmissionCommentsPresenter.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/SubmissionCommentsPresenterTest.kt

Test plan: In the ticket. Also smoke test that the assignment enhancement feature works correctly when there is an attempt id, and in that case only those comments will be displayed.
refs: MBL-16736
release note: Fixed a bug where some submission comments were not visible.

[MBL-16736][Student] Submission comments with comment[attempt] value set as null are missing

---

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/util/LockInfoHTMLHelper.kt
apps/student/src/main/java/com/instructure/student/util/ModuleUtility.kt
apps/student/src/test/java/com/instructure/student/test/util/ModuleUtilityTest.kt

[MBL-16727][Student] 'Go To Modules' link opens a new screen which overflows the previous one

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/annnotation/AnnotationSubmissionUploadFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/AnnotationSubmissionViewFragment.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/PdfStudentSubmissionView.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/PdfSubmissionViewFragment.kt

Test plan: In the ticket + Smoke test viewing different types of submissions.
refs: MBL-16735
release note: Fixed a crash on the submission details screen.

[MBL-16735][Student] Submission view crashes on config change

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/LoginSignInPage.kt

Implement negative login test case (invalid, and empty credentials will displayed the corresponding error message).
refs: MBL-16689

[MBL-16689][Student] -  Negative Login Test Cases Implementation

---

apps/teacher/src/main/java/com/instructure/teacher/activities/BaseAppCompatActivity.kt

Test plan: In the ticket, check it on phone and tablet also.
refs: MBL-16652
release note: Implemented storage quota limit error.

[MBL-16652][Teacher] Show 'exceeded storage quota' toast when file upload storage is full

---

libs/pandautils/build.gradle
libs/pandautils/flank.yml

Test plan: Not needed.
refs: MBL-16807

[MBL-16807][Student][Teacher] Set up library integration tests on Bitrise

---

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/DashboardPresenter.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DashboardCard.kt

Test plan: In the ticket. Also smoke test the Dashboard with different users (compare with web).
refs: MBL-16800
release note: Fixed a bug where some courses would not show on the Dashboard
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72397075/714033aa-afc9-45b9-b1e4-fd1a789e9322" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72397075/909faef8-44c4-444f-9511-6135b29a251e" maxHeight=500></td>
</tr>
</table>

[MBL-16800][Student][Teacher] Enrollment dates are not checked when loading Dashboard tiles

---

apps/student/src/main/java/com/instructure/student/features/dashboard/DashboardRepository.kt
apps/student/src/test/java/com/instructure/student/features/dashboard/DashboardRepositoryTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DashboardCard.kt
libs/pandautils/schemas/com.instructure.pandautils.room.offline.OfflineDatabase/1.json
libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/entities/DashboardCardEntity.kt

Test plan: Change the default Dashboard card ordering on web. Check that the offline mode ordering is the same as in online mode.
refs: MBL-16841

[MBL-16841][Student] Fix Dashboard card ordering in Offline mode

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt

Test plan: Steps are in the ticket.
refs: MBL-16650
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/376ff729-c6e5-4cac-b3e9-04dde163a86e" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/b9c694c5-c82a-46cf-b31c-ce862da5ac1f" maxHeight=500></td>
</tr>
</table>

[MBL-16650][Student] Left Side menu font remains k5 when logging in with a user after a k5 login

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/NotificationsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/NotificationPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt

Workaround to handle API flakiness in ToDoE2E and NotificationsE2E tests.
refs: MBL-16849

[MBL-16849][Student] - Handle API flakiness of Notifications and Todo E2E test cases

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentFragment.kt

Test plan:
1. *Manage Offline Content* menu item on *Dashboard*
2. Rotate the screen
refs: MBL-16834
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/815a1855-364c-46a9-85a3-998989dd92f3" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/91f1864c-83d2-45a2-8767-25d5c897d27e" maxHeight=500></td>
</tr>
</table>

[MBL-16834][Student] Offline mode: Select/Deselect all button is disappearing when change orientation or put the app in the background

---

apps/student/flank.yml
apps/student/flank_e2e.yml
apps/student/flank_e2e_lowres.yml
apps/student/flank_landscape.yml
apps/student/flank_multi_api_level.yml
apps/student/flank_tablet.yml
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/NotificationsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ShareExtensionInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/LeftSideNavigationDrawerPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/ProfileSettingsPage.kt
apps/teacher/flank.yml
apps/teacher/flank_e2e.yml
apps/teacher/flank_e2e_lowres.yml
apps/teacher/flank_landscape.yml
apps/teacher/flank_multi_api_level.yml
apps/teacher/flank_tablet.yml
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/CommentLibraryPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditSyllabusPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InAppUpdatePageTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasRunner.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt

Update all corresponding workflows test devices in both apps to API Level 29 device.
Fix and refactor tests on new devices.
Latest all-ui-tests run on Student: https://app.bitrise.io/build/0f5b145d-9775-4f1d-9b28-6093529a0e68
Latest all-ui-tests run on Teacher: https://app.bitrise.io/build/e5e9e222-56fd-404a-8990-85b1305e8def (1 failed multi api level test is fixed since this run as well)
refs: MBL-16854

[MBL-16854][Student][Teacher] - Update test devices in firebase

---

apps/student/flank_e2e_lowres.yml
apps/teacher/flank_e2e_lowres.yml

Because API level 29 low resolution device is too flaky in Firebase Test Lab

Rollback lowres devices to API lvl 26

---

apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusView.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizListFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt

refs: MBL-16893
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/03a9474a-07f7-4fbd-9a51-814ec0bcc08a" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/53480952/1fa60fd3-6070-4917-bab8-0064bcb4cc1c" maxHeight=500></td>
</tr>
</table>

[MBL-16893][Teacher] Tablet: Refactor Syllabus fragment split view

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PagesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/PagesApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/PageApiModel.kt

Extend PagesE2E test with testing editable, non-editable pages
Add some needed webview methods as well.
Extend API calls to handle editing_roles parameter.
refs: MBL-16873

[MBL-16873][Student] - Extend PagesE2E test with testing editable, non-editable pages

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/usergroups/UserGroupFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ShareExtensionInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/GroupBrowserPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt

Implement user group folder control flow (create folder, upload file, create subfolder, open folder).
Add some UserGroup related classes.
Initial commit (will be continued with the exact test case)
refs: MBL-16890

[MBL-16890][Student] - Test folder control flow in user groups

---

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/widget/GradesViewWidgetService.kt
apps/student/src/main/java/com/instructure/student/widget/NotificationViewWidgetService.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/StreamItem.kt

Test plan: 
- Test the Grades and the Notifications widgets. Scores should not be displayed when LGO is enabled.
- I also fixed graded group discussions in this ticket because that still showed points regardless of course settings.
refs: MBL-16925

[MBL-16925][Student] Widgets LGO

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModelTest.kt

Test plan: Check that the points are not displayed on the schedule items when LGO is turned on, and displayed if turned off.
refs: MBL-16929 

[MBL-16929][Student] K5 Schedule LGO

---

apps/flutter_parent/lib/models/course_grade.dart
apps/flutter_parent/lib/models/enrollment.dart
apps/flutter_parent/lib/models/enrollment.g.dart
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ElementaryGradesInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/GradesPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Enrollment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/grades/GradesViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/grades/GradesViewModel.kt
libs/pandautils/src/main/res/layout-sw720dp/item_grade_row.xml
libs/pandautils/src/main/res/layout/item_grade_row.xml
libs/pandautils/src/test/java/com/instructure/pandautils/features/elementary/grades/GradesViewModelTest.kt

Test plan: 
- Verify that no quantitative data is shown on K5 grades when quantitative data is restricted.
- The progress should be hidden as well.
- Verify that everything works the same when quantitative data is not restricted.
- There was a slight API change what we also implemented in the Parent app, test that as well.
refs: MBL-16931

[MBL-16931][Student] K5 Grades LGO

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SyllabusE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SyllabusPage.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/CoursesApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt

Extend SyllabusE2E test with Syllabus/Summary tab display logic
Extend API with syllabusBody on non-subaccount seeding.
refs: MBL-16335

[MBL-16335][Student] - Extend SyllabusE2E test with Syllabus/Summary tab display logic

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt

Separate InboxE2ETest cases in both apps (Student and Teacher), and major refactor on them.
refs: MBL-16865

[MBL-16865][Student][Teacher] - Split up InboxE2E test case in both Apps

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/java/com/instructure/student/di/NavigationActivityModule.kt
apps/student/src/main/java/com/instructure/student/features/navigation/NavigationRepository.kt
apps/student/src/main/java/com/instructure/student/features/navigation/datasource/NavigationNetworkDataSource.kt
apps/student/src/test/java/com/instructure/student/features/navigation/NavigationRepositoryTest.kt
apps/student/src/test/java/com/instructure/student/features/navigation/datasource/GradesListNetworkDataSourceTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UserAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/viewmodel/LoginViewModel.kt
libs/login-api-2/src/test/java/com/instructure/loginapi/login/viewmodel/LoginViewModelTest.kt

Test plan: 
- Verify that when the user is in offline mode and logged in, we can open the app and the Dashboard will be displayed
- Verify that after an offline login we do a token check the first time the user goes online and if the token is expired we lof out the user.
- This can only be tested by disabling the cache (or waiting 1 hour after login), I have added a patch for this. [no_network_cache.patch](https://github.com/instructure/canvas-android/files/12557932/no_network_cache.patch)
refs: MBL-16877

[MBL-16877][Student] Keep user logged in while offline

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt

Use different type of module items in ModulesE2E test in Teacher app.
Extend test with publish/unpublish module and assert how the module items behave, and extend the test with open the module items and assert that their corresponding detailer page is displayed and loaded.
refs: MBL-16327

[MBL-16327][Teacher] - Use different type of module items in ModulesE2E test in Teacher app

---

libs/flutter_student_embed/lib/screens/calendar/planner_fetcher.dart

refs: MBL-17032
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/bdf73686-175f-4f3e-a28a-be3ef0282253" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/196e873f-c914-43c3-8936-23276803b8b6" maxHeight=500></td>
</tr>
</table>

[MBL-17032][Student] Student receives an error trying to view their current calendar

---

apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_percentage_dialog.dart

[MBL-17138][Parent] Manage Students settings dialogs are overlapping

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/offlinecontent/OfflineContentViewModel.kt

Test plan: Check select/deselect logics (it's in the OfflineContentFragment class, updateMenuText method) that it works well.
refs: MBL-17152
<table>
<tr>
<td><img width="362" src="https://github.com/instructure/canvas-android/assets/92309696/0dabfb39-f1da-4ed5-a77e-44b955e9c03d" height=800></td>
<td>
</tr>
</table>

[MBL-17152][Student] - Fix burnt in selectedCount (to 0) to get it from the coursesData

---

apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_screen.dart

[MBL-17151][Parent] Manage Student notification dialog new value does not refreshed in list when it's 'Never'

---

apps/flutter_parent/lib/models/course_grade.dart

[MBL-17175][Parent] Users are seeing error "Uh oh! We're not sure what happened" when opening app or viewing grades

---

apps/student/src/main/java/com/instructure/student/activity/SettingsActivity.kt
apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt

refs: MBL-17184
release note: Fixed a bug where the theme of the settings page would not update.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/fd3424d0-d9a7-443d-90a8-c29bc47b137b"></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/427fe128-1469-4e26-b47c-3cb8f8cf0413"></td>
</tr>
</table>

[MBL-17184][Student] Apply theme to settings fragment onConfigChange

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/LtiLaunchFragment.kt

refs: MBL-17189
release note: Fixed a bug where some LTI tools would not open.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/7ec163a1-536e-4381-bb99-630e4f668d30"></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/e8b0af46-4ca8-47e8-ab2f-15f1780dfbc3"></td>
</tr>
</table>

[MBL-17189][Teacher] Launch LTI tools with id

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineCourseBrowserE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncProgressE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncSettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/utils/OfflineTestUtils.kt
automation/espresso/build.gradle
automation/espresso/src/main/AndroidManifest.xml
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt

java.net.UnknownHostException: Unable to resolve host "http-inputs-inst.splunkcloud.com": No address associated with hostname
Probably the issue was that the device was offline when the test has failed so it cannot open the connection for the Splunk URL.

Nightly - Offline - Attempt to fix CI UnknownHostException.

---

apps/flutter_parent/lib/screens/account_creation/account_creation_interactor.dart
apps/flutter_parent/lib/screens/settings/legal_screen.dart
apps/flutter_parent/test/screens/account_creation/account_creation_interactor_test.dart
apps/flutter_parent/test/screens/settings/legal_screen_test.dart
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
apps/student/src/main/java/com/instructure/student/dialog/LegalDialogStyled.kt
apps/teacher/src/main/java/com/instructure/teacher/dialog/LegalDialog.kt

Change the Privacy Policy URL from "https://www.instructure.com/canvas/privacy" to "https://www.instructure.com/privacy-security", since it seems like it has changed on the web and the old one only has alias on it.
Test plan: Check if the changed URL works in all the apps.
refs: MBL-17256
release note: Change Privacy Policy URL in all apps.

[MBL-17256][All] - Change the Privacy Policy URL

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PeopleListPage.kt

Extend PeopleE2ETest with filter by (user) groups.
Seed user groups and assign student to them.
refs: MBL-17041

[MBL-17041][Teacher] - Extend People E2E test with filter by (user) groups

---

apps/student/src/main/java/com/instructure/student/dialog/EditTextDialog.kt
apps/student/src/main/java/com/instructure/student/features/files/list/FileListFragment.kt

Test plan: Smoke test file renaming and edit username dialogs.
Add Selection to EditTextDialog (it's used in profile settings as well).
Request focus to make the selection visible for users.
Handle that folder names (which does not contain '.' character) should be entirely selected.
refs: MBL-1725
release note: Add selection to file name within the file renaming dialog and profile settings edit username dialog

[MBL-17250][Student] - Add Selection to the EditTextDialog

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AnnouncementAPI.kt

refs: MBL-17258
release note: Fixed an issue where announcements wouldn't load when there is more than 100.

[MBL-17258][Student] Courses with over 100 announcements fail to load

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLeftSideMenuE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLoginE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTestExtensions.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/FileFolderApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/FileUploadsApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/CourseFolderUploadApiModel.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/CourseRootFolderApiModel.kt

Implement E2E Offline test for student course Files.
Implement API to generate course files.
Move 'device' to StudentTest class. (in later tickets it will be refactored for the existing offline tests to use this same object).
Add COURSE_FILE as new file upload type.
Refactor uploadTextFile method to handle course files as well.
Add different wait types/methods to some flaky tests for further monitoring which is the most
stabile.
refs: MBL-17121

[MBL-17121][Student] - Create Offline E2E test for Course Files

---

apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListEffectHandler.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListModels.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListUpdate.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt
apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListEffectHandlerTest.kt
apps/teacher/src/test/java/com/instructure/teacher/unit/modules/list/ModuleListUpdateTest.kt
libs/pandares/src/main/res/values/strings.xml

Test plan: See ticket for design. Test if the correct snackbar shows for every event. The 'Can't publish...' snackbars are blocked by api changes, we'll revisit them when the apis are ready.
refs: MBL-17278

[MBL-17278][Teacher] Bulk module update snackbars

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAllCoursesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineCourseBrowserE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLeftSideMenuE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLoginE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncProgressE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/utils/OfflineTestUtils.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/usergroups/UserGroupFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt

Extract common parts of the Offline E2E tests.
(Dashboard notification waiting after sync, waiting after turn off the network, extract UIDevice to StudentTest base class).
refs: MBL-17331

[MBL-17331][Student] - Extract common parts of the Offline E2E tests

---

apps/student/src/main/java/com/instructure/student/features/coursebrowser/CourseBrowserFragment.kt
apps/student/src/main/java/com/instructure/student/features/pages/details/PageDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/features/pages/list/PageListFragment.kt
apps/student/src/main/java/com/instructure/student/util/TabHelper.kt

Test plan: Test with a front page as the 'Home' of a course. Smoke test some other 'Home' settings and the Pages tab itself.
Fix front page issue by passing homePageTitle as the parameter for the TabHelper.getRouteByTabId method (null safely).
refs: MBL-17356
release note: Front Page title fixed when navigating from Course Browser by 'Home'.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/92309696/8c268b44-4f68-4ddc-bee0-d9c2752cfec2" height=800 width=1400></td>
<td><img src="https://github.com/instructure/canvas-android/assets/92309696/dba991c3-8824-4f05-a8e7-5c93b1bd54bd" height=800 width=1400></td>
</tr>
</table>

[MBL-17356][Student] - Fix front page title bug when navigating to front page from CourseBrowser 'Home'

---

apps/flutter_parent/lib/screens/courses/courses_screen.dart
apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
apps/flutter_parent/test/screens/courses/courses_screen_test.dart

refs: MBL-17371
release note: Added percentage to course grade.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/90d57beb-cb2a-4176-9deb-90d2538ca9ff" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/4e2c1d98-96d4-4fd5-9a47-52894d9a2991" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/d3014180-269e-4ca8-827e-1ac920717a15" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/109959688/ee60c646-d975-47c4-a09a-f41de306aa81" maxHeight=500></td>
</tr>
</table>

[MBL-17371][Parent] Grades page displays letter grade with no percentage

---

apps/student/src/main/java/com/instructure/student/activity/InterwebsToApplication.kt
apps/student/src/main/res/layout/interwebs_to_application.xml
apps/teacher/src/main/java/com/instructure/teacher/activities/RouteValidatorActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/features/login/TeacherLoginNavigation.kt
apps/teacher/src/main/res/layout/activity_route_validator.xml
libs/pandautils/src/main/java/com/instructure/pandautils/binding/ViewBindingDelegate.kt

Test plan: In the ticket. Test both the Teacher and the Student app. Also smoke test the behavior with normal login and smoke test WebViews that need authentication (for example quizzes)
refs: MBL-17327
release note: Fixed a bug where embedded media prompts for authentication after QR login.

[MBL-17327][Student][Teacher] Embedded media content prompts for authentication when logged in via QR login

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/notification/preferences/NotificationPreferencesViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/notification/preferences/PushNotificationPreferencesViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/notification/preferences/PushNotificationPreferencesViewModelTest.kt

refs: MBL-17325
release note: Updated push notification categories.

[MBL-17325][Student] Unsupported push notifications can be toggled

---

apps/student/flank_e2e_offline.yml
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/ManageOfflineContentE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAllCoursesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAnnouncementsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineCourseBrowserE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDashboardE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLeftSideMenuE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineLoginE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePagesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflinePeopleE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncProgressE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyncSettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/offline/SyncProgressPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt

Fix breaking Offline E2E tests.
4 Offline E2E successful runs in a row:
https://app.bitrise.io/build/79201f49-dc2e-4b45-a745-d730105a0caa
https://app.bitrise.io/build/a1b9ba9d-9647-4541-983a-500cd57f7722
https://app.bitrise.io/build/7b33d1b9-b520-4d74-949f-3708c09b1dc7
https://app.bitrise.io/build/61035303-3d8d-4cfa-8c44-cede07dd9e26
refs: MBL-17419

[MBL-17419][Student] - Fix breaking Offline E2E tests

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt

Test plan: Expand/collapse animation should trigger when swiping on the calendar. When the expand is disabled the swipe should have no effect either.
refs: MBL-17391

[MBL-17391][Student] Calendar swipe animation

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ProgressPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
automation/espresso/src/main/kotlin/com/instructure/espresso/ScreenshotTestRule.kt

Implement Bulk Module Update E2E test.
Add and refactor some methods in (Composable) ProgressPage.
Note: File module item actions will be implemented in a separate test case in a separate ticket.
refs: MBL-17280

[MBL-17280][Teacher] - Implement Bulk Update Modules E2E Test

---

libs/pandautils/src/main/java/com/instructure/pandautils/compose/CanvasTheme.kt

I also added the `TextSelectionColors` that was already added to the theme on the calendar branch.
Test plan: Check the letter spacing on the module publish progress screen.
refs: MBL-17930

[MBL-17390][Student][Teacher] Fix Compose fonts

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SchedulePage.kt

Fix scheduleE2ETest (breaking since Compose UI test dependency was imported. ViewInteraction evaluations became slower)

Fix scheduleE2ETest

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/GoToQuizPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/PageDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt

Test previous and next arrows in Student ModulesE2ETest.
Add new page objects.
Minor refactor on existing logic.
Implement ModuleItemInteraction to the corresponding Student module item pages.
refs: MBL-17384

[MBL-17384][Student] - Test previous and next arrows in Student Modules E2E Test

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxFragment.kt
libs/pandautils/src/main/res/layout/fragment_inbox.xml

[MBL-17441][Student] Inbox filter string can be barely seen after changing from dark to light mode

---

apps/student/src/main/java/com/instructure/student/fragment/ToDoListFragment.kt

refs: MBL-17438
release note: Fixed a bug where some group discussions wouldn't open from the To Do list.

[MBL-17438][Student] Graded Group Discussions Fail to Launch from To-Do List for Students Outside the First Group

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/worker/FileUploadWorker.kt

Test plan: To reproduce the issue you need to break the last API request that we make when uploading a file from the share extension (that adds the submission and attaches the file). Also smoke test the share extension.
refs: MBL-17375

[MBL-17375][Student] Investigate why submission is not in SpeedGrader

---

apps/teacher/src/main/java/com/instructure/teacher/di/CalendarModule.kt
apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRepository.kt
apps/teacher/src/test/java/com/instructure/teacher/features/calendar/TeacherCalendarRepositoryTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FeaturesAPI.kt

Test plan: Increase the calendar context limit in the account settings and check the filter limit in the Teacher app, it should be 20 now. This only works on beta currently.
refs: MBL-17498

[MBL-17498][Teacher] Added request for calendar context limit feature.

---

apps/student/src/main/java/com/instructure/student/features/discussion/details/DiscussionDetailsFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionUtils.kt

Test plan: See ticket. If offline initials should load instead of profile picture.
refs: MBL-17186
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/12711295-5118-4231-af73-b3e2338bf1b5" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/7bd10ab6-b0b5-4ca8-b1c7-d39bffe8ae1b" maxHeight=500></td>
</tr>
</table>

[MBL-17186][Student] Show initials on discussions if offline 

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterScreenUiState.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/filter/composables/CalendarFilterScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/filter/CalendarFilterViewModelTest.kt

Test plan: Select all button should not be present in the Teacher app when nothing is selected, because of the filter limit. Smoke test the Student filters also.
refs: MBL-17537

[MBL-17537][Teacher] Remove select all option from the calendar

---

apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRepository.kt
apps/teacher/src/test/java/com/instructure/teacher/features/calendar/TeacherCalendarRepositoryTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt

Note: I also fixed the RCE focus issue here, where you open the create event screen and it scrolls down to the bottom when the screen is scrollable.
refs: MBL-17582

[MBL-17582][Student][Teacher] Show no items when no filter is selected

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/compose/CalendarE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentComposeTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/TeacherCalendarToDoDetailsPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/compose/CalendarE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherComposeTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/ToDoDetailsInteractionTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarEventCreateEditPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarEventDetailsPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarScreenPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoCreateUpdatePage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoDetailsPage.kt
libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/CanvasThemedAppBar.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt

Implement Calendar To Do E2E test cases in both apps.
Add some Page Object classes.
Add some testTags.
Minor refactor (rename some methods and classes to clarify possible future confusion).
refs: MBL-17268

[MBL-17268][Student][Teacher] - Implement Calendar To Do E2E test cases in both apps

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarStateMapper.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/Calendar.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarStateMapperTest.kt

Test plan: Check if the first day of the calendar is set according to the correct locale. You need to set the locale in the user settings in Canvas, can be done on the web.
refs: MBL-17593

[MBL-17593][Student][Teacher] Localize calendar week first day

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/GroupManager.kt
libs/pandautils/src/main/java/com/instructure/pandautils/views/RecipientChipsInput.kt

Test plan: In the ticket. Smoke test the same functionality in the Teacher app. This change affects that as well since that part of the Inbox screen is shared.
refs: MBL-17608

[MBL-17608][Student][Teacher] Students without permissions can message entire sections by typing section name

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadDialogViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/file/upload/FileUploadUtilsHelper.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/file/upload/FileUploadViewModelTest.kt

refs: MBL-17641
release note: Fixed a bug where some temporary files would not be deleted.

[MBL-17641][Student][Teacher] Delete temp files when removed from file upload

---

apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt

refs: MBL-17648
release note: Fixed a bug, where the Dashboard would not load properly on the first app start.
<table>
<tr>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/75c5ced1-99eb-4221-b6eb-66d1e57dd72e" maxHeight=500></td>
<td><img src="https://github.com/instructure/canvas-android/assets/72087159/f5750d3e-1f59-45b4-90dd-aa25f4c6a4db" maxHeight=500></td>
</tr>
</table>

[MBL-17648][Teacher] Reload Dashboard on notifications permission

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AnnouncementsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DiscussionsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineAnnouncementsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineDiscussionsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AnnouncementInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/StudentCalendarInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/offline/NativeDiscussionDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/TeacherCalendarPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsDetailsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/NativeDiscussionsDetailsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/DiscussionTopicsApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/DiscussionApiModel.kt
automation/espresso/src/main/kotlin/com/instructure/espresso/TestingUtils.kt

Major refactor on E2E tests to handle new discussion redesign as default in both the Teacher and Student apps.
Rename, restructure some page objects.
Add some util functions.
Separate native and web view based Discussion Details Page.
refs: MBL-17668

[MBL-17668][Student][Teacher] -  Refactor E2E tests to handle new discussion redesign as default

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CalendarEventAPI.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventRepository.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventUiState.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendarevent/createupdate/CreateUpdateEventRepositoryTest.kt

Test plan: In the ticket. The description might be a bit confusing, but the real issue is editing one occurrence from a recurring event. That should be working now. + Smoke test event editing in both apps.
refs: MBL-17691
release note: Fixed an issue where editing a single occurrence in a recurring event would show an incorrect error message.

[MBL-17691][Student][Teacher] Recurrence edit does not consider the previous change in the calendar

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadModels.kt
apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadUpdate.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadEffectHandlerTest.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadUpdateTest.kt

[MBL-17710][Student] Fixed 'File upload dialog remembers index of deleted file'

---

apps/student/src/main/java/com/instructure/student/mobius/common/ui/MobiusFragment.kt

Test plan: Test config change (for example split-view) on all the mobius screens (all the screens related to submissions and observer pairing). 
refs: MBL-17764
release note: Fixed a crash on the submission details screen.

[MBL-17764][Student] Submission details crashes

---

apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsFragment.kt
apps/student/src/main/java/com/instructure/student/features/assignments/details/AssignmentDetailsViewModel.kt
apps/student/src/test/java/com/instructure/student/features/assignmentdetails/AssignmentDetailsViewModelTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileExtensions.kt

refs: MBL-17736
release note: Fixed a bug, where Studio submission was allowed incorrectly.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/301a59a3-20e9-4aa8-b09d-7f4beb3c65ac" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/9cb2f93c-5c0b-496c-8653-77717f814cb5" maxHeight=500></td>
</tr>
</table>

[MBL-17736][Student] Hide Studio submission type if video file submission is not allowed

---

apps/student/src/main/java/com/instructure/student/features/modules/progression/LockedModuleItemFragment.kt
apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/fragments/HtmlContentFragment.kt

Test plan: In the ticket. The change that caused that issue was introduced in this PR: https://github.com/instructure/canvas-android/pull/325. Since then Google Drive LTI has changed and it works on my sandbox, but you can double check with yours as well. By the way the change introduced in the mentioned PR does not work on the old Google Drive LTI anymore (the one example that is linked in the ticket).
refs: MBL-17741
release note: Fixed an issue where embedded Kaltura videos wouldn't show on pages.

[MBL-17741][Student] Embedded Kaltura playlist video's do not show on Pages.

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt

Attempt to stabilize letter grade related tests on nightly by repeating the refresh and assert flow after the api call with an increasing delay up to maximum 4 sec.

[Student]  - Nightly: Stabilize Letter Grade Only related E2E tests

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizListFragment.kt

refs: MBL-17719
release note: Fixed a bug, where opening a Quiz from the Quiz list screen would navigate to the wrong destination.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/74f9b6f9-ad25-4550-a146-dcbcaa97792b" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/b43959bc-99f5-4bbe-9202-55e5dde893d9" maxHeight=500></td>
</tr>
</table>

[MBL-17719][Teacher] Route to quiz details from quiz list

---

apps/parent/src/main/java/com/instructure/parentapp/features/login/ParentAcceptableUsePolicyRouter.kt

Test plan: Test the AUP screen, should work like in the production version. The policy details cannot be opened yet, it depends on other tickets.
refs: MBL-17611

[MBL-17611][Parent] AUP screen

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SyllabusE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyllabusE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SyllabusInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SyllabusPage.kt

Implement Offline Syllabus E2E Test.
Implement Assignment base Syllabus interaction test.
Add asserting to toolbar title and course name on Syllabus page. (add this assertion to existing 'online' Syllabus E2E Test as well).
refs: MBL-17387

[MBL-17387][Student] - Implement Offline Syllabus E2E Test

---

apps/teacher/src/main/java/com/instructure/teacher/features/assignment/details/AssignmentDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRouter.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CalendarInteractionTest.kt

Test plan: Check that assignments and discussions route correctly on tablet.
refs: MBL-17776
affects: Techer
release note: Fixed an issue where assignments and discussions wouldn't open from the calendar on tablets.

[MBL-17776][Teacher] Assignments and discussions not opening from the Calendar on tablet

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/offline/sync/CourseSync.kt

refs: MBL-17787
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/3df7d1cb-83f4-4d86-b08a-4482f65e1847" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/47b3c750-f4fa-41ea-be55-be266fe1fe7d" maxHeight=500></td>
</tr>
</table>

[MBL-17787][Student] Fetch course settings during offline sync

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyllabusE2ETest.kt

Remove KnownBug annotation from Offline Syllabus E2E test (as the bug has been fixed yet).

Remove KnownBug annotation from Offline Syllabus E2E test

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/offline/OfflineSyllabusTestE2E.kt

Enroll user as student in student pronounE2ETest.
Change Offline Syllabus file.
Successful e2e-offline-standalone test run: https://app.bitrise.io/build/e0a5c00d-428c-4fec-849a-c5ffbea0177b
Successful e2e-standalone test run: https://console.firebase.google.com/project/delta-essence-114723/testlab/histories/bh.51e9e887f5fb835f/matrices/5183340710908906592/details?stepId=bs.d1229033c4e5e64b&testCaseId=3 (only testSubscribeToCalendar is failing and it's not related to these changes at all).

Fix E2E tests (Student pronoun test and offline syllabus test)

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/ConferenceDetailsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/ConferenceListPage.kt

Extend Conferences E2E test. (Asserting toolbar titles,subtitles, openexternally button, description, type)
refs: MBL-16939

[MBL-16939][Student] - Extend Conferences E2E test

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxMessagePage.kt

Refactor InboxE2E tests in both the Student and Teacher app to assert that making a conversation unread in the 'Archived' filter will dismiss it from the 'Archived' list.
refs: MBL-17733

[MBL-17733][Student][Teacher] - Add 'making an archived conversation unread' process to Inbox E2E tests

---

apps/teacher/src/main/java/com/instructure/teacher/features/assignment/submission/AssignmentSubmissionListFragment.kt

refs: MBL-17822
release note: Fixed a bug, where not the correct student's submission was opened in SpeedGrader in some cases.

[MBL-17822][Teacher] Filtering submissions by section doesn't open the correct students submission

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewUnsupportedFileFragment.kt

This bug was related to the Samsung HTML Viewer application.
When files are retrieved from a FileCache, their names and extensions are replaced with IDs. Since some external applications may rely on this information, we can rename the retrieved files to their original names and extensions so they will be accessible to external applications as well.
Test plan:
- Upload an XML file to user Files
- Open it from the Teacher app with the default Samsung HTML Viewer
refs: MBL-17828
release note: XML files can be opened from user Files
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/a66aede8-275c-40ed-90ac-634c2aec90f4" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/65fba82f-d8ec-4407-b276- …

[MBL-17828][Teacher] Cannot open XML files

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsDetailsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsListPage.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/DiscussionTopicsApi.kt
automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/DiscussionApiModel.kt

Extend DiscussionE2E test with testing the Close/Open for Comments filter and replies on the new discussion webview.
Add the API methods for seeding (replies/entries).
refs: MBL-17687

[MBL-17687][Teacher] - Extend DiscussionE2E test with replies and close/open for comments filtering

---

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt

Refactor Discussion E2E test according to MBL-17823 changes:
- Closed for Comments renamed to Close for Comments
- Empty filter groups disappear automatically

Refactor Discussion E2E test according to MBL-17823 bug changes

---

apps/flutter_parent/lib/network/api/course_api.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_interactor.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart
apps/flutter_parent/test/screens/assignments/assignment_details_interactor_test.dart
apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
apps/flutter_parent/test/utils/test_helpers/mock_helpers.mocks.dart

Test plan:
- Turn assignment enhancements off.
- Create an assignment, submit an attempt, add a grade.
- Open the parent app and go to the assignment and view the submission.
- Submission viewer should show the attempt.
- Close the window.
- Turn assignment enhancements on.
- Pull to refresh the parent app's assignment screen.
- Open the submission viewer.
- Submission viewer should still show the attempt.
refs: MBL-17860
release note: Add support to submission viewer to properly display for non-enhanced assignments.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/c43d7f04-5e19-4824-94bf-725b1945f0c8" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/69822315-4615-43b5-acd6-d32fb282fbfc" …

[MBL-17860][Parent] Support submission view in case assignment enhancement is not enabled

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt

Update colors according to new color palette in dark mode E2E tests in both apps.

Update colors according to new color palette in dark mode E2E tests

---

apps/student/src/main/java/com/instructure/student/features/files/details/FileDetailsFragment.kt
apps/student/src/main/res/layout/fragment_file_details.xml
apps/student/src/main/res/layout/viewholder_discussion_group_header.xml

Test plan:
- Check file details screen on mobile landscape when file is locked
- Check file details screen on mobile landscape when file is not locked
- Check discussion list on dark mode
refs: MBL-17786
affects: student

[MBL-17786][Student] UI glitches

---

apps/student/build.gradle
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PushNotificationsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/PushNotificationsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt
apps/teacher/build.gradle
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PushNotificationsE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PushNotificationsPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
libs/pandautils/src/main/res/layout/fragment_notification_preferences.xml

Implement E2E Tests for Push Notifications screen UI checks in both apps.
Add new page objects.
Add some ids.
Add dedicated users' vault variables to build gradle and use them in tests.
refs: MBL-17379

[MBL-17379][Student][Teacher] - Implement E2E Tests for Push Notifications UI

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/e2e/usergroups/UserGroupFilesE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ShareExtensionInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/UserFilesInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileChooserPage.kt
apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt

Implement E2E test case for uploading to 'global' files.
Also, covering a bug to try to add and remove multiple times to see if a "counter" is displayed in the file name, because it shouldn't).
Rename FileUploadPage to FileChooserPage as it is actually the file chooser dialog.
Add some page object methods and assertions.
refs: MBL-17761

[MBL-17761][Student] - Implement E2E test case for uploading to 'Global' Files

---

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/InboxConversationInteractionTest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt
apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt
apps/student/src/main/java/com/instructure/student/holders/InboxMessageHolder.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxMessagePageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxMessagePage.kt
apps/teacher/src/main/java/com/instructure/teacher/adapters/MessageAdapter.kt
apps/teacher/src/main/java/com/instructure/teacher/binders/MessageBinder.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/MessageThreadFragment.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Conversation.kt

Test plan: Intercept and edit response body when fetching conversation details, add field cannot_reply=true
refs: MBL-17827
release note: Reply button is removed for messages where reply is disabled
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/cf6565ba-b204-4b38-8acf-e3be9ddd325f" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/c3a9e27b-be68-4531-8769-2286a38864ca" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0ca99783-4610-4bb6-8c78-5ed18476a5df" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/385e2783-58ee-43e5-9086-e1f5ef5e5f25" maxHeight=500></td>
</tr>
</table>

[MBL-17827][Student][Teacher] Removed reply button for messages where reply is disabled

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/HelpLinks.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/help/HelpDialogViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/help/HelpDialogViewModelTest.kt

Test plan: Open Help dialog on beta environment.
refs: MBL-17938
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/52876f8f-0c09-46dc-9c32-717ec5685d33" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/d09bbf0d-dea7-4c63-958c-dbaa02103914" maxHeight=500></td>
</tr>
</table>

[MBL-17938] [Student] Make HelpLinks class attributes nullable

---

apps/student/src/main/java/com/instructure/student/features/assignments/reminder/CustomReminderDialog.kt

refs: MBL-17974
release note: Handle 0 value in assignment reminder custom dialog

[MBL-17974][Student] - Handle 0 value in assignment reminder custom dialog

---

apps/flutter_parent/lib/models/assignment.dart
apps/flutter_parent/lib/models/assignment.g.dart
apps/flutter_parent/lib/screens/courses/details/course_details_model.dart
apps/student/src/main/java/com/instructure/student/features/grades/GradesListRepository.kt
apps/student/src/test/java/com/instructure/student/features/grades/GradesListRepositoryTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ObserveeAssignment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/GradesViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/AssignmentGroupExtensions.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/grades/GradesViewModelTest.kt

refs: MBL-17945
release note: Hidden New Quizzes are now not displayed in the Grades list
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/294f397d-3a34-407a-9cf8-7fd562fdc4c0" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/8209b2d6-84f0-41d3-b278-23f01c434941" maxHeight=500></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/dfd0e6e5-55a4-4785-86fd-98925941e23e" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/f52472a9-ca5f-4469-9a13-1cd9f1fd1f66" maxHeight=500></td>
</tr>
</table>

[MBL-17945][Student][Parent] Filter hidden New Quizzes in the Grades list

---

apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt
apps/student/src/main/java/com/instructure/student/holders/NotificationViewHolder.kt
apps/student/src/main/java/com/instructure/student/widget/NotificationViewWidgetService.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/StreamItem.kt

refs: MBL-17987
release note: Fixed a bug where discussion mention alerts couldn't be opened.

[MBL-17987][Student] Clicking alerts regarding a Discussion mention gives an error

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AnnouncementsE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/QuizListPageTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizListPage.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt

Extend Quizzes E2E test with searching
refs: MBL-16952

[MBL-16952][Teacher] - Extend Quizzes E2E test with searching

---

automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateEventInteractionTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/CreateUpdateToDoInteractionTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarEventCreateEditPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/CalendarToDoCreateUpdatePage.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendarevent/createupdate/composables/CreateUpdateEventScreen.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendartodo/createupdate/composables/CreateUpdateToDoScreen.kt

Test plan: See ticket. The save button should be disabled if the title is blank.
refs: MBL-18072
release note: Fixed a bug, where calendar events could be saved with a blank title.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/b275256a-24ad-453a-afc3-67497ca9544e" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/5f1c7301-2c5f-4400-974b-c1a06f77325e" maxHeight=500></td>
</tr>
</table>

[MBL-18072][All] Disable save button when event/todo title is blank

---

apps/flutter_parent/lib/screens/login_landing_screen.dart
apps/flutter_parent/lib/screens/web_login/web_login_screen.dart

Test plan: Use the user credentials from the ticket.
1. Login to the Canvas domain.
2. Log out 
3. Select the last school's login button
4. Proper Canvas login page should be visible
Previously auth provider handling wasn't correct in the Parent app and domain's AuthProvider wasn't saved. Now it's fixed with this PR, but the last domain's shortcut button won't work immediately because of the missing information. You have to search for the domain in the Find my school list and login. After the relogin the last school's shortcut button will work properly.
refs: MBL-18081
release note: Login providers are now properly handled at the last domain's button.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/87dc3611-0e1c-4 …

[MBL-18081][Parent] Fix last domain handling

---

apps/student/src/androidTest/java/com/instructure/student/di/TestApplicationModule.kt
apps/student/src/androidTest/java/com/instructure/student/espresso/fakes/FakeEnabledTabs.kt
apps/student/src/main/java/com/instructure/student/di/ApplicationModule.kt
apps/student/src/main/java/com/instructure/student/router/EnabledTabs.kt
apps/student/src/test/java/com/instructure/student/router/EnabledTabsTest.kt

Test plan: Test multiple tab and details screen navigations in the Student application. Test if both enabled and disabled tabs are handled properly. Try out cross course references as well.
I've created a navigation description to easily test it: /assignments/Navigation assignment. Please don't modify my sandbox's settings, test other configurations in your own sandbox.
refs: MBL-18106

[MBL-18106][Student] Cross course tab reference handling fix

---

apps/parent/src/main/java/com/instructure/parentapp/features/calendar/ParentCalendarRepository.kt
apps/parent/src/test/java/com/instructure/parentapp/features/calendar/ParentCalendarRepositoryTest.kt
apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/UpdateFilePermissionsPage.kt
apps/teacher/src/main/java/com/instructure/teacher/features/calendar/TeacherCalendarRepository.kt
apps/teacher/src/test/java/com/instructure/teacher/features/calendar/TeacherCalendarRepositoryTest.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FeaturesAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/EnvironmentSettings.kt

Test plan: In the ticket. The new Parent app should be tested as well.
refs: MBL-18132
release note: Fixed an issue where only 10 calendars could be selected.

[MBL-18132][Teacher] Fixed calendar context limit api change

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditFileFolderFragment.kt
apps/teacher/src/main/res/values/strings.xml

Test plan:
- In the Teacher app, select a module, go to files, and open the edit dialog on a file
- Set file name to blank or add only whitespaces to title
- Error message should be shown, file should not be saved
refs: MBL-18160
release note: Fixed an issue where a file could be renamed to blank.

[MBL-18160][Teacher] Edit file empty title bug fixed

---

apps/flutter_parent/lib/models/assignment.dart
apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart

Test plan: See ticket for the Flutter Parent app. 
refs: MBL-18183
release note: Remove Missing label for assignments with No Submission type.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/4c077969-341c-4ae1-83fe-809cd8218f96" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/e7262920-b1c3-455e-a5d8-b86c2ea527b4" maxHeight=500></td>
</tr>
</table>

[MBL-18183][Parent] Fix no submission assignments label

---

apps/teacher/src/main/res/layout/navigation_drawer.xml

- Note that the options headline had been excluded from accessibility as it's just a decorative item. The same solution had been used as the Student app.
refs: MBL-18257

[MBL-18257][Teacher][A11y] Fix navigation drawer accessibility

---

apps/student/src/main/java/com/instructure/student/features/coursebrowser/CourseBrowserFragment.kt
apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt

Test plan: 
- If color overlay is disabled the smart search icon should still be visible.
- Elementary view should load the smart search in a webview.
refs: none

Fix Smart Search

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt

RC finding: When selecting a recipient on the inbox compose message screen, and then change the course to a course in which that recipient is not in, the recipient name will remain in the recipient list, However the 'send' button will remain disabled (which prevents the user from sending messages to a particular course with recipients who are not enrolled to that course and it's good), but on the UI it could be misleading.

Fix inbox recipients update

---

libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/inbox/compose/ContextPickerScreenTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/compose/composables/SelectContextScreen.kt

Test plan: Open Student app, go to Inbox, select New Message FAB, tap course selector. Favorite and other courses are grouped.
refs: MBL-18565
release note: Favorite and other courses are grouped in Course selector in Inbox screen
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/55405dfe-58ac-41d0-9821-dc707d59d4d5" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/ac9c6353-b42d-4620-854e-070a7e5ea35c" maxHeight=500></td>
</tr>
</table>

[MBL-18565][All] Inbox course selector grouping

---

apps/parent/src/test/java/com/instructure/parentapp/features/inbox/compose/ParentInboxComposeRepositoryTest.kt
apps/student/src/test/java/com/instructure/student/features/inbox/compose/StudentInboxComposeRepositoryTest.kt
apps/teacher/src/test/java/com/instructure/teacher/features/inbox/compose/TeacherInboxComposeRepositoryTest.kt
libs/pandares/src/main/res/values-en/strings.xml
libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/inbox/compose/RecipientPickerScreenTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeRepository.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/RecipientPickerScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt

- Note that there is currently a bug in the recipient picker where the search field is not reset after closing the picker. This has already been fixed on the release branch but has not yet been merged back.
refs: MBL-17866
release note: Inbox recipient picker search field is now aware of the selected role.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/da6fb650-e4ff-4273-8775-04a944b24ead" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/1aeab7b9-4468-4057-906b-2adaa62bc87a" maxHeight=500></td>
</tr>
</table>

[MBL-17866][All] Change Inbox recipient search behavior

---

apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsScreen.kt

[MBL-18604] 'Save' button disabled state on alert settings dialog is not accessible in dark mode

---

apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsViewModel.kt

[MBL-18603][Parent] Tapping Alert Settings toggles too fast may can result 'unexpected error' bottom message

---

apps/parent/src/main/java/com/instructure/parentapp/features/grades/ParentGradesRepository.kt
apps/parent/src/test/java/com/instructure/parentapp/features/grades/ParentGradesRepositoryTest.kt

refs: MBL-18583
release note: Fixed a bug where assignments with 'Not Graded' type would be visible on Grades.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/1669f334-7c34-41ce-abe6-c83253d14392" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/c1e14f52-9f93-4385-b8df-e8f6b1e78bfb" maxHeight=500></td>
</tr>
</table>

[MBL-18583][Parent] Hide 'Not Graded' assignments from Grades

---

apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewExtensions.kt

Test plan:
- I fixed the issue with the quiz opening by showing a dialog on the quiz screen and then redirecting back.
- The other issue with the pages is a special case, it seems like the page was already renamed and it's embedded in the syllabus with the old link (page links are generated from the pages name). Somehow the API can handle these redirects, but it's impossible to handle this offline. This should be a rare case, and we won't fix it.
refs: MBL-18571

[MBL-18571][Student] Fix quiz opening from webview in offline.

---

apps/parent/src/main/java/com/instructure/parentapp/features/alerts/list/AlertsViewModel.kt
apps/parent/src/test/java/com/instructure/parentapp/features/alerts/list/AlertsViewModelTest.kt

Test plan: In the ticket. As we discussed on the Android meeting, undoing dismissed alerts will always mark the alerts as read.
refs: MBL-18623

[MBL-18623][Parent] Fixed undo mechanism in alerts.

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/details/InboxDetailsFragment.kt

Test plan: I couldn't reproduce the issue. This happens when the user tries to open a link from the inbox compose screen, but the phone does not have a browser app that would handle the opening of the link.
refs: MBL-18632

[MBL-18632][All] Inbox crash

---

apps/parent/src/androidTest/java/com/instructure/parentapp/ui/e2e/SettingsE2ETest.kt
apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardViewModel.kt
apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/InboxCountUpdater.kt
apps/parent/src/main/java/com/instructure/parentapp/features/main/MainActivity.kt
apps/parent/src/test/java/com/instructure/parentapp/features/dashboard/DashboardViewModelTest.kt
apps/parent/src/test/java/com/instructure/parentapp/features/dashboard/TestInboxCountUpdater.kt
apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt
apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewData.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxViewModelTest.kt

Test plan: 
- Open Student or Teacher app
- Go to Inbox
- Select multiple items
- Press Unread/Read/Delete
- Unread count should be updated immediately
refs: MBL-18569
release note: Inbox unread count badge is updated correctly

[MBL-18569][Student][Teacher] Unread count updated offline on batch operations

---

apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt
libs/pandares/src/main/res/values/colors.xml

[MBL-18587][Parent] In the Filter Tray of an assignment the "Grading Period" and "Sort" text does not meet contrast requirements

---

translations/import.rb

Test plan: I am not sure how we can test this now since we just updated the translations, but we can test this later when there are new translations available.
refs: MBL-18645
affects: -

[MBL-18645][All]Removed code where we skip the values-en string folder.

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt

Test plan: I couldn't reproduce the issue, so this might be a possible fix, we will monitor crashes after the new release.
refs: MBL-18630

[MBL-18630][Teacher] RecyclerView crash

---

apps/parent/src/androidTest/java/com/instructure/parentapp/ui/compose/alerts/details/AnnouncementDetailsScreenTest.kt
apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsFragment.kt
apps/parent/src/main/java/com/instructure/parentapp/features/alerts/details/AnnouncementDetailsScreen.kt

Test plan: In the ticket. Note: the link in the video still won't open, because it's a file link and custom tabs won't handle files, but any other link will open in a custom tab.
refs: MBL-18656

[MBL-18656][Parent] Added WebView callbacks to announcement details.

---

apps/parent/src/main/res/values/themes.xml
apps/student/src/main/res/values/themes_canvastheme.xml
libs/login-api-2/src/main/res/values/styles.xml
libs/pandares/src/main/res/values/colors.xml

Test plan:
- Open all 3 apps in dark mode and light mode selected
- Status bar should be readable in all cases
refs: MBL-18657
release note:

[MBL-18657][All] Fixed status bar color on app start

---

apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListEffectHandler.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListModels.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListUpdate.kt
apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt

I had to do this a bit hacky way, because of this legacy RecyclerView used here. There is no way that we can get the positions of the headers, so we just subtract one from the first item's position in it's group.
refs: MBL-18047

[MBL-18047][Teacher] Added option to navigate to module headers from links.

---

apps/parent/src/main/AndroidManifest.xml

Test plan: only test the email link, there was an other issue that got fixed on the release branch, the url-s are not gonna work until the release branch is merged back
refs: MBL-18668

[MBL-18668][Parent] Cannot open Gmail mailing app when clicking email link on Terms of Use page

---

apps/student/src/main/java/com/instructure/student/features/legal/StudentLegalRouter.kt
apps/teacher/src/main/java/com/instructure/teacher/features/legal/TeacherLegalRouter.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt

Test plan: In the ticket. Actually it's quite hard to reproduce this in the Student because once you login the terms of use is requested and it will be cached, so it will open correctly. In the teacher we only request it on the LegalDialog, so you can test there. Just go offline after a new login and before opening the legal dialog.
refs: MBL-18669

[MBL-18669][Student][Teacher] Terms of Use page 'Webpage not available'

---

automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/InboxComposeInteractionTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/composables/InboxComposeScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt

refs: MBL-18681
release note: The inbox compose message exit confirmation is now only displayed after changes have been made.

[MBL-18681][All] Compose message exit confirmation

---

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt
apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsUpdateTest.kt

refs: MBL-18680
release note: Quiz results can now be viewed for locked New Quizzes
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/6e026f30-0f03-4a4c-b20d-4bee9b2ba080" maxHeight=500></td>
<td><img src="https://github.com/user-attachments/assets/7c4c6504-01a5-4bac-9ebc-4a0a61ae3572" maxHeight=500></td>
</tr>
</table>

[MBL-18680][Student] Quiz results for locked New Quizzes

---

apps/parent/src/main/java/com/instructure/parentapp/features/courses/details/CourseDetailsScreen.kt

Test plan: test if course details screen compose message has the correct subject by tab 
refs: MBL-18747

[MBL-18747][Parent] CourseDetailsScreen crash fix

---

libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileDownloader.kt

Test plan: test file downloader on Android 9, Android 10 and Android 11+, it should work in all cases. (It can be tested downloading a file from Inbox or Announcement Details.)
refs: MBL-18748

[MBL-18748][Parent] FileDownloader.downloadFileToDevice permission error

---

apps/student/src/main/java/com/instructure/student/features/modules/list/ModuleListFragment.kt
apps/student/src/main/java/com/instructure/student/features/modules/progression/CourseModuleProgressionFragment.kt
apps/student/src/main/java/com/instructure/student/features/modules/util/ModuleProgressionUtility.kt
apps/student/src/main/java/com/instructure/student/util/CourseModulesStore.kt

Reason of the bug:
Previously empty list meant that the module's items hadn't been initialised. If a module had only a sub header which is not handled as valid module item the app got into an infinite loop as the list of module items was always empty.
Solution for the bug:
Differentiate uninitialised modules and empty modules with null values.
refs: MBL-18705

[MBL-18705][Student] Fix Module items continuously reload

---

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
apps/student/src/main/res/layout/activity_navigation.xml

release note: Removed unnecessary bottom divider.

Hide bottom divider when bottomnavbar is not visible

---

libs/pandautils/src/main/res/layout/fragment_assignment_details.xml

Test plan: Check if the loading indicator is present on Assignment Details.
refs: MBL-18782
release note: Fixed a bug where the Assignment Details screen had no loading indicator.

[MBL-18782][Student][Parent] Fix loading on Assignment Details

---

apps/student/src/main/java/com/instructure/student/router/EnabledTabs.kt
apps/student/src/test/java/com/instructure/student/router/EnabledTabsTest.kt

Test plan: See ticket. Should work with 'wiki' and 'pages'
refs: MBL-18786
release note: Fixed a bug where navigating to Pages did not work in some cases.

[MBL-18786][Student] Fix Pages enabled tabs routing.

---

automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/interaction/InboxListInteractionTest.kt

Fix breaking inbox interaction test in landscape mode conversations so the 'UNDO' message won't overlap the conversation).

Fix breaking inbox interaction test in landscape mode

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/DueDatesFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/fragments/EditQuizDetailsFragment.kt
apps/teacher/src/main/java/com/instructure/teacher/presenters/EditQuizDetailsPresenter.kt
apps/teacher/src/main/java/com/instructure/teacher/utils/AssignmentExtensions.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/AssignmentManager.kt
libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/postmodels/AssignmentPostBody.kt

Test plan: test edit assignment and quiz, I had to make some modification saving quiz details, it should be tested exhaustively
refs: MBL-18776
release note: It's possible now to remove even the last 'Assign To' block on Edit Assignment screen.

[MBL-18776][Teacher] Last assignment "assign to" cannot be deleted

---

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/CourseBrowserE2ETest.kt
apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PickerSubmissionUploadInteractionTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/SmartSearchPage.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/common/pages/compose/SmartSearchPreferencesPage.kt

Add assertion extension to SmartSearch E2E test for group counters.
refs: MBL-18662
release note:

[MBL-18662][Student] - Extend Smart Search E2E test with counter assertion

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxRepository.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxRepositoryTest.kt

refs: MBL-18840
release note: Fixed a bug where the wrong inbox signature would load in some cases.

[MBL-18840][All] Always fetch inbox signature from network

---

libs/pandautils/src/androidTest/java/com/instructure/pandautils/room/offline/daos/EnrollmentDaoTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/di/OfflineModule.kt
libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/daos/EnrollmentDao.kt
libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/CourseFacade.kt
libs/pandautils/src/main/java/com/instructure/pandautils/room/offline/facade/EnrollmentFacade.kt
libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/CourseFacadeTest.kt
libs/pandautils/src/test/java/com/instructure/pandautils/room/offline/facade/EnrollmentFacadeTest.kt

refs: MBL-18790
release note: Fixed a bug where the total grades would display incorrectly in offline mode.

[MBL-18790][Student] Only return enrollments for the current user in offline mode.

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/grades/gradepreferences/GradePreferencesUiState.kt

Test plan: in the ticket (comment)
refs: MBL-18842
release note: Updated grades filter icon behaviour.

[MBL-18842][Parent] Filter icon displays as 'empty' even though there is a filter selected but it's default

---

apps/parent/flank.yml
apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewData.kt
apps/parent/src/main/java/com/instructure/parentapp/features/addstudent/AddStudentViewModel.kt
apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsFragment.kt
apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsUiState.kt
apps/parent/src/main/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsViewModel.kt
apps/parent/src/main/java/com/instructure/parentapp/features/dashboard/DashboardFragment.kt
apps/parent/src/main/java/com/instructure/parentapp/features/managestudents/ManageStudentsFragment.kt
apps/parent/src/test/java/com/instructure/parentapp/features/addstudent/AddStudentViewModelTest.kt
apps/parent/src/test/java/com/instructure/parentapp/features/alerts/settings/AlertSettingsViewModelTest.kt
automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/UserEndpoints.kt

Test plan: test removing a student, mock an api error with proxy, see the error snackbar, then retry it without the api error.
refs: MBL-18873
release note: Fixed error handling when unpairing a student fails.

[MBL-18873][Parent] Fixed unpair student error handling

---

libs/login-api-2/src/main/res/values-en/strings.xml
libs/login-api-2/src/main/res/values/strings.xml
libs/pandares/src/main/res/values/strings.xml

Unify 'Report a problem' dialog title. (It was 'Report A Problem' in …Student and Teacher and we came to the conclusion with product that it should be 'Report a problem' in all 3 apps. Parent was already like this)
refs: MBL-18938
release note: Report a problem dialog title unified to 'Report a problem'.

[MBL-18938][Student][Teacher] - Unify 'Report a problem' dialog title

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/QLClientConfig.kt
libs/login-api-2/src/main/java/com/instructure/loginapi/login/tasks/LogoutTask.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/list/InboxRepository.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/list/InboxRepositoryTest.kt

Test plan: Test all cases, even what already worked since I came up with a complete different solution.
refs: MBL-18929
affects: Student, Parent, Teacher
release note: Fixed a caching issue related to inbox signature.

[MBL-18929][All] Inbox signautre loads previous user signature if composing message with any FAB button

---

libs/pandautils/src/main/AndroidManifest.xml
libs/pandautils/src/main/res/values/themes_canvasthemes.xml

refs: MBL-18914
release note: Fixed a minor UI glitch on profile picture crop screen.

[MBL-18914][Student][Teacher] The profile picture checkmark/X icons are hard to tap, and in landscape mode the checkmark can’t be tapped at all

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/legal/LegalDialogFragment.kt

refs: MBL-18918
release note: Showing 'No Internet Connection' dialog when clicking terms of use offline.

[MBL-18918][Student] Offline: 'Terms of Use' link should pop-up 'No Internet Connection' dalog instead of 'Webpage not available.'

---

apps/student/src/main/java/com/instructure/student/features/login/StudentLoginNavigation.kt
libs/horizon/src/main/java/com/instructure/horizon/HorizonActivity.kt

Test plan: Check if widgets and dymamic shortcuts (the ones from the launcher icon) is disabled when a Career user logs in and check if those are enabled again when an Academic user logs in. I couldn't remove the Bookmarks shortcut dynamically, but it doesn't break the Horizon experience.
refs: CLX-2234

[CLX-2234][Horizon] Disable Widgets and shortcuts in the Horizon experience

---

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/DiscussionAPI.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/compose/HorizonInboxComposeScreen.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/details/HorizonInboxDetailsRepository.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/details/HorizonInboxDetailsScreen.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/details/HorizonInboxDetailsUiState.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/details/HorizonInboxDetailsViewModel.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListScreen.kt
libs/horizon/src/main/java/com/instructure/horizon/features/inbox/list/HorizonInboxListViewModel.kt

Test plan: See ticket. I also fixed a different issue, where course announcements wouldn't change to read after opening them. There is no read status for global announcements.
refs: CLX-2052

[CLX-2052][Horizon] Fixed unread filter for announcements.

---

apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt

Test plan: Open quiz details, press SpeedGrader button, app should not crash
refs: MBL-19098
release note:

[MBL-19098][Teacher] Fixed crash on quiz details

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/SpeedGraderGradeScreen.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsScreen.kt

Test plan: 
- Open an assignment in SpeedGrader which has no rubrics, comments should be expanded, and not collapsable
- Open an assignment in SpeedGrader which has rubrics, comments should collapsed, and can be expanded
refs: MBL-19103
release note:

[MBL-19103][Teacher] Expand comments

---

apps/teacher/src/main/java/com/instructure/teacher/features/settings/TeacherSettingsRouter.kt
libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/RatingDialog.kt

refs: MBL-19044
release note: Modified rating dialog button text.

[MBL-19044][Teacher] 'Rate on the Play Store' dialog positive button string could be different when the user pops the dialog manually

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/speedgrader/grade/comments/SpeedGraderCommentsViewModelTest.kt

Test plan: Add a comment with no attempt on a submission.
- The comment should be visible in SG when viewing the first attempt.
- The comment should not be visible in SG when viewing any other attempt.
refs: MBL-19220

[MBL-19220][Teacher] Show no-attempt comments only for the first attempt

---

apps/parent/src/main/java/com/instructure/parentapp/di/feature/CalendarModule.kt
apps/student/src/main/java/com/instructure/student/di/feature/CalendarModule.kt
apps/student/src/main/java/com/instructure/student/features/calendar/StudentCalendarBehavior.kt
apps/student/src/test/java/com/instructure/student/features/calendar/StudentCalendarBehaviorTest.kt
apps/teacher/src/main/java/com/instructure/teacher/di/CalendarModule.kt
libs/pandautils/src/androidTest/java/com/instructure/pandautils/compose/features/calendar/CalendarScreenTest.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarBehavior.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarScreenUiState.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/CalendarViewModel.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/calendar/composables/CalendarScreen.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarBehaviorTest.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/calendar/CalendarViewModelTest.kt

Test plan:
refs: PFS-25692, PFS-25742
affects: Students App

Restrict Add event from Calendars for Students App

---

libs/pandares/src/main/res/values/strings.xml
libs/pandautils/src/main/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/inbox/compose/InboxComposeViewModelTest.kt

Test plan: see the ticket, also test forwarding message and parent app
refs: MBL-19363
affects: Student, Parent, Teacher
release note: Users are no longer able to send Inbox messages from courses that have been concluded or are part of a past term.

[MBL-19363][All] Inbox messages can be sent from course participation courses in closed terms

---

libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsFragment.kt
libs/pandautils/src/main/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModel.kt
libs/pandautils/src/test/java/com/instructure/pandautils/features/assignments/details/AssignmentDetailsViewModelTest.kt

Test plan:  Since push notifications only work in production, this can be tested using a deep link to open the submission details with a specific submission ID. Verify that the correct student's submission is displayed (not the first one). I couldn't fix the attempt issue because the attempt number is not part of the push notification, older push notifications will still open the latest attempt but that is an edge case.
refs: MBL-19203
release note: Fixed an issue where submission comment push notifications wouldn't route to the submission.

[MBL-19203][Student] Push notification for teacher comment opens Assignment Details instead of Submission Details

---

libs/horizon/src/main/java/com/instructure/horizon/features/dashboard/course/card/DashboardCourseCardContent.kt
libs/horizon/src/main/java/com/instructure/horizon/features/learn/course/CourseDetailsScreen.kt
libs/horizon/src/main/java/com/instructure/horizon/features/learn/course/score/CourseScoreScreen.kt
libs/horizon/src/main/java/com/instructure/horizon/horizonui/Extensions.kt
libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/CollapsableContentCard.kt
libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleContainer.kt
libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/cards/ModuleItemCard.kt
libs/horizon/src/main/java/com/instructure/horizon/horizonui/organisms/inputs/singleselect/SingleSelect.kt
libs/horizon/src/main/res/values/strings.xml

[CLX-3022][Horizon] Learn screen accessibility
