instructure/canvas-android

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/AssignmentDetailsRenderPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/views/GradeCellRenderTest.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/DonutChartView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeCellView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeCellViewState.kt, apps/student/src/main/res/drawable/vd_checkmark_large.xml, apps/student/src/main/res/drawable/vd_x_large.xml, apps/student/src/main/res/layout/fragment_assignment_details.xml, apps/student/src/main/res/layout/view_student_grade_cell.xml, apps/student/src/qa/java/com/instructure/student/SingleFragmentTestActivity.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt, libs/pandares/src/main/res/values/strings.xml
See [ticket](https://instructure.atlassian.net/browse/MBL-10254) for test plan
=> [Student][MBL-10254] Grade cell

apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt
=> [Student][MBL-12243] Fix quiz locked by module message for native quizzes

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentSubmissionListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderGradePageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt, apps/teacher/src/main/res/layout/fragment_assignment_details.xml, apps/teacher/src/main/res/layout/fragment_assignment_submission_list.xml, apps/teacher/src/main/res/layout/fragment_inbox.xml, apps/teacher/src/main/res/layout/fragment_quiz_details.xml, automation/canvas_espresso/build.gradle, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
I also turned on Teacher accessibility testing by default.
=> [Teacher][Accessibility][MBL-12268]: Addressed accessibility issues only seen in low-res devices

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
=> [Student][MBL-12253] Fix pending invites showing after restricted participation end date

apps/student/src/main/java/com/instructure/student/fragment/OldSubmissionDetailsFragment.java
=> [Student][MBL-12421] Fix opening canvadoc submissions

apps/teacher/src/main/java/com/instructure/teacher/presenters/CoursesPresenter.kt
Only show courses with teacher enrollments to teachers.
=> [Teacher][MBL-12453] Fix to only show teacher enrollments in teacher app

apps/student/flank.yml, apps/student/flank_e2e.yml, apps/student/flank_sweep.yml, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/CollaborationsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DiscussionsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/EventsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/InboxE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PagesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SettingsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SyllabusE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/E2EAnnotation.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/StubAnnotation.kt
Also added a "Stub" annotation, and tweaked our flank configuration files appropriately.
(Note that I did not yet add a notification test stub, because I'd like to investigate whether it's even possible to test notifications before doing so.)
=> [Student][Automation][MBL-12551]: Stubbed out remaining E2E UI tests

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/APIHelper.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
Can be tested in the instance mentioned in a comment in the jira ticket (joubel) as well as twilson in the LTI course.
=> [Student][MBL-11764] Fix loading embedded lti's

apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt
We already have this functionality in place, I just added tests to make sure it stays there.
=> [Student][MBL-10256] Add tests to verify submit button hidden when no submissions expected

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderFilesPageTest.kt
Will add them back later when server-side bug is fixed.
=> [Teacher][Tests][MBL-12837]: Commented out some Teacher tests

libs/annotations/src/main/java/com/instructure/annotations/FileCaching/FetchFileAsyncTask.kt, libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.java
=> [Teacher][MBL-12814] Fix error when viewing quiz question files

apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListView.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt
=> [Teacher][MBL-12823] Make modules with embedded Studio vids work again

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderFilesPageTest.kt
These tests had been broken by a server-side change, and are now working again.
=> [Teacher][MBL-12838]: Restored Teacher tests

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
See ticket for some testing creds. Jordan's account also has one that's good for testing.
We only grab the first observee in a course and display their grades.
=> [Student][MBL-12668] Show grades when logged in as an observer

apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/AssignmentDetailsRenderPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt, apps/student/src/main/res/layout/fragment_assignment_details.xml, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/QuizAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/QuizManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt, libs/pandares/src/main/res/values/strings.xml
Wip for the weekend, still needs tests.
=> [Student] Assignment details quiz/discussion support

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/EventsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/TodoE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CalendarPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/fragment_calendar_listview.xml, apps/student/src/main/res/layout/fragment_inbox.xml, apps/student/src/main/res/layout/fragment_list_todo.xml, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/CoursesListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTestExtensions.kt
Populated DashboardE2ETest, EventsE2ETest, TodoE2ETest.
Please let me know if I have missed any relevant functionality that should be included in high-level E2E tests.
=> [Student][E2E][MBL-12713]: Added some end-to-end UI tests

apps/student/src/main/res/layout/adapter_rubric_empty.xml, apps/student/src/main/res/layout/fragment_submission_files.xml, libs/pandautils/src/main/res/values/strings.xml
See ticket for the specs Jordan posted.
=> [Student][MBL-12909] Update empty states for rubric and files tabs in submission details

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/url/UrlSubmissionUploadUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/url/ui/UrlSubmissionUploadFragment.kt, apps/student/src/main/res/layout/fragment_url_submission_upload.xml
Don't fill in the submission text field with previous submission when resubmitting.
=> [Student] Remove pre-population from text/url submissions

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEffectHandler.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsEventBusSource.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsModels.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/ui/UploadStatusSubmissionView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadModels.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/ui/PickerSubmissionUploadFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/common/EventBusSource.kt, apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt, apps/student/src/main/res/layout/dialog_submission_picker_media.xml, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadUpdateTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/FileUploadAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FileUploadManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/NotoriousManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ProgressRequestBody.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt, libs/pandautils/src/main/java/com/instructure/pandautils/services/NotoriousUploadService.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/FileUploadUtils.java, libs/pandautils/src/main/java/com/instructure/pandautils/utils/NotoriousUploader.kt
Also added video recording and loading into the file picker.
=> [Student][MBL-12705] Add media submission dialog

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/file/UploadStatusSubmissionPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt, apps/student/src/main/java/com/instructure/student/util/FileUtils.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/util/FileUtilsTest.kt, libs/pandautils/src/main/java/com/instructure/pandautils/views/FloatingRecordingView.kt
Added support for the various file types in the panda picker and the upload status view.
=> [Student][MBL-12918] File type icons

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/UploadStatusSubmissionRenderTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/SubmissionCommentsPresenterTest.kt
Here's a first crack at the SubmissionCommentsPresenterTest (unit test).
Also, MBL-12964: I "Fixed" the UploadStatusSubmissionRenderTest.displaysLoadingState UI test by disabling  it for API < 24.
=> [Student][Tests][MBL-12914]: Added SubmissionCommentsPresenterTest

apps/student/src/main/java/com/instructure/student/fragment/ViewImageFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsUpdateTest.kt
To test, attempt to view a file submission for image formats that aren't automatically converted to PDF by docviewer (e.g. gif, svg)
=> [Student][MBL-12981] Submission details: Handle displaying image submissions

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsModels.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsUpdate.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/ui/SubmissionMessageFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/ui/SubmissionDetailsView.kt, apps/student/src/main/res/layout/fragment_submission_message.xml, apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsUpdateTest.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderEmptyFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt, libs/pandares/src/main/res/drawable/vd_unsupported_content.xml, libs/pandares/src/main/res/values/strings.xml, libs/pandares/src/main/res/values/strings_not_translatable.xml
Added analytics as well to the Unsupported Content submission type case.
=> [Student][MBL-12979] Add fragment for none, paper, and unsupported submission types

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/emptySubmission/ui/SubmissionDetailsEmptyContentView.kt
Only for assignments with no submissions
=> [Student][HOTFIX][R-6.6.0] Temporarily hide submission button on submission details page

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt, apps/teacher/src/main/res/values/strings.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DiscussionParticipant.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/DiscussionTopicHeader.kt, libs/pandares/src/main/res/values/strings.xml
This crash appears to be caused by blueprint courses, which don't copy over the author. See fabric for domains and user ids to masquerade with to test.
=> [student][MBL-13019][RC-6.6] Fix assignment deets discussion crash

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/SubmissionDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/MediaUploadUtils.kt
SubmissionFileUploadReceiver.java line 90
SubmissionDetailsPresenter.java line 95
MediaUploadUtils.java line 211
GradesListRecyclerAdapter.java line 383
GradesListRecyclerAdapter.java line 175
See ticket for test details on the grades stuff.
=> [Student][MBL-13037] Miscellaneous crash fixes due to 6.6.0

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/EnrollmentAPI.kt
=> [Parent][MBL-12975] Include completed state when fetching observer enrollments

apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/InboxConversationFragment.kt, apps/student/src/main/java/com/instructure/student/interfaces/MessageAdapterCallback.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AddMessageFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/MessageThreadFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/interfaces/MessageAdapterCallback.java
While digging into this I noticed that monologues weren't working at all, so those have also been fixed. See the ticket for a detailed description regarding the reply behavior changes. The TL;DR is that we try to match web behavior as closely as possible.
=> [Student][Teacher][MBL-10782] Update inbox reply functionality

apps/student/flank_landscape.yml, apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionDetailsRenderPage.kt, libs/login-api-2/src/main/res/layout-land/activity_login_landing_page.xml
Also fixed some test failures that were occurring in landscape mode.
=> [Student][UITests][MBL-12977]: Add support for landscape test run

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PersonDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/fragment_people_details.xml, apps/student/src/main/res/layout/fragment_people_list.xml
Please let me know if you can think of anything else that should go into a People E2E test.
=> [Student][E2E][MBL-13005]: People E2E Test

apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/InboxApi.kt
MBL-13077: Fixed low-res scrolling issues in AssignmentsE2ETest
MBL-13078: Fixed a mock canvas conversations API glitch.
=> [Student][MBL-13077,MBL-13078] : Fixed some problems with nightly tests

apps/student/src/main/db/com/instructure/student/Submission.sq, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/SubmissionUtils.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submission/picker/PickerSubmissionUploadEffectHandler.kt, apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt, apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/PickerSubmissionUploadEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/SubmissionDetailsEmptyContentEffectHandlerTest.kt
Progress updates are still broken on the UploadStatusSubmission page until MBL-13041 is done. (including transitioning to the success/fail state from in progress)
=> [Student][MBL-12701] Inlined notorious in submission service

apps/build.gradle, apps/student/.gitignore, apps/student/build.gradle, apps/student/proguard-rules.txt, apps/student/src/main/java/com/instructure/student/activity/LoginActivity.kt, buildSrc/src/main/java/GlobalDependencies.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt, open_source_data/student/files.list, open_source_data/student/newrelic.properties, open_source_data/student/private.properties
Notes:
-- We are just going to get "out-of-the-box" functionality from New Relic for now -- mainly interaction tracing and network tracking.  No custom metrics yet.
-- The enabling of New Relic is controlled by a Remote Config parameter.  For now, it will be on for 6% of our users, but we can tweak that (or even turn it all the way off) via Remote Config.
The remote config parameter looks like this:
The RemoteConfigPool condition looks like this:
=> [Student][NewRelic][MBL-13102]: Incorporate New Relic into student app

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt
Fix the bottom bar divider still being shown.
=> [Student][RC-6.6.1] bottom bar divider

apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeEffectHandler.kt, apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeModel.kt, apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostGradeUpdate.kt, apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/PostPolicyFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostGradeView.kt, apps/teacher/src/main/java/com/instructure/teacher/features/postpolicies/ui/PostGradeViewState.kt, apps/teacher/src/test/java/com/instructure/teacher/unit/postpolicies/PostGradeEffectHandlerTest.kt, apps/teacher/src/test/java/com/instructure/teacher/unit/postpolicies/PostGradeUpdateTest.kt, libs/canvas-api-2/src/main/graphql/com/instructure/canvasapi2/PostPolicyQuery.graphql, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/AssignmentManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/PostPolicyManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/SectionManager.kt
This also adds the mutations for post policies
=> [Teacher][MBL-13104] Post Policies loop

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DashboardInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/fragment_module_list.xml, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
This is a fairly bare-bones test that (1) unpublished modules don't appear, and (2) published modules are displayed.
=> [Student][E2E][MBL-13003]: Initial crack at a modules E2E test

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/SyllabusE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SubmissionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/course_discussion_topic.xml, apps/student/src/main/res/layout/fragment_discussions_details.xml, apps/student/src/main/res/layout/fragment_file_list.xml, apps/student/src/main/res/layout/view_comment_attachment.xml, apps/student/src/main/res/layout/viewholder_discussion_group_header.xml, apps/student/src/main/res/layout/viewholder_file.xml, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt
The Syllabus test is pretty basic.  LMK if you think that it needs to be more rigorous.
With the Files test, I constructed some pages to test discussion attachments, but then ended up backing out of that when I discovered that what I wanted to test was behind a webview.  But the work that I did will be useful later when the Discussions E2E test is written.
I also fixed several accessibility bugs that were surfaced with these new tests.
=> [Student][E2E][MBL-13001,MBL-13007]: Files, Syllabus E2E tests

apps/teacher/src/main/java/com/instructure/teacher/adapters/GradeableStudentSubmissionAdapter.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentSubmissionListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/holders/GradeableStudentSubmissionViewHolder.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/AssignmentSubmissionListPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/FeatureFlags.kt, apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt, apps/teacher/src/main/res/menu/menu_filter_submissions.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FeaturesManager.kt
Removed our local feature flag for post policies and rely on the canvas feature flag instead. Also updated the places we show the "hidden" eye icon to use the feature flag.
=> [Teacher][MBL-12988] Post policy feature flag from Canvas

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DiscussionsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PagesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PageListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/fragment_course_pages.xml, apps/student/src/main/res/layout/fragment_create_discussion.xml, apps/student/src/main/res/layout/fragment_discussions_details.xml, libs/rceditor/build.gradle
Note that:
--Discussions includes announcements
--Some a11y issues were also fixed
=> [Student][E2E][MBL-13000,MBL-13004]: E2E tests for pages & discussions

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/ModulesApi.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/ModuleApiModel.kt
Added some items (assignments, quiz, page, discussion) to the modules in the test.
=> [Student][E2E][MBL-13138]: Beef up Modules E2E test with some module items

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/fragment_quiz_list.xml, apps/student/src/main/res/layout/fragment_quiz_start.xml, apps/student/src/main/res/layout/quiz_essay_question.xml, apps/student/src/main/res/layout/quiz_file_upload.xml, apps/student/src/main/res/layout/quiz_list_layout.xml, apps/student/src/main/res/layout/quiz_multi_choice.xml, apps/student/src/main/res/layout/quiz_multiple_dropdown.xml, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/QuizzesApi.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt, libs/pandares/src/main/res/values/strings.xml
Also includes some accessibility fixes.
Please LMK if you can think of any useful ways to beef up this E2E test.
=> [Student][E2E][MBL-13006]: Initial attempt at Quizzes E2E test

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShardE2ETest.kt, apps/student/src/main/java/com/instructure/student/util/ModuleUtility.java, apps/student/src/test/java/com/instructure/student/test/util/ModuleUtilityTest.kt, apps/teacher/src/test/java/com/instructure/teacher/unit/RouteTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/StreamItem.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/APIHelper.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/APIHelperTest.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/StreamUnitTest.kt, libs/interactions/src/main/java/com/instructure/interactions/router/Route.kt
=> [Student][Teacher][MBL-13227] Fix routing for multi-shard courses

apps/teacher/build.gradle, apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderGradeFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderGradePresenter.kt
=> [Teacher][MBL-13254] Fix speed grader crash

apps/student/src/main/java/com/instructure/student/adapter/ModuleListRecyclerAdapter.kt
To test:
See ticket OR set up a simple mastery path enabled assignment in a module with an OR choice. Selecting that assignment in the module list (or the choice) should not crash.
=> w[Student][MBL-13286] Crash fix for Mastery Paths

apps/parent/build.gradle, apps/parent/src/main/AndroidManifest.xml, apps/teacher/build.gradle, apps/teacher/src/main/AndroidManifest.xml
To test:
Just make sure that the parent/teacher apps launch. We should get the crash statistics in the firebase console once this is released 🤞
=> [Teacher][Parent][MBL-13361] Fix for getting firebase crash statistics

apps/student/flank_tablet.yml, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/views/SubmissionRubricTooltipTest.kt
=> [Student][Tests][MBL-13372]: Support test runs against tablet

apps/student/build.gradle, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/SubmissionDetailsRenderTest.kt, buildSrc/src/main/groovy/TimingsListener.groovy
For now, we just report build data for successful Bitrise runs.
UPDATE:  I also stubbed out a couple of tests that won't pass consistently until we fix MBL-13405.
=> [Student][Builds][MBL-13398]: Track student build stats in Sumologic

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/dialog_what_if.xml, apps/student/src/main/res/layout/fragment_course_grades.xml, apps/student/src/main/res/layout/viewholder_grade.xml, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/QuizzesApi.kt, libs/pandares/src/main/res/values/strings.xml
Also fixed several a11y issues.
=> [Student][E2E][MBL-13002]: E2E test for grades page

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/CourseInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PageListPage.kt, apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/FileEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/FolderEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/RootEndpoint.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/AuthUtils.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/PathUtils.kt
I ultimately ended up punting on the completion of testCourse_openFile(), despite having completed much of it, because we do not yet have the ability to show mocked content in webviews.  Created ticket https://instructure.atlassian.net/browse/MBL-13451 for adding mocking support for webview requests.
Note that I did change production code in a minor way in PageDetailsFragment.  Please let me know if you see any problem with that.
=> [Student][InteractionTests][MBL-13237]: CourseInteractionTest

apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/FileUploadManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/FileFolder.kt, libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/UploadFilesDialog.kt, libs/pandautils/src/main/java/com/instructure/pandautils/services/FileUploadService.kt, libs/pandautils/src/main/res/values/strings.xml
This also fixes so that students can upload files to groups.
=> [Teacher][Student][MBL-13423] Show file upload button if folder allows it

apps/student/src/main/res/layout/view_assignment_override.xml
Evidently this is the one true way to set the speakable text for an EditText.
=> [Student][A11y][MBL-13516]: Fixed a11y issues in create-discussion flow on tablet

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ModulesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModuleProgressionPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/course_module_progression.xml, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/PathUtils.kt
Note that I punted on the LTI test.  It is still covered by new ticket https://instructure.atlassian.net/browse/MBL-13517.
=> [Student][InteractionTests][MBL-13230] : ModuleInteractionTests

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/QuizInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizListPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/PathUtils.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/Randomizer.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/QuizQuestion.kt
Note that I changed production code in QuizQuestion.kt.
Also, I snuck in a fix to the repeat-assignment-names problem in another interaction test.
=> [Student][InteractionTests][MBL-13232]: QuizInteractionTests

apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizDetailsPage.kt
The old java.lang.Integer.min call is apparently not supported in API-23.
=> [Student][Interaction][MBL-13232]: Fix for min() call in QuizDetailsPage

apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/activities/SplashActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/InboxFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/ViewUnsupportedFileFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/StudentContextPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/LoggingUtility.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/RecyclerViewUtils.java, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Logger.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/CanvasContextExtensions.kt
* Deleting an inbox message while viewing it would crash
* Recycler view utils crashed on null pointer
* Trying to open a file that didn’t have a supported app would crash (docx)
* Trying to view a users information that was removed from the course would crash
* Bonus - trying to view a users information from a group would crash
* Attempt to fix DNS crash from UnknownHostException, added logs to try and collect more data
To test: See ticket for individual repro steps.
=> [Teacher][MBL-13553] Fix the top crashes in teacher from crashlytics

apps/flutter_parent/lib/api/alert_api.dart, apps/flutter_parent/lib/api/utils/api_prefs.dart, apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/models/alert.dart, apps/flutter_parent/lib/models/alert.g.dart, apps/flutter_parent/lib/models/serializers.dart, apps/flutter_parent/lib/models/serializers.g.dart, apps/flutter_parent/lib/screens/alerts/alerts_interactor.dart, apps/flutter_parent/lib/screens/alerts/alerts_screen.dart, apps/flutter_parent/lib/utils/design/parent_theme.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/lib/utils/widgets/full_screen_scroll_container.dart, apps/flutter_parent/test/screens/alerts/alerts_interactor_test.dart, apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart, apps/flutter_parent/test/screens/alerts_screen_test.dart, apps/flutter_parent/test/utils/widgets/full_screen_scroll_container_test.dart
Also added a helper widget for centering something in a scroll view. This is useful for empty/error states when we want the user to still be able to swipe refresh, while displaying the content in the center of the screen.
=> [Flutter-Parent][MBL-13491] Alerts list

apps/student/build.gradle, apps/student/src/main/java/com/instructure/student/activity/LoginActivity.kt, apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/CalendarListViewFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/CourseBrowserFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/InboxFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/PeopleListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/QuizListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/ToDoListFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/syllabus/ui/SyllabusFragment.kt, libs/pandautils/build.gradle, libs/pandautils/src/main/java/com/instructure/pandautils/utils/TelemetryUtils.kt
This should allow us to more easily add NewRelic to our builds or remove NewRelic from our builds.
However, it also now pulls NewRelic into all apps.  (Or no apps, depending on which way we decide to go.)
There are a lot of files with small changes in the PR -- it should easier to review than it looks.
=> [All][NewRelic][MBL-13570]: Consolidated NewRelic low-level logic.

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SubmissionDetailsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SubmissionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionCommentsRenderPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/SubmissionEndpoints.kt, libs/pandautils/src/main/res/layout/view_floating_media_recorder.xml
A couple of notes:
(1) I punted the video comment and audio comment tests to an E2E test.  It was just too tough trying to mock the Notorious server.  It's a bummer that those tests won't run every PR, but at least they will run nightly.
(2) I attempted to streamline addAssignment() and addAssignmentsToGroups() in MockCanvas so that the latter created assignments via the former.  The intent was to standardize the way that we create assignments.  Sorry that that might be a little extra code to review.
=> [Student][Interaction][MBL-13246]: SubmissionDetailsInteractionTest

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/InboxInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt
Sadly, one major component of the fix was to make our message bodies much smaller so that everything fits on a short landscape page.
=> [Student][Interaction][MBL-13240]: Tweaks to make InboxInteractionTests more landscape-friendly

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PagesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PageListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/FolderEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/PathUtils.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/PagesApi.kt
Implemented group links interaction tests.
Also beefed up / cleaned up the MockCanvas logic related to creating files and folders.
=> [Android][Interaction][MBL-13244]: GroupLinksInteractionTest

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SubmissionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/renderPages/SubmissionCommentsRenderPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
I ran all student tests (interaction + e2e) before committing this, and they all passed.
=> [Student][Tests][MBL-13631]: Assorted fixes to make our tests landscape-friendly

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/HelpPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
Included disabling a couple of those tests in landscape because there are real bugs that cause those tests to fail.
=> [Student][Interaction][MBL-13248]: Fix landscape issues with SettingsInteractionTest

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentListInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/LoginLandingPage.kt
MBL-13249: Also converted AssignmentListPageTest to AssignmentListInteractionTest.
=> [Android][Interaction][MBL-13233]: Nav drawer interaction test

apps/student/flank.yml, apps/student/flank_landscape.yml, apps/student/flank_sweep.yml, apps/student/flank_tablet.yml, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GroupLinksInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomWebViewLogic.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt
Also increased the shard count of our FTL runs
=> [Student][Interaction][MBL-13639]: Assorted test fixes for tablet, multi-device runs

apps/flutter_parent/lib/api/utils/api_prefs.dart, apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/test/api/api_prefs_test.dart, apps/flutter_parent/test/api/dio_config_test.dart
Cleaned up ApiPrefs and AppLocalizations to remove unreachable lines.
=> [Flutter-Parent][MBL-13662] Dio testing

buildSrc/src/main/groovy/TimingsListener.groovy
We always add in the TimingsListener via the student gradle file, which gets configured in the teacher test as well.  So we had to look beyond the current project (which is always "student") in sending our data.
=> [Teacher,Student][Splunk][MBL-13689]: Fix build splunk-reporting to work for teacher

apps/flutter_parent/lib/screens/alerts/alerts_screen.dart, apps/flutter_parent/lib/screens/courses/courses_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart, apps/flutter_parent/lib/screens/web_login/web_login_screen.dart
Just to clean up the code a little, consolidating Center(child: CircularProgressIndicator()) with LoadingIndicator().
=> [Flutter-Parent][MBL-13676] Use LoadingIndicator

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTestExtensions.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt
Tests student, teacher, TA, parent.
=> [Student[]E2E][MBL-13345]: E2E test for logging into student app as various roles

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AssignmentGroup.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
This commit adds analytics for what if grade usage and disables what if grades in the case of assignment group rules. 
To Test:
-Enable new gradebook
-Go to any assignment group in a course, edit the group and either modify low/high score drops, or assignment never drops.
-What if grades should not display
=> [Student][MBL-13664] What if disabled for rules

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PickerSubmissionUploadInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/UserFilesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PickerSubmissionUploadPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/viewholder_file_upload.xml, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/AssignmentEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/SubmissionEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/UserEndpoints.kt
Phew -- this was more complicated that I thought, due to the complexity of properly mocking our two-stage file-upload mechanism.
I only implemented the one P1 test -- the P2 tests can stay stubbed for now.
=> [Student][Interaction][MBL-13236] : PickerSubmissionUploadInteractionTest

apps/student/src/main/java/com/instructure/student/fragment/CourseBrowserFragment.kt
It's entirely possible that some subsequent code will choke if these fields are null.
=> [Student][Crashfix][MBL-13737]: Hardened FragmentCourseBrowser.onOffsetChanged() against some null values

apps/student/src/main/java/com/instructure/student/fragment/PeopleDetailsFragment.kt, apps/student/src/main/res/layout/fragment_people_details.xml
To repro: Go to a course -> people -> tap on a user -> tap on the compose FAB before the user finishes loading.
=> [Student][MBL-13739] Fix crash when tapping compose button in People Details fragment before user has loaded

libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.java
https://console.firebase.google.com/u/1/project/automatic-rite-88319/crashlytics/app/android:com.instructure.candroid/issues/5c941d7df8b88c2963044293?time=last-seven-days&sessionId=5E136697036A00017E1BDF1CE8860107_DNE_0_v2
=> [Student][MBL-13741] Added check before showing error dialog in Sign In

libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginFindSchoolActivity.kt
See tickets for more deets, super simple change. Just want to prevent users from attempting a no network search for a domain.
=> [All][MBL-13721] Added no network check to domain search

apps/student/src/main/java/com/instructure/student/dialog/ShareFileDestinationDialog.java, apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/LTIWebViewFragment.kt, apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
For referencing these crashes in Firebase:
AssignmentListFragment - Line 74
LTIWebViewFragment.java - Line 216
RouteMatcher.java - Line 306
ShareFileDestinationDialog.java - Line 329
=> [Student][MBL-13785] A few more crash fixes

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/models/unread_count.dart, apps/flutter_parent/lib/models/unread_count.g.dart, apps/flutter_parent/lib/network/api/alert_api.dart, apps/flutter_parent/lib/network/api/inbox_api.dart, apps/flutter_parent/lib/screens/alerts/alerts_interactor.dart, apps/flutter_parent/lib/screens/alerts/alerts_screen.dart, apps/flutter_parent/lib/screens/dashboard/alert_notifier.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_interactor.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart, apps/flutter_parent/lib/utils/common_widgets/badges.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/test/screens/alerts/alerts_interactor_test.dart, apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart, apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart, apps/flutter_parent/test/utils/widgets/badges_test.dart
Also adds badge to alert list items when they’re unread (helps validating the count is correct), design checked by Dave.
This commit also adds some shared badge widgets to consolidate some UI and logic.
=> [Flutter-Parent][MBL-13594] Add alerts badge

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart, apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
Looks like we are following our loading/refresh indicator pattern we've established.
This is just something I noticed while poking around.
=> [Flutter Parent][MBL-13743] Refresh Indicator design check

apps/flutter_parent/lib/models/attachment.dart, apps/flutter_parent/lib/models/attachment.g.dart, apps/flutter_parent/lib/models/serializers.dart, apps/flutter_parent/lib/network/api/inbox_api.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/conversation_details_interactor.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/conversation_details_screen.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/message_widget.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart, apps/flutter_parent/lib/screens/inbox/reply/conversation_reply_interactor.dart, apps/flutter_parent/lib/screens/inbox/reply/conversation_reply_screen.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/test/screens/inbox/conversation_details/conversation_details_screen_test.dart, apps/flutter_parent/test/screens/inbox/conversation_details/message_widget_test.dart, apps/flutter_parent/test/screens/inbox/reply/conversation_reply_interactor_test.dart, apps/flutter_parent/test/screens/inbox/reply/conversation_reply_screen_test.dart
Also moves the message item UI to its own MessageWidget
=> [Flutter Parent][MBL-13654] Reply to a conversation

apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseGradesPage.kt
This was the best I could come up with after a couple hours of staring at the recent retries/failures.
=> [Student][E2E][MBL-13793]: One more speculative fix for GradesE2ETest instability

apps/flutter_parent/lib/models/assignment.dart, apps/flutter_parent/lib/models/assignment.g.dart, apps/flutter_parent/lib/models/serializers.g.dart, apps/flutter_parent/lib/screens/courses/details/course_details_interactor.dart, apps/flutter_parent/lib/screens/courses/details/course_details_model.dart, apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart, apps/flutter_parent/test/models/assignment_test.dart, apps/flutter_parent/test/screens/courses/course_details_interactor_test.dart, apps/flutter_parent/test/screens/courses/course_details_model_test.dart, apps/flutter_parent/test/screens/courses/course_grades_screen_test.dart
Clean up for LA-274 to include submissions as part of the assignment group call. This is getting priority fixed now as the api changed to return a list of submissions now, rather than a single submission for an assignment. Mostly, this is code cleanup to remove the extra submissions call.
=> [Flutter-Parent][MBL-13813] Course details grade fix

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt
We were getting occasional timeouts in the renderings of the Privacy Policy page and the Canvas Guides page.  I doubled the timeout from 10 secs to 20 secs.
=> [Student][Tests][MBL-13817]: Addressed some timeouts in SettingsInteractionTests

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/message_widget.dart, apps/flutter_parent/lib/utils/common_widgets/user_name.dart, apps/flutter_parent/lib/utils/style_slicer.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/utils/style_slicer_test.dart, apps/flutter_parent/test/utils/widgets/user_name_test.dart
Adds StyleSlicer, a more general-purpose text formatting solution.
=> [Flutter Parent] Fix message author formatting

apps/flutter_parent/lib/models/assignment.g.dart, apps/flutter_parent/lib/screens/courses/details/course_details_model.dart, apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_syllabus_screen.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/screens/courses/course_details_screen_test.dart
Testing:
Mobile dev has a course with a syllabus that has embedded media and links, good for testing.
=> [Flutter Parent][MBL-13015] Syllabus Screen

apps/teacher/src/main/res/layout/fragment_discussions_details.xml
See ticket for testing creds and repro steps.
Only did this for Teacher, not Parent.
=> [Teacher][MBL-1651] Show full title in details view for discussion details view

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/StudentContextPageTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UserAPI.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/UsersApiPactTests.kt
See ticket for testing creds
Only works on beta right now
Go to Inactive Group -> People -> Check for Inactive Bill
=> [Student][MBL-13752] Hide inactive users

apps/flutter_parent/lib/screens/courses/courses_screen.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/utils/common_widgets/badges.dart, apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart, apps/flutter_parent/test/screens/inbox/conversation_list/conversation_list_test.dart, apps/flutter_parent/test/utils/widgets/badges_test.dart
Also adding badge to app bar drawer icon for inbox message unread count. It has different styling, so I added a BadgeOptions class where you can specify ‘onPrimarySurface’ to get correct colors when placed on an app bar.
=> [Flutter-Parent][MBL-13830] Badge polish

apps/flutter_parent/lib/network/api/inbox_api.dart, apps/flutter_parent/lib/network/utils/api_prefs.dart, apps/flutter_parent/lib/network/utils/dio_config.dart, apps/flutter_parent/test/network/api_prefs_test.dart, apps/flutter_parent/test/utils/platform_config.dart, apps/flutter_parent/test/utils/test_app.dart, apps/flutter_parent/test/utils/widgets/error_report/error_report_interactor_test.dart
Adds a new platform config for initializing sqflite, which is used by our caching library.
=> [Flutter-Parent][MBL-13923] Clear cache on logout

apps/student/src/main/java/com/instructure/student/fragment/AssignmentBasicFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/DiscussionSubmissionViewFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizPreviewWebviewFragment.kt
Also fixes other places where external pdf links won’t open.
See tickets for repro steps.
=> [Student][Teacher][MBL-13930][MBL-13931] Assignment external pdf links

apps/student/src/main/java/com/instructure/student/dialog/HelpDialogStyled.kt
The internal webview doesn't seem to like whatever javascript is doing here, so I'm just kicking it out to the external browser.
=> [Student][MBL-13928] Fix chat with support help dialog link

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart, apps/flutter_parent/test/screens/login/domain_search_screen_test.dart, apps/flutter_parent/test/screens/login/login_landing_screen_test.dart
Dave requested we change 'Find School or District' to just 'Find School'
=> [Flutter Parent] Find School or District -> Find School

apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_screen.dart
Was reading the wrong value on toggle.
=> [Flutter-Parent][MBL-13638] Fix talkback on manage children switches

apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart
Trying to be consistent with sizes between our normal screens and the nav drawer. By default, flutter makes drawer content a smaller size.
=> [Flutter Parent] Bump drawer text size to be consistent with screens

apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart, apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_interactor.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart, apps/flutter_parent/lib/screens/inbox/reply/conversation_reply_screen.dart, apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart, apps/flutter_parent/test/screens/courses/course_details_screen_test.dart, apps/flutter_parent/test/screens/inbox/create_conversation/create_conversation_interactor_test.dart, apps/flutter_parent/test/screens/inbox/create_conversation/create_conversation_screen_test.dart
- Changed Inbox "To" field icon from plus to address book
- Remove 'Done' button from recipient picker
- Only show teachers and the target student in the recipient picker
- Fix double divider unter AppBar in reply/create conversation screens, unify divider thickness
=> [Flutter Parent] Misc inbox polish

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart
Also add semantics label for assignment group row for expanding/collapsing.
=> [Flutter-Parent] Fix course grade assignment icon position

apps/flutter_parent/lib/l10n/app_localizations.dart
Refer to the README.md to see what strings need for the extracting script.
Waiting to submit the generated arb file until we’re ready for another beta (or until we get a bitrise job setup to do this extracting).
=> [Flutter-Parent] Fix strings that aren’t setup properly

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
Another round of test stabilization.  Can't promise it will be the last.  :-(
=> [Student][Testing][MBL-13979]: More test stabilization

libs/canvas-api-2/build.gradle, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/EnrollmentsApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/UsersApiPactTests.kt
I also changed our consumer name from "mobile" to "android" to allow for separate ios contracts.
=> [Student][Pact][MBL-13982]: Tweaks to allow publishing our pact contract(s) from Bitrise

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ConferencesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
=> [Student][E2E][MBL-12999]: Basic conferences E2E test

libs/rceditor/src/main/java/instructure/rceditor/RCEInsertDialog.java, libs/rceditor/src/main/java/instructure/rceditor/RCETextEditorView.kt, libs/rceditor/src/main/res/layout/rce_dialog_insert.xml, libs/rceditor/src/main/res/values/rce_colors.xml, libs/rceditor/src/main/res/values/rce_strings.xml
I added in some super simple error checking (no empty or http urls) to the url link dialog in addition to defaulting to https:// for all non-scheme'd urls.
=> [RCE][MBL-13588] Link fixes for RCE

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/RemoteFile.kt, libs/pandares/src/main/res/values/strings.xml
See [ticket](https://instructure.atlassian.net/browse/MBL-13984) for repro
=> [Student][MBL-13984] Show lock explanation for discussion attachments

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/CollaborationsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CollaborationsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ConferencesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CourseBrowserPage.kt
Just verifies that the page comes up correctly.  Does not attempt to start a collaboration.
=> [Student][E2E][MBL-12998]: Very basic E2E test for collaborations page

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/models/serializers.dart, apps/flutter_parent/lib/models/serializers.g.dart, apps/flutter_parent/lib/models/terms_of_service.dart, apps/flutter_parent/lib/models/terms_of_service.g.dart, apps/flutter_parent/lib/network/api/accounts_api.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/screens/help/help_screen.dart, apps/flutter_parent/lib/screens/help/legal_screen.dart, apps/flutter_parent/lib/screens/help/terms_of_use_screen.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart, apps/flutter_parent/test/screens/help/help_screen_test.dart, apps/flutter_parent/test/screens/help/legal_screen_test.dart, apps/flutter_parent/test/screens/help/terms_of_service_screen_test.dart
Also, after working with Design, it was decided that the help dialog would become a help screen.
=> [Flutter Parent][MBL-13978] Legal screen

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt, apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/util/ModuleUtility.java, apps/student/src/test/java/com/instructure/student/test/util/ModuleUtilityTest.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ApiEndpoint.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/PathUtils.kt
=> [Student][MBL-14000] Fix page name/url/title when loaded from module

apps/student/src/main/AndroidManifest.xml, apps/teacher/src/main/AndroidManifest.xml, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.java
This is really just for student/teacher. I'll look into adding the same behavior to flutter parent. Don't merge w/o product approval.
=> [All] Add manifest and webview setting to allow for http

apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart, apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
Fixes the crash:
https://console.firebase.google.com/project/automatic-rite-88319/crashlytics/app/android:com.instructure.parentapp/issues/6832035367e9a8baceb3bed347f6a673
=> [Flutter-Parent] Fix npe in assignment details for isGraded

apps/flutter_parent/lib/router/parent_router.dart, apps/flutter_parent/lib/screens/alerts/alerts_screen.dart, apps/flutter_parent/lib/screens/courses/courses_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_summary_screen.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart, apps/flutter_parent/lib/screens/help/help_screen.dart, apps/flutter_parent/lib/screens/help/legal_screen.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart, apps/flutter_parent/lib/screens/not_a_parent_screen.dart, apps/flutter_parent/lib/screens/web_login/web_login_screen.dart, apps/flutter_parent/lib/utils/quick_nav.dart, apps/flutter_parent/test/screens/courses/course_summary_screen_test.dart, apps/flutter_parent/test/screens/help/legal_screen_test.dart, apps/flutter_parent/test/screens/login/login_landing_screen_test.dart
There are a few screens left out that will require some refactoring, but most are covered with this PR.
=> [Parent] Majority of internal routes

apps/flutter_parent/test/utils/accessibility_utils.dart
Form factor can be changed via environment variables.
=> [Parent][Test][MBL-14046]: Enable widget tests to run on alternative form factors

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/EditFavoritesRecyclerAdapter.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Group.kt
To test:
See ticket
Also verify that groups still show up for users that have groups (my student has a few groups if needed for testing).
=> [Student][MBL-14028] Don’t show concluded groups

apps/flutter_parent/lib/utils/common_widgets/error_report/error_report_dialog.dart, apps/flutter_parent/lib/utils/common_widgets/full_screen_scroll_container.dart, apps/flutter_parent/test/utils/widgets/full_screen_scroll_container_test.dart
TIL: In flutter, you can wrap a dialog in a scroll view
To test: See ticket for how small screens don't view the report problem dialog well.
Should also test on a big screen size to make sure it still looks good for the majority of devices.
=> [Flutter-Parent][MBL-14080] Report problem dialog for small devices

apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart
Also fixes the filter button in the grade list page to meet a11y tap target size requirements
=> [Flutter Parent][MBL-14096] Fix LoginLandingScreen overflow in landscape

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/ExternalToolAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/ExternalToolManager.kt
PR feedback, being consistent!
=> [Student][MBL-14066] Studio for submission type with lots of LTIs part 2

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/models/course.dart, apps/flutter_parent/lib/network/utils/api_prefs.dart, apps/flutter_parent/lib/screens/calendar/calendar_screen.dart, apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_filter_screen/calendar_filter_list_interactor.dart, apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_filter_screen/calendar_filter_list_screen.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/test/network/api_prefs_test.dart, apps/flutter_parent/test/screens/calendar/calendar_screen_test.dart, apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_filter_list_interactor_test.dart, apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_filter_list_screen_test.dart
Ties into the persistence as well. For now, it seems that courses are the only context we're dealing with.
=> [Flutter Parent][MBL-13920] Calendar Filter

apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/lib/screens/alerts/alerts_screen.dart, apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart, apps/flutter_parent/lib/utils/quick_nav.dart, apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart
This wires up the rest of the alerts and fixes a bug with external routes (that I created). See new logic/comments below.
=> [Parent][MBL-14063] Alert routing and bug fix

apps/flutter_parent/lib/network/api/announcement_api.dart, apps/flutter_parent/lib/network/utils/authentication_interceptor.dart, apps/flutter_parent/lib/screens/announcements/announcement_details_interactor.dart, apps/flutter_parent/lib/screens/announcements/announcement_details_screen.dart, apps/flutter_parent/test/network/authentication_interceptor_test.dart, apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart, apps/flutter_parent/test/screens/announcements/announcement_details_interactor_test.dart, apps/flutter_parent/test/screens/announcements/announcement_details_screen_test.dart
Also fixes an issue where refresh tokens fails and forever retries
To test:
Make an announcement
View it in parent app
Change the announcement
Pull to refresh in parent app, verify update received
=> [Flutter-Parent][MBL-14085] Announcement PTR

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricPresenter.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/rubricTab/SubmissionRubricPresenterTest.kt
To test:
See ticket for repro steps
=> [Student][MBL-14097] Allow partial rubric grading

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ConferencesE2ETest.kt
MBL-14127 created to re-write test.
=> [Student][E2E][MBL-14126]: Disable/Stub ConferencesE2ETest

translations/import.rb, translations/local-import.rb
Accessing by bracket will return nil instead of throwing an error like accessing via 'fetch'.
=> Fix translation import for flutter fail

apps/student/src/main/java/com/instructure/student/activity/InterwebsToApplication.kt
Wasn't using clear task, so you could go back to the QR login screen after logging in... Woops.
=> [Student][RC 6.7] Quick fix for bug in qr login

libs/canvas-api-2/build.gradle, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/ApiPactTestBase.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/AssignmentsApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/SubmissionsApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactAssignmentLogic.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactAttachmentLogic.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactAuthorLogic.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactCommonLogic.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactRubricLogic.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactSubmissionLogic.kt
Also covers MBL-13410.
Basically, 4 tests:
-- Request an assignment as a teacher
-- Request an assignment as a student
-- Retrieve your submission for an online_text_entry assignment
-- Retrieve your submission for an online_upload assignment
=> [Student][Pact][MBL-13409] | Pact tests for assignments and submissions

apps/student/src/main/java/com/instructure/student/util/AppManager.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SettingsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteResolver.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/AppManager.kt, apps/teacher/src/main/res/layout/fragment_settings.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt, libs/pandautils/src/main/java/com/instructure/pandautils/fragments/RemoteConfigParamsFragment.kt
From student and teacher.  We'll need another ticket for parent.
I also (1) Added a "remote config" menu under options in the Teacher app, (2) Cleaned up the RemoteConfigParamsFragment to work correctly.
=> [Student][Teacher][MBL-14145]: Now emitting build_type and os_version user properties

apps/flutter_parent/lib/network/api/user_api.dart
=> [Flutter-Parent] Tiny type fix for permissions

translations/flutter-generate-hooks.rb
=> [Flutter-Parent] Run flutter pub get as first part of script

apps/flutter_parent/lib/screens/manage_students/manage_students_screen.dart, apps/flutter_parent/test/screens/login/domain_search_screen_test.dart, apps/flutter_parent/test/screens/manage_students/manage_students_screen_test.dart
QR code pairing won't be part of this next release so this just hides it from the user.
=> [Flutter Parent][MBL-14214] Hide QR code pairing

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/network/api/accounts_api.dart, apps/flutter_parent/lib/network/utils/api_prefs.dart, apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/lib/screens/domain_search/domain_search_interactor.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart, apps/flutter_parent/test/l10n/app_localizations_delegate_test.dart, apps/flutter_parent/test/screens/alert_thresholds/alert_thresholds_interactor_test.dart, apps/flutter_parent/test/screens/alerts/alerts_screen_test.dart, apps/flutter_parent/test/screens/crash_screen_test.dart, apps/flutter_parent/test/screens/events/event_details_screen_test.dart, apps/flutter_parent/test/screens/login/domain_search_interactor_test.dart, apps/flutter_parent/test/screens/login/domain_search_screen_test.dart, apps/flutter_parent/test/screens/login/web_login_screen_test.dart, apps/flutter_parent/test/screens/not_a_parent_screen_test.dart, apps/flutter_parent/test/screens/under_construction_screen_test.dart, apps/flutter_parent/tools/codecov_exclusions
Takes us form 93.8% to 96.3%
Added some tests for missing line count, excluded more things that we can’t/won’t test.
=> [Flutter-Parent] Improve code coverage from tests

apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/test/router/panda_router_test.dart
This fixes the case where a user scans the QR code from canvas for a fresh install / or isn't logged in already.
=> [Parent] QR Login bug fix

apps/flutter_parent/lib/screens/assignments/assignment_details_screen.dart, apps/flutter_parent/test/screens/assignments/assignment_details_screen_test.dart
=> [Flutter Parent] Assignment status icon tweaks

apps/flutter_parent/lib/screens/alert_thresholds/alert_thresholds_percentage_dialog.dart, apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart
- Removes double dividers from domain search screen
- Removes counter from alert threshold percentage input
=> [Flutter Parent] Remove double dividers, remove threshold input counter

apps/flutter_parent/lib/screens/inbox/conversation_details/message_widget.dart, apps/flutter_parent/test/screens/inbox/conversation_details/message_widget_test.dart
=> [Flutter Parent] Tap message header to expand participant info

apps/flutter_parent/lib/main.dart, apps/flutter_parent/lib/parent_app.dart, apps/flutter_parent/lib/utils/notification_util.dart, apps/flutter_parent/test/utils/notification_util_test.dart
To Test:
Set up a notification reminder, then kill the app.
=> [Parent] notification init change for routing

apps/flutter_parent/test_driver/flutter_driver_extensions.dart, apps/flutter_parent/test_driver/grades_assignments.dart, apps/flutter_parent/test_driver/pages/dashboard_page.dart
This root cause of this issue was very hard to pin down, as the issue itself was unpredictably intermittent.  But I think that this delay added between creating an assignment and creating a submission for that assignment will address suspected delayed-task issues to a degree.
=> [Parent][E2E][MBL-14260]: Speculative fix for submission-seeding issue

apps/flutter_parent/android/app/build.gradle, apps/flutter_parent/lib/screens/alerts/alerts_screen.dart
=> [Parent] Add animation to alert deletion

apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart, apps/flutter_parent/lib/utils/common_widgets/avatar.dart, apps/flutter_parent/test/utils/widgets/avatar_test.dart
- Uses darker color for help icon on login landing screen
- Uses correct styling for group message icon
=> [Flutter Parent] More UI tweaks

apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart
To test:
Make sure assignments without descriptions finish loading.
Make sure assignments with descriptions finish loading.
Make sure assignments that are locked finish loading.
=> [Flutter-Parent] Fix always loading when assignment has no description

apps/flutter_parent/lib/utils/common_widgets/web_view/canvas_web_view.dart
For users that have a killed app and click on a link to a screen with a web view, then press the back button, a crash can occur. This sidesteps that _slightly_ by not displaying the web view in an inactive state, though hopefully one day the flutter team will fix the issue plaguing JNI linking and we won’t need this anymore.
=> [Flutter-Parent] Fix issues with JNI linking for web views

apps/flutter_parent/lib/screens/courses/details/course_details_model.dart, apps/flutter_parent/lib/screens/courses/details/course_details_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_front_page_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_grades_screen.dart, apps/flutter_parent/lib/screens/courses/details/course_syllabus_screen.dart, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/screens/courses/course_details_screen_test.dart
To Test:
Move between the various tabs to ensure that contextual messaging properly sets the subject.
=> [Parent][RC 3.2.0] Fix for contextual messaging and version bump

apps/flutter_parent/lib/screens/qr_login/qr_login_tutorial_screen_interactor.dart, apps/flutter_parent/lib/utils/veneers/barcode_scan_veneer.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/screens/login/qr_login_tutorial_screen_interactor_test.dart
Behavior unchanged, just had to modify some of the error handling logic and get those tests passing.
=> [Parent] Barcode Scanner 3.0

apps/flutter_parent/android/app/src/main/kotlin/com/instructure/parentapp/plugins/OldAppMigrations.kt, apps/flutter_parent/lib/network/utils/api_prefs.dart, apps/flutter_parent/lib/screens/manage_students/manage_students_screen.dart, apps/flutter_parent/lib/screens/qr_login/qr_login_tutorial_screen.dart, apps/flutter_parent/lib/utils/crash_utils.dart, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/network/api_prefs_test.dart, apps/flutter_parent/test/utils/widgets/masquerade_ui_test.dart
=> [Flutter-Parent][RC-3.2.0] Fix migration for users not on refresh tokens

apps/flutter_parent/lib/models/grading_period.dart, apps/flutter_parent/lib/models/grading_period.g.dart, apps/flutter_parent/lib/screens/dashboard/student_horizontal_list_view.dart, apps/flutter_parent/pubspec.yaml
int -> double for grading period weight
null fix for add student
version bump
=> [Parent][RC 3.2] Hotfix changes

apps/flutter_parent/lib/models/dataseeding/create_course_info.dart, apps/flutter_parent/lib/models/dataseeding/create_course_info.g.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/conversation_details_screen.dart, apps/flutter_parent/lib/screens/inbox/conversation_details/message_widget.dart, apps/flutter_parent/lib/screens/inbox/conversation_list/conversation_list_screen.dart, apps/flutter_parent/lib/screens/inbox/create_conversation/create_conversation_screen.dart, apps/flutter_parent/test_driver/apis/course_seed_api.dart, apps/flutter_parent/test_driver/flutter_driver_extensions.dart, apps/flutter_parent/test_driver/inbox.dart, apps/flutter_parent/test_driver/inbox_test.dart, apps/flutter_parent/test_driver/pages/assignment_details_page.dart, apps/flutter_parent/test_driver/pages/conversation_create_page.dart, apps/flutter_parent/test_driver/pages/conversation_details_page.dart, apps/flutter_parent/test_driver/pages/conversation_list_page.dart, apps/flutter_parent/test_driver/pages/course_details_page.dart, apps/flutter_parent/test_driver/pages/course_grades_page.dart, apps/flutter_parent/test_driver/pages/dashboard_page.dart
I tried to be pretty comprehensive about sending emails from various places, as well as replying to an email, and making sure that all of the info showed up properly in the conversation list / inbox.
=> [Parent][E2E][MBL-13949] |  Inbox E2E test for Parent

apps/flutter_parent/lib/screens/calendar/calendar_widget/calendar_widget.dart, apps/flutter_parent/lib/screens/dashboard/dashboard_screen.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/test/screens/calendar/calendar_widget/calendar_widget_test.dart, apps/flutter_parent/test/screens/dashboard/dashboard_screen_test.dart
May also fix the tests that were failing sometimes
=> [Flutter-Parent] Fix today notifier crashing when switching users

apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTestExtensions.kt
"Flaky" in this case = "Fails frequently on tablet runs"
=> [Student][Automation][MBL-14348]: Speculative fixes for a couple of flaky tests

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SettingsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/PairObserverRenderTest.kt
Mostly related to the new PairObserver functionality.
=> MBL-14369: Assorted test fixes.

libs/flutter_student_embed/.gitignore, libs/flutter_student_embed/lib/screens/to_do/to_do_details_screen.dart, libs/flutter_student_embed/lib/utils/design/student_colors.dart, libs/flutter_student_embed/pubspec.lock, libs/flutter_student_embed/pubspec.yaml, libs/flutter_student_embed/test/models/enrollment_test.dart, libs/flutter_student_embed/test/network/paged_list_test.dart, libs/flutter_student_embed/test/screens/to_do/to_do_details_screen_test.dart, libs/flutter_student_embed/test/testutils/accessibility_utils.dart, libs/flutter_student_embed/test/testutils/finders.dart, libs/flutter_student_embed/test/testutils/mock_helpers.dart, libs/flutter_student_embed/test/testutils/network_image_response.dart, libs/flutter_student_embed/test/testutils/platform_config.dart, libs/flutter_student_embed/test/testutils/test_app.dart, libs/flutter_student_embed/test/testutils/test_utils.dart, libs/flutter_student_embed/tools/code_coverage.dart, libs/flutter_student_embed/tools/codecov_exclusions, libs/flutter_student_embed/tools/l10n_extract_push.rb, libs/flutter_student_embed/tools/process_test_results.bash, libs/flutter_student_embed/tools/run_all_ui_tests.bash
Added a test for each directory to have that established. Migrated over all the infrastructure related things to testing, making a new 'testutils' directory for it (rather than being intermixed with actual 'utils' tests for production code)
Had to make some changes to colors/styles too get a11y to pass.
To test, just run the tests 😄
The code coverage tool should work for this module now. Lots of missing coverage from tests that still need to be ported over or written.
=> [Student][MBL-14363] Testing infrastructure for student flutter

apps/student/src/main/java/com/instructure/student/fragment/FlutterCalendarFragment.kt
To test: Tap multiple tabs on the bottom nav bar such that there are two more more planner fragments in the back stack. Background and then resume the app. Navigating back to a previous planner fragment should no longer result in a white screen and the planner should be fully interactive.
=> [Student][MBL-14374] Fix white planner screen after backgrounding the app

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/MediaComment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Message.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/ApiPactTestBase.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/InboxApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/SubmissionsApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactConversationLogic.kt
Also commented out a couple of unused model fields.
=> [Student][Pact][MBL-14235] | Add Pact tests for conversations/inbox

apps/teacher/src/main/java/com/instructure/teacher/adapters/DiscussionListAdapter.kt, apps/teacher/src/main/java/com/instructure/teacher/events/BusEvents.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionBottomSheetMenuFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/DiscussionsDetailsPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/viewinterface/DiscussionsDetailsView.kt, apps/teacher/src/main/res/layout/bottom_sheet_discussion_menu.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/DiscussionAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/DiscussionManager.kt, libs/pandautils/src/main/assets/discussion_html_footer_item.html, libs/pandautils/src/main/assets/discussion_html_footer_item_rtl.html, libs/pandautils/src/main/assets/discussion_html_header_item.html, libs/pandautils/src/main/assets/discussion_html_header_item_rtl.html, libs/pandautils/src/main/assets/discussion_html_template_item.html, libs/pandautils/src/main/assets/discussion_html_template_item_rtl.html, libs/pandautils/src/main/java/com/instructure/pandautils/discussions/DiscussionEntryHtmlConverter.kt
Make sure to test RTL as well!
=> [Teacher][MBL-14300] Mark discussion reply as unread

apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/PermissionUtils.kt, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.java
See ticket for repro steps and creds. 
I have also setup a test quiz in my sandbox for april, if you don't want to be submitting to someone else's sandbox. 
Side note: I have no idea where the files go. I couldn't find them in the user files, nor the course files. Must be some special place for quiz file uploads.
=> [Student][MBL-14353] Allow file uploads for question bank quizzes

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomActions.kt
I ran the resulting DiscussionsInteractionTest suite against FTL several times and these changes seem to make a difference in stability.  There were some failures, followed by additional fixes, and it seems like we landed in a good place.
But I can't promise that this will be the last round of stabilization needed.
=> [Student][Automation][MBL-14436]: Speculative fixes for some discussion tests

apps/student/src/main/java/com/instructure/student/fragment/FlutterCalendarFragment.kt
Adds an additional fix for re-attaching FlutterView to the engine when using multiple FlutterFragments. This is a workaround for changes introduced into the Flutter engine [here](https://github.com/flutter/engine/pull/16527).
=> [Student][R-6.8.0] Fix Flutter re-attach issue

buildSrc/src/main/groovy/TimingsListener.groovy
I was adding up individual build times for all subtasks, but that seemed to come up short.  What I measure/report now is much more representative of a cumulative build time.
=> [Ops][MBL-14498]: Fix build time reported to Splunk

apps/student/src/main/java/com/instructure/student/dialog/HelpDialogStyled.kt, apps/teacher/src/main/java/com/instructure/teacher/dialog/HelpDialogStyled.kt
Just removed the requirement for the tel: link to include a plus.
=> [Student][Teacher][MBL-14492] Update for TEL: phone links

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/network/utils/analytics.dart, apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart, apps/flutter_parent/lib/screens/pairing/qr_pairing_screen.dart, apps/flutter_parent/lib/screens/qr_login/qr_login_util.dart, apps/flutter_parent/lib/utils/service_locator.dart, apps/flutter_parent/test/router/panda_router_test.dart, apps/flutter_parent/test/screens/login/login_landing_screen_test.dart
Adds the bottom sheet picker and modifies the QRPairingScreen to prep it for routing to account creation (coming soon **TM**).
=> [Parent][MBL-14287] QR Account creation chooser

apps/flutter_parent/lib/models/serializers.dart
This will hopefully fix E2E tests
=> [Parent] Remove UserColor from serializer

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/QuizAPI.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/QuizzesApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/logic/PactQuizLogic.kt
Removed one test, changed another to point at a different (still "hot") endpoint.  Removed no-longer-used endpoints.
=> [Student][Pact][MBL-14528]: Adjusted quiz pact tests

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AddMessagePageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/DiscussionsListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxMessagePageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CoursesListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DiscussionsListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTestExtensions.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt
Also MBL-14575: Convert DiscussionListPageTest from Ditto to MockCanvas.
=> [Teacher][MBL-14574][MBL-14575]: Convert inbox tests from Ditto to MockCanvas

apps/teacher/src/main/java/com/instructure/teacher/presenters/AllCoursesPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/CoursesPresenter.kt
This change also updates AllCoursesPresenter to use coroutines for loading data
=> [Teacher][MBL-11774] Update course colors when refreshing the dashboard or all-courses list

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssigneeListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentDetailsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentDueDatesPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentSubmissionListPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditAssignmentDetailsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AddMessagePage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssigneeListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentListPage.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/AssignmentEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/SubmissionEndpoints.kt, automation/canvas_espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/utils/Randomizer.kt
Phew -- this one took some work.
=> [Teacher][Assignments][MBL-14577] | Convert assignment-related tests from Ditto to MockCanvas

apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
Test plan: see [ticket](https://instructure.atlassian.net/browse/MBL-14641) for credentials and repro
=> [MBL-14641][Student/Teacher] Fix links to files in new RCE

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
=> [Student][Settings][MBL-14614]: Fixed searchCanvasGuides test

README.md
Also updates the parent build command
=> Update readme with student/teacher build status

apps/student/build.gradle
Probably not super crucial, but with 6.8.2 being a tag cut release I wanted to update the version number to avoid confusion for next release.
=> [Student] Update build version to reflect release 6.8.2

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt
Just cherry picked this from master to the 6.8.3 release.
=> [Student][RC 6.8.3] Cherry pick fix for quizzes 2 lti

libs/login-api-2/src/main/java/com/instructure/loginapi/login/adapter/DomainAdapter.kt
To repro: Open the Find My School page in either Student or Teacher, type in any number of characters in the search field, and press backspace to clear out all characters.
=> [loginapi] Fix crash in domain search screen

apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/views/GradeCellRenderTest.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeCellView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeCellViewState.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/gradeCell/GradeStatisticsView.kt, apps/student/src/main/res/layout/view_student_grade_cell.xml, apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/AssignmentAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AssignmentScoreStatistics.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/AssignmentsApiPactTests.kt, libs/pandares/src/main/res/values/strings.xml
refs: MBl-14711
affects: student
release note: Added support for assignment score statistics
=> Add score statistics

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt
Need to compensate for altered web content of privacy policy.
refs: MBL-14724
release note: Fixed the privacy policy test
=> [Student][Tests][MBL-14724]: Fix privacy policy test

apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt
refs: MBL-14776
release note: Fixed an inbox test
=> [Student][Inbox][MBL-14776]: Fix a problem with delete-message test in landscape mode

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/QuizTakingPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/QuizzesApi.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/QuizApiModel.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomWebViewLogic.kt
refs: MBL-14749
release note: Added e2e test for webview-based quizzes
=> [Student][Quizzes][MBL-14749]: Re-wrote quiz e2e test for webview-based quizzes

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/QuizzesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt
Can't get it working in FTL.  May revisit later, but for now I don't want it failing our nightly E2E runs.
refs: MBL-14781
release note: Disabled the QuizzesE2ETest
=> [Student][Quizzes][MBL-14781]: Stubbed QuizzesE2ETest

apps/flutter_parent/lib/screens/calendar/planner_fetcher.dart, apps/flutter_parent/test/screens/calendar/planner_fetcher_test.dart
See ticket for repro
refs: MBL-14738
release note: Fixes duplicate events showing on the calendar
=> [Parent][MBL-14738] Fix duplicate calendar events

apps/gradle.properties, apps/settings.gradle, apps/student/build.gradle, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/AssignmentDetailsRenderTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/renderTests/UploadStatusSubmissionRenderTest.kt, apps/student/src/main/java/com/instructure/student/db/Extensions.kt, apps/student/src/main/java/com/instructure/student/util/FileDownloadJobIntentService.kt, apps/student/src/test/java/com/instructure/student/db/sqlColAdapters/SubmissionDbQueriesTest.kt, apps/student/src/test/java/com/instructure/student/test/SubmissionServiceTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsUpdateTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submission/UploadStatusSubmissionUpdateTest.kt, apps/teacher/build.gradle, automation/espresso/build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/java/GlobalDependencies.kt, gradle/coverage.gradle, gradle/gradle/wrapper/gradle-wrapper.properties, libs/annotations/src/main/java/com/instructure/annotations/FileCaching/FetchFileAsyncTask.kt, libs/canvas-api-2/build.gradle, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/QLClientConfig.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/AwaitQL.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/weave/AwaitQLPaginated.kt, libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.kt
=> [Ops][MBL-14770] Update Android Gradle Plugin

apps/teacher/src/main/java/com/instructure/teacher/fragments/CreateOrEditPageDetailsFragment.kt
refs: MBL-14789
release note: Added unsaved changes confirmation dialog for back press on Page details.
test plan:
=> MBL-14789 - Unsaved changes confirmation dialog on back press.

.gitcommit
refs:
affects: ALL
release note:
test plan:
=> Added -gitcommit to the project.

libs/pandautils/src/main/java/com/instructure/pandautils/fragments/RemoteConfigParamsFragment.kt
Fixed a problem where old TextWatchers were still registered with a ViewHolder when it got recycled on the Remote Config settings page, resulting in multiple responses to field changes.  This was causing the RemoteConfig E2E test to fail, but it was actually an app issue.
refs: MBL-14822
release note: Fixed internally used Remote Config settings page
=> [Student][Teacher][RemoteConfig][MBL-14822]: Fix problem on remote config settings page

apps/student/flank_sweep.yml
I did a run of our tests against API-30 on FTL and everything passed.  So we shouldn't have any problems right out of the gate.
=> [Student][API-30][MBL-14821]: EZ: Now including API-30 in our multi-device runs

apps/student/flank.yml, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ProfileSettingsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PandaAvatarPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ProfileSettingsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/res/layout/panda_image.xml
I added a test for creating and saving a Panda avatar.
I also spent some time trying code up some tests for Mastery Paths, but ultimately shelved that due to its significant complexity and sketchy documentation.
Overall coverage went from 51.4% to 52.4% with this new test.
=> [Student][Coverage][MBL-14756] | code coverage rd3

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ModuleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/InboxConversationPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt
Now testing that the assignment within the locked module has the "locked" icon on it and does not respond to clicks.
=> [Student][Modules][MBL-14865]: A better test for a locked module

apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ModuleListPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListRecyclerAdapter.kt, apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/ModuleListViewState.kt, apps/teacher/src/main/java/com/instructure/teacher/features/modules/list/ui/binders/ModuleListEmptyItemBinder.kt, apps/teacher/src/main/res/layout/adapter_module_empty_item.xml, apps/teacher/src/test/java/com/instructure/teacher/unit/modules/ModuleListPresenterTest.kt
refs: MBL-14841
release note: Empty state added for modules with no items.
test plan:
=> [Teacher][MBL-14841] Empty state added for modules with no items

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Account.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AccountNotification.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AccountRole.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignee.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AuthenticatedSession.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/CanvasError.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/CanvasTheme.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ColumnDatum.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/CreateFolder.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/CustomColumn.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/GradeableStudentSubmission.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Placements.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/QuizOverride.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/StreamItem.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Tab.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ToDo.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/UsageRights.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/User.kt
Just removed some old todos that we don't need anymore
=> [all] Clean up some no longer needed TODOs

apps/student/src/main/res/layout/panda_image.xml, apps/student/src/main/res/values/dimens.xml
refs: MBL-14880
release note: Fixed some accessibility issues in the Profile Settings / Create Panda Avatar screen
=> [Android][MBL-14880]: Fixed some accessibility issues in the panda avatar creation screen

apps/teacher/flank_landscape.yml, apps/teacher/flank_sweep.yml, apps/teacher/flank_tablet.yml
Added .yml files to create new bitrise workflows for UI Tests.
Tablet mode:
https://app.bitrise.io/build/7722b0f9b838e19a#?tab=log
=> [Teacher][Tests][MBL-14757] | Enable teacher start nightly runs

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/InboxPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/ModuleListRenderTest.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/EditQuizDetailsFragment.kt
The multi_device test run now passes with these changes.
https://app.bitrise.io/build/40030a15d2f265bc
=> [Teacher][Tests][MBL-14939] | Address API-23 test failures for the teacher app

apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt
Testing: Repro steps are in the ticket.
refs: MBL-14946
release note: Fixed an issue when the time is not shown on calendar events in some cases.
=> [Student][MBL-14946] Calendar event won't show time if start time and end time is the same

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
Testing: Repro steps are well defined in the ticket. I would suggest creating test data in your own sandbox, instead of using the one specified in the ticket, because dates are important here, and the ticket was created 3 years ago, also you can edit the dates of the course to check edge cases.
refs: MBL-14870
release note: Fixed a bug where in some cases students can't see course invites
=> [Student][MBL-14870] Course participation setting prevents students from seeing invitations on the dashboard

apps/student/flank_tablet.yml, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PushNotificationInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/TodoInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/FileListPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NotificationPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/TodoPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/UserEndpoints.kt
(1) Added a test for ToDo page filtering
(2) Added a basic test for the notification page
(3) Extended the FilesE2ETest to test renaming and deleting of file
=> [Student][Tests][MBL-14912] | more code coverage

apps/teacher/build.gradle, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
Added teacher dashboard e2e test
refs: MBL-14918
=> MBL-14918 Teacher dashboard e2e test

apps/student/src/main/java/com/instructure/student/adapter/QuizListRecyclerAdapter.kt, apps/teacher/src/main/java/com/instructure/teacher/holders/QuizViewHolder.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/QuizListPresenter.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/QuizAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Quiz.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/QuizzesApiPactTests.kt
Testing: In the JIRA ticket
refs: MBL-14899
release note: Fixed a bug where quizzes created with New Quizzes don't show in the list.
=> [MBL-14899][Student][Teacher] New Quizzes assignments do not display on quiz index

apps/flutter_parent/lib/models/locked_module.dart, apps/flutter_parent/lib/models/locked_module.g.dart
Simple nullability fix for this field, which was causing the course details page to not load.
refs: MBL-14976
release note: Fixed a bug causing some courses to not load
test plan:
See ticket.
=> [Parent][MBL-14976] Fixed bug with courses not loading in parent

apps/teacher/flank_e2e.yml, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt
=> [MBL-14974][Teacher] Added flank_e2e.yml and updated DashboardE2ETest

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditQuizDetailsPage.kt, apps/teacher/src/main/res/layout-sw760dp/view_submissions_donut_group.xml, apps/teacher/src/main/res/layout/fragment_assignment_details.xml, apps/teacher/src/main/res/layout/fragment_quiz_details.xml, buildSrc/src/main/java/GlobalDependencies.kt, libs/pandautils/build.gradle, libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/RatingDialog.kt, libs/pandautils/src/main/java/com/instructure/pandautils/dialogs/UploadFilesDialog.kt, libs/rceditor/src/main/java/instructure/rceditor/RCEFragment.kt
We had to update the Material Design library to make the Chips in the inbox accessible. Unfortunately this added some transitive dependency changes which caused some build issues (basically they just updated the libraries with nullability annotations). Also from the 1.2.0 version of the Material Design library the Swipe Refresh Layout is packaged separately so we had to add that as well.
Testing: Run the mentioned UI tests on a Nexus 9 API 25 emulator. Also a quick smoke testing the teacher and the student app would be good, because a global dependency version was upgraded.
refs: MBL-14949
release note: Fixed accessibility issues.
=> [MBL-14949][Teacher] Accessibility issue on multiple pages on TABLET

apps/flutter_parent/android/build.gradle, apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/lib/utils/notification_util.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml, apps/flutter_parent/test/utils/notification_util_test.dart, apps/flutter_sdk_url, buildSrc/src/main/java/com/instructure/android/buildtools/transform/FlutterA11yOffsetTransformer.kt, libs/flutter_student_embed/pubspec.lock, libs/flutter_student_embed/pubspec.yaml
refs: MBL-14938
release notes: Updated the flutter SDK and the outdated dependencies.
=> [MBL-14938][Parent] Update flutter version

apps/teacher/build.gradle
refs:
affects:
release note:
test plan:
=> Version Bump 11.1.5 (37)

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderGradePage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTestExtensions.kt, apps/teacher/src/main/res/layout/fragment_assignment_submission_list.xml, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
refs: MBL-14901
release notes: Extended test matrix
=> [MBL-14901][Teacher] Created speedgrader e2e tests

apps/flutter_parent/lib/network/api/auth_api.dart, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/OAuthAPI.kt
refs: MBL-15011
affects: All
release note: Moved sensitive data from query parameters to body on OAuth calls.
=> [MBL-15011][All] Moved sensitive data from OAuth token query params.

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
refs: MBL-15014
release note: Fixed a crash in Speed Grader.
=> [Teacher][MBL-15014] PdfFragment crash fix

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/StudentContextPage.kt
=> [MBL-14902][Teacher] Created E2E test for People

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
=> [MLB-15012][Student]Reworked assignments e2e test, assignment types are being tested separately

automation/espresso/src/main/kotlin/com/instructure/espresso/ScreenshotTestRule.kt
=> [MBL-15083][Teacher][Student]Raised the number of test retries on failures from 1 to 4

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt
refs: MBL-15002
release note: Fixed a bug where an unwanted error message was visible.
test plan:
Steps to reproduce in the ticket. The unwanted error message should no longer be visible.
=> [MBL-15002][Student] Unexpected error toast fix.

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderPage.kt
=> [MBL-15053][Teacher] Tablet workflow test fixes

apps/teacher/flank.yml
=> [MBL-14972][Teacher] Update flank yml, now ready to use with bitrise primary forklow

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt
Test plan: In the ticket: https://instructure.atlassian.net/browse/MBL-15016
refs: MBL-15016
release note: Fixed a bug where not graded assignments show up in grades.
=> [Student][MBL-15016] Grades page includes items that are not_graded

apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart, apps/flutter_parent/test/screens/login/domain_search_screen_test.dart, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginFindSchoolActivity.kt
refs: MBL-15030
affects: All
release note:
test plan: If you write something in the domain search that ends with '.', we should navigate to that domain without the period.
=> [MBL-15030][All] Remove period at the end of the domain

apps/flutter_parent/lib/screens/web_login/web_login_screen.dart, apps/flutter_parent/test/screens/login/web_login_screen_test.dart, apps/teacher/src/test/java/com/instructure/teacher/features/calendar/event/CalendarEventStateTransformerTest.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.kt, libs/login-api-2/src/main/res/layout/activity_sign_in.xml
Testing: Steps are in the ticket.
refs: MBL-14784
affects: All
release note: Improved loading indication on the login screen.
=> [MBL-14784][All] Improve loading indication in the login webview

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditSyllabusPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditQuizDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditSyllabusPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/pages/EditSyllabusRenderPage.kt
Test: Executed via bitrise
refs: MBL-15055
=> [MBL-15055][Teacher]Landscape mode test fixes

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt, apps/student/src/main/java/com/instructure/student/util/CourseModulesStore.kt
Test plan: Repro steps in the ticket. Please also test if the module progression can open correctly from a bookmarked module.
refs: MBL-15076
release note: Fixed a crash when trying to open a module in a course which has lots of modules.
=> [MBL-15076][Student] App crashes when accessing module items

apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/SyllabusUpdate.kt, apps/teacher/src/test/java/com/instructure/teacher/features/syllabus/SyllabusUpdateTest.kt
=> [Teacher][MBL-15114] Edit syllabus changes are not visible after saving them

apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusView.kt
=> [Teacher][MBL-15115] Edit syllabus pull-to-refresh screen problem

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt, automation/espresso/src/main/kotlin/com/instructure/espresso/ViewInteractionExtensions.kt
refs: MBL-15080
affects: Automation
test plan: -
=> [MBL-15080][Automation] Swipe up action created

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SyllabusE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SyllabusPage.kt
=> [MBL-15054][Teacher]Syllabus E2E test added for teacher

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderGradePageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderGradePage.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/SubmissionEndpoints.kt
refs: MBL-15113
affects: Automation
test plan: -
=> [MBL-15113][Automation] Added UI tests for SpeedGrader grading

apps/student/src/main/java/com/instructure/student/holders/ModuleViewHolder.kt, apps/student/src/main/res/layout/viewholder_module.xml
refs: MBL-15086
release note: Fixed indentation in modules list.
=> [Student][MBL-15086] Module indentation not available

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditPageDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PageListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
=> [MBL-15131][Teacher] PagesE2E tests added for teacher

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt
=> [MBL-15143][Teacher] Accessibility fix on speedgrader

apps/teacher/src/main/java/com/instructure/teacher/view/grade_slider/SpeedGraderSlider.kt, apps/teacher/src/main/res/layout/view_speed_grader_slider.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewExtensions.kt
Test plan: Test if the touch is detected on the SpeedGrader buttons when clicking slightly outside of the border. Show pointer location setting can be helpful.
refs: MBL-15139
=> [MBL-15139][Teacher] Move TouchTarget delegate to extension

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ModulesPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
=> [MBL-15154][Teacher]Modules E2E tests added for teacher

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderCommentsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SpeedGraderGradePageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderCommentsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderPage.kt
refs: MBL-15128
test plan: Execute Landscape workflow on Bitrise
=> [MBL-15128][Teacher]Fix speedgradercommentspagetest on landscape

apps/flutter_parent/lib/screens/account_creation/account_creation_interactor.dart, apps/flutter_parent/lib/screens/help/legal_screen.dart, apps/flutter_parent/test/screens/account_creation/account_creation_interactor_test.dart, apps/flutter_parent/test/screens/help/legal_screen_test.dart, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/SettingsInteractionTest.kt, apps/student/src/main/java/com/instructure/student/dialog/LegalDialogStyled.kt, apps/teacher/src/main/java/com/instructure/teacher/dialog/LegalDialog.kt
refs: MBL-15184
affects: All
release note: Added new Privacy Policy URL
test plan: Settings > Legal > Privacy Policy
=> [MBL-15184][All] Changed Privacy Policy

apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/InternalWebviewFragment.kt
refs: MBL-15048
release note: Fixed a bug where links couldn't be opened in the app in HTML files.
=> [MBL-15048][Student] Routing from HTML files is not working

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AnnouncementsListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditAnnouncementPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
=> [MBL-15171][Teacher]Added announcements e2e test for teacher

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AddMessagePage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/ChooseRecipientsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
Inbox E2E test added for Teacher
refs: MBL-15185
=> [MBL-15185][Teacher] create inbox e2e test teacher

scripts/generate-release-notes.js, scripts/generate_release_notes.js
refs: MBL-15176
affects: Ops
release note: Release notes are generated automatically
test plan: -
=> [MBL-15176][Ops] Release notes automation

apps/student/src/main/java/com/instructure/student/activity/ShareFileUploadActivity.kt, apps/student/src/main/java/com/instructure/student/adapter/AllCoursesRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/EditFavoritesRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/TodoListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/dialog/CanvasContextListDialog.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ModelExtensions.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt
Test plan: In the ticket. You can compare the courses in the all courses list with the web. It would be also good to test all the screens which were affected by the api call change.
refs: MBL-15116
release note: Fixed a bug where hard completed courses didn't show up in course list.
=> [MBL-15116][Student] Hard-completed enrollments cannot be accessed

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/EnrollmentAPI.kt
refs: MBL-15165
release note: Fixed a bug where invites wasn't shown for future courses.
=> [Student][MBL-15165] Course participation dates in the future prevent students from seeing invitations

apps/student/src/main/java/com/instructure/student/adapter/assignment/AssignmentListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/fragment/AssignmentListFragment.kt, libs/pandares/src/main/res/values/strings.xml
=> [MBL-15202][Student] Change the assignments list screen's title

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/ToDoManager.kt
refs: MBL-15201
release note: Fixed a bug where items in the ToDo widget would appear out of order.
=> [MBL-15201][Student] ToDo widget items soring

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/content/TextSubmissionViewFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderTextSubmissionFragment.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/assets/html_wrapper.html, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt
Test plan: Enable TalkBack and try to iterate over to the WebView in screens where it loads downloaded html content.
refs: MBL-15181
affects: Student/Teacher
release note: Fixed accessibility issues related to web content.
=> [MBL-15181][Student][Teacher] TalkBack WebView focus

apps/student/src/main/java/com/instructure/student/adapter/ModuleListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/fragment/ModuleListFragment.kt
Test plan: The two linked tickets in the story description should be tested. Test users and description can be found in the ticket.
refs: MBL-15070
release note: Added empty view for modules.
=> [MBL-15070][Student] Module empty state

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/views/CommentMediaAttachmentView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/comments/ui/views/CommentSubmissionView.kt, apps/student/src/main/res/layout/view_comment_submission_attachment.xml, apps/teacher/src/main/java/com/instructure/teacher/view/CommentMediaAttachmentView.kt, apps/teacher/src/main/java/com/instructure/teacher/view/CommentSubmissionView.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/MediaComment.kt, libs/pandares/src/main/res/values/strings.xml
refs: MBL-15243
release note: Fixed a crash on the submission screen.
=> [Student/Teacher][MBL-15243] CommentSubmissionView crash

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/TodoPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
=> [MBL-15224][Teacher]Added Todo E2E tests for teacher

apps/teacher/src/main/java/com/instructure/teacher/services/FileDownloadService.kt
refs: MBL-15247
release note: Fixed a crash.
test plan:
=> [MBL-15247][Teacher] FileDownloadService crash fix

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
refs: MBL-15248
release note: Fixed a crash
=> [MBL-15248][Student] CourseModuleProgressionFragment crash

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/EditQuizDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/EditQuizDetailsPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/viewinterface/EditQuizDetailsView.kt, apps/teacher/src/main/res/layout/fragment_edit_assignment_details.xml, apps/teacher/src/main/res/layout/fragment_edit_quiz_details.xml
refs: MBL-15246
release note: Fixed a crash
=> [MBL-15246][Teacher] EditQuizDetailsFragment and EditAssignmentDetailsFragment crashes

apps/student/src/main/AndroidManifest.xml, apps/teacher/src/main/AndroidManifest.xml, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt, libs/pandautils/src/main/res/xml/network_security_config.xml
=> [Student][Teacher][MBL-15242] Disable cleartext traffic in WebViews

apps/student/src/main/res/layout/fragment_submission_message.xml, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsPresenterTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/GradeCellStateTest.kt, apps/teacher/src/main/res/layout/adapter_course_browser.xml, apps/teacher/src/main/res/layout/fragment_course_browser_empty.xml, apps/teacher/src/main/res/layout/fragment_empty.xml, apps/teacher/src/main/res/layout/fragment_not_a_teacher.xml, apps/teacher/src/main/res/layout/fragment_speedgrader_empty.xml, apps/teacher/src/main/res/menu/menu_compose_message_activity.xml, libs/login-api-2/src/main/res/values/styles.xml, libs/pandares/src/main/res/values/colors.xml, libs/pandautils/src/main/assets/discussion_html_header_item.html, libs/pandautils/src/main/assets/discussion_html_header_item_rtl.html, libs/pandautils/src/main/assets/discussion_html_template_item.html, libs/pandautils/src/main/assets/discussion_html_template_item_rtl.html, libs/rceditor/src/main/res/values/rce_colors.xml
refs: MBL-15087
test plan: Generally check the subtitles/dates/etc. that everything displays correctly.
=> [MBL-15087][Teacher/Student] A11y compliant 'faded' color

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/SyllabusPageTest.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt
Test plan: Test if the syllabus is working correctly.
refs: MBL-15255
=> [Teacher][MBL-15255] Removed syllabus feature flag

apps/student/src/main/res/layout/fragment_file_list.xml
Test Plan: Open the files screen -> Tap on the "Add files/folders" tab and open the items -> Traverse forward with TalkBack and check if it announces the new items.
refs: MBL-15100
release note: Fixed an accessibility issue
=> [MBL-15100][Student] Accessibility fix in Files

apps/student/src/main/java/com/instructure/student/fragment/CalendarFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/FlutterCalendarFragment.kt, libs/flutter_student_embed/lib/screens/calendar/calendar_screen.dart, libs/flutter_student_embed/lib/screens/to_do/create_update_to_do_screen.dart, libs/flutter_student_embed/lib/screens/to_do/to_do_details_screen.dart, libs/flutter_student_embed/lib/utils/alert_dialog_channel.dart, libs/flutter_student_embed/test/screens/to_do/create_update_to_do_screen_test.dart, libs/flutter_student_embed/test/screens/to_do/to_do_details_screen_test.dart
Test plan: Test both dialogs on the Calendar screen of the Student app. More details in the ticket.
refs: MBL-15099
release note: Fixed accessibility issues
=> [Student][MBL-15099] Fixed dialog accessibility issues in Flutter embed

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt
=> [Teacher][MBL-15281]Added scroll to Announcements interaction tests on course browser

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizListPage.kt
=> [MBL-15282][Teacher]Added Quiz E2E Test

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt
=> [MBL-15287][Teacher]Fixed AnnouncementsE2ETest on teacher

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditQuizDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizListPage.kt
=> [MBL-15289][Teacher]Extend quiz e2e tests on teacher

apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SettingsFragment.kt, apps/teacher/src/main/res/layout/fragment_settings.xml, apps/teacher/src/main/res/layout/navigation_drawer.xml, apps/teacher/src/main/res/values/styles.xml
refs: MBL-15273
release note: Menu redesign
test plan:
=> [MBL-15273][Teacher] Navigation drawer redesign

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt, apps/student/src/main/res/layout/navigation_drawer.xml, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/NavDrawerPage.kt, apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt, apps/teacher/src/main/res/layout/navigation_drawer.xml
refs: MBL-15326
affects: All
test plan:
=> [MBL-15326][All] Fix NavDrawer tests

apps/student/src/main/java/com/instructure/student/activity/ShareFileUploadActivity.kt, apps/student/src/main/java/com/instructure/student/adapter/AllCoursesRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/EditFavoritesRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/adapter/TodoListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/dialog/CanvasContextListDialog.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ModelExtensions.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/CoursesApiPactTests.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt
This reverts the changes made in MBL-15116, because it caused a bug.
refs: MBL-15334
release note: Fixed a bug where students could see courses where they were not enrolled.
=> [Student][MBL-15334] Deleted enrollments show on the dashboard

apps/student/src/main/java/com/instructure/student/adapter/TodoListRecyclerAdapter.kt
refs: MBL-15323
release note: Fixed a bug where grading tasks show up in the To Do list
=> [Student][MBL-15323] Students can see items needing grading in To Do if they have TA roles in other courses

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AssignmentDetailsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditAssignmentDetailsPage.kt
=> [MBL-15294][Teacher]Added Assignment E2E tests for teacher

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionsReplyFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/DiscussionsDetailsPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/viewinterface/DiscussionsDetailsView.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/PandaRationedBusEvent.kt
refs: MBL-15301
release note: Fixed a bug where new discussion replies don't get focus.
=> [MBL-15301][Student][Teacher] Discussion replies don't get focus

apps/teacher/src/main/java/com/instructure/teacher/fragments/PageDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteResolver.kt
refs: MBL-15338
release note: Fixed a bug where modules open outside the app.
=> [MBL-15338][Teacher] ModuleList routing

apps/teacher/src/main/java/com/instructure/teacher/router/RouteResolver.kt
refs: MBL-15366
test plan: Go to modules page.
=> [MBL-15366][Teacher] Modules crash fix

apps/student/build.gradle, apps/teacher/build.gradle, buildSrc/src/main/java/GlobalDependencies.kt
refs: MBL-15285
affects: All
test plan: Sanity check
=> [MBL-15285][All] play:core dependency update

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricPresenter.kt
refs: MBL-15335
release note: Fixed a crash on Submissions & Rubrics.
test plan: Repro steps in the ticket.
=> [MBL-15335][Student] Fixed a crash on submissions & rubrics

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/res/layout/fragment_discussions_details.xml, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt, apps/teacher/src/main/res/layout/fragment_discussions_details.xml, libs/pandares/src/main/res/values/strings.xml
refs: MBL-15121
test plan: Go to discussion details > If the screen reader is enabled a button should be visible on the top that navigates to a webview with the same discussion.
=> [MBL-15121][Student][Teacher] Accessibility button added for discussions

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt, apps/student/src/main/res/layout/fragment_assignment_details.xml
refs: MBL-15264
test plan: Using TalkBack the Submit button should appear at the top of the screen, not obstructing the webview.
=> [MBL-15264][Student] Added accessibility button to assignment details

apps/teacher/src/main/java/com/instructure/teacher/activities/LoginLandingPageActivity.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/viewmodel/LoginViewModel.kt, libs/login-api-2/src/test/java/com/instructure/loginapi/login/viewmodel/LoginViewModelTest.kt, libs/pandautils/src/main/java/com/instructure/pandautils/di/FeatureFlagModule.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt, libs/pandautils/src/test/java/com/instructure/pandautils/utils/FeatureFlagProviderTest.kt
=> [MBL-15436][Student] Standard Dashboard showing for K5 users when offline

libs/pandautils/src/main/java/com/instructure/pandautils/typeface/TypefaceBehavior.kt
=> [Student][MBL-15437] Font doesn't change back to system font on K5 logout in some cases.

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/SubmissionStateTypeAdapter.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/SubmissionState.kt
=> [MBL-15464][Student] K5 Due today text not shown

apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentSubmissionListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/QuizDetailsPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/Const.kt
Test plan: In the ticket. Refer to the linked iOS ticket for more detailed description.
refs: MBL-15427
release note: Fixed a bug where student names were visible in anonymous surveys.
=> [MBL-15427][Teacher] Anonymous survey submissions and student names are visible

apps/student/src/androidTest/java/com/instructure/student/ui/pages/ElementaryDashboardPage.kt, apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt, apps/student/src/main/java/com/instructure/student/navigation/ElementaryNavigationBehavior.kt, apps/student/src/main/java/com/instructure/student/navigation/NavigationBehavior.kt, apps/student/src/main/res/layout/navigation_drawer.xml
Test plan: Verify correct drawer menu items.
refs: MBL-15461
=> [MBL-15461][Student] K5 Drawer menu items

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Course.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Section.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/unit/CourseTest.kt
refs: MBL-15430
release note: Fixed a bug where assignments couldn't be submitted for courses with past or future sections.
=> [MBL-15430][Student] Students cannot submit in courses with past or future section dates

apps/student/flank_landscape.yml, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DiscussionsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/HomeroomPage.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubLandscapeAnnotation.kt
refs: MBL-15488
test plan: Fixed some nightly tests, not much testing is required. Added Stub option for landscape tests only, we should focus on removing that when we have our new SET.
=> [MBL-15488][Student][Teacher] Fix nightly builds

apps/student/build.gradle, apps/teacher/build.gradle
refs: MBL-15487
test plan: Check the changes in the Deploy workflow
=> [MBL-15487][Student][Teacher] Added updatePriority to releases

scripts/update-jira-issues.js
=> [MBL-13496][Ops] Jira automation script added

apps/student/build.gradle, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/NavigationDrawerInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/CanvasWebViewPage.kt, apps/teacher/build.gradle, buildSrc/src/main/java/com/instructure/android/buildtools/transform/LocaleTransformer.kt
=> [MBL-15517][Student][Teacher] Fix LocaleTransformer

apps/teacher/build.gradle, apps/teacher/flank_e2e_coverage.yml
=> [MBL-15450][Teacher] Added code-cov support for Teacher

apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/AddMessagePresenter.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/ConversationEndpoints.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/InboxApi.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/InboxApiPactTests.kt
Test plan: Test if sending messages and replying to messages both work correctly in both apps. Verify in Charles that query params are not exposed.
refs: MBL-15496
=> [MBL-15496][Student][Teacher] Change message request params to fields

apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt, apps/student/src/main/res/layout/fragment_application_settings.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/ApiPrefs.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt, libs/pandautils/src/test/java/com/instructure/pandautils/utils/FeatureFlagProviderTest.kt
Test plan: 
- Log in with a K5 user and verify that the new switch is present in settings.
- Verify that changing the switch and restarting the app changes the dashboard.
- Verify that the switch is not present for other users.
refs: MBL-15525
=> [MBL-15525][Student] Switch K5 mode on and off

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/GradesPage.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, automation/espresso/src/main/kotlin/com/instructure/espresso/NestedScrollViewExtension.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt, libs/pandautils/src/main/res/layout-sw720dp/item_grade_row.xml, libs/pandautils/src/main/res/layout/item_grade_row.xml, libs/pandautils/src/main/res/layout/item_grading_period_selector.xml
=> [MBL-15551][Student] K5 Grades UI tests

libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt
=> [MBL-15524][Student] Image gets centered in K5 Homeroom

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/HomeroomPage.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/HtmlContentFormatter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
Test plan: In the ticket. Test also the linked ticket.
refs: MBL-15497
release note: Fixed a bug where captions don't show on some videos.
=> [MBL-15497][Student][Teacher] Captions are not showing up in Canvas Mobile Apps

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ResourcesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt, apps/student/src/main/java/com/instructure/student/fragment/InboxComposeMessageFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/resources/StudentResourcesRouter.kt
Test plan: Specification in the ticket. Also check sending the message and verify that the teacher received it, and it is associated with the Homeroom course.
refs: MBL-15567
=> [MBL-15567][Student] Resources screen - Sending a message

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ElementaryDashboardInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ResourcesInteractionTest.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/ElementaryDashboardFragment.kt, apps/student/src/main/java/com/instructure/student/util/FeatureFlagPrefs.kt, apps/student/src/main/res/layout-sw720dp/fragment_elementary_dashboard.xml, libs/pandautils/src/main/res/layout-sw720dp/item_grade_row.xml, libs/pandautils/src/main/res/values/dimens.xml, libs/pandautils/src/main/res/values/styles.xml
Test plan: Specifications are in the ticket.
refs: MBL-15583
=> [MBL-15583][Student] Homeroom refinements

apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentListPage.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginInitActivity.kt
=> [MBL-15584][Teacher][Student] Fix dev login validation

libs/pandautils/src/main/java/com/instructure/pandautils/utils/ColorUtils.kt, libs/pandautils/src/main/res/layout-sw720dp/item_grade_row.xml, libs/pandautils/src/main/res/layout-sw720dp/item_schedule_course.xml, libs/pandautils/src/main/res/layout/item_course_card.xml, libs/pandautils/src/main/res/layout/item_grade_row.xml, libs/pandautils/src/main/res/layout/item_schedule_course.xml, libs/pandautils/src/main/res/layout/item_schedule_missing_item.xml
refs: MBL-15592
release note: Fixed a crash on K5 Homeroom
=> [MBL-15592][Student] Homeroom crash

libs/pandautils/src/main/java/com/instructure/pandautils/adapters/itemdecorations/StickyHeaderItemDecoration.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleRecyclerViewAdapter.kt
Test plan: On the schedule screen do a pull to refresh. Start scrolling and scroll continuously until the refresh finishes.
=> Fixed pull to refresh crash.

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt, libs/pandares/src/main/res/values/strings.xml
refs: MBL-15562
release note: Added a more detailed error message to Assignment details.
=> [MBL-15562][Teacher] Add closed grading period error message.

apps/teacher/src/main/java/com/instructure/teacher/view/grade_slider/SpeedGraderSlider.kt
refs: MBL-15350
release note: Added the option to click the end labels of the SpeedGrader slider.
test plan: Tap on the min/max value, the grade should change.
=> [MBL-15350][Teacher] Added actions to the end labels for SpeedGrader

apps/flutter_parent/lib/models/planner_item.dart, apps/flutter_parent/lib/models/planner_item.g.dart, apps/flutter_parent/lib/screens/calendar/planner_fetcher.dart, libs/flutter_student_embed/lib/models/planner_item.dart, libs/flutter_student_embed/lib/models/planner_item.g.dart, libs/flutter_student_embed/lib/screens/calendar/planner_fetcher.dart
refs: MBL-15591
release note: Fixed an issue where the calendar would not load sometimes.
test plan: See ticket for examples.
If the plannableDate is null, we could not show the item anyway.
=> [MBL-15591][Parent][Student] Calendar load error fix

apps/flutter_parent/lib/main.dart, apps/flutter_parent/plugins/webview_flutter/LICENSE, apps/flutter_parent/plugins/webview_flutter/android/build.gradle, apps/flutter_parent/plugins/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java, apps/flutter_parent/plugins/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java, apps/flutter_parent/plugins/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java, apps/flutter_parent/plugins/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java, apps/flutter_parent/plugins/webview_flutter/lib/platform_interface.dart, apps/flutter_parent/plugins/webview_flutter/lib/src/webview_method_channel.dart, apps/flutter_parent/plugins/webview_flutter/lib/webview_flutter.dart, apps/flutter_parent/plugins/webview_flutter/pubspec.yaml, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml
Test plan: Bug description is in the ticket. This should be verified on Android 12, but test also lower versions if WebViews work correctly.
refs: MBL-15605
release note: Fixed a bug where keyboard didn't open on the login screen using Android 12.
=> [MBL-15605][Parent] Keyboard does not open on login screens when using Android 12

apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt, apps/student/src/main/res/layout/viewholder_grade.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt, libs/pandares/src/main/res/values/strings.xml
refs: MBL-15706
release note: Assignments are now ordered by due date on the Grades page.
test plan: The assignments should be ordered by due date on the grades page. See ticket for example.
Not Submitted and Missing labels should be visible as well if applicable.
=> [MBL-15706][Student] Correct sorting on the Grades page

apps/student/src/main/java/com/instructure/student/activity/BaseRouterActivity.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/homeroom/StudentHomeroomRouter.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/schedule/StudentScheduleRouter.kt, apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt
refs: MBL.15687
release note: C4E design for Subject pages.
test plan: Check if the courses route to the correct Subject page. (K5 or not)
=> [MBL-15687][Student] Enable K5 subject pages for production

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/main/java/com/instructure/student/adapter/GradesListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseFragment.kt, apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCoursePagerAdapter.kt, apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewData.kt, apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModel.kt, apps/student/src/main/java/com/instructure/student/holders/PeopleHeaderViewHolder.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/grades/StudentGradesRouter.kt, apps/student/src/main/java/com/instructure/student/router/RouteMatcher.kt, apps/student/src/main/res/layout/elementary_course_webview.xml, apps/student/src/test/java/com/instructure/student/features/elementary/course/ElementaryCourseViewModelTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt
=> Student 6.15.0 smoke test fixes

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SchedulePage.kt
refs: MBL-15763
implement today button interaction test case for k5 schedule page
=> [MBL-15763] - Implement missing today button schedule interaction test case

apps/teacher/src/main/java/com/instructure/teacher/view/SubmissionContentView.kt, libs/pandares/src/main/res/values/strings.xml
Test plan: Verify grading and annotating student annotation submissions works. You can test this only on beta currently, I marked the PR draft, so we wouldn't merge before deploying the feature to production.
refs: MBL-15743
release note: Added support for student annotation submission type.
=> [MBL-15743][Teacher] Student Annotation support

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/AnnouncementsListPageTest.kt, apps/teacher/src/main/res/layout/fragment_create_or_edit_announcement.xml, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
=> [MBL-15712][Teacher] Fixed A11y issues on create announcements screen

apps/student/build.gradle, apps/student/src/main/res/layout/fragment_course_grades.xml
refs: MBL-15788
release note: Accessibility improvement
=> [Student][MBL-15788] A11y issue on Grades

libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/HtmlContentFormatter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
Test plan: See ticket. Details about the solution can be found in my comment on the ticket.
refs: MBL-15755
=> [MBL-15755][Student] Scrollable iframe cannot be scrolled in WebView

apps/student/src/main/java/com/instructure/student/fragment/GradesListFragment.kt
Test plan: See the updated part in the ticket.
refs: MBL-15792
=> [MBL-15792][Student] What-if score result (%) will jump back the previously set after uncheck and re-check the what-if score checkbox

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/AssignmentSet.kt
refs: MBL-15759
release note: Fixed a bug where mastery path choices in modules were not visible.
=> [Student][MBL-15759] Conditional mastery path selection UI issue

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ElementaryDashboardInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ResourcesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ElementaryDashboardPage.kt
Refactor elementary tab selection and assertion methods to be more generic and reduce code duplication by using an ElementaryTabType enum
refs: MBL-15801
=> [MBL-15801] [Student] - Refactor Elementary Tab selection and assertion methods 

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ElementaryDashboardInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ResourcesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/RemoteConfigUtils.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/FeatureFlagProvider.kt, libs/pandautils/src/test/java/com/instructure/pandautils/utils/FeatureFlagProviderTest.kt
Test plan: Smoke test K5 dashboard and dashboard with a non-K5 user.
refs: MBL-15633
=> [MBL-15633][Student] Remove K5 Firebase feature flag

apps/student/src/main/java/com/instructure/student/fragment/LtiLaunchFragment.kt
refs: MBL-15810
release note: Fixed a bug where LTIs in pages won't open in some cases.
=> [MBL-15810][Student] Error using Lauching External Tool button on Pages containing SCORM content

apps/teacher/src/main/java/com/instructure/teacher/activities/SpeedGraderActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Assignment.kt
refs: MBL-15811
release note: Fixed a bug where names were shown when opening anonymous assignments from the To Do screen.
=> [MBL-15811][Teacher] To-do list will show the name of students for Anonymous assignments

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ResourcesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ResourcesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ResourcesPage.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/SeedApi.kt
=> [MBL-15767] - Fix breaking resources k5 e2e test case.

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/OAuthAPI.kt
refs: MBL-15848
release note: Fixed a bug where Student View would load the teacher version.
test plan: The student view should now load the student version of the subject page.
=> [MBL-15848][Student] Fix Student View

buildSrc/src/main/java/GlobalDependencies.kt
refs: MBL-15856
release note: Fixed a crash on the Submission Details screen.
test plan: See ticket
=> [MBL-15856][Teacher] Fixed ANR on Submission Details

translations/flutter-extract.rb
refs: MBL-15869
test plan: The workflow should run properly.
=> [MBL-15869] Fix translation workflow

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/CommentLibraryPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CommentLibraryPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderCommentsPage.kt, automation/espresso/src/main/kotlin/com/instructure/espresso/CustomViewAssertions.kt
Extend comment library interaction tests with some general methods and 2 additional test cases.
refs: MBL-15876
=> [Android][Teacher] - Extend comment library interaction tests

apps/student/flank_tablet.yml, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ElementaryDashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentTest.kt, apps/student/src/main/java/com/instructure/student/mobius/elementary/importantdates/StudentImportantDatesRouter.kt, apps/teacher/flank_tablet.yml, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubTabletAnnotation.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/MockCanvas.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/ScheduleItem.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesRouter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesViewData.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesViewModel.kt, libs/pandautils/src/main/res/layout-sw720dp/fragment_important_dates.xml, libs/pandautils/src/main/res/layout/fragment_important_dates.xml, libs/pandautils/src/test/java/com/instructure/pandautils/features/elementary/importantdates/ImportantDatesViewModelTest.kt
=> [MBL-15817][Student] Important dates interaction tests

apps/student/src/main/java/com/instructure/student/features/elementary/course/ElementaryCoursePagerAdapter.kt
refs: MBL-15891
release note: Fixed a crash when opening files from elementary subject pages.
=> [Student][MBL-15891] Crash when opening a file from K5 subject pages

apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/submissionDetails/drawer/rubric/SubmissionRubricPresenter.kt
Test plan: I couldn't reproduce the issue in my sandbox without making some temporary modifications in the code, but the issue and the fix is straightforward from the stack trace.
refs: MBL-15892
release note: Fixed a crash on submission details screen.
=> [Student][MBL-15892] Crash on submission details screen

apps/student/src/main/java/com/instructure/student/holders/GradeViewHolder.kt
refs: MBL-15886
release note: Fixed a bug where the missing label was visible for graded assignments.
=> [MBL-15886][Student] Grade status fix for assignments w/o submission

libs/flutter_student_embed/lib/network/api/course_api.dart, libs/flutter_student_embed/lib/network/api/planner_api.dart
refs: MBL-15866
release note: Fixed a bug in calendar filtering.
test plan: See ticket
=> [Student][MBL-15866] Calendar does not display all events after re-enable all courses' checkbox

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/DashboardInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/GradesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/HomeroomInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ImportantDatesInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ScheduleInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/StubLandscapeAnnotation.kt
fix and stabilize stublandscape tests.
refs: MBL-15851
=> [MBL-15851] Student | Investigate and fix StubLandscape tests

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt
=> [MBL-15907][Student] - Fix breaking e2e k5 nightly test

buildSrc/src/main/java/com/instructure/android/buildtools/transform/ScreenViewTransformer.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewData.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/elementary/schedule/ScheduleViewModel.kt, libs/pandautils/src/main/res/values/strings.xml
refs: MBL-15625
release note: Accessibility improvements.
test plan: Using TalkBack mark schedule items as done and not done. TalkBack should announce witch item has been changed.
=> [MBL-15625][Student] Schedule a11y improvements

apps/student/src/main/java/com/instructure/student/features/dashboard/edit/EditDashboardFragment.kt
refs: MBL-15626
release note: Accessibility improvements.
test plan: Using TalkBack add/remove items to/from the Dashboard. TalkBack should announce the Snackbar text.
=> [MBL-15626][Student] Added TalkBack announcements

libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
refs: MBL-15933
release note: Fixed a crash on the annotations screen.
test plan: Test annotations.
=> [MBL-15933][Teacher] Fix annotation crash

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ImportantDatesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ImportantDatesPage.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/api/AssignmentsApi.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/model/AssignmentApiModel.kt, automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/Randomizer.kt
Implement important dates E2E test for Canvas For Elementary courses and extend AssignmentsAPI to handle important dates.
refs: MBL-15836
=> [MBL-15836][Student] - Important dates E2E test for C4E

apps/student/proguard-rules.txt, apps/student/src/main/AndroidManifest.xml, apps/student/src/main/java/com/instructure/student/util/FileUtils.kt, apps/student/src/main/res/menu/pspdf_activity_menu.xml, apps/teacher/proguard-rules.txt, apps/teacher/src/dev/AndroidManifest.xml, apps/teacher/src/main/AndroidManifest.xml, apps/teacher/src/prod/AndroidManifest.xml, buildSrc/src/main/java/GlobalDependencies.kt, libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt
Test plan: Verify that every PSPDFKit functionality works in the app as intended:
- Annotating PDF submission types and student annotation submission types as a teacher.
- Opening PDF files as a teacher.
- Annotating PDF files for student annotation submission type and submitting the assignment as a student.
- Opening PDF files as a student (here you can add annotations, search in the file, change different settings about how the PDF is shown, these should be tested as well).
- Compare all functionality with the current app available in the Play Store.
There were also some proguard issues so the best way to test this build would be to build it locally while changing the `minifyEnabled` and the `shrinkResources` properties to `true` in the debug config of the `build.gradle` file of the …
=> [MBL-15671][Student][Teacher] PSPDFKit update

apps/student/src/main/res/layout/fragment_conference_list.xml, apps/student/src/main/res/layout/fragment_inbox_conversation.xml, apps/student/src/main/res/layout/fragment_unsupported_feature.xml
Test plan: see ticket.
refs: MBL-15908
release note: Fixed a bug where screen background was transparent in some cases.
=> [Student][MBL-15908] Content background is transparent when opened from the quick-launch options

apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt, apps/student/src/test/java/com/instructure/student/test/util/ModuleUtilityTest.kt
=> [MBL-15937][Student] Group discussion reply causes anomaly

apps/student/src/main/java/com/instructure/student/adapter/DashboardRecyclerAdapter.kt
refs: MBL-15934
release note: Fixed a bug where future courses would not show up on the Dashboard.
=> [MBL-15934][Student] Future courses show up on Dashboard

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
=> [MBL-15947][Student][Teacher]QR login for an "act as user" session.

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/GradesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
Minor refactors when measuring current coverage state
refs: MBL-15955
=> [MBL-15955] [Student] [Techer] -  Refactor during Test coverage measuring

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditAssignmentDetailsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/EditQuizDetailsPageTest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssigneeListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/renderTests/pages/EditSyllabusRenderPage.kt, automation/espresso/build.gradle, automation/espresso/src/main/kotlin/androidx/test/espresso/base/GetRootsOracle.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CustomMatchers.kt, buildSrc/src/main/java/GlobalDependencies.kt
Test plan: Don't need to manually test this, just check if all the auto tests pass.
refs: MBL-15649
=> [MBL-15649][Student][Teacher] Update testing dependencies

apps/teacher/src/main/java/com/instructure/teacher/presenters/AssigneeListPresenter.kt
refs: MBL-15963
release note: Fixed a bug where students on the assignee list were not correctly ordered.
=> [MBL-15963][Teacher] Order of assignee list now matches people page

apps/student/src/main/java/com/instructure/student/fragment/CourseModuleProgressionFragment.kt
Test plan: I wasn't able to reproduce this, but the fix is self-explanatory.
refs: MBL-15995
release note: Fixed a crash on module progression screen.
=> [MBL-15995][Student] Crash on module progression

apps/student/src/main/java/com/instructure/student/fragment/DashboardFragment.kt
refs: MBL-15996
release note: Fixed a crash on the Dashboard.
test plan: I was not able to repro this. It was an NPE so I made it null-safe.
=> [MBL-15996][Student] Fixed Dashboard crash

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/AssignmentDetailsInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/BookmarkInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/AssignmentDetailsPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/BookmarkPage.kt
Implement Bookmarks E2E test + some refactor.
refs: MBL-15987
=> [MBL-15987]  [Student] - Implement Bookmarks E2E test

apps/flutter_parent/lib/utils/web_view_utils.dart, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt, libs/rceditor/src/main/java/instructure/rceditor/RCETextEditor.kt
refs: MBL-15975
affects: All
release note: Rendering LaTex equations.
=> [MBL-15975][All] LaTex equations rendering

apps/student/src/androidTest/java/com/instructure/student/ui/pages/ModulesPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/StudentContextPage.kt
Fix breaking landscape and tablet nightly tests.
refs: MBL-16025
=> [MBL-16025] [Student] [Teacher] - Fix breaking landscape and tablet nightly tests.

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CourseSettingsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CourseBrowserPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/CoursesListPage.kt
Course Settings E2E test implementation.
refs: MBL-15988
=> [MBL-15988] Teacher - Implement course settings e2e test

apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt
refs: MBL-16003
release note: Fixed a bug where the loading would not finish on the Notifications screen.
=> [MBL-16003][Student] Fixed infinite loading on Notifications

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AnnouncementsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/BookmarksE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DiscussionDetailsPage.kt
Implement Student Announcements E2E test.
refs: MBL-16019
=> [MBL-16019][Student] - Implement announcements e2e test

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/PeopleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/PeopleListPage.kt
Refactor peopleE2E test in Student app and put it back to run on nightly.
Also, logging has been added to the test case.
refs: MBL-16020
=> [MBL-16020][Student] - Refactor peopleE2E test in Student app and put it back to run on nightly

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/AssignmentSubmissionListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/FileListPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt, apps/teacher/src/main/res/layout/fragment_file_list.xml, automation/espresso/src/main/kotlin/com/instructure/espresso/ViewUtils.kt
Extending Page object with FileListPage.
Adding ID to fragment_file_list.xml
Extract pressBackButton() method to ViewUtils.
refs: MBL-16021
=> [MBL-16021][Teacher] - Implement Teacher FilesE2E test

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AssignmentE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CommentLibraryE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CourseSettingsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DiscussionsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PeopleE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SpeedGraderE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SyllabusE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/TodoE2ETest.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/CanvasTest.kt
Add logging to some existing teacher e2e test.
Some minor refactor on some cases to be more readable.
refs: MBL-15974
=> [MBL-15974] [Teacher] - Extend e2e console logging - Add logging to some Teacher E2E test cases

apps/student/src/main/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModel.kt, apps/student/src/test/java/com/instructure/student/features/dashboard/edit/EditDashboardViewModelTest.kt, automation/espresso/src/main/kotlin/com/instructure/canvas/espresso/mockCanvas/endpoints/CourseEndpoints.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/CourseAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/CourseManager.kt
refs: MBL-16032
release note: Fixed a bug where courses would appear under the wrong section on the Edit Dashboard screen.
test plan: Smoke test the Edit Dashboard screen. See ticket for examples.
=> [MBL-16032][Student] API calls for Edit Dashboard sections 

apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt, apps/student/src/main/java/com/instructure/student/flutterChannels/FlutterComm.kt, libs/flutter_student_embed/lib/screens/calendar/calendar_widget/calendar_day.dart, libs/flutter_student_embed/lib/screens/to_do/create_update_to_do_screen.dart, libs/flutter_student_embed/lib/screens/to_do/to_do_details_screen.dart, libs/flutter_student_embed/lib/utils/common_widgets/colored_status_bar.dart, libs/flutter_student_embed/lib/utils/design/dark_colors.dart, libs/flutter_student_embed/lib/utils/design/light_colors.dart, libs/flutter_student_embed/lib/utils/design/student_colors.dart, libs/flutter_student_embed/lib/utils/design/student_theme.dart, libs/flutter_student_embed/lib/utils/native_comm.dart, libs/flutter_student_embed/test/screens/calendar/calendar_widget/calendar_day_of_week_headers_test.dart, libs/flutter_student_embed/test/screens/calendar/calendar_widget/calendar_day_test.dart
Test plan: Verify that the Flutter screens work correctly in dark/light mode:
- Calendar
- Calendar filter
- To Do details
- Create To Do
refs: MBL-16077
=> [MBL-16077][Student] Dark mode in Flutter screens

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/NotificationsE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/interaction/PushNotificationInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NewMessagePage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/NotificationPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/CommentLibraryE2ETest.kt
Implement Student Notifications E2E test
Add override for enableAndConfigureAccessibilityChecks method to CommentLibraryE2ETest.kt.
Stabilize setRecipient method in Inbox test.
refs: MBL-16023
=> [MBL-16023][Student] - Implement Student Notifications E2E test

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/ModulesE2ETest.kt
Merge ModulesE2ETest cases into one case in Teacher.
refs: MBL-16055
=> [MBL-16055] [Teacher] - Merge Modules E2E tests into one test case

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
Refactor and merge InboxE2E tests in Teacher.
refs: MBL-16054
=> [MBL-16054] [Teacher] - Refactor and merge InboxE2E tests in Teacher

apps/student/src/main/java/com/instructure/student/di/NavigationActivityModule.kt, apps/student/src/main/java/com/instructure/student/navigation/DefaultNavigationBehavior.kt, apps/student/src/main/java/com/instructure/student/navigation/ElementaryNavigationBehavior.kt, apps/student/src/main/java/com/instructure/student/navigation/NavigationBehavior.kt
=> [MBL-16096][Student] StudentView unsupported feature view stucks when clicking on Inbox bottom-menu

apps/student/src/main/java/com/instructure/student/widget/BaseRemoteViewsService.kt, apps/student/src/main/java/com/instructure/student/widget/GradesViewWidgetService.kt, apps/student/src/main/java/com/instructure/student/widget/NotificationViewWidgetService.kt, apps/student/src/main/java/com/instructure/student/widget/TodoViewWidgetService.kt, apps/student/src/main/res/drawable/widget_dark_bg.xml, apps/student/src/main/res/drawable/widget_light_bg.xml, apps/student/src/main/res/layout/activity_widget_setup.xml
Test plan: Verify that the widgets colors are correct both in dark mode and light mode (test both widget color modes with both app color modes).
refs: MBL-16107
=> [MBL-16107][Student] Fix widget styles

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/FilesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/FilesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/SettingsE2ETest.kt
Fix breaking FilesE2ETest and ProfileSettingsE2E test in Teacher nightly.
Fix breaking FilesE2ETest test in Student nightly.
refs:
=> Nightly fixes

apps/teacher/src/main/java/com/instructure/teacher/fragments/FileListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/FileListPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/viewinterface/FileListView.kt
refs: MBL-16112
release note: Fixed a bug where creating the first folder does not update the view.
=> [MBL-16112][Teacher] Update empty state on folder creation

apps/teacher/src/main/res/layout-sw760dp/view_floating_media_recorder_video.xml, buildSrc/src/main/java/GlobalDependencies.kt, libs/pandautils/build.gradle, libs/pandautils/src/main/java/com/instructure/pandautils/views/FloatingRecordingView.kt, libs/pandautils/src/main/res/layout/view_floating_media_recorder_video.xml
Test plan:
- Verify that the floating camera view that is used to post video comments on submissions works correctly in both apps.
refs: MBL-15648
=> [MBL-15648][Student][Teacher] Remove CameraKit dependency

apps/teacher/src/main/java/com/instructure/teacher/di/DashboardModule.kt, apps/teacher/src/main/java/com/instructure/teacher/features/dashboard/notifications/TeacherDashboardRouter.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/CoursesFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt, apps/teacher/src/main/res/layout/fragment_courses.xml
refs: MBL-15849
release note: Added Announcements, Invites and Conferences to the Dashboard.
test plan: Check to see if the Dashboard Notifications are working.
=> [MBL-15849][Teacher] Dashboard Notifications for Teacher

apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt
refs: MBL-16000
test plan: Check if the event is logged correctly.
=> [MBL-16000][Student] Analytics for toggling the C4E switch

apps/teacher/src/main/java/com/instructure/teacher/activities/InitActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/CoursesFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/InboxFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/ToDoFragment.kt
=> [MBL-16114][Teacher] Links to top level screens have white toolbar

libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/User.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/MasqueradeHelper.kt
=> [MBL-16137][Student] Student view does not work for Consortium accounts

apps/student/src/main/java/com/instructure/student/fragment/BasicQuizViewFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionsReplyFragment.kt, libs/annotations/src/main/java/com/instructure/annotations/PdfSubmissionView.kt, libs/pandares/src/main/res/values/strings.xml
=> [MBL-16166][Student] Crashlytics stabilisation

apps/student/flank_e2e_lowres.yml, apps/teacher/flank_e2e_lowres.yml
refs: MBL-16164
release note:
test plan:
=> [MBL-16164][Teacher][Student] - Create Low Resolution device E2E test flank files

libs/rceditor/src/main/java/instructure/rceditor/RCETextEditorView.kt
=> [MBL-16175][Teacher][Student] Validation is missing from image Alt dialog

apps/teacher/src/main/java/com/instructure/teacher/fragments/LtiLaunchFragment.kt
=> [MBL-16176][Teacher] Rotating device in LTI tool view will open it twice

apps/flutter_parent/lib/network/utils/analytics.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml, apps/student/build.gradle, apps/student/src/main/java/com/instructure/student/util/BaseAppManager.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/AssignmentDetailsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/assignment/details/submissionDetails/commentTab/SubmissionCommentsEffectHandlerTest.kt, apps/student/src/test/java/com/instructure/student/test/settings/pairobserver/PairObserverEffectHandlerTest.kt, apps/teacher/build.gradle, buildSrc/src/main/java/GlobalDependencies.kt, libs/canvas-api-2/build.gradle, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/AppManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/Analytics.kt, libs/flutter_student_embed/lib/utils/crash_utils.dart, libs/pandautils/build.gradle
Test plan:
- Smoke test
refs: MBL-16171
affects: All
=> [MBL-16171][All] Remove all the Google Analytics reporting from all the apps

libs/pandautils/src/main/java/com/instructure/pandautils/utils/ExoPlayerHelper.kt
=> [MBL-16177][Teacher] Audio comment is freezing while loosing focus from app and gives it back

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/QuizE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/QuizListPage.kt
Merge redundant quiz test cases into one case.
refs: MBL-16057
=> [MBL-16057][Teacher] - Merge quizes e2e test cases

apps/student/src/main/java/com/instructure/student/activity/BaseRouterActivity.kt, apps/student/src/main/java/com/instructure/student/fragment/ParentFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/InternalWebViewFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt, libs/pandautils/src/main/java/com/instructure/pandautils/loaders/OpenMediaAsyncTaskLoader.kt
=> [MBL-16180][Teacher] Cannot open uploaded document type files from the app

apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsViewState.kt, apps/teacher/src/main/java/com/instructure/teacher/features/calendar/event/CalendarEventFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/PageDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/models/Page.kt, libs/pandautils/src/main/java/com/instructure/pandautils/views/CanvasWebView.kt
=> [MBL-16195][Student][Teacher] window.location.pathname returns incomplete data

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt
Merge and extend pages e2e test cases.
refs: MBL-16058
=> [MBL-16058][Teacher] -  Collapse and extend pages e2e tests

libs/flutter_student_embed/lib/screens/calendar/calendar_widget/calendar_month.dart
=> [MBL-16191][Student] Calendar dates shift in week/month view when using the device with different locales

apps/teacher/src/main/java/com/instructure/teacher/features/syllabus/ui/SyllabusView.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/CourseBrowserFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/router/RouteMatcher.kt
refs: MBL-15332
Test plan:
- Course navigation should be on the left side, syllabus should be on the right side of the split view
- Phone navigation should be unchanged
=> [MBL-15332][Teacher] Syllabus in landscape mode on tablets

apps/student/flank_multi_api_level.yml, apps/teacher/flank_multi_api_level.yml, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/SpeedGraderGradePage.kt, automation/espresso/build.gradle
Introduce multi api level tests in Teacher
Add FlakyE2E and KnownBug annotations to be not run in this workflow.
set device to lowres since it supports more api levels.
refs: MBL-16168
=> [MBL-16168][Teacher][Student] - Introduce multi api level tests in teacher

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/AssignmentsE2ETest.kt
Investigate testMediaCommentsE2E.
Tested it on local and on FTL, worked well.
Put back video comment testing part of the code.
refs: MBL-13604
=> [MBL-13604][Student] - SPIKE: Investigate testMediaCommentsE2E

apps/flutter_parent/android/app/src/main/AndroidManifest.xml, apps/student/src/main/AndroidManifest.xml, apps/student/src/main/java/com/instructure/student/mobius/common/ui/SubmissionService.kt, apps/student/src/main/java/com/instructure/student/util/FileDownloadJobIntentService.kt, apps/student/src/main/java/com/instructure/student/util/ShortcutUtils.kt, apps/student/src/main/java/com/instructure/student/widget/CanvasWidgetProvider.kt, apps/student/src/main/java/com/instructure/student/widget/CanvasWidgetRowFactory.kt, apps/student/src/main/java/com/instructure/student/widget/GradesWidgetProvider.kt, apps/student/src/main/java/com/instructure/student/widget/NotificationViewWidgetService.kt, apps/student/src/main/java/com/instructure/student/widget/NotificationWidgetProvider.kt, apps/student/src/main/java/com/instructure/student/widget/TodoWidgetProvider.kt, apps/teacher/src/main/AndroidManifest.xml, apps/teacher/src/main/java/com/instructure/teacher/services/FileDownloadService.kt, buildSrc/src/main/java/GlobalDependencies.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/utils/LocaleUtils.kt, libs/pandautils/src/main/java/com/instructure/pandautils/receivers/PushExternalReceiver.kt, libs/pandautils/src/main/java/com/instructure/pandautils/update/UpdateManager.kt
Test plan:
- Smoke test all 3 apps thoroughly on a device running Android 12.
- If something seems to be not working as intended also check it with the current production app on the same device. In this case we can identify if the problem is caused by the target SDK or it already affects Android 12 users.
- Focus more on the platform interactions:
- Push notifications
- Services (file upload, file download, file submission)
- Widgets
- Share extension
refs: MBL-16150
affects: All
=> [All][MBL-16150] Update target API level to 12

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/PagesE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditPageDetailsPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PageListPage.kt
Added page creation flow to PagesE2E test on Teacher app.
refs: MBL-16206
=> [Android][Teacher] - Insert page creation flow on UI

libs/flutter_student_embed/lib/network/utils/dio_config.dart
=> [MBL-16220][Student] Calendar needs to be refreshed day by day after filter

libs/pandautils/src/main/java/com/instructure/pandautils/activities/BaseViewMediaActivity.kt
refs: MBL-16132
<table>
<tr>
<td><img src="" maxHeight=500></td>
<td><img src="" maxHeight=500></td>
</tr>
</table>
=> [MBL-16132][Student][Teacher] Pause video when set focus to a different app

apps/flutter_parent/android/app/src/main/AndroidManifest.xml, apps/flutter_parent/lib/main.dart, apps/flutter_parent/lib/utils/veneers/flutter_downloader_veneer.dart, apps/flutter_parent/pubspec.lock, apps/flutter_parent/pubspec.yaml
refs: MBL-16247
release note: Fixed a crash when downloading inbox attachments.
=> [MBL-16247][Parent] App repetitively crashes on attachment download

automation/dataseedingapi/src/main/kotlin/com/instructure/dataseeding/util/RestRetryInterceptor.kt
=> [Student][Teacher] Fixed RestRetryInterceptor

apps/student/src/main/java/com/instructure/student/activity/CallbackActivity.kt, apps/student/src/main/java/com/instructure/student/activity/NavigationActivity.kt, apps/student/src/main/java/com/instructure/student/adapter/NotificationListRecyclerAdapter.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/NotificationListFragment.kt, apps/student/src/main/java/com/instructure/student/holders/NotificationViewHolder.kt, apps/student/src/main/java/com/instructure/student/interfaces/NotificationAdapterToFragmentCallback.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/AssignmentDetailsPresenter.kt, apps/student/src/main/res/layout/viewholder_notification.xml, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/DiscussionAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/InboxApi.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/SubmissionAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/apis/UnreadCountAPI.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/DiscussionManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/InboxManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/SubmissionManager.kt, libs/canvas-api-2/src/main/java/com/instructure/canvasapi2/managers/UnreadCountManager.kt, libs/canvas-api-2/src/test/java/com/instructure/canvasapi2/pact/canvas/apis/InboxApiPactTests.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/Extensions.kt
refs: MBL-15693
release note: Added notification count badge.
test plan: Smoke test all kind of notification.
=> [MBL-15693][Student] Course announcement notifications

apps/flutter_parent/lib/l10n/app_localizations.dart, apps/flutter_parent/lib/network/utils/api_prefs.dart, apps/flutter_parent/lib/router/panda_router.dart, apps/flutter_parent/lib/screens/domain_search/domain_search_screen.dart, apps/flutter_parent/lib/screens/login_landing_screen.dart, apps/flutter_parent/lib/screens/web_login/web_login_screen.dart, apps/student/src/androidTest/java/com/instructure/student/ui/utils/StudentActivityTestRule.kt, apps/student/src/main/java/com/instructure/student/activity/LoginLandingPageActivity.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherActivityTestRule.kt, apps/teacher/src/main/java/com/instructure/teacher/activities/LoginLandingPageActivity.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginFindSchoolActivity.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginLandingPageActivity.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/activities/BaseLoginSignInActivity.kt, libs/login-api-2/src/main/java/com/instructure/loginapi/login/util/LoginPrefs.kt, libs/login-api-2/src/main/res/drawable/bg_button_rounded_outline.xml, libs/login-api-2/src/main/res/layout-land/activity_login_landing_page.xml, libs/login-api-2/src/main/res/layout/activity_login_landing_page.xml, libs/login-api-2/src/main/res/values/strings.xml, libs/login-api-2/src/main/res/values/styles.xml
refs: MBL-16270
affects: All
release note: Improved the login flow by saving the last institution's login page.
test plan:
- Acceptance criteria is in the ticket.
- Testing with a test sandbox will only remember and show the domain on the login screen. The reason for this is that we won't search for that school, but enter the domain directly.
- To see the name of the school you need to select a school from the search suggestions.
=> [MBL-16270][All] Improve mobile login

apps/teacher/src/main/java/com/instructure/teacher/activities/BaseAppCompatActivity.kt, apps/teacher/src/main/java/com/instructure/teacher/activities/FullscreenActivity.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/MediaUploadUtils.kt
refs: MBL-16162
test plan: need to test the following places without permissions and with permissions in Student and Teacher app
- CreateAnnouncementFragment
- CreateDiscussionFragment 
- DiscussionsReplyFragment
- EditPageDetailsFragment
- EditSyllabusFragment
- CreateOrEditAnnouncementFragment
- CreateOrEditPageDetailsFragment
- DiscussionsUpdateFragment
- EditAssignmentFragment
- EditQuizDetailsFragment
- EditProfileFragment
=> [MBL-16162][Student][Teacher] RCE insert image improvements

apps/student/src/androidTest/java/com/instructure/student/ui/interaction/ShareExtensionInteractionTest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/ShareExtensionTargetPage.kt
Add new no assignment selected test case to share extension interact…
refs: MBL-16306
=> [MBL-16306][Student] - Add new no assignment selected test case to share extension interaction tests

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/LoginE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/LoginLandingPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/LoginSignInPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/LoginE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/LoginLandingPage.kt
Refactor Login tests in Student and Teacher app to handle last saved school button.
Also, added a new case to Student and Teacher app as well in which we directly test the newly added, last saved institute feature.
refs: MBL-16305
=> [MBL-16305][Student][Teacher] - Refactor Login tests in Student and Teacher app to handle last saved school

apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/PageDetailsFragment.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
refs: MBL-15325
release note: Added option to open embedded google docs in the browser.
test plan: in the ticket
=> [MBL-15325][Student][Teacher] Users should be able to open embedded google slides in the browser

apps/student/src/main/java/com/instructure/student/features/files/search/FileSearchFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/AccountPreferencesFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/ApplicationSettingsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/BookmarksFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/FeatureFlagsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/FileListFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/ProfileSettingsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/ui/PairObserverFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/settings/pairobserver/ui/PairObserverView.kt, apps/student/src/main/java/com/instructure/student/util/StudentToolbarSetupBehavior.kt, apps/student/src/main/res/layout/fragment_file_search.xml, apps/teacher/src/main/java/com/instructure/teacher/features/files/search/FileSearchFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/FeatureFlagsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/ProfileFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SettingsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/TeacherToolbarSetupBehavior.kt, apps/teacher/src/main/res/layout/fragment_file_search.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/Extensions.kt, libs/pandautils/src/main/res/layout/fragment_notification_preferences.xml
refs: MBL-16311
release note: Toolbar theme fixes.
test plan: in the ticket
=> [MBL-16311][Student][Teacher] Toolbar theme fixes

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/InboxE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxMessagePage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/InboxPage.kt
Extend Teacher Inbox E2E test. - Star, Delete, Archive, unread features.
refs: MBL-16211
=> [MBL-16211][Teacher] - Extend InboxE2E with Star, Delete, Archive, unread features

apps/student/src/main/java/com/instructure/student/fragment/AssignmentBasicFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/CalendarEventFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/LtiLaunchFragment.kt, apps/student/src/main/java/com/instructure/student/fragment/PageDetailsFragment.kt, apps/student/src/main/java/com/instructure/student/mobius/assignmentDetails/ui/AssignmentDetailsView.kt, apps/teacher/src/main/java/com/instructure/teacher/features/calendar/event/CalendarEventFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/AssignmentDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/LtiLaunchFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/PageDetailsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/QuizDetailsFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/binding/BindingAdapters.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/HtmlContentFormatter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/utils/WebViewExtensions.kt
refs: MBL-16307
test plan: check the following screens
- Assignment
- Calendar event
- Discussion
- Page
- Quiz
=> [MBL-16307][Student][Teacher] Merge WebViewExtensions and HtmlContentFormatter

libs/pandautils/src/main/res/menu/search.xml
refs: MBL-16320
test plan: In the ticket
=> [MBL-16320][Student] Search (magnifying glass) icon on Pages List page disappearing under specific circumstance

apps/build.gradle, apps/student/build.gradle, apps/student/src/main/java/com/instructure/student/util/BaseAppManager.kt, apps/teacher/build.gradle, apps/teacher/src/main/java/com/instructure/teacher/utils/BaseAppManager.kt, buildSrc/src/main/java/GlobalDependencies.kt
refs: MBL-16346
test plan: Check the events on the Heap dashboard.
=> [MBL-16346][Student][Teacher] Heap analytics

libs/pandautils/src/main/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModel.kt, libs/pandautils/src/test/java/com/instructure/pandautils/features/dashboard/notifications/DashboardNotificationsViewModelTest.kt
refs: MBL-16355
release note: Fixed a crash when uploading files.
test plan:
=> [MBL-16355][Student] Fix File Upload crash

libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/target/ShareExtensionTargetFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/target/ShareExtensionTargetViewData.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/shareextension/target/ShareExtensionTargetViewModel.kt, libs/pandautils/src/main/res/layout/fragment_share_extension_target.xml
=> [MBL-16362][Student] The Selected Course or Assignment is not read by Talkback when navigating to the dropdowns in Share flow

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/GradesElementaryE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/HomeroomE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ImportantDatesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ResourcesE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/SchedulePage.kt
Put console logging on K5 E2E tests as well.
Some minor refactor.
refs: MBL-16317
=> [MBL-16317][Student] - Extend console logging on K5 E2E tests

apps/teacher/src/main/java/com/instructure/teacher/fragments/EditAssignmentDetailsFragment.kt, libs/pandares/src/main/res/values/strings.xml, libs/pandautils/src/main/java/com/instructure/pandautils/utils/ViewStyler.kt
=> [MBL-16314][Teacher] Publish/Unpublish assignments

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/ShareExtensionE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/e2e/k5/ScheduleE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/AnnouncementsE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/EditAnnouncementPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/PeopleListPage.kt
Fix some nightly tests 
(announcements calling discussion edit fragment from now, so it has to be changed)
=> Fix some nightly tests 

apps/student/src/main/java/com/instructure/student/features/discussion/StudentDiscussionRouter.kt, apps/student/src/main/java/com/instructure/student/fragment/DiscussionListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/factory/DiscussionListPresenterFactory.kt, apps/teacher/src/main/java/com/instructure/teacher/features/discussion/TeacherDiscussionRouter.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/DiscussionsListFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/DiscussionListPresenter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouter.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouterFragment.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouterViewData.kt, libs/pandautils/src/main/java/com/instructure/pandautils/features/discussion/router/DiscussionRouterViewModel.kt, libs/pandautils/src/test/java/com/instructure/pandautils/features/discussion/router/DiscussionRouterViewModelTest.kt
refs: MBL-16393
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/72087159/202491010-6bb78645-a706-48b1-8892-7cb16af24efe.png" maxHeight=500></td>
<td><img src="https://user-images.githubusercontent.com/72087159/202490952-2b287cbb-f113-46ad-b42a-2623c6c997fa.png" maxHeight=500></td>
</tr>
</table>
=> [MBL-16393][Teacher] Fixed announcement routing

apps/student/src/androidTest/java/com/instructure/student/ui/e2e/DashboardE2ETest.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/DashboardPage.kt, apps/student/src/androidTest/java/com/instructure/student/ui/pages/HelpPage.kt
Implement test for check Help Menu and it's content.
refs: MBL-16329
=> [MBL-16329][Student] - Help menu Test

apps/student/src/main/java/com/instructure/student/features/documentscanning/DocumentScanningActivity.kt
=> [MBL-16422][Student] DocumentScanning intent security

apps/teacher/src/androidTest/java/com/instructure/teacher/ui/e2e/DashboardE2ETest.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/DashboardPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/pages/HelpPage.kt, apps/teacher/src/androidTest/java/com/instructure/teacher/ui/utils/TeacherTest.kt
Implement test for check Help Menu and it's content
refs: MBL-16324
=> [MBL-16324][Teacher] - Implement test for check Help Menu and it's content

apps/teacher/src/main/java/com/instructure/teacher/factory/SpeedGraderCommentsPresenterFactory.kt, apps/teacher/src/main/java/com/instructure/teacher/fragments/SpeedGraderCommentsFragment.kt, apps/teacher/src/main/java/com/instructure/teacher/presenters/SpeedGraderCommentsPresenter.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/SGPendingMediaCommentReceiver.kt, apps/teacher/src/main/java/com/instructure/teacher/utils/TeacherPrefs.kt, libs/pandautils/src/main/java/com/instructure/pandautils/di/DatabaseModule.kt, libs/pandautils/src/main/java/com/instructure/pandautils/room/AppDatabase.kt, libs/pandautils/src/main/java/com/instructure/pandautils/room/daos/FileUploadInputDao.kt, libs/pandautils/src/main/java/com/instructure/pandautils/room/daos/PendingSubmissionCommentDao.kt, libs/pandautils/src/main/java/com/instructure/pandautils/room/entities/PendingSubmissionCommentEntity.kt, libs/pandautils/src/main/java/com/instructure/pandautils/room/model/PendingSubmissionCommentWithFileUploadInput.kt, libs/pandautils/src/main/java/com/instructure/pandautils/services/NotoriousUploadService.kt
refs: MBL-16433
test plan: Test everything relating to submission comments
=> [MBL-16433] Submission comments saved to DB
